export const DASHBOARD_TAGLINES = [
  "Your dream school won't accept laziness. Let's go.",
  "Future top scorer, logging in.",
  "Small sessions. Big dreams. You've got this.",
  "One session closer to that acceptance letter.",
  "The grind now, the glory later.",
  "Your future self is rooting for today's you.",
  "Less doomscrolling, more reviewing. Deal.",
  "Consistent beats cramming. Every. Single. Time.",
  "You showed up. That's already half the battle.",
  "That entrance exam won't ace itself.",
  "Another day, another step closer to your dream school.",
  "Today's practice is tomorrow's edge.",
  "Progress tastes better than regret.",
  "The top scorer was also a beginner once.",
  "Your dream school's doors are opening — study up.",
  "Not today, distractions. Not today.",
  "10 questions. That's all it takes to start.",
  "Every expert was once a student who kept going.",
  "Effort compounds. So does laziness. Choose wisely.",
  "Dream big, review bigger.",
  "The version of you that gets in? They studied today.",
  "It's giving future scholar energy. Let's go.",
  "Study arc: activated.",
  "Brain cells, assemble.",
  "Your acceptance letter is already written — you just need to earn it.",
  "You didn't come this far to only come this far.",
  "Eyes on the prize. Dream school loading.",
  "Future you is begging present you to study.",
  "One topic at a time. You've got this.",
  "A little effort today, a lot of celebration later.",
  "The dream is free. The grind is sold separately.",
  "No shortcuts — but this app helps. Let's begin.",
  "The review session you skip could be the one that matters.",
  "Your classmates are reviewing. Just saying.",
  "Let's make today count.",
] as const;

export const PROGRESS_TAGLINES = [
  "Look how far you've come.",
  "Every session here is proof you're serious.",
  "Numbers don't lie — and yours are climbing.",
  "Graphs up. Glow up.",
  "Each bar is a battle you showed up for.",
  "Stats don't lie. You're getting better.",
  "This page is your proof of effort.",
  "Progress is quiet — until it isn't.",
  "Momentum is building. Keep going.",
  "Your dedication, visualized.",
  "Growth mode: active.",
  "Every wrong answer made you smarter.",
  "The data says you're doing the work.",
  "Each session left a mark. See for yourself.",
  "You can't fake these numbers. Well done.",
  "A little better every day adds up to a lot.",
  "Your effort, rendered in charts.",
  "This is what showing up looks like.",
  "Behind every score is a student who tried.",
  "The climb is slow. The summit is worth it.",
  "Your story, told in accuracy percentages.",
  "Good scores don't happen by accident.",
  "The numbers remember every session you showed up for.",
  "Slow and steady builds the score.",
  "This is what discipline looks like from the outside.",
  "Stronger than you were last week. Facts.",
  "One more topic practiced. One less thing to worry about.",
  "Your accuracy is climbing. So is your confidence.",
  "Every session moves the needle. Keep moving.",
  "No cramming needed when you've been consistent.",
  "You're building something real here. Don't stop.",
  "Each number here represents real effort. Wear it proudly.",
  "Tracking progress is the first step to improving it.",
  "Your graph has only one direction it wants to go.",
  "The student who showed up — that's you.",
] as const;

export function pickRandom<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
