import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface Q {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: number;
}

async function seedTopic(slug: string, questions: Q[], topicId: string) {
  console.log(`\nSeeding ${questions.length} questions for topic: ${slug} (${topicId})`);
  const rows = questions.map((q) => ({
    topic_id: topicId,
    question_text: q.question_text,
    choice_a: q.choice_a,
    choice_b: q.choice_b,
    choice_c: q.choice_c,
    choice_d: q.choice_d,
    correct_choice: q.correct_choice,
    explanation: q.explanation,
    difficulty: q.difficulty,
    status: "approved",
    is_premium: true,
  }));
  const { error } = await supabase.from("questions").insert(rows);
  if (error) { console.error(`  Error seeding ${slug}:`, error.message); return; }
  console.log(`  Inserted ${rows.length} questions.`);
}

// ── LOGIC & CRITICAL THINKING (20 Qs) ────────────────────────────────────────

const LOGIC: Q[] = [
  {
    question_text: `All mammals are warm-blooded. Whales are mammals. What conclusion must be true?`,
    choice_a: "All warm-blooded animals are whales.",
    choice_b: "Whales are warm-blooded.",
    choice_c: "Some mammals are not warm-blooded.",
    choice_d: "Whales are the only warm-blooded sea animals.",
    correct_choice: "b",
    explanation: "This is a valid syllogism: All A are B; Whales are A; therefore Whales are B (warm-blooded).",
    difficulty: 1,
  },
  {
    question_text: `No reptiles are warm-blooded. Crocodiles are reptiles. Which conclusion is valid?`,
    choice_a: "All cold-blooded animals are reptiles.",
    choice_b: "Crocodiles are warm-blooded.",
    choice_c: "Crocodiles are not warm-blooded.",
    choice_d: "Some reptiles are warm-blooded.",
    correct_choice: "c",
    explanation: "No reptiles are warm-blooded (universal negative) + Crocodiles are reptiles → Crocodiles are not warm-blooded.",
    difficulty: 1,
  },
  {
    question_text: `If it rains, the ground gets wet. The ground is wet. Which of the following is a valid conclusion?`,
    choice_a: "It is raining.",
    choice_b: "It may or may not be raining.",
    choice_c: "It is not raining.",
    choice_d: "The ground is always wet.",
    correct_choice: "b",
    explanation: "The wet ground confirms the consequent but does not confirm the antecedent (affirming the consequent fallacy). Other causes could have made the ground wet.",
    difficulty: 2,
  },
  {
    question_text: `If a student passes the UPCAT, then the student qualifies for UP admission. Maria did not pass the UPCAT. What can be concluded?`,
    choice_a: "Maria does not qualify for UP admission.",
    choice_b: "Maria may still qualify for UP admission.",
    choice_c: "Maria will retake the UPCAT.",
    choice_d: "Maria does not want to attend UP.",
    correct_choice: "b",
    explanation: "Denying the antecedent ('did not pass') does not allow a definitive conclusion about the consequent. Maria might qualify through other means.",
    difficulty: 3,
  },
  {
    question_text: `All doctors are college graduates. Some college graduates are wealthy. Which conclusion is definitely true?`,
    choice_a: "All doctors are wealthy.",
    choice_b: "Some doctors are wealthy.",
    choice_c: "No conclusion about doctors and wealth can be drawn.",
    choice_d: "All wealthy people are doctors.",
    correct_choice: "c",
    explanation: "The middle term (college graduates) links doctors and wealthy people, but since 'some' college graduates are wealthy, no definite conclusion about doctors and wealth is logically valid.",
    difficulty: 3,
  },
  {
    question_text: `Either the power is out or the bulb is broken. The power is not out. What must be true?`,
    choice_a: "The bulb may or may not be broken.",
    choice_b: "Both the power is out and the bulb is broken.",
    choice_c: "The bulb is broken.",
    choice_d: "Neither the power nor the bulb has a problem.",
    correct_choice: "c",
    explanation: "In an inclusive-or disjunction, if one disjunct is false, the other must be true. Power is not out → bulb must be broken.",
    difficulty: 2,
  },
  {
    question_text: `Some students who study hard fail the exam. Ramon studies hard. What must be true?`,
    choice_a: "Ramon will fail the exam.",
    choice_b: "Ramon will pass the exam.",
    choice_c: "Ramon may pass or fail the exam.",
    choice_d: "Hard-working students always fail exams.",
    correct_choice: "c",
    explanation: "'Some who study hard fail' means it is possible but not certain. Ramon may pass or fail.",
    difficulty: 2,
  },
  {
    question_text: `If Ana goes to the party, then Ben goes too. Ben did not go to the party. What can be concluded?`,
    choice_a: "Ana went to the party.",
    choice_b: "Ana did not go to the party.",
    choice_c: "Ben went to the party alone.",
    choice_d: "Neither Ana nor Ben likes parties.",
    correct_choice: "b",
    explanation: "This is modus tollens: If P then Q; not Q; therefore not P. Ben did not go → Ana did not go.",
    difficulty: 2,
  },
  {
    question_text: `All nurses are licensed. All licensed professionals pay annual fees. Which conclusion is valid?`,
    choice_a: "All nurses pay annual fees.",
    choice_b: "All people who pay annual fees are nurses.",
    choice_c: "Some nurses are not licensed.",
    choice_d: "Annual fees are only paid by nurses.",
    correct_choice: "a",
    explanation: "Chain syllogism: Nurses → licensed → pay fees. Therefore all nurses pay annual fees.",
    difficulty: 1,
  },
  {
    question_text: `No student who cheats deserves to pass. Kevin deserves to pass. What must be true?`,
    choice_a: "Kevin did not cheat.",
    choice_b: "Kevin cheated.",
    choice_c: "Kevin may or may not have cheated.",
    choice_d: "Cheating students always fail.",
    correct_choice: "a",
    explanation: "If cheating → does not deserve to pass (contrapositive: deserves to pass → did not cheat). Kevin deserves to pass → Kevin did not cheat.",
    difficulty: 2,
  },
  {
    question_text: `If the economy grows, unemployment decreases. If unemployment decreases, crime rates fall. The economy grew. What follows?`,
    choice_a: "Crime rates remain the same.",
    choice_b: "Unemployment increases.",
    choice_c: "Crime rates fall.",
    choice_d: "The economy will continue to grow.",
    correct_choice: "c",
    explanation: "Chain of conditionals: Economy grew → unemployment decreases → crime rates fall.",
    difficulty: 2,
  },
  {
    question_text: `"All politicians are liars" is assumed true. Senator Cruz is not a liar. What must follow?`,
    choice_a: "Senator Cruz is a politician.",
    choice_b: "Senator Cruz is not a politician.",
    choice_c: "Some politicians are not liars.",
    choice_d: "Senator Cruz may or may not be a politician.",
    correct_choice: "b",
    explanation: "Contrapositive of 'All politicians are liars' is 'Not a liar → not a politician.' Cruz is not a liar → not a politician.",
    difficulty: 2,
  },
  {
    question_text: `Premise 1: All fruits contain seeds.\nPremise 2: A banana is a fruit.\nPremise 3: Seedless bananas exist.\n\nWhat is the relationship between the premises?`,
    choice_a: "Premises 1 and 2 together imply Premise 3.",
    choice_b: "Premises 1 and 2 are consistent with Premise 3.",
    choice_c: "Premise 3 contradicts Premise 1.",
    choice_d: "Premise 2 contradicts Premise 1.",
    correct_choice: "c",
    explanation: "If all fruits contain seeds (P1) and a seedless banana is a banana/fruit (P2), then P3 (seedless bananas exist) directly contradicts P1.",
    difficulty: 3,
  },
  {
    question_text: `A survey found that students who sleep more than eight hours per night score higher on exams. A student concludes: "I will score higher if I sleep more." What is the flaw in this reasoning?`,
    choice_a: "The student used faulty arithmetic.",
    choice_b: "Correlation does not imply causation.",
    choice_c: "The survey sample was too large.",
    choice_d: "There is no flaw; the reasoning is valid.",
    correct_choice: "b",
    explanation: "The survey shows a correlation between sleep and scores, but this does not prove that sleeping more causes higher scores. Other factors may be involved.",
    difficulty: 3,
  },
  {
    question_text: `"You should support free healthcare because my grandfather died waiting for treatment." What type of argument is this?`,
    choice_a: "Argument from authority",
    choice_b: "Hasty generalization",
    choice_c: "Appeal to emotion",
    choice_d: "False dilemma",
    correct_choice: "c",
    explanation: "Using a personal emotional story to support a policy argument, without logical evidence, is an appeal to emotion.",
    difficulty: 2,
  },
  {
    question_text: `"Either you support this bill or you are against the poor." This statement is an example of:`,
    choice_a: "A valid disjunction",
    choice_b: "A false dilemma",
    choice_c: "Modus ponens",
    choice_d: "An ad hominem attack",
    correct_choice: "b",
    explanation: "A false dilemma presents only two choices when more options exist. One can have nuanced views on a bill without being 'against the poor.'",
    difficulty: 2,
  },
  {
    question_text: `Five people are seated in a row: A, B, C, D, and E.\n• A sits next to B.\n• C sits at one of the ends.\n• D is between B and E.\n\nWhich seating arrangement is possible?`,
    choice_a: "C – A – B – D – E",
    choice_b: "E – D – B – A – C",
    choice_c: "A – B – D – E – C",
    choice_d: "B – A – C – D – E",
    correct_choice: "b",
    explanation: "Check B: C is at one end ✓, A sits next to B ✓ (B-A), D is between B and E ✓ (E-D-B). All conditions satisfied.",
    difficulty: 3,
  },
  {
    question_text: `Four friends — Gina, Hector, Iris, and Jun — each prefer a different subject: Math, Science, History, and English.\n• Gina does not like Math or Science.\n• Hector likes History.\n• Iris does not like English.\n\nWhat subject does Jun prefer?`,
    choice_a: "Math",
    choice_b: "Science",
    choice_c: "History",
    choice_d: "English",
    correct_choice: "d",
    explanation: "Hector → History. Gina → not Math, not Science → English or History → English (since Hector has History). Iris → not English → Math or Science. Jun → the remaining subject. Gina=English, Hector=History, Iris=Math or Science. Jun gets the other of Math/Science... but we need to determine Iris. Since Iris is not English, Iris gets Math or Science. Jun gets the other. Actually Gina=English, Hector=History, leaving Math and Science for Iris and Jun. No further constraint eliminates one for Jun. Let me recheck: Iris not English → Math or Science. Jun gets Math or Science. No constraint specifies which. The question implies a unique answer. Let me re-examine: Gina: not Math, not Science → History or English. Hector: History → Gina gets English. Iris: not English → Math, Science, or History. History is taken → Math or Science. Jun gets the remaining. Still ambiguous between Jun=Math or Jun=Science. I need to fix this question by adding a constraint. Since the script is being written, I'll adjust the explanation to note that Gina=English, Hector=History, and the remaining are Math and Science for Iris and Jun — and add a constraint: Iris likes Math → Jun likes Science... but this isn't stated. Let me change the answer to something that IS determined: What subject does Gina prefer? That's English, which is determined.",
    difficulty: 2,
  },
  {
    question_text: `A clock shows 3:00. What is the angle between the hour and minute hands?`,
    choice_a: "60°",
    choice_b: "90°",
    choice_c: "120°",
    choice_d: "180°",
    correct_choice: "b",
    explanation: "At 3:00, the minute hand points to 12 and the hour hand points to 3. Each hour mark = 30°. Three hour marks apart = 3 × 30° = 90°.",
    difficulty: 1,
  },
  {
    question_text: `In a race, Aida finished ahead of Belle. Belle finished ahead of Carlo. Donna finished after Aida but before Belle. Who finished second?`,
    choice_a: "Aida",
    choice_b: "Belle",
    choice_c: "Carlo",
    choice_d: "Donna",
    correct_choice: "d",
    explanation: "Order: Aida (1st) → Donna (after Aida but before Belle) → Belle → Carlo. So the order is Aida, Donna, Belle, Carlo. Donna finished second.",
    difficulty: 2,
  },
];

// Fix question 18 (index 17) — the four-friends question had an ambiguous answer
// Rewrite it to ask about Gina instead of Jun
LOGIC[17] = {
  question_text: `Four friends — Gina, Hector, Iris, and Jun — each prefer a different subject: Math, Science, History, and English.\n• Gina does not like Math or Science.\n• Hector likes History.\n• Iris does not like English.\n\nWhat subject does Gina prefer?`,
  choice_a: "Math",
  choice_b: "Science",
  choice_c: "History",
  choice_d: "English",
  correct_choice: "d",
  explanation: "Hector → History. Gina: not Math, not Science → History or English. History is taken by Hector → Gina prefers English.",
  difficulty: 2,
};

// ── NUMERICAL REASONING (20 Qs) ──────────────────────────────────────────────

const NUMERICAL: Q[] = [
  {
    question_text: `What is the next number in the sequence?\n2, 4, 8, 16, 32, __`,
    choice_a: "48",
    choice_b: "60",
    choice_c: "64",
    choice_d: "72",
    correct_choice: "c",
    explanation: "Each term is multiplied by 2: 32 × 2 = 64.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n1, 4, 9, 16, 25, __`,
    choice_a: "30",
    choice_b: "36",
    choice_c: "40",
    choice_d: "49",
    correct_choice: "b",
    explanation: "The sequence is perfect squares: 1², 2², 3², 4², 5², 6² = 36.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n3, 6, 11, 18, 27, __`,
    choice_a: "36",
    choice_b: "38",
    choice_c: "40",
    choice_d: "42",
    correct_choice: "b",
    explanation: "Differences: +3, +5, +7, +9, +11. Next term: 27 + 11 = 38.",
    difficulty: 2,
  },
  {
    question_text: `What is the missing number?\n5, 10, __, 40, 80`,
    choice_a: "15",
    choice_b: "20",
    choice_c: "25",
    choice_d: "30",
    correct_choice: "b",
    explanation: "Each term doubles: 5 → 10 → 20 → 40 → 80. The missing term is 20.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n1, 1, 2, 3, 5, 8, 13, __`,
    choice_a: "18",
    choice_b: "20",
    choice_c: "21",
    choice_d: "24",
    correct_choice: "c",
    explanation: "This is the Fibonacci sequence: each term is the sum of the two preceding terms. 8 + 13 = 21.",
    difficulty: 1,
  },
  {
    question_text: `What is the missing number in the sequence?\n100, 96, 88, 76, __, 40`,
    choice_a: "60",
    choice_b: "62",
    choice_c: "64",
    choice_d: "66",
    correct_choice: "a",
    explanation: "Differences: −4, −8, −12, −16, −20. Missing term: 76 − 16 = 60. Check: 60 − 20 = 40 ✓.",
    difficulty: 2,
  },
  {
    question_text: `What is the next number in the sequence?\n2, 5, 10, 17, 26, __`,
    choice_a: "35",
    choice_b: "36",
    choice_c: "37",
    choice_d: "38",
    correct_choice: "c",
    explanation: "Differences: +3, +5, +7, +9, +11. Next: 26 + 11 = 37.",
    difficulty: 2,
  },
  {
    question_text: `What is the missing number?\n81, 27, 9, __, 1`,
    choice_a: "3",
    choice_b: "4",
    choice_c: "5",
    choice_d: "6",
    correct_choice: "a",
    explanation: "Each term is divided by 3: 81 ÷ 3 = 27 ÷ 3 = 9 ÷ 3 = 3 ÷ 3 = 1.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n7, 14, 28, 56, __`,
    choice_a: "84",
    choice_b: "100",
    choice_c: "112",
    choice_d: "120",
    correct_choice: "c",
    explanation: "Each term multiplies by 2: 56 × 2 = 112.",
    difficulty: 1,
  },
  {
    question_text: `What is the missing number?\n4, 9, 16, __, 36`,
    choice_a: "20",
    choice_b: "24",
    choice_c: "25",
    choice_d: "30",
    correct_choice: "c",
    explanation: "Perfect squares: 2² = 4, 3² = 9, 4² = 16, 5² = 25, 6² = 36. Missing = 25.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n1, 3, 7, 15, 31, __`,
    choice_a: "47",
    choice_b: "55",
    choice_c: "63",
    choice_d: "64",
    correct_choice: "c",
    explanation: "Each term = 2 × previous − 1, or differences double: +2, +4, +8, +16, +32. Next: 31 + 32 = 63.",
    difficulty: 2,
  },
  {
    question_text: `What is the missing number?\n2, 6, 12, 20, __, 42`,
    choice_a: "28",
    choice_b: "30",
    choice_c: "32",
    choice_d: "34",
    correct_choice: "b",
    explanation: "Terms are n(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42. Missing = 30.",
    difficulty: 2,
  },
  {
    question_text: `What is the next number in the sequence?\n512, 256, 128, 64, __`,
    choice_a: "16",
    choice_b: "32",
    choice_c: "48",
    choice_d: "64",
    correct_choice: "b",
    explanation: "Each term halves: 64 ÷ 2 = 32.",
    difficulty: 1,
  },
  {
    question_text: `What is the missing number?\n1, 4, 10, 22, __, 94`,
    choice_a: "44",
    choice_b: "46",
    choice_c: "48",
    choice_d: "50",
    correct_choice: "b",
    explanation: "Pattern: multiply by 2 then add 2. 1×2+2=4, 4×2+2=10, 10×2+2=22, 22×2+2=46, 46×2+2=94 ✓.",
    difficulty: 3,
  },
  {
    question_text: `In a number pattern, the rule is: multiply by 3 and subtract 1. If the first term is 2, what is the 4th term?`,
    choice_a: "47",
    choice_b: "50",
    choice_c: "53",
    choice_d: "56",
    correct_choice: "c",
    explanation: "Term 1 = 2. Term 2 = 2×3−1 = 5. Term 3 = 5×3−1 = 14. Term 4 = 14×3−1 = 41. Hmm, that gives 41. Let me recalculate: 2→5→14→41. None of the choices match 41. Let me fix: rule is 'add previous term and multiply by 2': Term1=2, Term2=2×3−1=5, actually let me change the rule. Rule: double and add 3. T1=2, T2=7, T3=17, T4=37. Still doesn't match. Let me use different choices.",
    difficulty: 2,
  },
  {
    question_text: `What is the next number in the sequence?\n0, 1, 3, 6, 10, 15, __`,
    choice_a: "18",
    choice_b: "20",
    choice_c: "21",
    choice_d: "25",
    correct_choice: "c",
    explanation: "Triangular numbers: differences increase by 1 each time (+1, +2, +3, +4, +5, +6). Next: 15 + 6 = 21.",
    difficulty: 2,
  },
  {
    question_text: `A sequence follows the rule: each term = sum of the two terms before it, starting with 2 and 3. What is the 6th term?`,
    choice_a: "18",
    choice_b: "21",
    choice_c: "23",
    choice_d: "26",
    correct_choice: "c",
    explanation: "Terms: 2, 3, 5, 8, 13, 21... wait: 2+3=5, 3+5=8, 5+8=13, 8+13=21. 6th term = 21. Let me fix choices.",
    difficulty: 2,
  },
  {
    question_text: `What is the next number in the sequence?\n−3, −1, 3, 9, 17, __`,
    choice_a: "25",
    choice_b: "27",
    choice_c: "29",
    choice_d: "31",
    correct_choice: "b",
    explanation: "Differences: +2, +4, +6, +8, +10. Next: 17 + 10 = 27.",
    difficulty: 2,
  },
  {
    question_text: `What is the missing number?\n2, 3, 5, 8, 13, __, 34`,
    choice_a: "18",
    choice_b: "20",
    choice_c: "21",
    choice_d: "22",
    correct_choice: "c",
    explanation: "Fibonacci-like: each term = sum of two before. 8+13=21. Next: 13+21=34 ✓.",
    difficulty: 1,
  },
  {
    question_text: `What is the next number in the sequence?\n1, 8, 27, 64, 125, __`,
    choice_a: "196",
    choice_b: "210",
    choice_c: "216",
    choice_d: "225",
    correct_choice: "c",
    explanation: "Perfect cubes: 1³, 2³, 3³, 4³, 5³, 6³ = 216.",
    difficulty: 1,
  },
];

// Fix the problematic questions (index 14 and 16)
NUMERICAL[14] = {
  question_text: `A number pattern follows the rule: multiply by 2, then subtract 1. If the first term is 3, what is the 4th term?`,
  choice_a: "31",
  choice_b: "33",
  choice_c: "37",
  choice_d: "41",
  correct_choice: "d",
  explanation: "T1=3. T2=3×2−1=5. T3=5×2−1=9. T4=9×2−1=17. Hmm still not matching. Let me use: T1=5, T2=5×2−1=9, T3=9×2−1=17, T4=17×2−1=33. Answer=33.",
  difficulty: 2,
};
NUMERICAL[14] = {
  question_text: `A sequence follows the rule: multiply the previous term by 2, then subtract 1. Starting from 5, what is the 4th term?`,
  choice_a: "29",
  choice_b: "31",
  choice_c: "33",
  choice_d: "35",
  correct_choice: "c",
  explanation: "T1=5. T2=5×2−1=9. T3=9×2−1=17. T4=17×2−1=33.",
  difficulty: 2,
};

NUMERICAL[16] = {
  question_text: `A sequence follows the rule: each term equals the sum of the two preceding terms, starting with 2 and 3. What is the 6th term?`,
  choice_a: "18",
  choice_b: "19",
  choice_c: "21",
  choice_d: "23",
  correct_choice: "c",
  explanation: "Terms: T1=2, T2=3, T3=5, T4=8, T5=13, T6=21.",
  difficulty: 2,
};

// ── VERBAL REASONING (20 Qs) ─────────────────────────────────────────────────

const VERBAL: Q[] = [
  {
    question_text: `DOCTOR : HOSPITAL :: TEACHER : ?`,
    choice_a: "Student",
    choice_b: "School",
    choice_c: "Lesson",
    choice_d: "Blackboard",
    correct_choice: "b",
    explanation: "A doctor works in a hospital; a teacher works in a school.",
    difficulty: 1,
  },
  {
    question_text: `FISH : SCHOOL :: WOLF : ?`,
    choice_a: "Den",
    choice_b: "Pack",
    choice_c: "Herd",
    choice_d: "Flock",
    correct_choice: "b",
    explanation: "A group of fish is called a school; a group of wolves is called a pack.",
    difficulty: 2,
  },
  {
    question_text: `AUTHOR : BOOK :: COMPOSER : ?`,
    choice_a: "Orchestra",
    choice_b: "Instrument",
    choice_c: "Symphony",
    choice_d: "Concert",
    correct_choice: "c",
    explanation: "An author creates a book; a composer creates a symphony (musical composition).",
    difficulty: 1,
  },
  {
    question_text: `OPTIMISTIC : PESSIMISTIC :: BRAVE : ?`,
    choice_a: "Fearless",
    choice_b: "Reckless",
    choice_c: "Cowardly",
    choice_d: "Bold",
    correct_choice: "c",
    explanation: "Optimistic and pessimistic are antonyms. The antonym of brave is cowardly.",
    difficulty: 1,
  },
  {
    question_text: `OXYGEN : BREATHE :: FOOD : ?`,
    choice_a: "Taste",
    choice_b: "Grow",
    choice_c: "Cook",
    choice_d: "Eat",
    correct_choice: "d",
    explanation: "We breathe oxygen; we eat food. The relationship is substance → action performed with it.",
    difficulty: 1,
  },
  {
    question_text: `Which word does NOT belong in the group?\nApple, Mango, Banana, Carrot, Guava`,
    choice_a: "Apple",
    choice_b: "Mango",
    choice_c: "Carrot",
    choice_d: "Guava",
    correct_choice: "c",
    explanation: "All others are fruits; carrot is a vegetable.",
    difficulty: 1,
  },
  {
    question_text: `Which word does NOT belong in the group?\nMetro Manila, Cebu City, Davao City, Iloilo City, Philippines`,
    choice_a: "Metro Manila",
    choice_b: "Cebu City",
    choice_c: "Philippines",
    choice_d: "Iloilo City",
    correct_choice: "c",
    explanation: "All others are cities or metropolitan areas within the Philippines; 'Philippines' is the country itself.",
    difficulty: 1,
  },
  {
    question_text: `SCALPEL : SURGEON :: GAVEL : ?`,
    choice_a: "Lawyer",
    choice_b: "Judge",
    choice_c: "Jury",
    choice_d: "Defendant",
    correct_choice: "b",
    explanation: "A scalpel is the tool of a surgeon; a gavel is the tool of a judge.",
    difficulty: 2,
  },
  {
    question_text: `LIBRARY : BOOKS :: MUSEUM : ?`,
    choice_a: "Tourists",
    choice_b: "Artifacts",
    choice_c: "Tickets",
    choice_d: "Guides",
    correct_choice: "b",
    explanation: "A library houses books; a museum houses artifacts.",
    difficulty: 1,
  },
  {
    question_text: `Which word does NOT belong in the group?\nHappy, Joyful, Ecstatic, Melancholy, Elated`,
    choice_a: "Happy",
    choice_b: "Joyful",
    choice_c: "Melancholy",
    choice_d: "Elated",
    correct_choice: "c",
    explanation: "All others mean feeling positive emotions; melancholy means sadness or gloom.",
    difficulty: 1,
  },
  {
    question_text: `CATERPILLAR : BUTTERFLY :: TADPOLE : ?`,
    choice_a: "Salamander",
    choice_b: "Fish",
    choice_c: "Frog",
    choice_d: "Lizard",
    correct_choice: "c",
    explanation: "A caterpillar metamorphoses into a butterfly; a tadpole metamorphoses into a frog.",
    difficulty: 1,
  },
  {
    question_text: `TRANSPARENT : OPAQUE :: FLEXIBLE : ?`,
    choice_a: "Soft",
    choice_b: "Rigid",
    choice_c: "Fragile",
    choice_d: "Elastic",
    correct_choice: "b",
    explanation: "Transparent and opaque are antonyms; flexible and rigid are antonyms.",
    difficulty: 2,
  },
  {
    question_text: `Which word does NOT belong in the group?\nHamlet, Macbeth, Othello, Romeo and Juliet, Don Quixote`,
    choice_a: "Hamlet",
    choice_b: "Macbeth",
    choice_c: "Don Quixote",
    choice_d: "Othello",
    correct_choice: "c",
    explanation: "Hamlet, Macbeth, Othello, and Romeo and Juliet are all plays by Shakespeare; Don Quixote is a novel by Miguel de Cervantes.",
    difficulty: 2,
  },
  {
    question_text: `CLOCK : TIME :: THERMOMETER : ?`,
    choice_a: "Heat",
    choice_b: "Weather",
    choice_c: "Temperature",
    choice_d: "Fever",
    correct_choice: "c",
    explanation: "A clock measures time; a thermometer measures temperature.",
    difficulty: 1,
  },
  {
    question_text: `PENINSULA : LAND :: BAY : ?`,
    choice_a: "River",
    choice_b: "Water",
    choice_c: "Island",
    choice_d: "Coast",
    correct_choice: "b",
    explanation: "A peninsula is a landform surrounded partly by water; a bay is a body of water partially enclosed by land. Both involve land : water relationships.",
    difficulty: 2,
  },
  {
    question_text: `Which word does NOT belong in the group?\nAcetaminophen, Ibuprofen, Amoxicillin, Aspirin, Naproxen`,
    choice_a: "Acetaminophen",
    choice_b: "Amoxicillin",
    choice_c: "Aspirin",
    choice_d: "Naproxen",
    correct_choice: "b",
    explanation: "Acetaminophen, ibuprofen, aspirin, and naproxen are all analgesics/anti-inflammatory drugs; amoxicillin is an antibiotic.",
    difficulty: 3,
  },
  {
    question_text: `NOUN : GRAMMAR :: ATOM : ?`,
    choice_a: "Physics",
    choice_b: "Biology",
    choice_c: "Chemistry",
    choice_d: "Element",
    correct_choice: "c",
    explanation: "A noun is a fundamental unit of grammar; an atom is a fundamental unit of chemistry (matter studied in chemistry).",
    difficulty: 2,
  },
  {
    question_text: `ARCHIPELAGO : ISLANDS :: ANTHOLOGY : ?`,
    choice_a: "Authors",
    choice_b: "Poems or Stories",
    choice_c: "Publishers",
    choice_d: "Chapters",
    correct_choice: "b",
    explanation: "An archipelago is a collection of islands; an anthology is a collection of poems, stories, or other literary works.",
    difficulty: 2,
  },
  {
    question_text: `Which word does NOT belong in the group?\nSonnet, Haiku, Ballad, Novel, Ode`,
    choice_a: "Sonnet",
    choice_b: "Haiku",
    choice_c: "Novel",
    choice_d: "Ode",
    correct_choice: "c",
    explanation: "Sonnet, haiku, ballad, and ode are all forms of poetry; a novel is a long-form prose fiction.",
    difficulty: 2,
  },
  {
    question_text: `DROUGHT : WATER :: FAMINE : ?`,
    choice_a: "Poverty",
    choice_b: "Crops",
    choice_c: "Food",
    choice_d: "Disease",
    correct_choice: "c",
    explanation: "A drought is a severe shortage of water; a famine is a severe shortage of food.",
    difficulty: 2,
  },
];

// ── DATA ANALYSIS (20 Qs) ────────────────────────────────────────────────────

const DATA_ANALYSIS: Q[] = [
  {
    question_text: `The table below shows the number of students enrolled in five sections:\n\nSection | Enrollment\nA       | 42\nB       | 38\nC       | 45\nD       | 40\nE       | 35\n\nWhat is the average enrollment across all five sections?`,
    choice_a: "38",
    choice_b: "39",
    choice_c: "40",
    choice_d: "42",
    correct_choice: "c",
    explanation: "Total = 42+38+45+40+35 = 200. Average = 200 ÷ 5 = 40.",
    difficulty: 1,
  },
  {
    question_text: `A bar chart shows monthly sales (in thousands of pesos):\nJan: 80 | Feb: 55 | Mar: 90 | Apr: 70 | May: 100 | Jun: 85\n\nWhich month had the greatest increase from the previous month?`,
    choice_a: "March",
    choice_b: "May",
    choice_c: "June",
    choice_d: "February",
    correct_choice: "a",
    explanation: "Changes: Feb: −25, Mar: +35, Apr: −20, May: +30, Jun: +15. March had the greatest increase at +35.",
    difficulty: 2,
  },
  {
    question_text: `A survey of 200 students found that 60% prefer online learning and the rest prefer face-to-face. How many students prefer face-to-face learning?`,
    choice_a: "60",
    choice_b: "80",
    choice_c: "100",
    choice_d: "120",
    correct_choice: "b",
    explanation: "40% prefer face-to-face. 200 × 0.40 = 80 students.",
    difficulty: 1,
  },
  {
    question_text: `The table shows scores of 5 students in a quiz:\n\nStudent | Score\nAna     | 18\nBen     | 14\nCla     | 20\nDan     | 16\nEva     | 17\n\nWhat is the median score?`,
    choice_a: "16",
    choice_b: "17",
    choice_c: "18",
    choice_d: "20",
    correct_choice: "b",
    explanation: "Arranged in order: 14, 16, 17, 18, 20. Median (middle value) = 17.",
    difficulty: 1,
  },
  {
    question_text: `A pie chart shows how a student spends her day:\nSleep: 33% | School: 29% | Study: 17% | Recreation: 13% | Others: 8%\n\nIf a day has 24 hours, how many hours does she spend on recreation?`,
    choice_a: "2.5 hours",
    choice_b: "3 hours",
    choice_c: "3.1 hours",
    choice_d: "3.5 hours",
    correct_choice: "c",
    explanation: "Recreation = 13% of 24 hours = 0.13 × 24 = 3.12 ≈ 3.1 hours.",
    difficulty: 2,
  },
  {
    question_text: `The line graph shows a company's profits (in millions) from 2019 to 2023:\n2019: ₱12M | 2020: ₱8M | 2021: ₱10M | 2022: ₱15M | 2023: ₱18M\n\nBy how much did profits increase from 2020 to 2022?`,
    choice_a: "₱5M",
    choice_b: "₱6M",
    choice_c: "₱7M",
    choice_d: "₱10M",
    correct_choice: "c",
    explanation: "2022 profit − 2020 profit = ₱15M − ₱8M = ₱7M.",
    difficulty: 1,
  },
  {
    question_text: `The table shows the number of books read by students in one month:\n\nBooks Read | Frequency\n0           | 5\n1           | 12\n2           | 8\n3           | 4\n4           | 1\n\nHow many students participated in the survey?`,
    choice_a: "25",
    choice_b: "28",
    choice_c: "30",
    choice_d: "32",
    correct_choice: "c",
    explanation: "Total = 5 + 12 + 8 + 4 + 1 = 30 students.",
    difficulty: 1,
  },
  {
    question_text: `The table shows the number of books read by students in one month:\n\nBooks Read | Frequency\n0           | 5\n1           | 12\n2           | 8\n3           | 4\n4           | 1\n\nWhat is the mode (most common number of books read)?`,
    choice_a: "0",
    choice_b: "1",
    choice_c: "2",
    choice_d: "3",
    correct_choice: "b",
    explanation: "The highest frequency is 12, which corresponds to students who read 1 book. Mode = 1.",
    difficulty: 1,
  },
  {
    question_text: `A class of 30 students took an exam. The average score was 75. If 10 students who scored an average of 90 are excluded, what is the average of the remaining 20 students?`,
    choice_a: "60.5",
    choice_b: "65",
    choice_c: "67.5",
    choice_d: "70",
    correct_choice: "c",
    explanation: "Total score = 30 × 75 = 2250. Top 10 total = 10 × 90 = 900. Remaining total = 2250 − 900 = 1350. Average of 20 = 1350 ÷ 20 = 67.5.",
    difficulty: 2,
  },
  {
    question_text: `The chart shows rainfall (mm) for four months:\nJune: 200 | July: 280 | August: 260 | September: 180\n\nWhat is the range of rainfall across these months?`,
    choice_a: "80 mm",
    choice_b: "90 mm",
    choice_c: "100 mm",
    choice_d: "110 mm",
    correct_choice: "c",
    explanation: "Range = Maximum − Minimum = 280 − 180 = 100 mm.",
    difficulty: 1,
  },
  {
    question_text: `A school has 400 students. 45% are male. How many more female students are there than male?`,
    choice_a: "30",
    choice_b: "35",
    choice_c: "40",
    choice_d: "45",
    correct_choice: "c",
    explanation: "Male = 400 × 0.45 = 180. Female = 400 − 180 = 220. Difference = 220 − 180 = 40.",
    difficulty: 1,
  },
  {
    question_text: `Data set: 12, 15, 14, 10, 16, 13, 14, 11, 14, 18\n\nWhat is the mode of the data set?`,
    choice_a: "12",
    choice_b: "13",
    choice_c: "14",
    choice_d: "15",
    correct_choice: "c",
    explanation: "14 appears three times in the data set, more than any other value. Mode = 14.",
    difficulty: 1,
  },
  {
    question_text: `A student's test scores for five subjects are: 82, 78, 90, 85, and 75. What score must she get on a 6th test to raise her average to 84?`,
    choice_a: "92",
    choice_b: "94",
    choice_c: "96",
    choice_d: "98",
    correct_choice: "c",
    explanation: "Target total for 6 tests = 84 × 6 = 504. Current total = 82+78+90+85+75 = 410. Required score = 504 − 410 = 94.",
    difficulty: 2,
  },
  {
    question_text: `A student's test scores for five subjects are: 82, 78, 90, 85, and 75. What score must she get on a 6th test to raise her average to 84?\n\n(Correction: What is the median of the five original scores?)`,
    choice_a: "78",
    choice_b: "82",
    choice_c: "85",
    choice_d: "90",
    correct_choice: "b",
    explanation: "Arranged in order: 75, 78, 82, 85, 90. Median = 82.",
    difficulty: 1,
  },
  {
    question_text: `A graph shows the population of a city from 2000 to 2020 in intervals of 5 years:\n2000: 1.2M | 2005: 1.5M | 2010: 1.9M | 2015: 2.4M | 2020: 3.0M\n\nBetween which 5-year period did the population grow the most?`,
    choice_a: "2000–2005",
    choice_b: "2005–2010",
    choice_c: "2010–2015",
    choice_d: "2015–2020",
    correct_choice: "d",
    explanation: "Growth: 2000–05: 0.3M; 2005–10: 0.4M; 2010–15: 0.5M; 2015–20: 0.6M. Largest growth = 2015–2020.",
    difficulty: 2,
  },
  {
    question_text: `In a class of 40 students, 25 passed Math, 20 passed Science, and 10 passed both. How many students passed neither subject?`,
    choice_a: "3",
    choice_b: "5",
    choice_c: "7",
    choice_d: "10",
    correct_choice: "b",
    explanation: "By inclusion-exclusion: passed at least one = 25 + 20 − 10 = 35. Passed neither = 40 − 35 = 5.",
    difficulty: 2,
  },
  {
    question_text: `A survey asked 150 respondents about their preferred news source:\nTV: 48 | Social Media: 52 | Newspaper: 25 | Radio: 15 | Other: 10\n\nWhat percentage preferred social media?`,
    choice_a: "32.5%",
    choice_b: "34.7%",
    choice_c: "35.2%",
    choice_d: "36.0%",
    correct_choice: "b",
    explanation: "52 ÷ 150 × 100 = 34.67% ≈ 34.7%.",
    difficulty: 2,
  },
  {
    question_text: `A data set has a mean of 50 and a standard deviation of 10. Which value is exactly 2 standard deviations above the mean?`,
    choice_a: "60",
    choice_b: "65",
    choice_c: "70",
    choice_d: "75",
    correct_choice: "c",
    explanation: "2 standard deviations above the mean = 50 + (2 × 10) = 50 + 20 = 70.",
    difficulty: 2,
  },
  {
    question_text: `The table shows a company's expenses for one year:\nSalaries: ₱5.4M | Utilities: ₱0.8M | Supplies: ₱0.6M | Marketing: ₱1.2M | Other: ₱0.5M\n\nWhat fraction of total expenses is spent on salaries (expressed in simplest form)?`,
    choice_a: "½",
    choice_b: "⅔",
    choice_c: "⅗",
    choice_d: "27/40",
    correct_choice: "d",
    explanation: "Total = 5.4+0.8+0.6+1.2+0.5 = 8.5M. Fraction = 5.4/8.5 = 54/85 = 54/85. Let me check: GCD(54,85)=1. Hmm, 54/85 doesn't simplify to any of the choices. Let me recalculate: actually GCD(54,85)=1. The answer as a decimal is 0.635≈63.5%. None of the choices simplify to this. Let me fix this question.",
    difficulty: 3,
  },
  {
    question_text: `A school records the following test score distribution:\n\nScore Range | Number of Students\n90–100      | 8\n80–89       | 15\n70–79       | 20\n60–69       | 10\nBelow 60    | 7\n\nWhat percentage of students scored 80 or above?`,
    choice_a: "37.5%",
    choice_b: "38.3%",
    choice_c: "38.5%",
    choice_d: "40.0%",
    correct_choice: "a",
    explanation: "Students scoring 80+ = 8 + 15 = 23. Total = 8+15+20+10+7 = 60. Percentage = 23/60 × 100 = 38.33%.",
    difficulty: 2,
  },
];

// Fix the duplicate Q13/Q14 issue and the salary fraction question
DATA_ANALYSIS[12] = {
  question_text: `A student's test scores for five subjects are: 82, 78, 90, 85, and 75. What score must she get on a 6th test to raise her average to 84?`,
  choice_a: "90",
  choice_b: "92",
  choice_c: "94",
  choice_d: "96",
  correct_choice: "c",
  explanation: "Target total for 6 tests = 84 × 6 = 504. Current total = 82+78+90+85+75 = 410. Required score = 504 − 410 = 94.",
  difficulty: 2,
};
DATA_ANALYSIS[13] = {
  question_text: `The ages of seven employees in a department are: 24, 28, 35, 31, 27, 42, and 31. What is the median age?`,
  choice_a: "27",
  choice_b: "28",
  choice_c: "31",
  choice_d: "35",
  correct_choice: "c",
  explanation: "Arranged in order: 24, 27, 28, 31, 31, 35, 42. Median (4th value) = 31.",
  difficulty: 1,
};
DATA_ANALYSIS[18] = {
  question_text: `A company's annual expenses total ₱8.0 million. Salaries account for ₱4.8 million. What fraction of the total expenses is spent on salaries?`,
  choice_a: "½",
  choice_b: "⅗",
  choice_c: "¾",
  choice_d: "⅔",
  correct_choice: "b",
  explanation: "4.8 ÷ 8.0 = 0.6 = 3/5.",
  difficulty: 1,
};
DATA_ANALYSIS[19] = {
  question_text: `A school records the following test score distribution:\n\nScore Range | Number of Students\n90–100      | 8\n80–89       | 15\n70–79       | 20\n60–69       | 10\nBelow 60    | 7\n\nWhat percentage of students scored 80 or above?`,
  choice_a: "37.5%",
  choice_b: "38.3%",
  choice_c: "38.5%",
  choice_d: "40.0%",
  correct_choice: "b",
  explanation: "Students scoring 80+ = 8 + 15 = 23. Total = 8+15+20+10+7 = 60. Percentage = 23/60 × 100 ≈ 38.3%.",
  difficulty: 2,
};

// ── VISUAL & SPATIAL PATTERNS (20 Qs) ────────────────────────────────────────

const VISUAL_PATTERN: Q[] = [
  {
    question_text: `A sequence of shapes follows this pattern: Circle, Square, Triangle, Circle, Square, Triangle, ...\n\nWhat is the 14th shape in the sequence?`,
    choice_a: "Circle",
    choice_b: "Square",
    choice_c: "Triangle",
    choice_d: "Pentagon",
    correct_choice: "b",
    explanation: "The cycle repeats every 3 shapes. 14 ÷ 3 = 4 remainder 2. The 2nd shape in the cycle is Square.",
    difficulty: 1,
  },
  {
    question_text: `In a 3×3 grid of numbers:\n\n1  2  3\n4  5  6\n7  8  ?\n\nWhat number replaces the question mark?`,
    choice_a: "8",
    choice_b: "9",
    choice_c: "10",
    choice_d: "11",
    correct_choice: "b",
    explanation: "The grid contains consecutive integers 1 through 9. The missing number is 9.",
    difficulty: 1,
  },
  {
    question_text: `A tile floor uses the repeating pattern: Black, White, White, Gray, Black, White, White, Gray, ...\n\nWhat color is the 19th tile?`,
    choice_a: "Black",
    choice_b: "White",
    choice_c: "Gray",
    choice_d: "Black and White",
    correct_choice: "a",
    explanation: "The cycle has 4 tiles. 19 ÷ 4 = 4 remainder 3. The 3rd tile in the cycle is White. Wait: Cycle = B, W, W, G. Position 1=B, 2=W, 3=W, 4=G. 19 mod 4 = 3 → 3rd position = White (W).",
    difficulty: 2,
  },
  {
    question_text: `Consider the following number grid:\n\n 2   4   8\n 3   9  27\n 4  16  ?\n\nWhat number replaces the question mark?`,
    choice_a: "32",
    choice_b: "48",
    choice_c: "64",
    choice_d: "128",
    correct_choice: "c",
    explanation: "Each row: column 2 = column 1 squared; column 3 = column 1 cubed. Row 3: 4¹=4, 4²=16, 4³=64.",
    difficulty: 2,
  },
  {
    question_text: `A number pattern is arranged in rows:\nRow 1: 1\nRow 2: 2  3\nRow 3: 4  5  6\nRow 4: 7  8  9  10\n\nWhat is the last number in Row 6?`,
    choice_a: "18",
    choice_b: "19",
    choice_c: "20",
    choice_d: "21",
    correct_choice: "d",
    explanation: "Last number in row n = n(n+1)/2. Row 6: 6×7/2 = 21.",
    difficulty: 2,
  },
  {
    question_text: `Shapes in a row increase in sides: Triangle (3), Square (4), Pentagon (5), Hexagon (6), ...\n\nWhat is the 8th shape?`,
    choice_a: "Octagon",
    choice_b: "Nonagon",
    choice_c: "Decagon",
    choice_d: "Heptagon",
    correct_choice: "c",
    explanation: "The sequence starts at 3 sides. The 8th shape has 3 + (8−1) = 10 sides — a decagon.",
    difficulty: 2,
  },
  {
    question_text: `In the pattern below, find the missing number:\n\n3   6   12\n4   8   16\n5  10   ?\n\nWhat replaces the ?`,
    choice_a: "15",
    choice_b: "18",
    choice_c: "20",
    choice_d: "25",
    correct_choice: "c",
    explanation: "Each row: column 2 = column 1 × 2; column 3 = column 1 × 4. Row 3: 5 × 4 = 20.",
    difficulty: 1,
  },
  {
    question_text: `A color sequence follows: Red, Blue, Green, Red, Blue, Green, ...\n\nIf this sequence is written in a line, what color is in position 25?`,
    choice_a: "Red",
    choice_b: "Blue",
    choice_c: "Green",
    choice_d: "Yellow",
    correct_choice: "a",
    explanation: "Cycle length = 3. 25 ÷ 3 = 8 remainder 1. Position 1 in the cycle = Red.",
    difficulty: 1,
  },
  {
    question_text: `Consider this letter pattern:\nA   C   E   G   ?\n\nWhat letter comes next?`,
    choice_a: "H",
    choice_b: "I",
    choice_c: "J",
    choice_d: "K",
    correct_choice: "b",
    explanation: "The pattern skips one letter each time: A(skip B), C(skip D), E(skip F), G(skip H), I.",
    difficulty: 1,
  },
  {
    question_text: `In the following matrix, what number replaces the ?:\n\n 1   4   9\n16  25  36\n49  64   ?\n\n`,
    choice_a: "72",
    choice_b: "81",
    choice_c: "90",
    choice_d: "100",
    correct_choice: "b",
    explanation: "The matrix contains perfect squares in order: 1²,2²,...,9². The last entry is 9² = 81.",
    difficulty: 1,
  },
  {
    question_text: `A staircase pattern uses blocks: Step 1 has 1 block, Step 2 has 3 blocks, Step 3 has 6 blocks, Step 4 has 10 blocks.\n\nHow many blocks does Step 6 have?`,
    choice_a: "15",
    choice_b: "18",
    choice_c: "21",
    choice_d: "25",
    correct_choice: "c",
    explanation: "Triangular numbers: Step n = n(n+1)/2. Step 6 = 6×7/2 = 21.",
    difficulty: 2,
  },
  {
    question_text: `In a 4×4 number grid, each row and column sums to 34 (magic square property).\n\n16  3  2  13\n 5 10 11   8\n 9  6  7  12\n 4  ?  14   1\n\nWhat is the missing number?`,
    choice_a: "13",
    choice_b: "14",
    choice_c: "15",
    choice_d: "16",
    correct_choice: "c",
    explanation: "The 4th row must sum to 34: 4 + ? + 14 + 1 = 34. ? = 34 − 19 = 15.",
    difficulty: 2,
  },
  {
    question_text: `A spiral number pattern begins at the center and grows outward:\nCenter = 1. The next ring contains numbers 2–9. The next ring contains 10–25.\n\nHow many numbers are in the 4th ring?`,
    choice_a: "16",
    choice_b: "20",
    choice_c: "24",
    choice_d: "28",
    correct_choice: "c",
    explanation: "Ring 1 = 1 number; Ring 2 = 8 numbers; Ring 3 = 16 numbers; Ring 4 = 24 numbers. Each ring adds 8 more than the previous.",
    difficulty: 3,
  },
  {
    question_text: `In this pattern, what comes next?\n\nAA, BB, CC, DD, ?\n\n`,
    choice_a: "DE",
    choice_b: "EE",
    choice_c: "EF",
    choice_d: "FF",
    correct_choice: "b",
    explanation: "Each pair repeats the same letter twice, advancing one letter alphabetically: AA, BB, CC, DD, EE.",
    difficulty: 1,
  },
  {
    question_text: `A sequence of figures shows:\nFigure 1: 4 dots | Figure 2: 9 dots | Figure 3: 16 dots | Figure 4: 25 dots\n\nHow many dots are in Figure 7?`,
    choice_a: "36",
    choice_b: "49",
    choice_c: "64",
    choice_d: "81",
    correct_choice: "c",
    explanation: "The pattern is (n+1)²: Figure 1=(1+1)²=4, Figure 2=(2+1)²=9, ... Figure 7=(7+1)²=64.",
    difficulty: 2,
  },
  {
    question_text: `In the following pattern, find the missing value:\n\nRow 1:   1\nRow 2:   1   1\nRow 3:   1   2   1\nRow 4:   1   3   3   1\nRow 5:   1   4   6   4   1\nRow 6:   1   5  10  10   5   ?\n`,
    choice_a: "1",
    choice_b: "5",
    choice_c: "10",
    choice_d: "15",
    correct_choice: "a",
    explanation: "This is Pascal's Triangle. Each row begins and ends with 1. The last number in Row 6 is 1.",
    difficulty: 2,
  },
  {
    question_text: `In a number grid, every number equals the sum of the two numbers directly above it:\n\nRow 1: 1  2  3  4\nRow 2: 3  5  7\nRow 3: 8  ?\n\nWhat is the missing number?`,
    choice_a: "10",
    choice_b: "11",
    choice_c: "12",
    choice_d: "13",
    correct_choice: "c",
    explanation: "Row 2: 1+2=3, 2+3=5, 3+4=7. Row 3: 3+5=8, 5+7=12.",
    difficulty: 2,
  },
  {
    question_text: `A letter-number sequence follows this pattern: A1, B3, C5, D7, E9, ...\n\nWhat is the 8th term?`,
    choice_a: "G13",
    choice_b: "H15",
    choice_c: "H13",
    choice_d: "G15",
    correct_choice: "b",
    explanation: "Letters advance by 1 (A, B, C...); numbers advance by 2 (1, 3, 5...). 8th letter = H; 8th number = 1 + (8−1)×2 = 15. Answer: H15.",
    difficulty: 2,
  },
  {
    question_text: `A tiling pattern alternates: 1 white tile, 2 black tiles, 1 white tile, 2 black tiles, ...\n\nIn the first 30 tiles, how many are white?`,
    choice_a: "8",
    choice_b: "9",
    choice_c: "10",
    choice_d: "12",
    correct_choice: "c",
    explanation: "Each cycle = 3 tiles (1 white + 2 black). 30 ÷ 3 = 10 complete cycles. White tiles = 10 × 1 = 10.",
    difficulty: 2,
  },
  {
    question_text: `The perimeter of a square is 4n, where n is the side length. In a growing pattern, the sides are 1, 2, 3, 4, 5. What is the sum of the perimeters of all five squares?`,
    choice_a: "50",
    choice_b: "55",
    choice_c: "60",
    choice_d: "65",
    correct_choice: "c",
    explanation: "Perimeters: 4, 8, 12, 16, 20. Sum = 4(1+2+3+4+5) = 4×15 = 60.",
    difficulty: 2,
  },
];

// Fix the tile color question (index 2) — recalculate
VISUAL_PATTERN[2] = {
  question_text: `A tile floor uses the repeating pattern: Black, White, White, Gray, Black, White, White, Gray, ...\n\nWhat color is the 19th tile?`,
  choice_a: "Black",
  choice_b: "White",
  choice_c: "Gray",
  choice_d: "Black and White",
  correct_choice: "b",
  explanation: "Cycle length = 4: positions 1=Black, 2=White, 3=White, 4=Gray. 19 ÷ 4 = 4 remainder 3. 3rd position in cycle = White.",
  difficulty: 2,
};

// ── ABSTRACT REASONING (20 Qs) ───────────────────────────────────────────────

const ABSTRACT_REASONING: Q[] = [
  {
    question_text: `What is the next term in the series?\nZA, YB, XC, WD, __`,
    choice_a: "VD",
    choice_b: "VE",
    choice_c: "UE",
    choice_d: "VF",
    correct_choice: "b",
    explanation: "First letter goes backward (Z, Y, X, W, V); second letter goes forward (A, B, C, D, E). Next = VE.",
    difficulty: 2,
  },
  {
    question_text: `What is the next term in the series?\nAZ, BY, CX, DW, __`,
    choice_a: "EV",
    choice_b: "EU",
    choice_c: "FV",
    choice_d: "EW",
    correct_choice: "a",
    explanation: "First letter advances forward (A, B, C, D, E); second letter goes backward (Z, Y, X, W, V). Next = EV.",
    difficulty: 2,
  },
  {
    question_text: `Which set of letters follows the rule: every third letter of the alphabet?\nA, D, G, J, __`,
    choice_a: "L",
    choice_b: "M",
    choice_c: "N",
    choice_d: "K",
    correct_choice: "b",
    explanation: "A(1), D(4), G(7), J(10), M(13). Each letter is 3 positions after the previous.",
    difficulty: 1,
  },
  {
    question_text: `In a coded language, MANGO is written as NBOHP. How is GUAVA written in the same code?`,
    choice_a: "HVBWB",
    choice_b: "HVBWC",
    choice_c: "ITBXB",
    choice_d: "FUBVZ",
    correct_choice: "a",
    explanation: "Each letter is shifted forward by 1: M+1=N, A+1=B, N+1=O, G+1=H, O+1=P → NBOHP ✓. GUAVA: G+1=H, U+1=V, A+1=B, V+1=W, A+1=B → HVBWB.",
    difficulty: 2,
  },
  {
    question_text: `In a coded language, SCHOOL is written as VFKRRO. What is the code for TEACH?`,
    choice_a: "WHDFK",
    choice_b: "WGDFK",
    choice_c: "VGDFK",
    choice_d: "WHEJK",
    correct_choice: "a",
    explanation: "Each letter shifts forward by 3: S+3=V, C+3=F, H+3=K, O+3=R, O+3=R, L+3=O → VFKRRO ✓. TEACH: T+3=W, E+3=H, A+3=D, C+3=F, H+3=K → WHDFK.",
    difficulty: 2,
  },
  {
    question_text: `What is the next pair in the series?\n2A, 4B, 8C, 16D, __`,
    choice_a: "20E",
    choice_b: "24E",
    choice_c: "32E",
    choice_d: "32F",
    correct_choice: "c",
    explanation: "Numbers double (2, 4, 8, 16, 32); letters advance by one (A, B, C, D, E). Next = 32E.",
    difficulty: 2,
  },
  {
    question_text: `If PENCIL → OFMDLK using a code, what does the code do to each letter?`,
    choice_a: "Each letter shifts backward by 1",
    choice_b: "Each letter shifts forward by 1",
    choice_c: "Each letter shifts backward by 2",
    choice_d: "Alternate letters shift forward and backward",
    correct_choice: "a",
    explanation: "P−1=O, E−1=D, N−1=M, C−1=B... wait: P→O(−1), E→F(+1)? Let me check: PENCIL→OFMDLK. P→O(−1), E→F(+1), N→M(−1), C→D(+1), I→L(+3)? That doesn't follow a simple rule. This question has an error. Replacing with a clean question.",
    difficulty: 2,
  },
  {
    question_text: `Find the missing term:\nB2, D4, F6, H8, __`,
    choice_a: "I9",
    choice_b: "J10",
    choice_c: "K10",
    choice_d: "J12",
    correct_choice: "b",
    explanation: "Letters skip one (B, D, F, H, J); numbers increase by 2 (2, 4, 6, 8, 10). Next = J10.",
    difficulty: 1,
  },
  {
    question_text: `What is the rule in this series?\n1, 4, 13, 40, 121, __`,
    choice_a: "243",
    choice_b: "364",
    choice_c: "365",
    choice_d: "400",
    correct_choice: "b",
    explanation: "Rule: multiply by 3 and add 1. 1×3+1=4, 4×3+1=13, 13×3+1=40, 40×3+1=121, 121×3+1=364.",
    difficulty: 3,
  },
  {
    question_text: `What is the next term?\nABC, BCD, CDE, DEF, __`,
    choice_a: "EFG",
    choice_b: "EFH",
    choice_c: "EFI",
    choice_d: "DFG",
    correct_choice: "a",
    explanation: "Each group advances one letter: ABC → BCD → CDE → DEF → EFG.",
    difficulty: 1,
  },
  {
    question_text: `Find the missing term in the number-letter pattern:\n3C, 5E, 7G, 9I, __`,
    choice_a: "10J",
    choice_b: "11J",
    choice_c: "11K",
    choice_d: "12K",
    correct_choice: "c",
    explanation: "Numbers increase by 2 (3, 5, 7, 9, 11); letters skip one (C, E, G, I, K). Next = 11K.",
    difficulty: 2,
  },
  {
    question_text: `Which number replaces X?\n4 : 64 :: 3 : X`,
    choice_a: "9",
    choice_b: "18",
    choice_c: "27",
    choice_d: "36",
    correct_choice: "c",
    explanation: "4³ = 64. Applying the same rule (cube): 3³ = 27.",
    difficulty: 2,
  },
  {
    question_text: `A code replaces each letter with the one 4 positions forward in the alphabet (Z wraps around to D). What does the code produce from the word MIND?`,
    choice_a: "QMRH",
    choice_b: "QMRI",
    choice_c: "PMRG",
    choice_d: "QLRH",
    correct_choice: "a",
    explanation: "M+4=Q, I+4=M, N+4=R, D+4=H. Code = QMRH.",
    difficulty: 2,
  },
  {
    question_text: `In the series: 2, 3, 5, 7, 11, 13, __\nWhat is the pattern?`,
    choice_a: "Prime numbers",
    choice_b: "Odd numbers",
    choice_c: "Numbers with no factors",
    choice_d: "Fibonacci numbers",
    correct_choice: "a",
    explanation: "The series lists prime numbers in order: 2, 3, 5, 7, 11, 13, 17 (next prime).",
    difficulty: 1,
  },
  {
    question_text: `Find the next term:\nCBA, FED, IHG, LKJ, __`,
    choice_a: "OMN",
    choice_b: "ONM",
    choice_c: "MNO",
    choice_d: "NOM",
    correct_choice: "b",
    explanation: "Each group is three consecutive letters in reverse. LKJ → next three letters from M: O, N, M in reverse = ONM.",
    difficulty: 2,
  },
  {
    question_text: `In a pattern: 144, 121, 100, 81, 64, __\nWhat is the rule and next number?`,
    choice_a: "36",
    choice_b: "49",
    choice_c: "52",
    choice_d: "56",
    correct_choice: "b",
    explanation: "Descending perfect squares: 12²=144, 11²=121, 10²=100, 9²=81, 8²=64, 7²=49.",
    difficulty: 1,
  },
  {
    question_text: `What is the value of X in the relationship?\n25 : 5 :: 81 : X`,
    choice_a: "7",
    choice_b: "8",
    choice_c: "9",
    choice_d: "11",
    correct_choice: "c",
    explanation: "25 is the square of 5 (√25=5). Similarly, √81=9.",
    difficulty: 1,
  },
  {
    question_text: `Find the next three letters in the series:\nA, C, F, J, O, __`,
    choice_a: "S",
    choice_b: "T",
    choice_c: "U",
    choice_d: "V",
    correct_choice: "c",
    explanation: "Differences in position: A(1), C(3), F(6), J(10), O(15), U(21). Differences are +2, +3, +4, +5, +6. Next position = 15+6=21 = letter U.",
    difficulty: 3,
  },
  {
    question_text: `Which number does NOT fit the pattern?\n1, 4, 9, 16, 25, 35, 49`,
    choice_a: "16",
    choice_b: "25",
    choice_c: "35",
    choice_d: "49",
    correct_choice: "c",
    explanation: "All other numbers are perfect squares (1², 2², 3², 4², 5², 7²). 35 is not a perfect square; 6²=36 is missing.",
    difficulty: 2,
  },
  {
    question_text: `A coded number replaces each digit with its complement to 9 (e.g., 3→6, 7→2). What is the code for 1584?`,
    choice_a: "8315",
    choice_b: "8415",
    choice_c: "8514",
    choice_d: "9415",
    correct_choice: "b",
    explanation: "1→8, 5→4, 8→1, 4→5. Code = 8415.",
    difficulty: 2,
  },
];

// Fix the PENCIL code question (index 6) and replace with a clean question
ABSTRACT_REASONING[6] = {
  question_text: `In a code, each letter is replaced by the letter 2 positions behind it in the alphabet (A wraps to Y, B wraps to Z). What is the code for the word GRAPE?`,
  choice_a: "EPCNA",
  choice_b: "EOCNA",
  choice_c: "FOCNB",
  choice_d: "EPCMB",
  correct_choice: "b",
  explanation: "G−2=E, R−2=P, A−2=Y... wait: A wraps to Y? Let me recalculate: each letter shifts back by 2. G(7)→E(5), R(18)→P(16), A(1)→Y(25), P(16)→N(14), E(5)→C(3). Code = EPYNC.",
  difficulty: 2,
};
// The wrap-around makes this tricky - let me simplify
ABSTRACT_REASONING[6] = {
  question_text: `In a coded language, each letter is shifted back by 2 positions. What is the code for MANGO?`,
  choice_a: "KYLEB",
  choice_b: "KYLEP",
  choice_c: "KYLEM",
  choice_d: "KYMEM",
  correct_choice: "c",
  explanation: "M−2=K, A−2=Y, N−2=L, G−2=E, O−2=M. Code = KYLEM.",
  difficulty: 2,
};

// ── MAIN ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Fetching reasoning subtest…");
  const { data: subtest, error } = await supabase
    .from("subtests")
    .select("id, topics(id, slug)")
    .eq("slug", "reasoning")
    .single();

  if (error || !subtest) {
    console.error("Failed to fetch subtest:", error?.message);
    process.exit(1);
  }

  const topics = subtest.topics as { id: string; slug: string }[];
  const topicMap = new Map(topics.map((t) => [t.slug, t.id]));

  console.log("Topics found:", [...topicMap.keys()]);

  const TOPIC_QUESTIONS: [string, Q[]][] = [
    ["logic", LOGIC],
    ["numerical", NUMERICAL],
    ["verbal", VERBAL],
    ["data-analysis", DATA_ANALYSIS],
    ["visual-pattern", VISUAL_PATTERN],
    ["abstract-reasoning", ABSTRACT_REASONING],
  ];

  for (const [slug, questions] of TOPIC_QUESTIONS) {
    const topicId = topicMap.get(slug);
    if (!topicId) {
      console.error(`Topic not found: ${slug}`);
      continue;
    }
    await seedTopic(slug, questions, topicId);
  }

  console.log("\nDone! 120 Reasoning questions seeded.");
}

main().catch(console.error);
