import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface Q {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: number;
}

async function seedTopic(slug: string, questions: Q[], topicId: string) {
  console.log(`\nSeeding ${questions.length} questions for topic: ${slug} (${topicId})`);
  const rows = questions.map((q) => ({
    topic_id: topicId,
    question_text: q.question_text,
    choice_a: q.choice_a,
    choice_b: q.choice_b,
    choice_c: q.choice_c,
    choice_d: q.choice_d,
    correct_choice: q.correct_choice,
    explanation: q.explanation,
    difficulty: q.difficulty,
    status: "approved",
    is_premium: true,
  }));
  const { error } = await supabase.from("questions").insert(rows);
  if (error) { console.error(`  Error seeding ${slug}:`, error.message); return; }
  console.log(`  Inserted ${rows.length} questions.`);
}

// ── MAIN IDEA (Round 2) ──────────────────────────────────────────────────────

const MAIN_IDEA: Q[] = [
  {
    question_text: `The Philippines sits along the Pacific Ring of Fire, making it one of the most geologically active countries in the world. The archipelago experiences frequent earthquakes and volcanic eruptions. While this geological activity poses dangers, it has also shaped the country's fertile soils, which support rich agricultural production. Understanding the risks and benefits of living in a volcanically active region is essential for disaster preparedness.\n\nWhat is the main idea of the passage?`,
    choice_a: "The Philippines has frequent earthquakes that cause destruction.",
    choice_b: "Living near volcanoes makes farming easier for Filipinos.",
    choice_c: "The Philippines' location on the Ring of Fire brings both hazards and benefits.",
    choice_d: "Disaster preparedness is the most important issue in the Philippines.",
    correct_choice: "c",
    explanation: "The passage presents a balanced view—geological activity creates danger but also benefits like fertile soil—making C the best summary of the main idea.",
    difficulty: 2,
  },
  {
    question_text: `Street food is an integral part of Filipino culture. From fish balls and kwek-kwek to isaw and balut, these affordable snacks are sold by vendors across cities and towns. Street food offers locals and tourists an authentic taste of everyday Filipino life. However, concerns about food safety and hygiene have prompted calls for stricter regulations on street food vendors.\n\nWhat is the main idea of the passage?`,
    choice_a: "Street food is dangerous and should be avoided by tourists.",
    choice_b: "Filipino street food is a culturally significant but regulated industry.",
    choice_c: "Fish balls and balut are the most popular street foods in the Philippines.",
    choice_d: "Street food vendors need to earn more income from the government.",
    correct_choice: "b",
    explanation: "The passage covers street food's cultural importance and the regulatory concerns, making B the most complete summary.",
    difficulty: 2,
  },
  {
    question_text: `Wetlands, which include swamps, marshes, and mangroves, are among the most productive ecosystems on Earth. They serve as nurseries for fish, filter pollutants from water, and buffer coastlines against storm surges. Despite their importance, wetlands around the world are disappearing due to land conversion for agriculture, urban development, and pollution. Conservation efforts are urgently needed to protect these vital habitats.\n\nAccording to the passage, which of the following is a function of wetlands?`,
    choice_a: "Providing timber for the construction industry",
    choice_b: "Filtering pollutants from water",
    choice_c: "Supplying fresh drinking water directly to cities",
    choice_d: "Generating hydroelectric power",
    correct_choice: "b",
    explanation: "The passage explicitly states that wetlands 'filter pollutants from water,' making B the correct answer.",
    difficulty: 1,
  },
  {
    question_text: `The rise of social media influencers has transformed advertising. Brands now partner with popular online personalities to promote products, reaching millions of followers in a more personal, authentic way than traditional ads. Influencer marketing is especially effective among younger consumers who trust recommendations from people they follow online. However, critics warn that undisclosed paid partnerships can mislead consumers.\n\nWhat is the main idea of the passage?`,
    choice_a: "Social media influencers are more trustworthy than traditional celebrities.",
    choice_b: "Influencer marketing is an effective but potentially deceptive advertising strategy.",
    choice_c: "Young consumers should not trust online product recommendations.",
    choice_d: "Traditional advertising has been completely replaced by social media.",
    correct_choice: "b",
    explanation: "The passage highlights both the effectiveness of influencer marketing and the concern about undisclosed sponsorships, making B the best main idea.",
    difficulty: 2,
  },
  {
    question_text: `Urban gardening is growing in popularity in Philippine cities. Residents are transforming rooftops, balconies, and vacant lots into productive gardens. These spaces provide fresh vegetables, reduce urban heat, and create green havens in densely built environments. Community gardens also foster social connections among neighbors who work together to maintain them.\n\nAccording to the passage, which detail supports the idea that urban gardens benefit the environment?`,
    choice_a: "Urban gardens create social connections among neighbors.",
    choice_b: "Urban gardens reduce urban heat in cities.",
    choice_c: "Residents use balconies and rooftops for gardening.",
    choice_d: "Urban gardens provide fresh vegetables to families.",
    correct_choice: "b",
    explanation: "Reducing urban heat is an environmental benefit explicitly mentioned in the passage.",
    difficulty: 1,
  },
  {
    question_text: `The Philippines has the highest rate of social media use in the world, with Filipinos spending an average of nearly four hours per day on various platforms. Social media has become a primary source of news, entertainment, and social interaction. While it connects people across distances, concerns about misinformation, online harassment, and addiction are growing among mental health advocates and policy makers.\n\nWhat is the main idea of the passage?`,
    choice_a: "Filipinos should reduce the time they spend on social media each day.",
    choice_b: "Social media is an important source of news for all Filipinos.",
    choice_c: "Despite its connectivity benefits, social media in the Philippines raises serious concerns.",
    choice_d: "Online harassment is the biggest problem facing young Filipinos today.",
    correct_choice: "c",
    explanation: "The passage acknowledges social media's benefits (connectivity) while emphasizing growing concerns, making C the best main idea.",
    difficulty: 2,
  },
  {
    question_text: `Coral reefs cover less than one percent of the ocean floor yet support about twenty-five percent of all marine species. They provide food and income for hundreds of millions of people through fishing and tourism. Climate change, pollution, and destructive fishing practices are rapidly degrading these ecosystems. Scientists warn that without intervention, most of the world's coral reefs could disappear by 2050.\n\nAccording to the passage, which detail explains why coral reefs are economically important?`,
    choice_a: "Coral reefs cover less than one percent of the ocean floor.",
    choice_b: "Coral reefs support twenty-five percent of all marine species.",
    choice_c: "Coral reefs provide food and income through fishing and tourism.",
    choice_d: "Coral reefs could disappear by 2050 without intervention.",
    correct_choice: "c",
    explanation: "The passage states that reefs 'provide food and income for hundreds of millions of people through fishing and tourism,' which is the economic importance detail.",
    difficulty: 1,
  },
  {
    question_text: `Music education has long been considered a luxury in Philippine public schools, often the first program cut when budgets are tight. Yet research consistently shows that students who receive music instruction perform better in mathematics and reading. Music training develops discipline, teamwork, and creative thinking — skills that benefit learners across all subjects. Advocates argue that music should be treated as a core subject, not an elective.\n\nWhat is the main idea of the passage?`,
    choice_a: "Music education is too expensive for public schools to maintain.",
    choice_b: "Music education should be a core subject because of its broad academic and personal benefits.",
    choice_c: "Students who study music always get higher grades than those who do not.",
    choice_d: "Mathematics and reading are the most important subjects in school.",
    correct_choice: "b",
    explanation: "The passage argues for music's core subject status based on academic and personal development benefits, making B the main idea.",
    difficulty: 2,
  },
  {
    question_text: `Traditional weaving is a living art form in many Philippine communities. Tribes like the T'boli, Maranao, and Ifugao produce intricately patterned fabrics using techniques passed down through generations. Each pattern carries cultural meaning, telling stories of ancestry, nature, and belief. As younger generations move to cities, fewer weavers are mastering these crafts, putting traditional textile traditions at risk.\n\nAccording to the passage, what threatens the survival of traditional weaving?`,
    choice_a: "Lack of modern equipment for traditional weavers",
    choice_b: "Fewer young people learning traditional weaving as they move to cities",
    choice_c: "Loss of cultural meaning in weaving patterns",
    choice_d: "Competition from cheaper imported textiles",
    correct_choice: "b",
    explanation: "The passage specifically states that younger generations moving to cities means fewer people mastering these crafts, threatening the tradition.",
    difficulty: 1,
  },
  {
    question_text: `Plastic pollution in the ocean has reached crisis levels. Every year, millions of tons of plastic enter the sea, where it breaks into tiny particles called microplastics. Marine animals ingest these particles, which move up the food chain and ultimately end up in seafood consumed by humans. Reducing single-use plastic production and improving waste management are critical steps toward solving this global problem.\n\nWhat is the main idea of the passage?`,
    choice_a: "Microplastics are found in all marine animals around the world.",
    choice_b: "Ocean plastic pollution threatens marine ecosystems and human health.",
    choice_c: "Banning single-use plastics will completely solve ocean pollution.",
    choice_d: "Humans are the biggest victims of plastic pollution because they eat seafood.",
    correct_choice: "b",
    explanation: "The passage explains how plastic pollution harms marine life and eventually affects humans, making B the best statement of the main idea.",
    difficulty: 2,
  },
  {
    question_text: `The barangay is the smallest political unit in the Philippines. Each barangay is led by a barangay captain and a council that oversees local governance, conflict resolution, and community programs. Barangays serve as the frontline of government services, from health programs to peace and order. Understanding the barangay system is key to understanding how governance reaches ordinary Filipinos.\n\nAccording to the passage, what is the primary role of barangays?`,
    choice_a: "To elect the city mayor and provincial governor",
    choice_b: "To serve as the frontline of government services for citizens",
    choice_c: "To manage national infrastructure projects",
    choice_d: "To collect taxes on behalf of the national government",
    correct_choice: "b",
    explanation: "The passage says barangays 'serve as the frontline of government services,' which is their primary role as stated in the text.",
    difficulty: 1,
  },
  {
    question_text: `Filipino cuisine is a reflection of the country's history. Spanish colonization introduced dishes like adobo, sinigang, and lechon to the Filipino table, while Chinese traders brought pancit and lumpia. American influence added fast food culture and processed foods. Today, Filipino food is a rich fusion of indigenous flavors and foreign influences, making it one of Asia's most diverse culinary traditions.\n\nWhat is the main idea of the passage?`,
    choice_a: "Spanish colonizers had the greatest influence on Filipino cuisine.",
    choice_b: "Filipino cuisine is a diverse blend of indigenous and foreign culinary influences.",
    choice_c: "American fast food has replaced traditional Filipino food in many cities.",
    choice_d: "Pancit and lumpia were invented in the Philippines.",
    correct_choice: "b",
    explanation: "The passage traces multiple foreign influences on Filipino food, concluding it is a 'rich fusion,' making B the main idea.",
    difficulty: 2,
  },
  {
    question_text: `Deforestation in the Philippines has reduced forest cover from about ninety percent of the land area at the turn of the twentieth century to less than twenty percent today. This loss has led to soil erosion, flooding, and the extinction of endemic species. Reforestation programs have been launched by the government, but experts warn that the pace of tree-planting does not match the rate of forest loss.\n\nAccording to the passage, which is a direct consequence of deforestation in the Philippines?`,
    choice_a: "A reduction in agricultural productivity across Luzon",
    choice_b: "Increased flooding and soil erosion",
    choice_c: "The government's decision to launch reforestation programs",
    choice_d: "The reduction of forest cover to fifty percent",
    correct_choice: "b",
    explanation: "The passage explicitly lists 'soil erosion' and 'flooding' as consequences of deforestation.",
    difficulty: 1,
  },
  {
    question_text: `Senior citizens in the Philippines enjoy a range of legal privileges, including a twenty percent discount and VAT exemption on medicines, food, and other goods and services. These benefits are mandated by the Expanded Senior Citizens Act. Despite the law, many seniors report difficulty availing of their discounts due to lack of awareness among establishments or deliberate non-compliance. Advocacy groups continue to push for stricter enforcement.\n\nWhat is the main idea of the passage?`,
    choice_a: "The Expanded Senior Citizens Act gives seniors a ten percent discount on all goods.",
    choice_b: "Senior citizens in the Philippines are fully protected by existing laws.",
    choice_c: "Senior citizen benefits exist by law but enforcement remains a persistent challenge.",
    choice_d: "Advocacy groups should replace government agencies in protecting senior rights.",
    correct_choice: "c",
    explanation: "The passage describes both the legal entitlement and the gap in enforcement, making C the most accurate main idea.",
    difficulty: 2,
  },
  {
    question_text: `Sleep is essential for physical and mental health, yet many Filipinos are chronically sleep-deprived. Studies show that adults need seven to nine hours of sleep per night, but long working hours, long commutes, and heavy screen use push the average Filipino's sleep time well below this threshold. Poor sleep is linked to reduced productivity, weakened immunity, and increased risk of chronic disease. Health experts urge Filipinos to treat adequate sleep as a public health priority.\n\nAccording to the passage, which factor contributes to sleep deprivation among Filipinos?`,
    choice_a: "Eating late at night after long work shifts",
    choice_b: "Long commutes and heavy screen use",
    choice_c: "Lack of awareness about sleep requirements",
    choice_d: "Inadequate healthcare access in rural areas",
    correct_choice: "b",
    explanation: "The passage explicitly names 'long working hours, long commutes, and heavy screen use' as factors reducing sleep time.",
    difficulty: 1,
  },
];

// ── INFERENCE (Round 2) ──────────────────────────────────────────────────────

const INFERENCE: Q[] = [
  {
    question_text: `Maria studied nursing for four years but has been working as a call center agent for the past three years because the salary is significantly higher. She still keeps her nursing license renewed every year.\n\nWhat can be inferred from the passage?`,
    choice_a: "Maria plans to abandon nursing permanently.",
    choice_b: "Maria may eventually return to nursing despite her current career.",
    choice_c: "Maria is unhappy working in the call center industry.",
    choice_d: "Maria renews her license because it is required by her employer.",
    correct_choice: "b",
    explanation: "Renewing her license annually suggests Maria has not ruled out returning to nursing, even though economic reasons keep her in the call center.",
    difficulty: 2,
  },
  {
    question_text: `The river that once ran clear through the village had turned murky and foul-smelling. Children who used to swim there now stayed away. Fishing boats sat unused on the bank. Older villagers shook their heads and spoke of how things used to be.\n\nWhat can be inferred from the passage?`,
    choice_a: "The villagers are planning to relocate to another area.",
    choice_b: "The river's pollution has significantly disrupted the community's way of life.",
    choice_c: "Children are afraid of the river because of rumors.",
    choice_d: "The government has ordered the fishing boats to stop operating.",
    correct_choice: "b",
    explanation: "Children no longer swimming, fishing boats unused, and elders lamenting the past all indicate that pollution has disrupted daily life in the village.",
    difficulty: 2,
  },
  {
    question_text: `Every morning, Lolo Carding waters his small vegetable garden before sunrise, checks each plant carefully, and writes notes in a worn notebook. He has been doing this for forty years.\n\nWhat can be inferred about Lolo Carding?`,
    choice_a: "Lolo Carding sells his vegetables at the local market.",
    choice_b: "Lolo Carding is a retired agricultural scientist.",
    choice_c: "Lolo Carding is disciplined and deeply committed to his garden.",
    choice_d: "Lolo Carding keeps notes because his memory is failing.",
    correct_choice: "c",
    explanation: "The consistent forty-year routine of careful observation and note-taking strongly implies discipline and deep commitment to gardening.",
    difficulty: 1,
  },
  {
    question_text: `The new shopping mall offered dozens of job openings, and hundreds of applicants lined up before dawn on the first day of hiring. Many had traveled from distant provinces.\n\nWhat can be inferred from the passage?`,
    choice_a: "The mall was the largest in the region.",
    choice_b: "Unemployment and limited local job opportunities motivated the large turnout.",
    choice_c: "The mall's management had advertised the jobs on national television.",
    choice_d: "Most applicants were unqualified for the positions available.",
    correct_choice: "b",
    explanation: "Hundreds lining up before dawn, including those from distant provinces, implies high demand for employment due to limited job opportunities elsewhere.",
    difficulty: 2,
  },
  {
    question_text: `The school's top mathematics student spent the last week of summer vacation reviewing her notes instead of joining her friends at the beach. When asked why, she said, "I just want to be ready."\n\nWhat can be inferred about the student?`,
    choice_a: "The student dislikes going to the beach.",
    choice_b: "The student was forced to study by her parents.",
    choice_c: "The student values academic preparedness over leisure.",
    choice_d: "The student expects the upcoming school year to be very difficult.",
    correct_choice: "c",
    explanation: "Voluntarily studying over vacation to 'be ready' shows she prioritizes academic preparedness over leisure activities.",
    difficulty: 1,
  },
  {
    question_text: `After the typhoon, relief goods arrived first in the barangay closest to the main road. Communities deeper in the mountains waited for days. By the time aid reached them, many residents had already begun walking out to find food on their own.\n\nWhat can be inferred from the passage?`,
    choice_a: "Relief organizations deliberately ignored mountain communities.",
    choice_b: "Remote communities face greater challenges in accessing disaster relief.",
    choice_c: "The typhoon was too severe for relief operations to be effective.",
    choice_d: "Mountain residents did not report their situation to authorities.",
    correct_choice: "b",
    explanation: "The delay in reaching communities 'deeper in the mountains' clearly implies that geographic remoteness creates barriers to receiving timely disaster relief.",
    difficulty: 2,
  },
  {
    question_text: `The professor handed back the exam papers without making eye contact with the class. He placed the papers face-down on each desk and said only, "Review your work carefully before next week."\n\nWhat can be inferred from the professor's behavior?`,
    choice_a: "The professor was pleased with the class's overall performance.",
    choice_b: "The professor suspects some students of cheating.",
    choice_c: "The class performed poorly on the exam.",
    choice_d: "The professor is shy and avoids making eye contact with students.",
    correct_choice: "c",
    explanation: "Avoiding eye contact, placing papers face-down, and urging students to 'review carefully' are typical behaviors when a teacher is disappointed with poor results.",
    difficulty: 2,
  },
  {
    question_text: `Mang Ernesto, a jeepney driver for over two decades, began learning to drive a modern e-jeepney three months before the government's deadline to phase out old units. He practiced on weekends and attended a free seminar organized by the transport cooperative.\n\nWhat can be inferred about Mang Ernesto?`,
    choice_a: "Mang Ernesto opposes the government's modernization program.",
    choice_b: "Mang Ernesto is adapting proactively to the transport transition.",
    choice_c: "Mang Ernesto was required by his cooperative to attend the seminar.",
    choice_d: "Mang Ernesto plans to retire before the deadline arrives.",
    correct_choice: "b",
    explanation: "Voluntarily practicing and attending seminars ahead of the deadline shows that Mang Ernesto is proactively preparing for the modernization transition.",
    difficulty: 2,
  },
  {
    question_text: `The small carinderia near the university had been open for thirty years. When a large fast-food chain opened across the street, the carinderia's owner did not lower her prices or change her menu. Within a year, the carinderia was still packed during lunch hour.\n\nWhat can be inferred from the passage?`,
    choice_a: "Students prefer fast food over traditional Filipino meals.",
    choice_b: "The carinderia's loyal customers value its food more than convenience or price.",
    choice_c: "The fast-food chain failed to attract any customers near the university.",
    choice_d: "The carinderia owner was unaware of the new fast-food competitor.",
    correct_choice: "b",
    explanation: "Remaining packed without lowering prices or changing the menu despite nearby competition implies customers are loyal because they value the carinderia's food.",
    difficulty: 2,
  },
  {
    question_text: `Scientists discovered that a species of firefly found only in a small forest in Mindanao has not been seen in the wild for the past five years, despite organized search efforts.\n\nWhat can be inferred from this information?`,
    choice_a: "The firefly species has migrated to a different forest.",
    choice_b: "The firefly species may be extinct or critically endangered.",
    choice_c: "Scientists have stopped searching for the firefly species.",
    choice_d: "The Mindanao forest is too large for effective wildlife surveys.",
    correct_choice: "b",
    explanation: "Five years of unsuccessful searches for a species with a very limited habitat strongly implies it may be extinct or on the edge of extinction.",
    difficulty: 2,
  },
  {
    question_text: `When the scholarship applications opened, hundreds of students submitted their documents within the first hour. The scholarship office ran out of printed forms by mid-morning.\n\nWhat can be inferred from the passage?`,
    choice_a: "The scholarship is new and was not well publicized.",
    choice_b: "Financial need among students is widespread.",
    choice_c: "The scholarship office was poorly managed.",
    choice_d: "Most students prefer printed forms over online applications.",
    correct_choice: "b",
    explanation: "The overwhelming immediate response to scholarship applications implies that many students have significant financial need.",
    difficulty: 1,
  },
  {
    question_text: `The archaeologist brushed dirt from the artifact carefully, took photographs from multiple angles, and labeled the site coordinates on her map before placing the object in a padded case. She worked slowly despite the heat.\n\nWhat can be inferred about the archaeologist?`,
    choice_a: "The archaeologist is new to field work and unsure of the correct procedures.",
    choice_b: "The archaeologist believes the artifact is extremely valuable.",
    choice_c: "The archaeologist prioritizes accuracy and preservation over speed.",
    choice_d: "The archaeologist is preparing to sell the artifact to a private collector.",
    correct_choice: "c",
    explanation: "The careful, multi-step documentation process performed despite the heat shows a priority for accuracy and preservation, which is standard professional archaeological practice.",
    difficulty: 2,
  },
  {
    question_text: `Despite scoring in the top five percent of all UPCAT takers, Lea chose to enroll in a state university in her province rather than attending UP Diliman. She explained that staying close to her family was more important to her than prestige.\n\nWhat can be inferred about Lea?`,
    choice_a: "Lea is not academically competitive enough for UP Diliman.",
    choice_b: "Lea's family pressured her to stay in the province.",
    choice_c: "Lea prioritizes family ties over academic prestige.",
    choice_d: "Lea plans to transfer to UP Diliman in her second year.",
    correct_choice: "c",
    explanation: "Lea explicitly states that family closeness mattered more than prestige, and her choice reflects that personal value.",
    difficulty: 1,
  },
  {
    question_text: `The documentary film about the Mayon Volcano attracted thousands of viewers online within days of its release. Comments praised its stunning visuals but lamented that the communities at risk near the volcano still lacked adequate evacuation plans.\n\nWhat can be inferred from the viewers' comments?`,
    choice_a: "Viewers believe the documentary was inaccurate in its portrayal of the volcano.",
    choice_b: "Public interest in Mayon Volcano is driven mainly by its scenic beauty.",
    choice_c: "Admiring natural beauty does not eliminate concern for vulnerable communities.",
    choice_d: "The documentary was produced by the government as a tourism promotion.",
    correct_choice: "c",
    explanation: "Viewers praised the visuals while also expressing concern about evacuation plans, showing that aesthetic appreciation and humanitarian concern can coexist.",
    difficulty: 3,
  },
  {
    question_text: `The neighborhood's oldest tree, a century-old acacia, was cut down overnight to make way for a new commercial building. By morning, residents had gathered around the empty space where the tree had stood, some placing flowers on the stump.\n\nWhat can be inferred from the residents' behavior?`,
    choice_a: "Residents are angry at the construction company and will file a complaint.",
    choice_b: "The acacia tree held sentimental and communal significance for residents.",
    choice_c: "The residents gathered to prevent further trees from being cut.",
    choice_d: "Residents were surprised because the tree had been healthy.",
    correct_choice: "b",
    explanation: "Gathering at the site and leaving flowers on the stump is a mourning-like gesture indicating deep sentimental attachment to the lost tree.",
    difficulty: 2,
  },
];

// ── VOCABULARY IN CONTEXT (Round 2) ─────────────────────────────────────────

const VOCAB_IN_CONTEXT: Q[] = [
  {
    question_text: `The treaty was met with widespread acclaim from the international community, who praised the two nations for their willingness to cooperate.\n\nThe word "acclaim" most nearly means:`,
    choice_a: "criticism",
    choice_b: "indifference",
    choice_c: "approval and praise",
    choice_d: "surprise",
    correct_choice: "c",
    explanation: "'Acclaim' means enthusiastic praise or approval. The context confirms this with 'praised the two nations.'",
    difficulty: 2,
  },
  {
    question_text: `The scientist's theory was initially deemed implausible by her peers, who found the hypothesis too radical to accept without further evidence.\n\nThe word "implausible" most nearly means:`,
    choice_a: "unconvincing or unlikely",
    choice_b: "well-supported",
    choice_c: "revolutionary",
    choice_d: "dangerous",
    correct_choice: "a",
    explanation: "'Implausible' means not seeming reasonable or probable. The context — peers finding it 'too radical' — confirms the meaning.",
    difficulty: 2,
  },
  {
    question_text: `The program aimed to empower marginalized communities by giving them access to legal resources and educational opportunities previously unavailable to them.\n\nThe word "marginalized" most nearly means:`,
    choice_a: "wealthy and influential",
    choice_b: "treated as insignificant or excluded from mainstream society",
    choice_c: "located on the margins of urban areas",
    choice_d: "recently formed or organized",
    correct_choice: "b",
    explanation: "'Marginalized' refers to groups treated as socially unimportant or excluded from full participation in society.",
    difficulty: 2,
  },
  {
    question_text: `The CEO's candid interview surprised many shareholders, who were accustomed to vague, carefully worded corporate statements.\n\nThe word "candid" most nearly means:`,
    choice_a: "lengthy and detailed",
    choice_b: "honest and straightforward",
    choice_c: "aggressive and confrontational",
    choice_d: "rehearsed and polished",
    correct_choice: "b",
    explanation: "'Candid' means truthful and straightforward, which contrasts with the 'vague, carefully worded' responses shareholders usually expected.",
    difficulty: 2,
  },
  {
    question_text: `The village elder's wisdom was revered throughout the province; people traveled great distances to seek her counsel on matters both personal and communal.\n\nThe word "revered" most nearly means:`,
    choice_a: "feared",
    choice_b: "deeply respected and admired",
    choice_c: "tolerated despite flaws",
    choice_d: "frequently misunderstood",
    correct_choice: "b",
    explanation: "'Revered' means regarded with great respect and awe. People traveling far to seek her counsel reinforces this meaning.",
    difficulty: 1,
  },
  {
    question_text: `The artist's abstract paintings were controversial; some critics found them profound, while others considered them incoherent scribbles without meaning.\n\nThe word "incoherent" most nearly means:`,
    choice_a: "lacking clear or logical connection",
    choice_b: "technically advanced",
    choice_c: "emotionally moving",
    choice_d: "highly detailed and precise",
    correct_choice: "a",
    explanation: "'Incoherent' means lacking logical connection or clarity. This contrasts with 'profound' and fits the critics' negative view.",
    difficulty: 2,
  },
  {
    question_text: `The politician's populist rhetoric resonated with rural voters who felt neglected by the urban-centered government policies.\n\nThe word "rhetoric" most nearly means:`,
    choice_a: "financial promises made during a campaign",
    choice_b: "language used effectively to persuade an audience",
    choice_c: "written legislation submitted to congress",
    choice_d: "verbal attacks against political opponents",
    correct_choice: "b",
    explanation: "'Rhetoric' refers to persuasive or impressive-sounding language used in speech or writing, particularly in political contexts.",
    difficulty: 3,
  },
  {
    question_text: `The athlete's tenacity during the final grueling kilometers of the marathon inspired the crowd, who watched her fight through exhaustion to finish the race.\n\nThe word "tenacity" most nearly means:`,
    choice_a: "speed and agility",
    choice_b: "determination and persistence despite difficulty",
    choice_c: "calmness under pressure",
    choice_d: "physical strength",
    correct_choice: "b",
    explanation: "'Tenacity' means persistent determination. Fighting through exhaustion to finish illustrates this quality.",
    difficulty: 1,
  },
  {
    question_text: `The town's water supply became contaminated after heavy rains caused runoff from a nearby landfill to seep into the reservoir, making the water unfit for consumption.\n\nThe word "contaminated" most nearly means:`,
    choice_a: "reduced in quantity",
    choice_b: "made impure or unsafe through the introduction of harmful substances",
    choice_c: "temporarily unavailable",
    choice_d: "treated with chemicals to remove minerals",
    correct_choice: "b",
    explanation: "'Contaminated' means made impure by exposure to or addition of a polluting substance. The landfill runoff made the water 'unfit for consumption.'",
    difficulty: 1,
  },
  {
    question_text: `The negotiators reached an amicable settlement after months of dispute, with both sides expressing satisfaction with the outcome.\n\nThe word "amicable" most nearly means:`,
    choice_a: "legally binding",
    choice_b: "friendly and without hostility",
    choice_c: "unexpected and surprising",
    choice_d: "financially beneficial",
    correct_choice: "b",
    explanation: "'Amicable' means characterized by friendliness and goodwill. Both sides being satisfied suggests a harmonious resolution.",
    difficulty: 2,
  },
  {
    question_text: `The documentary exposed the egregious working conditions in the factory, shocking viewers with footage of child labor and unsafe equipment.\n\nThe word "egregious" most nearly means:`,
    choice_a: "slightly concerning",
    choice_b: "outrageously bad or shocking",
    choice_c: "unusual but not harmful",
    choice_d: "well-documented and legal",
    correct_choice: "b",
    explanation: "'Egregious' means outstandingly bad or shocking. Child labor and unsafe equipment being filmed 'shocking viewers' supports this meaning.",
    difficulty: 3,
  },
  {
    question_text: `The professor encouraged students to question prevailing assumptions rather than accept established knowledge as immutable truth.\n\nThe word "immutable" most nearly means:`,
    choice_a: "ancient and traditional",
    choice_b: "unchanging and permanent",
    choice_c: "complex and difficult to understand",
    choice_d: "widely accepted but unproven",
    correct_choice: "b",
    explanation: "'Immutable' means unchanging over time. The professor is encouraging students not to treat knowledge as permanent and fixed.",
    difficulty: 3,
  },
  {
    question_text: `The orphanage relied on the benevolence of local businesses and community members who regularly donated food, clothing, and school supplies.\n\nThe word "benevolence" most nearly means:`,
    choice_a: "legal obligation",
    choice_b: "goodwill and generosity toward others",
    choice_c: "financial investment for future return",
    choice_d: "government funding allocated for charities",
    correct_choice: "b",
    explanation: "'Benevolence' means the quality of being well-meaning and generous. Voluntary donations of food and supplies illustrate this.",
    difficulty: 1,
  },
  {
    question_text: `The company's rapid expansion into Southeast Asian markets was a strategic maneuver designed to outpace its competitors before the year's end.\n\nThe word "maneuver" most nearly means:`,
    choice_a: "a mistake made during a difficult situation",
    choice_b: "a careful or skillful action or plan",
    choice_c: "a legal contract signed between two parties",
    choice_d: "an unexpected change in company leadership",
    correct_choice: "b",
    explanation: "'Maneuver' refers to a planned and skillful move or action. The strategic, competitive context confirms this meaning.",
    difficulty: 2,
  },
  {
    question_text: `The barangay captain's speech was eloquent, moving many residents to tears as he described the sacrifices made by those who rebuilt the community after the flood.\n\nThe word "eloquent" most nearly means:`,
    choice_a: "long and repetitive",
    choice_b: "fluent and persuasive in speech or writing",
    choice_c: "formal and difficult to understand",
    choice_d: "softly spoken and barely audible",
    correct_choice: "b",
    explanation: "'Eloquent' means having or exercising the power of fluent, forceful, and appropriate speech. Moving people to tears confirms the speech's power.",
    difficulty: 1,
  },
];

// ── LITERARY ANALYSIS (Round 2) ──────────────────────────────────────────────

const LITERARY_ANALYSIS: Q[] = [
  {
    question_text: `"Her voice was a waterfall, rushing and relentless, filling every silence in the room."\n\nWhich literary device is used in this sentence?`,
    choice_a: "Simile",
    choice_b: "Personification",
    choice_c: "Metaphor",
    choice_d: "Hyperbole",
    correct_choice: "c",
    explanation: "The sentence directly compares the voice to a waterfall without using 'like' or 'as,' making it a metaphor.",
    difficulty: 1,
  },
  {
    question_text: `"The wind whispered secrets through the bamboo groves at midnight."\n\nWhich literary device is used in this sentence?`,
    choice_a: "Simile",
    choice_b: "Metaphor",
    choice_c: "Personification",
    choice_d: "Onomatopoeia",
    correct_choice: "c",
    explanation: "Attributing the human action of 'whispering secrets' to the wind is personification.",
    difficulty: 1,
  },
  {
    question_text: `"His smile was as warm as sunlight on a cold morning."\n\nWhich literary device is used in this sentence?`,
    choice_a: "Personification",
    choice_b: "Simile",
    choice_c: "Metaphor",
    choice_d: "Irony",
    correct_choice: "b",
    explanation: "The comparison uses 'as … as,' which is the hallmark of a simile.",
    difficulty: 1,
  },
  {
    question_text: `Read the following excerpt:\n\n"The examination results were posted on the bulletin board. Luis, who had barely opened a book all semester, placed first. His diligent seatmate, who had studied every night for months, placed last."\n\nWhich type of irony does this excerpt illustrate?`,
    choice_a: "Verbal irony",
    choice_b: "Dramatic irony",
    choice_c: "Situational irony",
    choice_d: "Cosmic irony",
    correct_choice: "c",
    explanation: "Situational irony occurs when the outcome is the opposite of what is expected. The diligent student failing while the lazy one succeeds is an unexpected reversal.",
    difficulty: 2,
  },
  {
    question_text: `Read the following passage:\n\n"The old fisherman sat alone on the shore each evening, watching the sea. He had given his whole life to the water — his youth, his strength, his closest friend. Now the sea gave him only silence in return."\n\nWhat is the dominant mood of this passage?`,
    choice_a: "Joyful and optimistic",
    choice_b: "Melancholy and lonely",
    choice_c: "Tense and suspenseful",
    choice_d: "Humorous and lighthearted",
    correct_choice: "b",
    explanation: "The imagery of loss (youth, strength, friend), sitting alone, and the sea returning only silence creates a melancholy and lonely mood.",
    difficulty: 2,
  },
  {
    question_text: `"Bells below the baobab beat a bright, bold, brilliant beat."\n\nThis sentence is an example of:`,
    choice_a: "Assonance",
    choice_b: "Alliteration",
    choice_c: "Onomatopoeia",
    choice_d: "Rhyme",
    correct_choice: "b",
    explanation: "Alliteration is the repetition of the same initial consonant sound in closely connected words. All major words begin with 'b.'",
    difficulty: 1,
  },
  {
    question_text: `Read the following excerpt:\n\n"The school principal proudly announced that the student who vandalized the gymnasium walls had been given the 'Student of the Month' award for his artistic talents."\n\nWhat literary device does the principal's announcement illustrate?`,
    choice_a: "Verbal irony",
    choice_b: "Situational irony",
    choice_c: "Understatement",
    choice_d: "Hyperbole",
    correct_choice: "a",
    explanation: "Verbal irony (sarcasm) occurs when something is said but the opposite is meant. The principal sarcastically calls vandalism 'artistic talent.'",
    difficulty: 2,
  },
  {
    question_text: `Read the following passage:\n\n"The author describes the government's response to the flooding as 'prompt and well-coordinated' while noting that relief goods arrived twelve days after the typhoon and only after national television crews showed up."\n\nWhat is the author's tone?`,
    choice_a: "Admiring and supportive",
    choice_b: "Neutral and objective",
    choice_c: "Satirical and critical",
    choice_d: "Sympathetic and sorrowful",
    correct_choice: "c",
    explanation: "Calling the response 'prompt' while noting the twelve-day delay and media-driven arrival reveals sarcasm and critical intent — a satirical tone.",
    difficulty: 3,
  },
  {
    question_text: `Read the following excerpt:\n\n"I have told you a thousand times: do not leave your shoes by the front door!"\n\nWhich literary device is used?`,
    choice_a: "Simile",
    choice_b: "Alliteration",
    choice_c: "Hyperbole",
    choice_d: "Flashback",
    correct_choice: "c",
    explanation: "Saying 'a thousand times' is an obvious exaggeration used for emphasis, which is hyperbole.",
    difficulty: 1,
  },
  {
    question_text: `Read the following passage:\n\n"Dr. Reyes had spent decades documenting endangered Philippine birds. She wrote not to impress academics but to ensure that every Filipino child could one day read about the creatures their ancestors knew."\n\nWhat is the author's primary purpose?`,
    choice_a: "To entertain readers with stories about wildlife",
    choice_b: "To persuade readers to become ornithologists",
    choice_c: "To honor a scientist's mission to preserve natural and cultural heritage",
    choice_d: "To inform readers about specific species of Philippine birds",
    correct_choice: "c",
    explanation: "The passage focuses on Dr. Reyes's motivation — preservation for future Filipinos — which frames it as a tribute to her conservation mission.",
    difficulty: 2,
  },
  {
    question_text: `Read the following story opening:\n\n"Nobody suspected that the quiet girl who sat alone in the last row would one day become the country's most celebrated poet."\n\nFrom which point of view is this story told?`,
    choice_a: "First person",
    choice_b: "Second person",
    choice_c: "Third person limited",
    choice_d: "Third person omniscient",
    correct_choice: "d",
    explanation: "The narrator reveals what 'nobody suspected' about a character's future, indicating omniscient knowledge beyond any single character's perspective.",
    difficulty: 2,
  },
  {
    question_text: `Read the following passage:\n\n"The empty school courtyard was filled with the echoes of children who had played there years before. The rusted swings creaked in the wind, as if remembering the weight of small, laughing bodies."\n\nWhich literary device is most evident in the phrase 'as if remembering the weight'?`,
    choice_a: "Simile",
    choice_b: "Metaphor",
    choice_c: "Personification",
    choice_d: "Allusion",
    correct_choice: "c",
    explanation: "'Remembering' is a human cognitive action attributed to the inanimate swings, making this personification.",
    difficulty: 2,
  },
  {
    question_text: `Read the following excerpt:\n\n"Mang Andoy laughed as he counted his coins — forty pesos for a full day's work under the scorching sun. 'More than enough,' he said."\n\nWhich literary device does Mang Andoy's statement illustrate?`,
    choice_a: "Hyperbole",
    choice_b: "Understatement",
    choice_c: "Metaphor",
    choice_d: "Dramatic irony",
    correct_choice: "b",
    explanation: "Calling forty pesos for a full day in the scorching sun 'more than enough' understates the hardship and inadequacy of his earnings.",
    difficulty: 3,
  },
  {
    question_text: `Read the following passage:\n\n"The novel's narrator frequently mentions small, forgotten details — the smell of her mother's cooking, the pattern on the kitchen floor tiles, the sound of the radio on Sunday mornings — while describing life abroad."\n\nWhat theme does this narrative technique most strongly suggest?`,
    choice_a: "The importance of cooking in Filipino culture",
    choice_b: "The narrator's longing for home and childhood",
    choice_c: "The difficulty of adjusting to life in a foreign country",
    choice_d: "The narrator's regret over leaving her family behind",
    correct_choice: "b",
    explanation: "Recalling sensory details of home while living abroad is a classic technique to convey nostalgia and longing for one's roots.",
    difficulty: 3,
  },
  {
    question_text: `Read the following passage:\n\n"After the earthquake, neighbors who had never spoken to each other were suddenly sharing food, tools, and shelter. The disaster stripped away the indifference that had grown between them over the years."\n\nWhat theme does this passage convey?`,
    choice_a: "Natural disasters destroy communities and isolate individuals.",
    choice_b: "Crisis can reawaken human compassion and community bonds.",
    choice_c: "Neighbors should not wait for disasters to cooperate.",
    choice_d: "Sharing resources is the most effective response to emergencies.",
    correct_choice: "b",
    explanation: "The passage shows how crisis broke through neighbors' indifference and restored a sense of community, conveying the theme that adversity can revive human connection.",
    difficulty: 2,
  },
];

// ── CONTEXT CLUES (Round 2) ──────────────────────────────────────────────────

const CONTEXT_CLUES: Q[] = [
  {
    question_text: `The professor was known for her acerbic remarks, which often left students feeling stung and embarrassed in front of the class.\n\nBased on context clues, "acerbic" most likely means:`,
    choice_a: "thoughtful and constructive",
    choice_b: "sharp and harsh in tone",
    choice_c: "quiet and reserved",
    choice_d: "overly enthusiastic",
    correct_choice: "b",
    explanation: "Remarks that leave students 'stung and embarrassed' suggest the word means sharp and harsh.",
    difficulty: 2,
  },
  {
    question_text: `The hikers were exhausted after the arduous trek through the jungle, taking five times longer than the estimated travel time.\n\nBased on context clues, "arduous" most likely means:`,
    choice_a: "short and easy",
    choice_b: "scenic and enjoyable",
    choice_c: "long, difficult, and tiring",
    choice_d: "dangerously unsafe",
    correct_choice: "c",
    explanation: "Exhaustion after a trek taking five times longer than expected indicates the journey was difficult and tiring.",
    difficulty: 1,
  },
  {
    question_text: `The council voted to rescind its earlier decision after new evidence revealed that the original policy had been based on inaccurate data.\n\nBased on context clues, "rescind" most likely means:`,
    choice_a: "strengthen and expand",
    choice_b: "formally withdraw or cancel",
    choice_c: "publicize and promote",
    choice_d: "investigate and review",
    correct_choice: "b",
    explanation: "Reacting to inaccurate data by 'rescinding' a decision implies canceling or reversing it.",
    difficulty: 2,
  },
  {
    question_text: `The child gazed at the towering building with wide eyes, visibly awestruck by its sheer scale and glittering glass facade.\n\nBased on context clues, "awestruck" most likely means:`,
    choice_a: "confused and disoriented",
    choice_b: "deeply frightened",
    choice_c: "overwhelmed with wonder and admiration",
    choice_d: "bored and unimpressed",
    correct_choice: "c",
    explanation: "Wide eyes gazing at the impressive building convey wonder and admiration, which is what 'awestruck' means.",
    difficulty: 1,
  },
  {
    question_text: `The mayor's response to the reporter's question was deliberately ambiguous, giving neither a clear yes nor a definite no.\n\nBased on context clues, "ambiguous" most likely means:`,
    choice_a: "confident and decisive",
    choice_b: "open to more than one interpretation; unclear",
    choice_c: "angry and defensive",
    choice_d: "overly lengthy and detailed",
    correct_choice: "b",
    explanation: "An answer that is 'neither a clear yes nor a definite no' is open to multiple interpretations — that is ambiguous.",
    difficulty: 2,
  },
  {
    question_text: `Her persistent and dogged pursuit of the truth, even after being told to drop the story, eventually led the journalist to uncover the corruption.\n\nBased on context clues, "dogged" most likely means:`,
    choice_a: "distracted and unfocused",
    choice_b: "relentless and determined",
    choice_c: "reckless and impulsive",
    choice_d: "slow and methodical",
    correct_choice: "b",
    explanation: "'Persistent and dogged' are paired together, and the outcome (uncovering corruption despite being told to stop) confirms the meaning of determined and relentless.",
    difficulty: 2,
  },
  {
    question_text: `The two senators who had been bitter rivals for years reached a tacit understanding during the negotiations — neither spoke of it openly, but both began voting in alignment on key bills.\n\nBased on context clues, "tacit" most likely means:`,
    choice_a: "unexpected and surprising",
    choice_b: "understood without being stated aloud",
    choice_c: "formally agreed upon and documented",
    choice_d: "temporary and unreliable",
    correct_choice: "b",
    explanation: "'Neither spoke of it openly' but both acted on it defines a tacit (unspoken, implied) agreement.",
    difficulty: 3,
  },
  {
    question_text: `The charity's resources were finite, so its directors had to prioritize which communities would receive aid and which would have to wait.\n\nBased on context clues, "finite" most likely means:`,
    choice_a: "poorly managed",
    choice_b: "highly valuable",
    choice_c: "limited and not endless",
    choice_d: "shared equally among all recipients",
    correct_choice: "c",
    explanation: "Having to prioritize because resources are 'finite' implies there is not enough for everyone — the resources are limited.",
    difficulty: 1,
  },
  {
    question_text: `The student's meticulous lab report impressed her teacher: every measurement was recorded precisely, each step was documented, and the conclusion was clearly reasoned.\n\nBased on context clues, "meticulous" most likely means:`,
    choice_a: "creative and innovative",
    choice_b: "showing great attention to detail",
    choice_c: "unnecessarily long and wordy",
    choice_d: "confidently written but untested",
    correct_choice: "b",
    explanation: "Precise measurements, full documentation, and clear reasoning describe careful, detail-oriented work — meticulous.",
    difficulty: 1,
  },
  {
    question_text: `After the long drought, the first heavy rains were a welcome respite for the farmers, who had watched their crops wither for months.\n\nBased on context clues, "respite" most likely means:`,
    choice_a: "a short delay",
    choice_b: "a temporary relief from something difficult",
    choice_c: "a permanent solution to a problem",
    choice_d: "an unexpected and dangerous event",
    correct_choice: "b",
    explanation: "Rain being 'welcome' after months of drought and crop damage indicates it provided relief — even if temporary.",
    difficulty: 2,
  },
  {
    question_text: `The hospital's labyrinthine corridors confused most first-time visitors, who often needed a staff member to guide them to the correct ward.\n\nBased on context clues, "labyrinthine" most likely means:`,
    choice_a: "brightly lit and modern",
    choice_b: "narrow and uncomfortable",
    choice_c: "complicated, with many twists and turns",
    choice_d: "noisy and crowded",
    correct_choice: "c",
    explanation: "Corridors that confuse visitors to the point of needing a guide suggest they are complex and maze-like — labyrinthine.",
    difficulty: 2,
  },
  {
    question_text: `Despite the adversity she faced — poverty, illness, and the loss of her father — she remained stoic, rarely showing her distress to those around her.\n\nBased on context clues, "stoic" most likely means:`,
    choice_a: "unable to feel emotions",
    choice_b: "enduring hardship without displaying emotions",
    choice_c: "pretending to be happy for others' benefit",
    choice_d: "easily overwhelmed by grief",
    correct_choice: "b",
    explanation: "Facing significant hardship while 'rarely showing distress' describes a stoic person who bears suffering without outward complaint.",
    difficulty: 2,
  },
  {
    question_text: `The charity's annual gala was a lavish affair — a five-course dinner, a live orchestra, and decorations that must have cost a fortune — raising questions about whether such excess was appropriate for a nonprofit.\n\nBased on context clues, "lavish" most likely means:`,
    choice_a: "simple and understated",
    choice_b: "elegant but affordable",
    choice_c: "sumptuously rich and extravagant",
    choice_d: "hastily organized",
    correct_choice: "c",
    explanation: "Five-course dinner, live orchestra, and expensive decorations all point to extravagance, which is the meaning of 'lavish.'",
    difficulty: 1,
  },
  {
    question_text: `Scientists warn that the situation is precarious: one more degree of warming could trigger irreversible changes in the planet's climate systems.\n\nBased on context clues, "precarious" most likely means:`,
    choice_a: "stable and well-understood",
    choice_b: "dangerously uncertain and potentially harmful",
    choice_c: "improving but slowly",
    choice_d: "already at a point of no return",
    correct_choice: "b",
    explanation: "A small change that could trigger 'irreversible' effects describes a dangerously uncertain situation — precarious.",
    difficulty: 2,
  },
  {
    question_text: `The suspect's alibi was corroborated by three independent witnesses, each of whom placed him at a different location far from the scene of the crime.\n\nBased on context clues, "corroborated" most likely means:`,
    choice_a: "weakened by additional information",
    choice_b: "supported and confirmed by evidence",
    choice_c: "challenged in court",
    choice_d: "created by the defense attorneys",
    correct_choice: "b",
    explanation: "Independent witnesses confirming the alibi means it was corroborated — supported or confirmed by other evidence.",
    difficulty: 2,
  },
];

// ── FACT VS OPINION (Round 2) ────────────────────────────────────────────────

const FACT_VS_OPINION: Q[] = [
  {
    question_text: `Which of the following is a FACT?\n\nA. The Philippine peso is the weakest currency in Southeast Asia.\nB. The Bangsamoro Autonomous Region in Muslim Mindanao (BARMM) was established in 2019.\nC. The government should prioritize building more public hospitals.\nD. Filipino workers are the hardest-working in the world.`,
    choice_a: "The Philippine peso is the weakest currency in Southeast Asia.",
    choice_b: "The Bangsamoro Autonomous Region in Muslim Mindanao (BARMM) was established in 2019.",
    choice_c: "The government should prioritize building more public hospitals.",
    choice_d: "Filipino workers are the hardest-working in the world.",
    correct_choice: "b",
    explanation: "BARMM's establishment in 2019 is a verifiable historical fact. Options A and D involve comparative judgments that are not factually precise; option C is a policy opinion.",
    difficulty: 1,
  },
  {
    question_text: `Which of the following is an OPINION?\n\nA. The Philippines has over 7,000 islands.\nB. Tagalog is one of the major languages spoken in the Philippines.\nC. Visiting Palawan is a more rewarding experience than visiting Boracay.\nD. The Philippine Sea is part of the Pacific Ocean.`,
    choice_a: "The Philippines has over 7,000 islands.",
    choice_b: "Tagalog is one of the major languages spoken in the Philippines.",
    choice_c: "Visiting Palawan is a more rewarding experience than visiting Boracay.",
    choice_d: "The Philippine Sea is part of the Pacific Ocean.",
    correct_choice: "c",
    explanation: "Comparing the 'reward' of visiting two destinations is a subjective judgment — an opinion. The other three are verifiable facts.",
    difficulty: 1,
  },
  {
    question_text: `Read the following passage and identify the sentence that expresses an OPINION:\n\n"The K-12 Basic Education Program extended basic schooling in the Philippines from ten to twelve years. (1) The program added two years of Senior High School to the curriculum. (2) Senior High School students choose from academic, technical-vocational, sports, or arts and design tracks. (3) The additional two years are a waste of time that should have been spent in college. (4) Enrollment in Grade 11 reached over 1.5 million students in the program's first year."\n\nWhich sentence is an OPINION?`,
    choice_a: "Sentence 1",
    choice_b: "Sentence 2",
    choice_c: "Sentence 3",
    choice_d: "Sentence 4",
    correct_choice: "c",
    explanation: "Sentence 3 expresses a negative value judgment about the program ('waste of time'). Sentences 1, 2, and 4 are verifiable facts.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is a FACT?\n\nA. Children learn best when they are allowed to play freely rather than attend structured classes.\nB. Studies show that regular physical activity reduces the risk of type 2 diabetes.\nC. Filipino family values are superior to those of Western cultures.\nD. The government wastes too much money on infrastructure projects.`,
    choice_a: "Children learn best when allowed to play freely rather than attend structured classes.",
    choice_b: "Studies show that regular physical activity reduces the risk of type 2 diabetes.",
    choice_c: "Filipino family values are superior to those of Western cultures.",
    choice_d: "The government wastes too much money on infrastructure projects.",
    correct_choice: "b",
    explanation: "The link between physical activity and reduced diabetes risk is supported by scientific research and verifiable. The other options reflect subjective beliefs or unsupported generalizations.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is an OPINION?\n\nA. Mount Apo is the highest mountain in the Philippines at 2,954 meters.\nB. Adobo is the most delicious Filipino dish ever created.\nC. The 1987 Philippine Constitution includes a Bill of Rights.\nD. The Philippines became independent from the United States on July 4, 1946.`,
    choice_a: "Mount Apo is the highest mountain in the Philippines at 2,954 meters.",
    choice_b: "Adobo is the most delicious Filipino dish ever created.",
    choice_c: "The 1987 Philippine Constitution includes a Bill of Rights.",
    choice_d: "The Philippines became independent on July 4, 1946.",
    correct_choice: "b",
    explanation: "Calling adobo 'the most delicious dish ever created' is a subjective judgment of taste — an opinion. The other statements are verifiable facts.",
    difficulty: 1,
  },
  {
    question_text: `Read the following passage:\n\n"The Philippines ranked among the top five countries in the world with the highest rates of online abuse against women and girls. Various laws, including the Anti-Violence Against Women and Children Act, exist to protect victims. However, these laws are clearly not being enforced strictly enough, as the numbers continue to rise. The government must do more."\n\nWhich sentence states a FACT?`,
    choice_a: "These laws are clearly not being enforced strictly enough.",
    choice_b: "The government must do more.",
    choice_c: "The Philippines ranked among the top five countries for online abuse against women and girls.",
    choice_d: "Both A and B are facts.",
    correct_choice: "c",
    explanation: "A country's ranking is based on measurable data — a verifiable fact. Sentences A and B involve judgment and prescription, making them opinions.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is a FACT?\n\nA. Online learning is always less effective than face-to-face instruction.\nB. The COVID-19 pandemic forced Philippine schools to shift to distance learning in 2020.\nC. Students who study online are less disciplined than those who attend in-person classes.\nD. Technology will eventually eliminate the need for human teachers.`,
    choice_a: "Online learning is always less effective than face-to-face instruction.",
    choice_b: "The COVID-19 pandemic forced schools to shift to distance learning in 2020.",
    choice_c: "Students who study online are less disciplined than in-person students.",
    choice_d: "Technology will eventually eliminate the need for human teachers.",
    correct_choice: "b",
    explanation: "The shift to distance learning due to COVID-19 in 2020 is a documented historical event. The other options make sweeping claims that involve opinion or speculation.",
    difficulty: 1,
  },
  {
    question_text: `Which of the following is an OPINION?\n\nA. The Philippines has a literacy rate of over ninety percent.\nB. Corruption is the single greatest obstacle to Philippine progress.\nC. Republic Act 10912 mandates Continuing Professional Development for licensed professionals.\nD. The population of Metro Manila exceeds twelve million people.`,
    choice_a: "The Philippines has a literacy rate of over ninety percent.",
    choice_b: "Corruption is the single greatest obstacle to Philippine progress.",
    choice_c: "Republic Act 10912 mandates Continuing Professional Development.",
    choice_d: "The population of Metro Manila exceeds twelve million people.",
    correct_choice: "b",
    explanation: "Declaring corruption the 'single greatest' obstacle is a subjective assessment — an opinion. The other statements are verifiable facts.",
    difficulty: 2,
  },
  {
    question_text: `Read the following passage:\n\n"Rice remains the staple food of most Filipino households. In recent years, the government has imported rice from Vietnam and Thailand to address supply shortfalls. Critics argue that this policy undermines local farmers and should be reversed immediately. Rice importation from these countries increased by thirty percent last year."\n\nWhich sentence is an OPINION?`,
    choice_a: "Rice remains the staple food of most Filipino households.",
    choice_b: "The government has imported rice from Vietnam and Thailand.",
    choice_c: "This policy undermines local farmers and should be reversed immediately.",
    choice_d: "Rice importation increased by thirty percent last year.",
    correct_choice: "c",
    explanation: "Saying the policy 'should be reversed' is a prescription based on a value judgment — an opinion. The other sentences state observable or measurable facts.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is a FACT?\n\nA. Jeepneys are the most iconic symbol of the Philippines.\nB. The PUV Modernization Program requires jeepneys older than fifteen years to be phased out.\nC. Modern PUVs are more comfortable but lack the cultural soul of traditional jeepneys.\nD. The government should have consulted more jeepney drivers before implementing the modernization program.`,
    choice_a: "Jeepneys are the most iconic symbol of the Philippines.",
    choice_b: "The PUV Modernization Program requires jeepneys older than fifteen years to be phased out.",
    choice_c: "Modern PUVs are more comfortable but lack the cultural soul of traditional jeepneys.",
    choice_d: "The government should have consulted more jeepney drivers before implementing the program.",
    correct_choice: "b",
    explanation: "The PUV Modernization Program's specific age-limit requirement is a verifiable policy fact. The other options are subjective assessments or normative judgments.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is an OPINION?\n\nA. The Philippines signed the Paris Agreement on climate change in 2016.\nB. The country's rainy season typically lasts from June to November.\nC. Typhoon preparedness education should begin in elementary school.\nD. The Philippines experiences an average of twenty typhoons per year.`,
    choice_a: "The Philippines signed the Paris Agreement in 2016.",
    choice_b: "The rainy season typically lasts from June to November.",
    choice_c: "Typhoon preparedness education should begin in elementary school.",
    choice_d: "The Philippines experiences an average of twenty typhoons per year.",
    correct_choice: "c",
    explanation: "Saying education 'should begin' at a certain level is a policy recommendation — an opinion. The other three are verifiable facts.",
    difficulty: 1,
  },
  {
    question_text: `Read the following passage:\n\n"The Senate approved a bill allocating five billion pesos for public school classroom construction. Education advocates called the amount insufficient, arguing that at least fifteen billion pesos is needed to address the classroom shortage. The Department of Education reported a shortage of approximately ninety thousand classrooms nationwide. More funding is obviously the only real solution to this problem."\n\nWhich sentence is a FACT?`,
    choice_a: "The amount is insufficient.",
    choice_b: "At least fifteen billion pesos is needed.",
    choice_c: "The Department of Education reported a shortage of approximately ninety thousand classrooms.",
    choice_d: "More funding is obviously the only real solution to this problem.",
    correct_choice: "c",
    explanation: "The DepEd's reported figure is an official statistic — a fact. Sentences A, B, and D all involve judgments or claims not directly verifiable from the passage.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is a FACT?\n\nA. The best way to reduce poverty is to invest in education.\nB. Social amelioration programs are more effective than job creation in reducing poverty.\nC. The national poverty rate in the Philippines decreased from 23.3% in 2015 to 16.7% in 2023.\nD. Poverty in rural areas is more difficult to address than poverty in urban centers.`,
    choice_a: "The best way to reduce poverty is to invest in education.",
    choice_b: "Social amelioration is more effective than job creation in reducing poverty.",
    choice_c: "The national poverty rate decreased from 23.3% in 2015 to 16.7% in 2023.",
    choice_d: "Rural poverty is more difficult to address than urban poverty.",
    correct_choice: "c",
    explanation: "The statistical change in poverty rate is a verifiable figure from government data. The other options are comparative judgments or prescriptions — opinions.",
    difficulty: 2,
  },
  {
    question_text: `Which of the following is an OPINION?\n\nA. Dengue fever is transmitted by the Aedes aegypti mosquito.\nB. The Department of Health reports thousands of dengue cases annually.\nC. Eliminating mosquito breeding sites is more effective than vaccines in preventing dengue.\nD. Dengue is a viral infection that can lead to severe hemorrhagic fever.`,
    choice_a: "Dengue is transmitted by the Aedes aegypti mosquito.",
    choice_b: "The DOH reports thousands of dengue cases annually.",
    choice_c: "Eliminating breeding sites is more effective than vaccines in preventing dengue.",
    choice_d: "Dengue can lead to severe hemorrhagic fever.",
    correct_choice: "c",
    explanation: "Comparing the effectiveness of two prevention strategies in absolute terms involves a judgment call that depends on context — this is an opinion. The other options are scientific or statistical facts.",
    difficulty: 3,
  },
  {
    question_text: `Read the following passage:\n\n"Magsasaka Cooperative sells organic vegetables grown without synthetic pesticides. Their produce is priced twenty to thirty percent higher than conventional vegetables. Organic food is always healthier and worth every extra centavo. Last year, the cooperative's sales grew by forty percent."\n\nWhich sentence is an OPINION?`,
    choice_a: "Magsasaka Cooperative sells organic vegetables grown without synthetic pesticides.",
    choice_b: "Their produce is priced twenty to thirty percent higher than conventional vegetables.",
    choice_c: "Organic food is always healthier and worth every extra centavo.",
    choice_d: "The cooperative's sales grew by forty percent last year.",
    correct_choice: "c",
    explanation: "'Always healthier' and 'worth every extra centavo' are value judgments — not universally provable claims. This makes sentence C an opinion.",
    difficulty: 2,
  },
];

// ── READING MATERIALS (Round 2) ──────────────────────────────────────────────

const READING_MATERIALS: Q[] = [
  {
    question_text: `SCHOOL LIBRARY NOTICE\n\nDear Students,\n\nPlease be reminded of the following library rules:\n• Books may be borrowed for a maximum of THREE (3) days.\n• A fine of ₱5.00 per day will be charged for overdue books.\n• Lost or damaged books must be replaced with a copy of the same title or its current market value.\n• Reference books, periodicals, and newspapers may NOT be taken out of the library.\n• Silence must be maintained at all times inside the library.\n\nThank you for your cooperation.\n— The Library Staff\n\nA student borrowed a novel on Monday and returned it the following Friday. How much is the overdue fine?`,
    choice_a: "₱5.00",
    choice_b: "₱10.00",
    choice_c: "₱15.00",
    choice_d: "₱20.00",
    correct_choice: "b",
    explanation: "Borrowed Monday = Day 1; Tuesday = Day 2; Wednesday = Day 3 (due date). Returned Friday = 2 days overdue. Fine = ₱5.00 × 2 = ₱10.00.",
    difficulty: 2,
  },
  {
    question_text: `BARANGAY HEALTH CENTER\nSchedule of Services\n\nMonday – Prenatal check-up and immunization (8:00 AM – 12:00 PM)\nTuesday – Family planning consultations (8:00 AM – 12:00 PM)\nWednesday – Senior citizen health monitoring (8:00 AM – 11:00 AM)\nThursday – General consultations / medical certificates (8:00 AM – 5:00 PM)\nFriday – Dental services (9:00 AM – 3:00 PM)\nSaturday – CLOSED\nSunday – CLOSED\n\nNote: Walk-in patients are accepted on a first-come, first-served basis.\n\nA mother wants to have her six-month-old baby vaccinated. On which day should she visit the health center?`,
    choice_a: "Tuesday",
    choice_b: "Wednesday",
    choice_c: "Thursday",
    choice_d: "Monday",
    correct_choice: "d",
    explanation: "Immunization services are scheduled on Monday from 8:00 AM to 12:00 PM.",
    difficulty: 1,
  },
  {
    question_text: `PRODUCT LABEL — INSECT REPELLENT LOTION\n\nActive Ingredient: DEET 20%\nDirections: Apply to exposed skin. Reapply every 4–6 hours or after swimming/sweating. Avoid contact with eyes, mouth, and open wounds.\nWarnings:\n• Do not apply directly to children under 2 years old.\n• If skin irritation develops, discontinue use and consult a physician.\n• Keep out of reach of children.\n• For external use only.\n\nA parent wants to apply the lotion to her 18-month-old child before an outdoor event. Based on the label, what should she do?`,
    choice_a: "Apply a small amount to test the child's reaction first.",
    choice_b: "Dilute the lotion with water before applying.",
    choice_c: "Do not apply the lotion to the child.",
    choice_d: "Apply to clothing instead of directly to skin.",
    correct_choice: "c",
    explanation: "The label explicitly states 'Do not apply directly to children under 2 years old.' An 18-month-old child is under 2 years old, so the lotion should not be used.",
    difficulty: 1,
  },
  {
    question_text: `COMMUNITY BULLETIN\n\nBLOOD DONATION DRIVE\nOrganized by: Samahang Kabataan ng Barangay Maliwanag\nDate: July 19, 2025 (Saturday)\nTime: 7:00 AM – 2:00 PM\nVenue: Barangay Covered Court\n\nWho can donate?\n✓ 18–65 years old\n✓ Weighs at least 50 kg\n✓ In good health (no colds, fever, or recent illness)\n✓ Has not donated blood in the last 3 months\n\nBring a valid ID. Walk-ins welcome!\n\nFor inquiries: 0917-555-1234\n\nWhich person is ELIGIBLE to donate blood at this drive?`,
    choice_a: "A 17-year-old student who weighs 55 kg and is healthy.",
    choice_b: "A 30-year-old who donated blood 2 months ago.",
    choice_c: "A 45-year-old who weighs 52 kg and has had no illness in the past month.",
    choice_d: "A 70-year-old retiree in excellent health.",
    correct_choice: "c",
    explanation: "The 45-year-old is within the age range (18–65), weighs over 50 kg, and has not been ill recently. A, B, and D fail one or more eligibility criteria.",
    difficulty: 1,
  },
  {
    question_text: `SCHOOL CANTEEN PRICE LIST\n\nRice meals:\nSinangag (garlic fried rice) .......... ₱20\nPandesal (2 pcs) .......................... ₱10\n\nViands:\nEgg (fried or scrambled) .............. ₱15\nTilapia (1 pc) ............................... ₱30\nAdobo (pork) ................................ ₱35\nVegetable stir-fry ......................... ₱25\n\nDrinks:\nSago't gulaman ........................... ₱15\nBuko juice ................................... ₱20\nBottled water ............................... ₱15\n\nA student orders sinangag, adobo, and buko juice. He pays with a ₱100 bill. How much change will he receive?`,
    choice_a: "₱15",
    choice_b: "₱20",
    choice_c: "₱25",
    choice_d: "₱30",
    correct_choice: "c",
    explanation: "Sinangag (₱20) + Adobo (₱35) + Buko juice (₱20) = ₱75. Change from ₱100 = ₱25.",
    difficulty: 1,
  },
  {
    question_text: `ANNOUNCEMENT\n\nThe Student Government Association (SGA) is accepting applications for the following positions:\n\n• President\n• Vice President for Internal Affairs\n• Secretary\n• Treasurer\n• Public Relations Officer (PRO)\n\nQualifications:\n– Must be a currently enrolled student with a general weighted average (GWA) of at least 85%\n– Must not have any pending disciplinary case\n– Must secure a letter of endorsement from a faculty adviser\n– Candidates running for Treasurer must have completed at least one accounting-related subject\n\nDeadline for submission of requirements: June 30, 2025\n\nWhich candidate does NOT qualify based on the stated requirements?`,
    choice_a: "A student with a GWA of 88% and a faculty endorsement who is running for PRO.",
    choice_b: "A student with a GWA of 83% and no disciplinary record who is running for Secretary.",
    choice_c: "A student with a GWA of 90% who has completed accounting subjects and is running for Treasurer.",
    choice_d: "A student with a GWA of 86% who has a faculty endorsement and is running for Vice President.",
    correct_choice: "b",
    explanation: "The student in B has a GWA of only 83%, which is below the required 85%, making them ineligible.",
    difficulty: 1,
  },
  {
    question_text: `FIRE SAFETY GUIDELINES — POSTED BY BUILDING MANAGEMENT\n\n1. Know the location of all fire exits and fire extinguishers on your floor.\n2. Do not block fire exits or emergency stairwells with furniture or equipment.\n3. In case of fire, use the stairs. DO NOT use the elevator.\n4. Activate the nearest fire alarm pull station when you discover a fire.\n5. Call 911 immediately.\n6. Do not attempt to fight a large fire yourself. Evacuate immediately.\n7. Report malfunctioning smoke detectors or fire extinguishers to building management within 24 hours.\n\nBased on the fire safety guidelines, what should a person do FIRST upon discovering a fire?`,
    choice_a: "Call 911 immediately.",
    choice_b: "Use the stairs to evacuate the building.",
    choice_c: "Activate the nearest fire alarm pull station.",
    choice_d: "Attempt to put out the fire using an extinguisher.",
    correct_choice: "c",
    explanation: "Guideline 4 states that upon discovering a fire, the first step is to activate the nearest fire alarm pull station. Calling 911 (guideline 5) comes after.",
    difficulty: 2,
  },
  {
    question_text: `TABLE: Monthly Average Rainfall (mm) in Selected Philippine Cities\n\nCity         | Jan | Feb | Mar | Apr | May | Jun\nManila       |  23 |  13 |  18 |  33 | 131 | 254\nCebu City    |  82 |  60 |  47 |  50 |  89 | 119\nDavao City   | 155 | 113 |  94 |  89 | 152 | 173\nTuguegarao   |  14 |  10 |  13 |  26 |  89 | 178\n\nBased on the table, which city receives the LEAST rainfall in February?`,
    choice_a: "Manila",
    choice_b: "Cebu City",
    choice_c: "Davao City",
    choice_d: "Tuguegarao",
    correct_choice: "d",
    explanation: "February rainfall: Manila = 13 mm, Cebu City = 60 mm, Davao City = 113 mm, Tuguegarao = 10 mm. Tuguegarao has the least at 10 mm.",
    difficulty: 1,
  },
  {
    question_text: `TABLE: Monthly Average Rainfall (mm) in Selected Philippine Cities\n\nCity         | Jan | Feb | Mar | Apr | May | Jun\nManila       |  23 |  13 |  18 |  33 | 131 | 254\nCebu City    |  82 |  60 |  47 |  50 |  89 | 119\nDavao City   | 155 | 113 |  94 |  89 | 152 | 173\nTuguegarao   |  14 |  10 |  13 |  26 |  89 | 178\n\nA family is planning a vacation in April and wants to visit the driest city. Based on the table, which city should they choose?`,
    choice_a: "Manila",
    choice_b: "Cebu City",
    choice_c: "Davao City",
    choice_d: "Tuguegarao",
    correct_choice: "d",
    explanation: "April rainfall: Manila = 33 mm, Cebu City = 50 mm, Davao City = 89 mm, Tuguegarao = 26 mm. Tuguegarao is driest in April.",
    difficulty: 1,
  },
  {
    question_text: `MEDICINE LABEL\n\nCOUGH SYRUP FOR CHILDREN\nActive Ingredient: Guaifenesin 100 mg per 5 mL\n\nDosage:\nAge 2–6: 2.5 mL every 4 hours (max 6 doses/day)\nAge 6–12: 5 mL every 4 hours (max 6 doses/day)\nAge 12 and above: 10 mL every 4 hours (max 6 doses/day)\n\nWarnings:\n• Do not exceed recommended dosage.\n• Do not give to children below 2 years old.\n• If cough persists for more than 7 days, consult a doctor.\n• Keep out of reach of children.\n\nA 9-year-old child has been coughing for 10 days despite taking the medicine as directed. What should the parents do?`,
    choice_a: "Double the dosage to speed up recovery.",
    choice_b: "Switch to the adult dosage for faster relief.",
    choice_c: "Consult a doctor, as the cough has persisted beyond 7 days.",
    choice_d: "Continue the medication for another week before worrying.",
    correct_choice: "c",
    explanation: "The label states: 'If cough persists for more than 7 days, consult a doctor.' At 10 days, the parents should seek medical advice.",
    difficulty: 1,
  },
  {
    question_text: `SCHOLARSHIP REQUIREMENTS — PROVINCIAL GOVERNMENT SCHOLARSHIP PROGRAM\n\nEligible Applicants:\n• Must be a permanent resident of the province for at least two (2) years\n• Must be a graduating high school student or a current college freshman or sophomore\n• Must have a General Weighted Average of at least 88%\n• Family income must not exceed ₱360,000 per year\n• Must not be receiving any other government scholarship\n\nRequired Documents:\n1. Duly accomplished application form\n2. Certified true copy of grades\n3. Barangay certificate of residency (at least 2 years)\n4. Certificate of family income (from DSWD or employer)\n5. Certificate of non-scholarship from school\n\nWhich applicant is INELIGIBLE for this scholarship?`,
    choice_a: "A college freshman with a GWA of 90% whose family earns ₱300,000 per year.",
    choice_b: "A graduating senior high student with a GWA of 88% who is a 3-year province resident.",
    choice_c: "A college sophomore with a GWA of 89% who currently holds a CHED scholarship.",
    choice_d: "A college freshman with a GWA of 91% whose family earns ₱250,000 per year.",
    correct_choice: "c",
    explanation: "The requirements state applicants 'must not be receiving any other government scholarship.' The sophomore in C currently holds a CHED scholarship, making them ineligible.",
    difficulty: 2,
  },
  {
    question_text: `PASSENGER FERRY SCHEDULE — CITY A TO CITY B\n\nDeparture Time | Travel Time | Fare (Economy) | Fare (First Class)\n6:00 AM        | 2 hrs 30 min | ₱350          | ₱600\n10:00 AM       | 2 hrs 30 min | ₱350          | ₱600\n2:00 PM        | 2 hrs 30 min | ₱350          | ₱600\n6:00 PM        | 2 hrs 30 min | ₱350          | ₱600\n\nNote: Tickets may be purchased at the terminal or online. Senior citizen and PWD discount: 20% off economy fare. Children below 3 years old: FREE.\n\nA family of two adults, one senior citizen, and one 2-year-old child takes the 10:00 AM ferry in economy class. What is the total fare?`,
    choice_a: "₱980",
    choice_b: "₱1,050",
    choice_c: "₱1,330",
    choice_d: "₱1,400",
    correct_choice: "a",
    explanation: "2 adults: 2 × ₱350 = ₱700. Senior citizen (20% off): ₱350 × 0.80 = ₱280. Child under 3: free. Total = ₱700 + ₱280 + ₱0 = ₱980. Choice B (₱1,050) would be the total if the senior paid full price; C (₱1,330) if the child also paid; D (₱1,400) if all four paid full fare.",
    difficulty: 2,
  },
  {
    question_text: `COMMUNITY GARDEN SIGN\n\nWELCOME TO LUNTIANG BUHAY COMMUNITY GARDEN\n\nGarden Hours: Monday – Saturday | 6:00 AM – 6:00 PM\nClosed on Sundays and Public Holidays\n\nGarden Rules:\n1. All plots must be tended at least twice a week.\n2. Use of chemical pesticides is strictly prohibited.\n3. Harvested produce belongs to the plot holder.\n4. Shared tools must be cleaned and returned after use.\n5. Visitors must be accompanied by a registered plot holder.\n6. Children under 12 must be supervised at all times.\n\nFor inquiries and plot registration: 0922-888-7654\n\nA visitor arrives at the garden on a Sunday afternoon and wants to check on her registered plot. Based on the sign, what is the issue?`,
    choice_a: "She may not enter because she is not accompanied by another plot holder.",
    choice_b: "She may not enter because the garden is closed on Sundays.",
    choice_c: "She may enter but may not harvest any produce on Sundays.",
    choice_d: "She may enter but must leave before 6:00 PM.",
    correct_choice: "b",
    explanation: "The sign states the garden is 'Closed on Sundays and Public Holidays.' She cannot enter regardless of her registered status.",
    difficulty: 1,
  },
  {
    question_text: `ELECTRICITY BILL — SAMPLE\n\nAccount Name: Juan dela Cruz\nBilling Period: April 1–30, 2025\nService Address: 123 Narra St., Barangay Pagasa\n\nConsumption: 180 kWh\nGeneration Charge: ₱6.50/kWh\nDistribution Charge: ₱2.00/kWh\nTransmission Charge: ₱1.00/kWh\nOther Charges: ₱150.00\n\nDue Date: May 20, 2025\nSurcharge for late payment: 2% of total bill\n\nWhat is the total electricity bill for April BEFORE any surcharge?`,
    choice_a: "₱1,620",
    choice_b: "₱1,770",
    choice_c: "₱1,920",
    choice_d: "₱2,070",
    correct_choice: "b",
    explanation: "Total rate per kWh = ₱6.50 + ₱2.00 + ₱1.00 = ₱9.50. Consumption charge = 180 × ₱9.50 = ₱1,710 - wait: 180 × 9.50 = ₱1,710. Other charges = ₱150. Total = ₱1,710 + ₱150 = ₱1,860. Hmm, none of the choices match ₱1,860. Let me recalculate: 180 × (6.50 + 2.00 + 1.00) = 180 × 9.50 = 1710 + 150 = 1860. Closest is C (₱1,920). Let me adjust: change other charges to ₱60 or adjust rates. Let me fix: Distribution = ₱1.50/kWh. 180 × (6.50+1.50+1.00) = 180 × 9.00 = 1620 + 150 = 1770 = choice B. I'll use Distribution = ₱1.50 in the corrected explanation.",
    difficulty: 2,
  },
  {
    question_text: `JOB ADVERTISEMENT\n\nPOSITION: Junior Accountant\nCOMPANY: Maliwanag Financial Solutions, Inc.\nLOCATION: Makati City (On-site)\n\nQUALIFICATIONS:\n• Bachelor's degree in Accountancy or any related business course\n• CPA licensure is preferred but not required for entry-level applicants\n• At least 1 year of relevant work experience (OJT experience accepted)\n• Proficient in MS Excel and accounting software (QuickBooks or MYOB)\n• Strong attention to detail and ability to meet deadlines\n• Fresh graduates are encouraged to apply\n\nBenefits: Government-mandated benefits, HMO, 13th month pay, annual performance bonus\n\nHow to Apply: Send your CV and transcript to careers@maliwanag.com.ph\n\nWhich applicant is MOST QUALIFIED for this position?`,
    choice_a: "A communication graduate with 2 years of sales experience and no accounting background.",
    choice_b: "A licensed CPA with 5 years of experience currently employed at a competing firm.",
    choice_c: "A fresh BS Accountancy graduate who completed a 6-month OJT at a bookkeeping firm and is proficient in QuickBooks.",
    choice_d: "A business administration graduate with experience in human resources but no accounting exposure.",
    correct_choice: "c",
    explanation: "The fresh Accountancy graduate meets the degree requirement, has OJT experience (accepted per the ad), and is proficient in QuickBooks. The CPA (B) is overqualified but technically eligible; however, C is the best fit for 'junior/entry-level' and matches all stated qualifications precisely.",
    difficulty: 2,
  },
];

// Fix the electricity bill question
READING_MATERIALS[13].question_text = `ELECTRICITY BILL — SAMPLE\n\nAccount Name: Juan dela Cruz\nBilling Period: April 1–30, 2025\nService Address: 123 Narra St., Barangay Pagasa\n\nConsumption: 180 kWh\nGeneration Charge: ₱6.50/kWh\nDistribution Charge: ₱1.50/kWh\nTransmission Charge: ₱1.00/kWh\nOther Charges: ₱150.00\n\nDue Date: May 20, 2025\nSurcharge for late payment: 2% of total bill\n\nWhat is the total electricity bill for April BEFORE any surcharge?`;
READING_MATERIALS[13].explanation = "Rate per kWh = ₱6.50 + ₱1.50 + ₱1.00 = ₱9.00. Consumption charge = 180 × ₱9.00 = ₱1,620. Add other charges: ₱1,620 + ₱150 = ₱1,770.";
READING_MATERIALS[13].correct_choice = "b";

// ── MAIN ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Fetching reading-comprehension subtest…");
  const { data: subtest, error } = await supabase
    .from("subtests")
    .select("id, topics(id, slug)")
    .eq("slug", "reading-comprehension")
    .single();

  if (error || !subtest) {
    console.error("Failed to fetch subtest:", error?.message);
    process.exit(1);
  }

  const topics = subtest.topics as { id: string; slug: string }[];
  const topicMap = new Map(topics.map((t) => [t.slug, t.id]));

  console.log("Topics found:", [...topicMap.keys()]);

  const TOPIC_QUESTIONS: [string, Q[]][] = [
    ["main-idea", MAIN_IDEA],
    ["inference", INFERENCE],
    ["vocab-in-context", VOCAB_IN_CONTEXT],
    ["literary-analysis", LITERARY_ANALYSIS],
    ["context-clues", CONTEXT_CLUES],
    ["fact-vs-opinion", FACT_VS_OPINION],
    ["reading-materials", READING_MATERIALS],
  ];

  for (const [slug, questions] of TOPIC_QUESTIONS) {
    const topicId = topicMap.get(slug);
    if (!topicId) {
      console.error(`Topic not found: ${slug}`);
      continue;
    }
    await seedTopic(slug, questions, topicId);
  }

  console.log("\nDone! 105 Reading Comprehension questions seeded (Round 2).");
}

main().catch(console.error);
