/**
 * Libreview seed script
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local"
  );
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ── Universities ────────────────────────────────────────────────────────────

const UNIVERSITIES = [
  { name: "University of the Philippines", slug: "up", is_active: true, display_order: 1 },
  { name: "Ateneo de Manila University", slug: "ateneo", is_active: false, display_order: 2 },
  { name: "De La Salle University", slug: "dlsu", is_active: false, display_order: 3 },
  { name: "University of Santo Tomas", slug: "ust", is_active: false, display_order: 4 },
  { name: "Others", slug: "others", is_active: true, display_order: 5 },
];

// ── Subtests ────────────────────────────────────────────────────────────────

const SUBTESTS = [
  {
    name: "Language Proficiency",
    slug: "language-proficiency",
    description: "Tests grammar, vocabulary, and correct use of the English language.",
    upcat_item_count: 80,
    mock_item_count: 20,
    display_order: 1,
  },
  {
    name: "Reading Comprehension",
    slug: "reading-comprehension",
    description: "Tests ability to understand and analyze written passages.",
    upcat_item_count: 60,
    mock_item_count: 15,
    display_order: 2,
  },
  {
    name: "Science",
    slug: "science",
    description: "Covers Biology, Chemistry, Physics, and Earth Science.",
    upcat_item_count: 60,
    mock_item_count: 15,
    display_order: 3,
  },
  {
    name: "Mathematics",
    slug: "mathematics",
    description: "Covers Algebra, Geometry, Statistics, and Trigonometry.",
    upcat_item_count: 40,
    mock_item_count: 10,
    display_order: 4,
  },
];

// ── Topics ───────────────────────────────────────────────────────────────────

const TOPICS_BY_SUBTEST: Record<string, { name: string; slug: string; description: string; display_order: number }[]> = {
  "language-proficiency": [
    { name: "Grammar and Usage", slug: "grammar-usage", description: "Subject-verb agreement, tenses, modifiers, and sentence structure.", display_order: 1 },
    { name: "Vocabulary", slug: "vocabulary", description: "Word meanings, synonyms, antonyms, and context clues.", display_order: 2 },
    { name: "Analogy", slug: "analogy", description: "Word relationships and analogical reasoning.", display_order: 3 },
  ],
  "reading-comprehension": [
    { name: "Main Idea and Details", slug: "main-idea", description: "Identifying central ideas, supporting details, and topic sentences.", display_order: 1 },
    { name: "Inference and Interpretation", slug: "inference", description: "Drawing conclusions and interpreting implied meaning.", display_order: 2 },
    { name: "Vocabulary in Context", slug: "vocab-in-context", description: "Understanding word meanings from surrounding text.", display_order: 3 },
  ],
  "science": [
    { name: "Biology", slug: "biology", description: "Cell biology, genetics, ecology, and human physiology.", display_order: 1 },
    { name: "Chemistry", slug: "chemistry", description: "Matter, chemical bonding, reactions, and the periodic table.", display_order: 2 },
    { name: "Physics", slug: "physics", description: "Motion, forces, energy, and waves.", display_order: 3 },
    { name: "Earth Science", slug: "earth-science", description: "Geology, meteorology, oceanography, and astronomy.", display_order: 4 },
  ],
  "mathematics": [
    { name: "Algebra", slug: "algebra", description: "Equations, inequalities, functions, and polynomials.", display_order: 1 },
    { name: "Geometry", slug: "geometry", description: "Shapes, angles, area, volume, and proofs.", display_order: 2 },
    { name: "Statistics and Probability", slug: "statistics", description: "Data interpretation, measures of central tendency, and probability.", display_order: 3 },
  ],
};

// ── Questions ─────────────────────────────────────────────────────────────

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

const QUESTIONS: Record<string, Q[]> = {
  // ── Language Proficiency: Grammar and Usage ──────────────────────────────
  "grammar-usage": [
    {
      question_text: "Choose the sentence with correct subject-verb agreement.",
      choice_a: "The committee have reached a decision.",
      choice_b: "The committee has reached a decision.",
      choice_c: "The committee were reaching a decision.",
      choice_d: "The committee reach a decision yesterday.",
      correct_choice: "b",
      explanation: "'Committee' is a collective noun treated as singular in American/formal English, so 'has' is correct.",
      difficulty: 1,
    },
    {
      question_text: "Select the sentence that uses the correct verb tense.",
      choice_a: "She had submitted the report before the deadline passes.",
      choice_b: "She has submitted the report before the deadline passed.",
      choice_c: "She had submitted the report before the deadline passed.",
      choice_d: "She submitted the report before the deadline will pass.",
      correct_choice: "c",
      explanation: "Past perfect ('had submitted') correctly expresses an action completed before another past event ('the deadline passed').",
      difficulty: 2,
    },
    {
      question_text: "Which sentence contains a dangling modifier?",
      choice_a: "Walking along the beach, she found a shell.",
      choice_b: "Walking along the beach, a shell was found.",
      choice_c: "While walking along the beach, she found a shell.",
      choice_d: "She found a shell while walking along the beach.",
      correct_choice: "b",
      explanation: "In option B, the participial phrase 'Walking along the beach' has no logical subject — the shell cannot walk.",
      difficulty: 2,
    },
    {
      question_text: "Identify the correct use of the apostrophe.",
      choice_a: "The student's notebook's were misplaced.",
      choice_b: "The students notebook was misplaced.",
      choice_c: "The student's notebook was misplaced.",
      choice_d: "The students' notebook's were misplaced.",
      correct_choice: "c",
      explanation: "'Student's' shows singular possessive; 'notebook' is a common noun that does not require an apostrophe here.",
      difficulty: 1,
    },
    {
      question_text: "Which option correctly completes the sentence? 'Neither the teachers nor the principal ___ aware of the incident.'",
      choice_a: "were",
      choice_b: "was",
      choice_c: "are",
      choice_d: "have been",
      correct_choice: "b",
      explanation: "With 'neither...nor', the verb agrees with the closer subject ('the principal'), which is singular, so 'was' is correct.",
      difficulty: 2,
    },
    {
      question_text: "Choose the sentence free of any grammatical error.",
      choice_a: "Between you and I, this is a difficult problem.",
      choice_b: "Between you and me, this is a difficult problem.",
      choice_c: "Between you and myself, this is a difficult problem.",
      choice_d: "Between you and mine, this is a difficult problem.",
      correct_choice: "b",
      explanation: "'Between' is a preposition requiring an object pronoun. 'Me' (not 'I' or 'myself') is the correct object pronoun.",
      difficulty: 1,
    },
    {
      question_text: "Select the sentence with correct parallel structure.",
      choice_a: "She likes to swim, jogging, and to cycle.",
      choice_b: "She likes swimming, jogging, and cycling.",
      choice_c: "She likes to swim, to jog, and cycling.",
      choice_d: "She likes swimming, to jog, and cycle.",
      correct_choice: "b",
      explanation: "Parallel structure requires the same grammatical form for all items in a list. 'Swimming, jogging, and cycling' are all gerunds.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence uses the subjunctive mood correctly?",
      choice_a: "If I was you, I would apologize.",
      choice_b: "If I am you, I would apologize.",
      choice_c: "If I were you, I would apologize.",
      choice_d: "If I had been you, I apologized.",
      correct_choice: "c",
      explanation: "The subjunctive 'were' is used in contrary-to-fact conditional clauses, regardless of the subject.",
      difficulty: 2,
    },
    {
      question_text: "Identify the sentence with a misplaced modifier.",
      choice_a: "She almost drove her children to school every day.",
      choice_b: "She drove her children to school almost every day.",
      choice_c: "Almost every day, she drove her children to school.",
      choice_d: "She drove almost every day her children to school.",
      correct_choice: "a",
      explanation: "In option A, 'almost' is placed before 'drove,' implying she nearly drove but didn't. The intended meaning requires 'almost every day.'",
      difficulty: 2,
    },
    {
      question_text: "Choose the correctly punctuated sentence.",
      choice_a: "The results were surprising however, we accepted them.",
      choice_b: "The results were surprising; however, we accepted them.",
      choice_c: "The results were surprising, however we accepted them.",
      choice_d: "The results were surprising however we accepted them.",
      correct_choice: "b",
      explanation: "A semicolon before a conjunctive adverb like 'however' correctly joins two independent clauses.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence uses 'fewer' and 'less' correctly?",
      choice_a: "There are less students in the room.",
      choice_b: "There are fewer water in the glass.",
      choice_c: "There are fewer students and less water.",
      choice_d: "There are less students and fewer water.",
      correct_choice: "c",
      explanation: "'Fewer' is used for countable nouns ('students') and 'less' for uncountable/mass nouns ('water').",
      difficulty: 1,
    },
    {
      question_text: "Which option identifies the error in this sentence? 'The data shows that global temperatures has risen.'",
      choice_a: "data should be datum",
      choice_b: "shows should be show",
      choice_c: "has should be have",
      choice_d: "Both A and C",
      correct_choice: "d",
      explanation: "'Data' is the plural of 'datum,' so the verb should be 'show' (not 'shows') and 'have risen' (not 'has risen').",
      difficulty: 3,
    },
    {
      question_text: "Select the sentence in which the pronoun agrees with its antecedent.",
      choice_a: "Each of the boys must bring their own lunch.",
      choice_b: "Each of the boys must bring his own lunch.",
      choice_c: "Each of the boys must bring its own lunch.",
      choice_d: "Each of the boys must bring our own lunch.",
      correct_choice: "b",
      explanation: "'Each' is an indefinite pronoun that is singular. The correct singular pronoun is 'his' (formal/traditional agreement).",
      difficulty: 2,
    },
    {
      question_text: "Which sentence uses the active voice?",
      choice_a: "The exam was passed by most students.",
      choice_b: "The scholarship was awarded to her.",
      choice_c: "Most students passed the exam.",
      choice_d: "The decision had been made by the board.",
      correct_choice: "c",
      explanation: "Active voice: the subject ('most students') performs the action ('passed'). All others are passive constructions.",
      difficulty: 1,
    },
    {
      question_text: "Choose the word that correctly completes the sentence. 'The principal ___ the student body to behave properly.'",
      choice_a: "inferred",
      choice_b: "implied",
      choice_c: "exhorted",
      choice_d: "deduced",
      correct_choice: "c",
      explanation: "'Exhort' means to strongly urge or appeal to someone to do something — fitting for a principal addressing students.",
      difficulty: 3,
    },
  ],

  // ── Language Proficiency: Vocabulary ────────────────────────────────────
  vocabulary: [
    {
      question_text: "What is the best synonym for 'ephemeral'?",
      choice_a: "eternal",
      choice_b: "transient",
      choice_c: "significant",
      choice_d: "abundant",
      correct_choice: "b",
      explanation: "'Ephemeral' means lasting for a very short time. 'Transient' means passing quickly, making it the closest synonym.",
      difficulty: 2,
    },
    {
      question_text: "Which word is an antonym of 'benevolent'?",
      choice_a: "generous",
      choice_b: "charitable",
      choice_c: "malevolent",
      choice_d: "compassionate",
      correct_choice: "c",
      explanation: "'Benevolent' means well-meaning and kind; 'malevolent' means having or showing a wish to do evil — direct antonym.",
      difficulty: 1,
    },
    {
      question_text: "The word 'loquacious' most nearly means:",
      choice_a: "silent",
      choice_b: "talkative",
      choice_c: "intelligent",
      choice_d: "aggressive",
      correct_choice: "b",
      explanation: "'Loquacious' comes from Latin 'loqui' (to speak). It describes someone who talks a great deal.",
      difficulty: 2,
    },
    {
      question_text: "Choose the word closest in meaning to 'ameliorate.'",
      choice_a: "worsen",
      choice_b: "ignore",
      choice_c: "improve",
      choice_d: "destroy",
      correct_choice: "c",
      explanation: "'Ameliorate' means to make something bad or unsatisfactory better.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is the best definition of 'cogent'?",
      choice_a: "vague and confusing",
      choice_b: "clear, logical, and convincing",
      choice_c: "emotional and passionate",
      choice_d: "incomplete and partial",
      correct_choice: "b",
      explanation: "A cogent argument is one that is clear, logical, and compelling enough to convince.",
      difficulty: 2,
    },
    {
      question_text: "The word 'perfidious' means:",
      choice_a: "perfect",
      choice_b: "treacherous and deceitful",
      choice_c: "very skillful",
      choice_d: "extremely powerful",
      correct_choice: "b",
      explanation: "'Perfidious' means guilty of betrayal or treachery, from Latin 'perfidia' (faithlessness).",
      difficulty: 3,
    },
    {
      question_text: "Choose the correct meaning of 'ubiquitous.'",
      choice_a: "rare and hard to find",
      choice_b: "present everywhere at the same time",
      choice_c: "extremely large",
      choice_d: "highly desirable",
      correct_choice: "b",
      explanation: "'Ubiquitous' means seeming to appear everywhere at the same time, e.g., 'smartphones are ubiquitous today.'",
      difficulty: 1,
    },
    {
      question_text: "What does 'enervate' mean?",
      choice_a: "to energize",
      choice_b: "to weaken or drain of energy",
      choice_c: "to excite",
      choice_d: "to reinforce",
      correct_choice: "b",
      explanation: "'Enervate' means to cause someone to feel drained of energy or vitality, the opposite of its appearance.",
      difficulty: 3,
    },
    {
      question_text: "Which word means 'showing a lack of experience, wisdom, or judgment'?",
      choice_a: "sagacious",
      choice_b: "astute",
      choice_c: "naïve",
      choice_d: "prudent",
      correct_choice: "c",
      explanation: "'Naïve' describes a person showing a lack of experience or wisdom, often in an innocent way.",
      difficulty: 1,
    },
    {
      question_text: "The best antonym for 'verbose' is:",
      choice_a: "wordy",
      choice_b: "concise",
      choice_c: "fluent",
      choice_d: "eloquent",
      correct_choice: "b",
      explanation: "'Verbose' means using more words than necessary. 'Concise' means giving information clearly in few words — its opposite.",
      difficulty: 1,
    },
    {
      question_text: "Which word best completes the sentence: 'Her ___ remarks offended everyone in the room.'?",
      choice_a: "sycophantic",
      choice_b: "acerbic",
      choice_c: "benign",
      choice_d: "timid",
      correct_choice: "b",
      explanation: "'Acerbic' means sharp and forthright, often in an unkind or critical way — fitting for offensive remarks.",
      difficulty: 3,
    },
    {
      question_text: "What does 'taciturn' mean?",
      choice_a: "very talkative",
      choice_b: "reserved or saying little",
      choice_c: "extremely clever",
      choice_d: "morally upright",
      correct_choice: "b",
      explanation: "A taciturn person tends to be quiet and not say much. It contrasts with 'loquacious.'",
      difficulty: 2,
    },
    {
      question_text: "Choose the synonym for 'intrepid.'",
      choice_a: "timid",
      choice_b: "fearless",
      choice_c: "cautious",
      choice_d: "indifferent",
      correct_choice: "b",
      explanation: "'Intrepid' means fearless and adventurous, often recklessly so.",
      difficulty: 1,
    },
    {
      question_text: "The word 'obfuscate' means to:",
      choice_a: "clarify",
      choice_b: "confuse or make unclear",
      choice_c: "strengthen",
      choice_d: "simplify",
      correct_choice: "b",
      explanation: "'Obfuscate' means to render obscure, unclear, or unintelligible.",
      difficulty: 3,
    },
    {
      question_text: "Which word is closest in meaning to 'propitious'?",
      choice_a: "unfavorable",
      choice_b: "favorable or giving a good omen",
      choice_c: "formal",
      choice_d: "aggressive",
      correct_choice: "b",
      explanation: "'Propitious' means giving or indicating a good chance of success; favorable — often used to describe timing or circumstances.",
      difficulty: 2,
    },
  ],

  // ── Language Proficiency: Analogy ────────────────────────────────────────
  analogy: [
    {
      question_text: "DOCTOR : PATIENT :: TEACHER : ___",
      choice_a: "classroom",
      choice_b: "student",
      choice_c: "lesson",
      choice_d: "school",
      correct_choice: "b",
      explanation: "A doctor serves a patient; a teacher serves a student. Both are professional-to-client relationships.",
      difficulty: 1,
    },
    {
      question_text: "DROUGHT : RAIN :: FAMINE : ___",
      choice_a: "poverty",
      choice_b: "hunger",
      choice_c: "food",
      choice_d: "water",
      correct_choice: "c",
      explanation: "Drought is the absence of rain; famine is the absence of food. Both are deficiency relationships.",
      difficulty: 1,
    },
    {
      question_text: "CANVAS : PAINTER :: ___: SCULPTOR",
      choice_a: "brush",
      choice_b: "clay",
      choice_c: "chisel",
      choice_d: "ink",
      correct_choice: "b",
      explanation: "Canvas is the material a painter works on; clay is the material a sculptor works with.",
      difficulty: 1,
    },
    {
      question_text: "TIMID : BOLD :: OPAQUE : ___",
      choice_a: "dark",
      choice_b: "transparent",
      choice_c: "reflective",
      choice_d: "dense",
      correct_choice: "b",
      explanation: "Timid and bold are antonyms; opaque (not allowing light through) and transparent (allowing light through) are antonyms.",
      difficulty: 2,
    },
    {
      question_text: "NOVEL : CHAPTER :: PLAY : ___",
      choice_a: "act",
      choice_b: "scene",
      choice_c: "line",
      choice_d: "script",
      correct_choice: "a",
      explanation: "A novel is divided into chapters; a play is divided into acts. Both are major structural divisions.",
      difficulty: 1,
    },
    {
      question_text: "IGNITE : FIRE :: GERMINATE : ___",
      choice_a: "seed",
      choice_b: "plant",
      choice_c: "soil",
      choice_d: "growth",
      correct_choice: "b",
      explanation: "Igniting causes fire to begin; germinating causes a plant to begin growing. Both describe the initiation of a result.",
      difficulty: 2,
    },
    {
      question_text: "ARCHIPELAGO : ISLANDS :: CONSTELLATION : ___",
      choice_a: "planets",
      choice_b: "stars",
      choice_c: "galaxies",
      choice_d: "moons",
      correct_choice: "b",
      explanation: "An archipelago is a group of islands; a constellation is a group of stars.",
      difficulty: 1,
    },
    {
      question_text: "SURGEON : SCALPEL :: CARPENTER : ___",
      choice_a: "wood",
      choice_b: "nail",
      choice_c: "saw",
      choice_d: "hammer",
      correct_choice: "c",
      explanation: "A surgeon uses a scalpel to cut; a carpenter uses a saw to cut. Both are worker-to-primary-cutting-tool relationships.",
      difficulty: 2,
    },
    {
      question_text: "MENDACIOUS : TRUTH :: COWARDLY : ___",
      choice_a: "fear",
      choice_b: "honor",
      choice_c: "bravery",
      choice_d: "weakness",
      correct_choice: "c",
      explanation: "A mendacious person lacks truth; a cowardly person lacks bravery. Both describe absence of a virtue.",
      difficulty: 3,
    },
    {
      question_text: "PROLOGUE : BEGINNING :: EPILOGUE : ___",
      choice_a: "middle",
      choice_b: "end",
      choice_c: "climax",
      choice_d: "conflict",
      correct_choice: "b",
      explanation: "A prologue comes at the beginning of a work; an epilogue comes at the end.",
      difficulty: 1,
    },
    {
      question_text: "WATER : THIRST :: SLEEP : ___",
      choice_a: "dream",
      choice_b: "fatigue",
      choice_c: "night",
      choice_d: "rest",
      correct_choice: "b",
      explanation: "Water alleviates thirst; sleep alleviates fatigue. Both are remedy-to-need relationships.",
      difficulty: 1,
    },
    {
      question_text: "ETYMOLOGY : WORDS :: ORNITHOLOGY : ___",
      choice_a: "insects",
      choice_b: "plants",
      choice_c: "birds",
      choice_d: "fish",
      correct_choice: "c",
      explanation: "Etymology is the study of words; ornithology is the study of birds. Both are field-of-study relationships.",
      difficulty: 2,
    },
    {
      question_text: "TAUTOLOGY : REPETITION :: HYPERBOLE : ___",
      choice_a: "understatement",
      choice_b: "exaggeration",
      choice_c: "comparison",
      choice_d: "substitution",
      correct_choice: "b",
      explanation: "Tautology is a type of repetition; hyperbole is a type of exaggeration.",
      difficulty: 3,
    },
    {
      question_text: "TRANSPARENT : OPAQUE :: AUDIBLE : ___",
      choice_a: "loud",
      choice_b: "silent",
      choice_c: "inaudible",
      choice_d: "clear",
      correct_choice: "c",
      explanation: "Transparent and opaque are antonyms (light can/cannot pass); audible and inaudible are antonyms (sound can/cannot be heard).",
      difficulty: 2,
    },
    {
      question_text: "RUDIMENTARY : SOPHISTICATED :: SPARSE : ___",
      choice_a: "empty",
      choice_b: "abundant",
      choice_c: "scarce",
      choice_d: "minimal",
      correct_choice: "b",
      explanation: "Rudimentary (basic) is the opposite of sophisticated; sparse (thinly spread) is the opposite of abundant.",
      difficulty: 2,
    },
  ],

  // ── Reading Comprehension: Main Idea ────────────────────────────────────
  "main-idea": [
    {
      question_text: "A paragraph begins: 'Coral reefs cover less than 1% of the ocean floor yet support over 25% of all marine life.' What is the main idea?",
      choice_a: "Coral reefs are very colorful underwater structures.",
      choice_b: "Coral reefs are disproportionately important to ocean biodiversity.",
      choice_c: "The ocean floor is mostly uninhabited.",
      choice_d: "Marine life depends entirely on the ocean floor.",
      correct_choice: "b",
      explanation: "The statistic highlights that a small area (1%) supports a large proportion (25%) of marine life — underscoring their disproportionate ecological importance.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence would BEST serve as the topic sentence of a paragraph about the dangers of social media?",
      choice_a: "Facebook was founded in 2004.",
      choice_b: "Teenagers spend an average of five hours daily on social media.",
      choice_c: "Excessive social media use has been linked to anxiety, depression, and cyberbullying.",
      choice_d: "Social media platforms include Instagram, TikTok, and X.",
      correct_choice: "c",
      explanation: "A good topic sentence states the main idea. Option C presents a clear, arguable claim that the rest of the paragraph can support.",
      difficulty: 1,
    },
    {
      question_text: "A passage describes how forests regulate rainfall, prevent soil erosion, and store carbon. What is the best title for this passage?",
      choice_a: "Types of Trees in Tropical Forests",
      choice_b: "The Critical Role of Forests in Climate Regulation",
      choice_c: "Why Logging Is a Profitable Industry",
      choice_d: "Soil Composition in Forest Regions",
      correct_choice: "b",
      explanation: "All three details (rainfall regulation, soil protection, carbon storage) are functions forests perform in regulating climate, making B the most comprehensive title.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is a DETAIL rather than a main idea?",
      choice_a: "Regular exercise has numerous health benefits.",
      choice_b: "Physical activity improves both mental and physical well-being.",
      choice_c: "Thirty minutes of walking per day can reduce the risk of heart disease.",
      choice_d: "Exercise is essential for maintaining a healthy lifestyle.",
      correct_choice: "c",
      explanation: "Option C is a specific fact that supports the broader idea that exercise has health benefits — it is a supporting detail, not a main idea.",
      difficulty: 2,
    },
    {
      question_text: "A paragraph's first sentence states a problem; middle sentences describe its causes; the last sentence proposes a solution. Where is the main idea most likely located?",
      choice_a: "In the last sentence only",
      choice_b: "In the middle sentences",
      choice_c: "In the first sentence",
      choice_d: "It is spread throughout the paragraph",
      correct_choice: "c",
      explanation: "In a problem-cause-solution structure, the opening sentence that introduces the problem typically states the controlling idea of the paragraph.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Despite advances in technology, poverty rates in developing nations remain stubbornly high. Lack of infrastructure, limited access to education, and political instability all contribute to this persistent inequality.' The implied main idea is:",
      choice_a: "Technology is not advancing fast enough.",
      choice_b: "Multiple structural factors perpetuate poverty in developing nations.",
      choice_c: "Education is the most important factor in reducing poverty.",
      choice_d: "Political instability causes all economic problems.",
      correct_choice: "b",
      explanation: "The passage lists several structural factors (infrastructure, education, politics) and frames them as contributors to persistent poverty — the implied main idea.",
      difficulty: 2,
    },
    {
      question_text: "Which revision would make the following topic sentence stronger? 'Exercise is good.'",
      choice_a: "Exercise is very, very good for people.",
      choice_b: "Some people exercise regularly.",
      choice_c: "Daily aerobic exercise significantly reduces the risk of cardiovascular disease.",
      choice_d: "There are many types of exercise.",
      correct_choice: "c",
      explanation: "A strong topic sentence is specific and arguable. Option C identifies a specific benefit with specific evidence compared to the vague original.",
      difficulty: 2,
    },
    {
      question_text: "The BEST supporting detail for the claim 'Deforestation is a global crisis' would be:",
      choice_a: "Trees produce oxygen through photosynthesis.",
      choice_b: "Some forests receive more than 200 inches of rain annually.",
      choice_c: "An estimated 15 billion trees are cut down each year.",
      choice_d: "Forests are home to many species of animals.",
      correct_choice: "c",
      explanation: "Quantitative evidence (15 billion trees per year) directly supports the scale implied by 'global crisis' — it is the most specific and impactful supporting detail.",
      difficulty: 2,
    },
    {
      question_text: "A student writes three paragraphs: the first covers air pollution, the second covers water pollution, and the third covers soil pollution. What is the most appropriate thesis for this essay?",
      choice_a: "Air pollution is the most dangerous type of pollution.",
      choice_b: "Pollution in its many forms poses a serious threat to environmental health.",
      choice_c: "Water pollution affects marine life.",
      choice_d: "Factories are the leading cause of global pollution.",
      correct_choice: "b",
      explanation: "The thesis must encompass all three paragraphs. Option B is broad enough to include all three forms of pollution discussed.",
      difficulty: 1,
    },
    {
      question_text: "In informational texts, the main idea is distinguished from supporting details because it:",
      choice_a: "appears only at the end of the text",
      choice_b: "is always stated directly",
      choice_c: "encompasses the overall message that other points support",
      choice_d: "consists of specific facts and statistics",
      correct_choice: "c",
      explanation: "The main idea is the overarching point; supporting details provide evidence, examples, or explanations for that point.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The moon has no atmosphere, experiences extreme temperature swings, and is bombarded by micrometeoroids.' This sentence BEST functions as:",
      choice_a: "a concluding statement",
      choice_b: "a topic sentence introducing harsh lunar conditions",
      choice_c: "a supporting detail about Earth's weather",
      choice_d: "a transition sentence",
      correct_choice: "b",
      explanation: "The sentence lists several characteristics of the moon that all point to a hostile environment — making it a strong topic sentence about harsh conditions.",
      difficulty: 2,
    },
    {
      question_text: "Which of these is an IMPLICIT (implied) main idea?",
      choice_a: "This essay will discuss the effects of climate change.",
      choice_b: "Climate change is the greatest threat facing humanity today.",
      choice_c: "Record floods, wildfires, and droughts have devastated communities worldwide.",
      choice_d: "Scientists have warned about climate change for decades.",
      correct_choice: "c",
      explanation: "Option C never states a main idea directly, but the accumulation of disasters implies that climate change is causing widespread harm — an implicit main idea.",
      difficulty: 3,
    },
    {
      question_text: "A summary of a passage SHOULD:",
      choice_a: "include the reader's personal opinion on the topic",
      choice_b: "restate all the details mentioned in the original",
      choice_c: "capture the main idea in fewer words without personal commentary",
      choice_d: "be longer than the original to ensure completeness",
      correct_choice: "c",
      explanation: "A summary condenses the essential meaning of a text without adding personal opinion or restating every detail.",
      difficulty: 1,
    },
    {
      question_text: "The term 'controlling idea' in a paragraph refers to:",
      choice_a: "the last sentence that wraps up the paragraph",
      choice_b: "the central claim that the paragraph develops and supports",
      choice_c: "a transitional phrase connecting paragraphs",
      choice_d: "the most interesting fact in the paragraph",
      correct_choice: "b",
      explanation: "The controlling idea is the central argument or assertion in the topic sentence that all other sentences in the paragraph support.",
      difficulty: 2,
    },
    {
      question_text: "Which statement about a thesis statement is CORRECT?",
      choice_a: "It should be phrased as a question.",
      choice_b: "It is always found in the conclusion of an essay.",
      choice_c: "It presents an arguable claim that the essay will support.",
      choice_d: "It lists all the facts the essay will present.",
      correct_choice: "c",
      explanation: "A thesis statement is the central, arguable claim of an essay, typically found in the introduction, that guides the entire paper.",
      difficulty: 1,
    },
  ],

  // ── Reading Comprehension: Inference ────────────────────────────────────
  inference: [
    {
      question_text: "Read: 'Maria glanced at her watch for the third time and tapped her foot impatiently.' What can you infer?",
      choice_a: "Maria is happy.",
      choice_b: "Maria is waiting for something or someone.",
      choice_c: "Maria dislikes wearing watches.",
      choice_d: "Maria is about to leave.",
      correct_choice: "b",
      explanation: "Repeatedly checking her watch and tapping her foot are behavioral cues associated with waiting or impatience.",
      difficulty: 1,
    },
    {
      question_text: "A character in a story says, 'Well, that was certainly… interesting,' after watching a poorly performed play. What does this MOST likely imply?",
      choice_a: "The character genuinely enjoyed the play.",
      choice_b: "The character found the play boring.",
      choice_c: "The character is being sarcastic about the play's quality.",
      choice_d: "The character wants to watch the play again.",
      correct_choice: "c",
      explanation: "The pause before 'interesting' and the vague word suggest the character is using irony or sarcasm, implying the opposite of genuine praise.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The shelves were empty, the windows were boarded up, and a 'For Lease' sign hung in the doorway.' What can be inferred?",
      choice_a: "The building is being renovated.",
      choice_b: "The business has closed down.",
      choice_c: "The building is a new construction.",
      choice_d: "The building is preparing to open.",
      correct_choice: "b",
      explanation: "Empty shelves, boarded windows, and a 'For Lease' sign are all indicators that the business has stopped operating.",
      difficulty: 1,
    },
    {
      question_text: "An author describes a city as having 'gleaming skyscrapers that pierced the clouds, streets full of hurrying workers, and the constant hum of machinery.' What can you infer about this city?",
      choice_a: "It is a small, quiet town.",
      choice_b: "It is an industrialized, fast-paced urban center.",
      choice_c: "It is a poor, underdeveloped area.",
      choice_d: "It is a rural farming community.",
      correct_choice: "b",
      explanation: "Skyscrapers, busy streets, and industrial sounds all point to an economically active, industrialized urban environment.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is an INFERENCE rather than a stated fact?",
      choice_a: "The student received a failing grade.",
      choice_b: "The exam had 50 questions.",
      choice_c: "The student probably did not study enough.",
      choice_d: "The teacher returned the exams on Monday.",
      correct_choice: "c",
      explanation: "Option C is not directly stated — it is a conclusion drawn from the fact of a failing grade. The other options are all observable facts.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Despite studying for weeks, Lena stared blankly at the questions. Her mind had gone completely white.' What is most likely happening to Lena?",
      choice_a: "She is daydreaming about her upcoming vacation.",
      choice_b: "She is experiencing test anxiety.",
      choice_c: "She did not understand the subject matter.",
      choice_d: "She is bored by the exam.",
      correct_choice: "b",
      explanation: "Despite preparation, her mind 'going white' (going blank) during the exam strongly implies test anxiety — a psychological block, not lack of study.",
      difficulty: 2,
    },
    {
      question_text: "A passage about a new diet ends with: 'Participants lost an average of 2 lbs per week with no reported side effects.' What can be reasonably inferred?",
      choice_a: "The diet is entirely risk-free for everyone.",
      choice_b: "The diet shows promising short-term results.",
      choice_c: "The diet will certainly replace all other diets.",
      choice_d: "The participants did not follow the diet correctly.",
      correct_choice: "b",
      explanation: "The data supports a cautiously positive inference about short-term effectiveness, but it is an overstatement to say it is risk-free for everyone or will replace all diets.",
      difficulty: 2,
    },
    {
      question_text: "Which question CANNOT be answered through inference alone?",
      choice_a: "What does the character feel based on her actions?",
      choice_b: "What year was the character born?",
      choice_c: "Why did the character make that decision?",
      choice_d: "What is likely to happen next?",
      correct_choice: "b",
      explanation: "The exact birth year is a specific factual detail that must be stated explicitly — it cannot be inferred without direct evidence.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The general paced back and forth, studying the map long into the night.' What can be inferred about the general's situation?",
      choice_a: "He is planning a military strategy.",
      choice_b: "He enjoys geography.",
      choice_c: "He is lost.",
      choice_d: "He is waiting for orders.",
      correct_choice: "a",
      explanation: "Generals pacing and studying maps at night is a classic context for strategic military planning under pressure.",
      difficulty: 1,
    },
    {
      question_text: "An author writes, 'The bread crumbs on the floor led from the kitchen to the bedroom.' This MOST likely implies:",
      choice_a: "Someone baked bread earlier.",
      choice_b: "Someone carried food while walking.",
      choice_c: "The house is very old.",
      choice_d: "The family is wealthy.",
      correct_choice: "b",
      explanation: "A trail of crumbs from one room to another implies someone was eating or carrying food while moving between rooms.",
      difficulty: 1,
    },
    {
      question_text: "What is the purpose of an inference question in a reading test?",
      choice_a: "To test if you memorized facts from the passage",
      choice_b: "To evaluate your ability to draw conclusions beyond what is literally stated",
      choice_c: "To assess your vocabulary",
      choice_d: "To check if you understand the author's background",
      correct_choice: "b",
      explanation: "Inference questions assess higher-order reading comprehension — going beyond the literal text to understand implied meanings and draw logical conclusions.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'She wore the same outfit for the fourth consecutive day.' The MOST reasonable inference is:",
      choice_a: "She is unaware of fashion trends.",
      choice_b: "She may be going through a difficult time.",
      choice_c: "She owns few clothes.",
      choice_d: "Both B and C are reasonable inferences.",
      correct_choice: "d",
      explanation: "Wearing the same clothes repeatedly can reasonably suggest either limited wardrobe or personal difficulty — both are defensible inferences without additional context.",
      difficulty: 3,
    },
    {
      question_text: "The author states that a politician 'chose her words carefully before each public appearance.' What can you MOST reasonably infer?",
      choice_a: "The politician is dishonest.",
      choice_b: "The politician is aware that her words carry weight and consequences.",
      choice_c: "The politician has poor communication skills.",
      choice_d: "The politician is shy.",
      correct_choice: "b",
      explanation: "Choosing words carefully suggests awareness that one's statements are scrutinized — a sign of political acuity, not dishonesty.",
      difficulty: 2,
    },
    {
      question_text: "A scientist publishes findings that contradict 20 years of established research. What can you infer about the scientific community's likely reaction?",
      choice_a: "They will immediately accept the findings.",
      choice_b: "They will likely scrutinize and debate the findings rigorously.",
      choice_c: "They will ignore the findings.",
      choice_d: "They will punish the scientist.",
      correct_choice: "b",
      explanation: "Scientific community norms involve peer review and scrutiny, especially for findings that challenge established consensus — rigorous debate is the most reasonable inference.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following BEST describes a 'logical inference'?",
      choice_a: "A guess based on personal opinion",
      choice_b: "A conclusion based on available evidence and reasoning",
      choice_c: "A statement found directly in the text",
      choice_d: "An emotional response to reading",
      correct_choice: "b",
      explanation: "A logical inference is a reasoned conclusion drawn from evidence — distinct from guessing, personal opinion, or direct quotation.",
      difficulty: 1,
    },
  ],

  // ── Reading Comprehension: Vocabulary in Context ─────────────────────────
  "vocab-in-context": [
    {
      question_text: "Read: 'The scientist's findings were so seminal that they changed the direction of the entire field.' In this context, 'seminal' most nearly means:",
      choice_a: "insignificant",
      choice_b: "groundbreaking and highly influential",
      choice_c: "controversial",
      choice_d: "recent",
      correct_choice: "b",
      explanation: "In context, 'seminal' means highly original and influential — findings important enough to redirect an entire field of study.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The politician's speech was so incendiary that it provoked riots.' The word 'incendiary' most likely means:",
      choice_a: "calm and measured",
      choice_b: "designed to cause anger or violence",
      choice_c: "boring and repetitive",
      choice_d: "inspiring and uplifting",
      correct_choice: "b",
      explanation: "The result of the speech (riots) tells us the speech was provocative and inflammatory — 'incendiary' literally means fire-starting, figuratively means provoking strong reaction.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Despite his ostensibly calm demeanor, his clenched fists betrayed his true feelings.' What does 'ostensibly' mean here?",
      choice_a: "genuinely",
      choice_b: "in appearance but not in reality",
      choice_c: "obviously",
      choice_d: "nervously",
      correct_choice: "b",
      explanation: "'Ostensibly' means apparently or seemingly, but the 'despite... betrayed' structure signals the appearance contradicts reality.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The refugee's story was harrowing — weeks at sea, dehydration, and the constant fear of being turned back.' The word 'harrowing' most nearly means:",
      choice_a: "inspiring",
      choice_b: "deeply distressing",
      choice_c: "unusual",
      choice_d: "lengthy",
      correct_choice: "b",
      explanation: "The context (weeks at sea, dehydration, fear) all describe suffering, so 'harrowing' means intensely distressing or traumatic.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The new law was seen as a panacea for crime, though critics argued it addressed symptoms rather than root causes.' A 'panacea' is:",
      choice_a: "a cure for all problems",
      choice_b: "a temporary measure",
      choice_c: "a punishment",
      choice_d: "a survey",
      correct_choice: "a",
      explanation: "A 'panacea' is a supposed remedy for all difficulties or diseases. The critics' objection (treating symptoms, not causes) reinforces this — they doubt it can solve everything.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'She navigated the labyrinthine bureaucracy with ease.' The word 'labyrinthine' most likely means:",
      choice_a: "fair and transparent",
      choice_b: "extremely complicated and difficult to navigate",
      choice_c: "corrupt",
      choice_d: "rapidly changing",
      correct_choice: "b",
      explanation: "From 'labyrinth' (a maze), 'labyrinthine' means complicated and full of confusing twists — fitting for bureaucracy one needs skill to navigate.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The company's profits were modest in the first quarter, but robust in the fourth.' In this context, 'robust' means:",
      choice_a: "declining",
      choice_b: "strong and healthy",
      choice_c: "unexpected",
      choice_d: "irregular",
      correct_choice: "b",
      explanation: "Contrasted with 'modest' (small), 'robust' in a financial context means strong, vigorous, and healthy.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'His candid assessment of the situation, though uncomfortable, helped the team plan more effectively.' The word 'candid' most nearly means:",
      choice_a: "gentle and tactful",
      choice_b: "truthful and direct",
      choice_c: "overly optimistic",
      choice_d: "secret",
      correct_choice: "b",
      explanation: "A candid assessment is honest and straightforward, even if uncomfortable — the context reinforces its helpfulness despite discomfort.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The speaker's tone was patronizing, as though addressing children rather than professionals.' 'Patronizing' most closely means:",
      choice_a: "supportive and encouraging",
      choice_b: "condescending, treating others as inferior",
      choice_c: "formal and technical",
      choice_d: "confident and assertive",
      correct_choice: "b",
      explanation: "Treating professionals 'as though they were children' is condescending — 'patronizing' means behaving as if one is superior to others.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The journalist's exposé on corruption was so thorough that it was considered definitive.' 'Definitive' in this context means:",
      choice_a: "incomplete",
      choice_b: "controversial",
      choice_c: "most complete and authoritative",
      choice_d: "theoretical",
      correct_choice: "c",
      explanation: "A 'definitive' work is considered the most complete, authoritative, and conclusive treatment of a subject.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The artist's latest work was deliberately abstruse, appealing only to those deeply familiar with postmodern theory.' 'Abstruse' means:",
      choice_a: "beautiful and elegant",
      choice_b: "difficult to understand",
      choice_c: "politically controversial",
      choice_d: "highly colorful",
      correct_choice: "b",
      explanation: "Something 'abstruse' is difficult to understand because it is complex or obscure — the context (requires deep theory knowledge) confirms this.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'The soldiers showed exemplary courage under fire.' The word 'exemplary' most likely means:",
      choice_a: "adequate",
      choice_b: "serving as a desirable model; outstanding",
      choice_c: "unusual",
      choice_d: "dangerous",
      correct_choice: "b",
      explanation: "'Exemplary' means serving as a model of excellence — worthy of imitation. It describes conduct that is outstanding.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'Her gregarious personality made her the center of every social gathering.' 'Gregarious' most nearly means:",
      choice_a: "shy and reserved",
      choice_b: "fond of company; sociable",
      choice_c: "intelligent and articulate",
      choice_d: "loud and aggressive",
      correct_choice: "b",
      explanation: "'Gregarious' means fond of the company of others — a gregarious person naturally attracts social gatherings.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The senator's equivocal answers frustrated reporters who wanted clear positions.' 'Equivocal' means:",
      choice_a: "honest and transparent",
      choice_b: "ambiguous, open to multiple interpretations",
      choice_c: "confident and assertive",
      choice_d: "emotional",
      correct_choice: "b",
      explanation: "Equivocal answers frustrate those seeking clarity because they are deliberately ambiguous — avoiding a clear commitment.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Despite the team's tenacious effort, they lost the championship by a single point.' 'Tenacious' most nearly means:",
      choice_a: "careless and underprepared",
      choice_b: "persistent and determined",
      choice_c: "talented but unlucky",
      choice_d: "exhausted",
      correct_choice: "b",
      explanation: "'Tenacious' means holding firm; not giving up easily. It describes the quality of persistence despite adversity.",
      difficulty: 1,
    },
  ],

  // ── Science: Biology ─────────────────────────────────────────────────────
  biology: [
    {
      question_text: "Which organelle is known as the 'powerhouse of the cell'?",
      choice_a: "Nucleus",
      choice_b: "Ribosome",
      choice_c: "Mitochondria",
      choice_d: "Golgi apparatus",
      correct_choice: "c",
      explanation: "Mitochondria produce ATP through cellular respiration, providing most of the cell's energy supply.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following correctly describes the process of meiosis?",
      choice_a: "It produces two genetically identical daughter cells.",
      choice_b: "It produces four genetically diverse haploid cells.",
      choice_c: "It occurs in all somatic cells.",
      choice_d: "It does not involve crossing over.",
      correct_choice: "b",
      explanation: "Meiosis produces four haploid gametes with genetic diversity from crossing over — unlike mitosis, which produces two diploid identical cells.",
      difficulty: 2,
    },
    {
      question_text: "In Mendelian genetics, if both parents are heterozygous for a dominant trait (Aa × Aa), what is the probability of an offspring being homozygous recessive (aa)?",
      choice_a: "25%",
      choice_b: "50%",
      choice_c: "75%",
      choice_d: "0%",
      correct_choice: "a",
      explanation: "The Punnett square for Aa × Aa gives: AA (25%), Aa (50%), aa (25%). The probability of aa is 25%.",
      difficulty: 2,
    },
    {
      question_text: "Which level of biological organization is DIRECTLY above the organ?",
      choice_a: "Cell",
      choice_b: "Tissue",
      choice_c: "Organism",
      choice_d: "Organ system",
      correct_choice: "d",
      explanation: "The biological hierarchy is: cell → tissue → organ → organ system → organism. Organ systems are composed of organs.",
      difficulty: 1,
    },
    {
      question_text: "During photosynthesis, which molecule acts as the primary electron donor?",
      choice_a: "CO₂",
      choice_b: "ATP",
      choice_c: "H₂O",
      choice_d: "NADPH",
      correct_choice: "c",
      explanation: "In the light reactions of photosynthesis, water (H₂O) is split (photolysis), releasing electrons that are used to reduce NADP⁺ to NADPH.",
      difficulty: 3,
    },
    {
      question_text: "Which type of RNA carries amino acids to the ribosome during translation?",
      choice_a: "mRNA",
      choice_b: "tRNA",
      choice_c: "rRNA",
      choice_d: "snRNA",
      correct_choice: "b",
      explanation: "Transfer RNA (tRNA) carries specific amino acids and matches anticodons to mRNA codons at the ribosome during translation.",
      difficulty: 2,
    },
    {
      question_text: "The relationship between a clownfish and a sea anemone, where both benefit, is called:",
      choice_a: "Parasitism",
      choice_b: "Commensalism",
      choice_c: "Mutualism",
      choice_d: "Competition",
      correct_choice: "c",
      explanation: "Mutualism is a symbiotic relationship where both organisms benefit. The clownfish gets protection; the anemone gets cleaning and nutrients.",
      difficulty: 1,
    },
    {
      question_text: "Which structure controls the passage of materials in and out of the cell?",
      choice_a: "Cell wall",
      choice_b: "Cytoplasm",
      choice_c: "Nucleus",
      choice_d: "Cell membrane",
      correct_choice: "d",
      explanation: "The cell membrane (plasma membrane) is selectively permeable and regulates what enters and exits the cell.",
      difficulty: 1,
    },
    {
      question_text: "In the nitrogen cycle, which bacteria convert atmospheric nitrogen (N₂) into ammonia (NH₃)?",
      choice_a: "Nitrifying bacteria",
      choice_b: "Denitrifying bacteria",
      choice_c: "Nitrogen-fixing bacteria",
      choice_d: "Decomposers",
      correct_choice: "c",
      explanation: "Nitrogen-fixing bacteria (e.g., Rhizobium) convert N₂ from the atmosphere into ammonia or ammonium ions — forms usable by plants.",
      difficulty: 2,
    },
    {
      question_text: "Which statement about DNA replication is correct?",
      choice_a: "It is conservative — the original strand is completely preserved in one daughter molecule.",
      choice_b: "It is semi-conservative — each daughter molecule contains one original and one new strand.",
      choice_c: "It is dispersive — original and new DNA is evenly distributed across both daughter molecules.",
      choice_d: "It occurs only in the cytoplasm.",
      correct_choice: "b",
      explanation: "The Meselson-Stahl experiment confirmed that DNA replication is semi-conservative: each daughter DNA molecule contains one parental and one newly synthesized strand.",
      difficulty: 2,
    },
    {
      question_text: "Which organ produces insulin to regulate blood sugar levels?",
      choice_a: "Liver",
      choice_b: "Kidney",
      choice_c: "Pancreas",
      choice_d: "Thyroid gland",
      correct_choice: "c",
      explanation: "The beta cells of the islets of Langerhans in the pancreas produce insulin, which facilitates glucose uptake by cells.",
      difficulty: 1,
    },
    {
      question_text: "A population of bacteria doubles every 20 minutes. Starting with 100 bacteria, how many will there be after 1 hour?",
      choice_a: "200",
      choice_b: "400",
      choice_c: "600",
      choice_d: "800",
      correct_choice: "d",
      explanation: "In 1 hour (60 min), there are 3 doubling periods: 100 → 200 → 400 → 800.",
      difficulty: 2,
    },
    {
      question_text: "What is the role of the enzyme helicase in DNA replication?",
      choice_a: "It joins Okazaki fragments on the lagging strand.",
      choice_b: "It synthesizes new nucleotides.",
      choice_c: "It unwinds and separates the DNA double helix.",
      choice_d: "It proofreads and repairs errors.",
      correct_choice: "c",
      explanation: "Helicase breaks hydrogen bonds between complementary base pairs, unwinding the double helix to create the replication fork.",
      difficulty: 3,
    },
    {
      question_text: "Which of the following best describes natural selection?",
      choice_a: "All organisms evolve at the same rate.",
      choice_b: "Organisms with favorable traits are more likely to survive and reproduce.",
      choice_c: "Traits acquired during an organism's lifetime are passed to offspring.",
      choice_d: "Evolution is directed toward greater complexity.",
      correct_choice: "b",
      explanation: "Natural selection is Darwin's mechanism: heritable traits that improve survival and reproduction become more common in a population over generations.",
      difficulty: 1,
    },
    {
      question_text: "The human digestive enzyme pepsin functions best in which pH environment?",
      choice_a: "Neutral (pH 7)",
      choice_b: "Basic (pH 8–9)",
      choice_c: "Highly acidic (pH 1–2)",
      choice_d: "Slightly acidic (pH 5–6)",
      correct_choice: "c",
      explanation: "Pepsin is a protease secreted by the stomach. It has optimal activity at the stomach's highly acidic pH of approximately 1.5–2.",
      difficulty: 2,
    },
  ],

  // ── Science: Chemistry ───────────────────────────────────────────────────
  chemistry: [
    {
      question_text: "What is the atomic number of carbon?",
      choice_a: "6",
      choice_b: "12",
      choice_c: "14",
      choice_d: "8",
      correct_choice: "a",
      explanation: "The atomic number equals the number of protons. Carbon has 6 protons, giving it atomic number 6. Its atomic mass (12) is often confused with the atomic number.",
      difficulty: 1,
    },
    {
      question_text: "Which type of chemical bond involves the sharing of electron pairs between atoms?",
      choice_a: "Ionic bond",
      choice_b: "Covalent bond",
      choice_c: "Metallic bond",
      choice_d: "Hydrogen bond",
      correct_choice: "b",
      explanation: "Covalent bonds form when atoms share electron pairs to achieve stable electron configurations.",
      difficulty: 1,
    },
    {
      question_text: "Balance the equation: H₂ + O₂ → H₂O. What are the correct coefficients?",
      choice_a: "1, 1, 1",
      choice_b: "2, 1, 2",
      choice_c: "2, 2, 2",
      choice_d: "1, 2, 2",
      correct_choice: "b",
      explanation: "2H₂ + O₂ → 2H₂O. This balances with 4 H atoms and 2 O atoms on each side.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is a property of acids?",
      choice_a: "pH greater than 7",
      choice_b: "Turns red litmus paper blue",
      choice_c: "Donates protons (H⁺) in solution",
      choice_d: "Produces OH⁻ ions in solution",
      correct_choice: "c",
      explanation: "According to the Brønsted-Lowry definition, an acid is a proton (H⁺) donor. Acids have pH < 7 and turn blue litmus red.",
      difficulty: 1,
    },
    {
      question_text: "What happens to the volume of a gas if pressure is doubled at constant temperature (Boyle's Law)?",
      choice_a: "It doubles",
      choice_b: "It is halved",
      choice_c: "It stays the same",
      choice_d: "It quadruples",
      correct_choice: "b",
      explanation: "Boyle's Law states P₁V₁ = P₂V₂. If pressure doubles (P₂ = 2P₁), then volume must halve (V₂ = V₁/2) at constant temperature.",
      difficulty: 2,
    },
    {
      question_text: "Which element has the highest electronegativity on the Pauling scale?",
      choice_a: "Oxygen",
      choice_b: "Nitrogen",
      choice_c: "Chlorine",
      choice_d: "Fluorine",
      correct_choice: "d",
      explanation: "Fluorine has the highest electronegativity (3.98 on the Pauling scale) of all elements, due to its small atomic radius and high nuclear charge.",
      difficulty: 2,
    },
    {
      question_text: "In the reaction Zn + 2HCl → ZnCl₂ + H₂, what type of reaction is this?",
      choice_a: "Synthesis",
      choice_b: "Decomposition",
      choice_c: "Single displacement",
      choice_d: "Double displacement",
      correct_choice: "c",
      explanation: "A single displacement reaction occurs when one element replaces another in a compound. Zinc replaces hydrogen from HCl.",
      difficulty: 2,
    },
    {
      question_text: "What is the molarity of a solution containing 2 moles of NaCl dissolved in 500 mL of solution?",
      choice_a: "1 M",
      choice_b: "2 M",
      choice_c: "4 M",
      choice_d: "0.5 M",
      correct_choice: "c",
      explanation: "Molarity = moles/liters = 2 mol / 0.5 L = 4 M.",
      difficulty: 2,
    },
    {
      question_text: "Which subatomic particle determines the chemical identity of an element?",
      choice_a: "Neutron",
      choice_b: "Electron",
      choice_c: "Proton",
      choice_d: "Positron",
      correct_choice: "c",
      explanation: "The number of protons (atomic number) uniquely identifies an element. Changing the proton count creates a different element.",
      difficulty: 1,
    },
    {
      question_text: "What is the IUPAC name of CH₃CH₂OH?",
      choice_a: "Methanol",
      choice_b: "Ethanol",
      choice_c: "Propanol",
      choice_d: "Ethene",
      correct_choice: "b",
      explanation: "CH₃CH₂OH is a two-carbon alcohol — ethanol (also called ethyl alcohol), the type found in alcoholic beverages.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is an exothermic process?",
      choice_a: "Melting of ice",
      choice_b: "Evaporation of water",
      choice_c: "Combustion of methane",
      choice_d: "Dissolution of ammonium nitrate",
      correct_choice: "c",
      explanation: "Combustion releases energy as heat and light — it is exothermic. Melting, evaporation, and dissolution of ammonium nitrate are endothermic.",
      difficulty: 2,
    },
    {
      question_text: "In a galvanic cell, oxidation occurs at the:",
      choice_a: "Cathode",
      choice_b: "Anode",
      choice_c: "Salt bridge",
      choice_d: "Electrolyte",
      correct_choice: "b",
      explanation: "In electrochemical cells, oxidation (loss of electrons) always occurs at the anode. Reduction (gain of electrons) occurs at the cathode. Mnemonic: An Ox, Red Cat.",
      difficulty: 2,
    },
    {
      question_text: "What is the hybridization of the carbon atoms in ethene (C₂H₄)?",
      choice_a: "sp³",
      choice_b: "sp²",
      choice_c: "sp",
      choice_d: "sp³d",
      correct_choice: "b",
      explanation: "Each carbon in ethene forms a double bond. sp² hybridization gives 3 sigma bonds plus an unhybridized p orbital for the pi bond.",
      difficulty: 3,
    },
    {
      question_text: "Which gas is produced when a metal carbonate reacts with an acid?",
      choice_a: "Hydrogen (H₂)",
      choice_b: "Oxygen (O₂)",
      choice_c: "Carbon dioxide (CO₂)",
      choice_d: "Nitrogen (N₂)",
      correct_choice: "c",
      explanation: "Metal carbonate + acid → salt + water + CO₂. For example: CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂.",
      difficulty: 1,
    },
    {
      question_text: "Le Chatelier's Principle states that if a system at equilibrium is disturbed, it will:",
      choice_a: "Shift to increase the disturbance",
      choice_b: "Shift to counteract the disturbance and re-establish equilibrium",
      choice_c: "Remain unchanged",
      choice_d: "Shift to always increase temperature",
      correct_choice: "b",
      explanation: "Le Chatelier's Principle: a system at equilibrium shifts in the direction that opposes the applied change (stress) to restore equilibrium.",
      difficulty: 2,
    },
  ],

  // ── Science: Physics ─────────────────────────────────────────────────────
  physics: [
    {
      question_text: "A car accelerates from rest to 30 m/s in 10 seconds. What is its acceleration?",
      choice_a: "3 m/s²",
      choice_b: "300 m/s²",
      choice_c: "0.3 m/s²",
      choice_d: "30 m/s²",
      correct_choice: "a",
      explanation: "a = Δv/t = (30 − 0) / 10 = 3 m/s².",
      difficulty: 1,
    },
    {
      question_text: "Newton's Third Law of Motion states that:",
      choice_a: "Force equals mass times acceleration.",
      choice_b: "An object at rest stays at rest unless acted upon by a net force.",
      choice_c: "For every action, there is an equal and opposite reaction.",
      choice_d: "The net force on an object equals its momentum.",
      correct_choice: "c",
      explanation: "Newton's Third Law: forces always come in action-reaction pairs that are equal in magnitude and opposite in direction.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is a vector quantity?",
      choice_a: "Speed",
      choice_b: "Mass",
      choice_c: "Temperature",
      choice_d: "Velocity",
      correct_choice: "d",
      explanation: "Velocity is a vector — it has both magnitude AND direction. Speed is a scalar (magnitude only). Mass and temperature are also scalars.",
      difficulty: 1,
    },
    {
      question_text: "What is the unit of electric resistance in the SI system?",
      choice_a: "Ampere",
      choice_b: "Volt",
      choice_c: "Ohm",
      choice_d: "Watt",
      correct_choice: "c",
      explanation: "The ohm (Ω) is the SI unit of electrical resistance, defined by Ohm's Law: R = V/I.",
      difficulty: 1,
    },
    {
      question_text: "A 5 kg object is lifted to a height of 10 m. What is its gravitational potential energy? (g = 10 m/s²)",
      choice_a: "50 J",
      choice_b: "500 J",
      choice_c: "5000 J",
      choice_d: "100 J",
      correct_choice: "b",
      explanation: "GPE = mgh = 5 × 10 × 10 = 500 J.",
      difficulty: 1,
    },
    {
      question_text: "What happens to the frequency of a wave if its wavelength is doubled while the wave speed remains constant?",
      choice_a: "The frequency doubles.",
      choice_b: "The frequency is halved.",
      choice_c: "The frequency remains the same.",
      choice_d: "The frequency quadruples.",
      correct_choice: "b",
      explanation: "v = fλ. If v is constant and λ doubles, then f = v/λ means f is halved.",
      difficulty: 2,
    },
    {
      question_text: "According to Ohm's Law, if voltage is doubled and resistance stays the same, current will:",
      choice_a: "halve",
      choice_b: "stay the same",
      choice_c: "double",
      choice_d: "quadruple",
      correct_choice: "c",
      explanation: "Ohm's Law: I = V/R. If R is constant and V doubles, then I doubles.",
      difficulty: 1,
    },
    {
      question_text: "The law of conservation of energy states that:",
      choice_a: "Energy can be created from matter.",
      choice_b: "Energy cannot be created or destroyed, only transformed.",
      choice_c: "Kinetic energy is always equal to potential energy.",
      choice_d: "Energy is always lost as heat.",
      correct_choice: "b",
      explanation: "The first law of thermodynamics (conservation of energy): the total energy in a closed system is constant. Energy changes form but is never created or destroyed.",
      difficulty: 1,
    },
    {
      question_text: "Two objects, one with mass 1 kg and one with mass 4 kg, fall from the same height in a vacuum. Which hits the ground first?",
      choice_a: "The 4 kg object",
      choice_b: "The 1 kg object",
      choice_c: "They hit at the same time.",
      choice_d: "Depends on the height",
      correct_choice: "c",
      explanation: "In a vacuum (no air resistance), all objects accelerate at the same rate (g ≈ 9.8 m/s²) regardless of mass — Galileo's principle.",
      difficulty: 2,
    },
    {
      question_text: "Which electromagnetic wave has the highest frequency?",
      choice_a: "Radio waves",
      choice_b: "Visible light",
      choice_c: "X-rays",
      choice_d: "Gamma rays",
      correct_choice: "d",
      explanation: "The EM spectrum from lowest to highest frequency: radio → microwave → infrared → visible → UV → X-ray → gamma ray. Gamma rays have the highest frequency and energy.",
      difficulty: 2,
    },
    {
      question_text: "A 60 W light bulb is left on for 2 hours. How much energy does it consume?",
      choice_a: "120 J",
      choice_b: "432,000 J",
      choice_c: "7,200 J",
      choice_d: "3,600 J",
      correct_choice: "b",
      explanation: "E = P × t = 60 W × (2 × 3600 s) = 60 × 7200 = 432,000 J.",
      difficulty: 2,
    },
    {
      question_text: "What is the phenomenon where light bends when passing from one medium to another?",
      choice_a: "Reflection",
      choice_b: "Diffraction",
      choice_c: "Refraction",
      choice_d: "Dispersion",
      correct_choice: "c",
      explanation: "Refraction is the bending of light (or other waves) as it passes from one medium to another due to a change in speed.",
      difficulty: 1,
    },
    {
      question_text: "A ball is thrown horizontally from a cliff. Which force acts on it during flight (ignoring air resistance)?",
      choice_a: "Gravity only",
      choice_b: "The initial throwing force only",
      choice_c: "Both gravity and the throwing force",
      choice_d: "No force acts on it",
      correct_choice: "a",
      explanation: "Once the ball leaves the hand, the throwing force no longer acts. Only gravity (and air resistance, which is ignored) acts on it during flight.",
      difficulty: 2,
    },
    {
      question_text: "The Doppler effect explains why a siren sounds higher-pitched as it approaches and lower-pitched as it moves away. This is because:",
      choice_a: "The siren becomes louder as it approaches.",
      choice_b: "The sound waves compress (higher frequency) as the source approaches and spread out (lower frequency) as it recedes.",
      choice_c: "The human ear is more sensitive to loud sounds.",
      choice_d: "The siren changes its actual frequency.",
      correct_choice: "b",
      explanation: "As a sound source approaches, wave fronts compress, increasing the perceived frequency (higher pitch). As it recedes, they spread out, decreasing perceived frequency.",
      difficulty: 2,
    },
    {
      question_text: "What is the momentum of a 2 kg object moving at 5 m/s?",
      choice_a: "2.5 kg·m/s",
      choice_b: "7 kg·m/s",
      choice_c: "10 kg·m/s",
      choice_d: "3 kg·m/s",
      correct_choice: "c",
      explanation: "Momentum p = mv = 2 kg × 5 m/s = 10 kg·m/s.",
      difficulty: 1,
    },
  ],

  // ── Science: Earth Science ───────────────────────────────────────────────
  "earth-science": [
    {
      question_text: "Which layer of the Earth is responsible for generating the planet's magnetic field?",
      choice_a: "Crust",
      choice_b: "Mantle",
      choice_c: "Outer core",
      choice_d: "Inner core",
      correct_choice: "c",
      explanation: "Earth's magnetic field is generated by convection currents of molten iron and nickel in the liquid outer core (the geodynamo effect).",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is caused by the collision of two continental plates?",
      choice_a: "Subduction zones",
      choice_b: "Ocean trenches",
      choice_c: "Mountain ranges",
      choice_d: "Mid-ocean ridges",
      correct_choice: "c",
      explanation: "When two continental plates collide, neither subducts easily, so the crust crumples and folds upward, forming mountain ranges like the Himalayas.",
      difficulty: 2,
    },
    {
      question_text: "The rock cycle describes how rocks:",
      choice_a: "Evolve into different types of minerals over time",
      choice_b: "Are formed, transformed, and recycled through geological processes",
      choice_c: "Only form from magma cooling",
      choice_d: "Move from the crust to the core",
      correct_choice: "b",
      explanation: "The rock cycle describes continuous transformations among igneous, sedimentary, and metamorphic rocks through geological processes like erosion, melting, and pressure.",
      difficulty: 1,
    },
    {
      question_text: "Which type of rock forms from the cooling and solidification of magma or lava?",
      choice_a: "Sedimentary",
      choice_b: "Metamorphic",
      choice_c: "Igneous",
      choice_d: "Organic",
      correct_choice: "c",
      explanation: "Igneous rocks (from Latin 'ignis' = fire) form when molten rock cools. Intrusive igneous rocks form below ground; extrusive form on the surface.",
      difficulty: 1,
    },
    {
      question_text: "What causes seasons on Earth?",
      choice_a: "Variation in Earth's distance from the Sun throughout the year",
      choice_b: "The tilt of Earth's axis relative to its orbital plane",
      choice_c: "The rotation of Earth on its axis",
      choice_d: "Sunspot activity",
      correct_choice: "b",
      explanation: "Earth's 23.5° axial tilt causes different hemispheres to receive more direct sunlight at different times of the year, creating seasons.",
      difficulty: 1,
    },
    {
      question_text: "The 'greenhouse effect' refers to:",
      choice_a: "The cooling of Earth's surface by cloud cover",
      choice_b: "The trapping of solar radiation by atmospheric gases, warming the Earth",
      choice_c: "The reflection of sunlight by ice caps",
      choice_d: "The absorption of CO₂ by oceans",
      correct_choice: "b",
      explanation: "Greenhouse gases (CO₂, CH₄, H₂O vapor) absorb outgoing infrared radiation and re-emit it, trapping heat in the lower atmosphere.",
      difficulty: 1,
    },
    {
      question_text: "Which type of seismic wave causes the most damage during an earthquake?",
      choice_a: "P-waves (primary waves)",
      choice_b: "S-waves (secondary waves)",
      choice_c: "Surface waves",
      choice_d: "All waves cause equal damage",
      correct_choice: "c",
      explanation: "Surface waves (Love and Rayleigh waves) travel along Earth's surface and cause the most ground shaking and structural damage during earthquakes.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is a renewable energy source?",
      choice_a: "Natural gas",
      choice_b: "Coal",
      choice_c: "Solar energy",
      choice_d: "Petroleum",
      correct_choice: "c",
      explanation: "Renewable energy sources are naturally replenished on a human timescale. Solar energy from the Sun is continuously available and inexhaustible.",
      difficulty: 1,
    },
    {
      question_text: "The Richter scale measures which property of earthquakes?",
      choice_a: "Duration",
      choice_b: "Depth",
      choice_c: "Magnitude (energy released)",
      choice_d: "Damage caused",
      correct_choice: "c",
      explanation: "The Richter scale is a logarithmic scale that measures earthquake magnitude — the energy released at the source. Each whole number increase represents ~31.6 times more energy.",
      difficulty: 1,
    },
    {
      question_text: "What is the primary cause of ocean tides?",
      choice_a: "Earth's rotation",
      choice_b: "Wind patterns over the ocean",
      choice_c: "Gravitational pull of the Moon",
      choice_d: "Underwater volcanic activity",
      correct_choice: "c",
      explanation: "The Moon's gravitational pull is the dominant cause of ocean tides. The Sun also contributes, but the Moon's effect is about 2.2 times stronger due to its proximity.",
      difficulty: 1,
    },
    {
      question_text: "Which atmospheric layer contains the ozone layer?",
      choice_a: "Troposphere",
      choice_b: "Stratosphere",
      choice_c: "Mesosphere",
      choice_d: "Thermosphere",
      correct_choice: "b",
      explanation: "The ozone layer is located in the stratosphere (15–35 km above Earth), where it absorbs most of the Sun's harmful ultraviolet radiation.",
      difficulty: 1,
    },
    {
      question_text: "Which principle states that rock layers (strata) are deposited horizontally and older layers lie below younger ones?",
      choice_a: "Uniformitarianism",
      choice_b: "Principle of lateral continuity",
      choice_c: "Law of superposition",
      choice_d: "Cross-cutting relationships",
      correct_choice: "c",
      explanation: "Steno's Law of Superposition states that in undisturbed rock sequences, older layers are found beneath younger layers.",
      difficulty: 2,
    },
    {
      question_text: "What is the 'water cycle' also known as?",
      choice_a: "Carbon cycle",
      choice_b: "Nitrogen cycle",
      choice_c: "Hydrological cycle",
      choice_d: "Rock cycle",
      correct_choice: "c",
      explanation: "The water cycle is formally called the hydrological cycle — the continuous movement of water through evaporation, condensation, precipitation, and runoff.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following correctly explains why the sky appears blue?",
      choice_a: "Blue light is absorbed by the atmosphere.",
      choice_b: "Blue light has the longest wavelength and travels straight.",
      choice_c: "Blue light scatters more in all directions due to its short wavelength (Rayleigh scattering).",
      choice_d: "Water vapor in the air gives the sky its blue color.",
      correct_choice: "c",
      explanation: "Rayleigh scattering: shorter wavelengths (blue, violet) scatter more in all directions when hitting air molecules. Our eyes are more sensitive to blue, making the sky appear blue.",
      difficulty: 2,
    },
    {
      question_text: "A volcano that erupts with very viscous lava and explosive eruptions is most likely of which type?",
      choice_a: "Shield volcano",
      choice_b: "Cinder cone",
      choice_c: "Stratovolcano (composite volcano)",
      choice_d: "Lava dome",
      correct_choice: "c",
      explanation: "Stratovolcanoes are built from alternating layers of lava, ash, and pyroclastic material. Their silica-rich, viscous magma traps gases, causing explosive eruptions.",
      difficulty: 3,
    },
  ],

  // ── Mathematics: Algebra ─────────────────────────────────────────────────
  algebra: [
    {
      question_text: "Solve for x: 2x + 5 = 13",
      choice_a: "x = 3",
      choice_b: "x = 4",
      choice_c: "x = 9",
      choice_d: "x = 6",
      correct_choice: "b",
      explanation: "2x + 5 = 13 → 2x = 8 → x = 4.",
      difficulty: 1,
    },
    {
      question_text: "What is the value of x in 3(x − 2) = 2(x + 1)?",
      choice_a: "x = 7",
      choice_b: "x = 8",
      choice_c: "x = 4",
      choice_d: "x = 6",
      correct_choice: "b",
      explanation: "3x − 6 = 2x + 2 → x = 8.",
      difficulty: 1,
    },
    {
      question_text: "Factor completely: x² − 9",
      choice_a: "(x − 3)²",
      choice_b: "(x + 3)(x − 3)",
      choice_c: "(x + 9)(x − 1)",
      choice_d: "(x − 9)(x + 1)",
      correct_choice: "b",
      explanation: "x² − 9 is a difference of squares: a² − b² = (a + b)(a − b), so x² − 9 = (x + 3)(x − 3).",
      difficulty: 1,
    },
    {
      question_text: "Solve the system: x + y = 7 and x − y = 3. What is x?",
      choice_a: "2",
      choice_b: "4",
      choice_c: "5",
      choice_d: "6",
      correct_choice: "c",
      explanation: "Adding the equations: 2x = 10, so x = 5. Then y = 7 − 5 = 2.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is the slope-intercept form of a line?",
      choice_a: "Ax + By = C",
      choice_b: "y − y₁ = m(x − x₁)",
      choice_c: "y = mx + b",
      choice_d: "x/a + y/b = 1",
      correct_choice: "c",
      explanation: "The slope-intercept form y = mx + b directly shows the slope (m) and y-intercept (b) of a linear function.",
      difficulty: 1,
    },
    {
      question_text: "Simplify: (3x²y)(4xy³)",
      choice_a: "12x²y³",
      choice_b: "12x³y⁴",
      choice_c: "7x³y⁴",
      choice_d: "12x²y⁴",
      correct_choice: "b",
      explanation: "(3 × 4)(x² × x)(y × y³) = 12 · x³ · y⁴.",
      difficulty: 2,
    },
    {
      question_text: "What are the solutions of x² − 5x + 6 = 0?",
      choice_a: "x = 1 and x = 6",
      choice_b: "x = −2 and x = −3",
      choice_c: "x = 2 and x = 3",
      choice_d: "x = −1 and x = −6",
      correct_choice: "c",
      explanation: "Factor: (x − 2)(x − 3) = 0 → x = 2 or x = 3. Check: 2 × 3 = 6 and 2 + 3 = 5.",
      difficulty: 2,
    },
    {
      question_text: "If f(x) = 2x² − 3x + 1, what is f(2)?",
      choice_a: "3",
      choice_b: "5",
      choice_c: "7",
      choice_d: "9",
      correct_choice: "a",
      explanation: "f(2) = 2(4) − 3(2) + 1 = 8 − 6 + 1 = 3.",
      difficulty: 2,
    },
    {
      question_text: "What is the discriminant of 2x² − 4x + 2 = 0, and what does it indicate?",
      choice_a: "Discriminant = 0; two equal real roots",
      choice_b: "Discriminant = 8; two distinct real roots",
      choice_c: "Discriminant = −8; no real roots",
      choice_d: "Discriminant = 16; two distinct real roots",
      correct_choice: "a",
      explanation: "b² − 4ac = (−4)² − 4(2)(2) = 16 − 16 = 0. A discriminant of zero means exactly one (repeated) real root.",
      difficulty: 2,
    },
    {
      question_text: "Solve the inequality: 2x − 3 > 7",
      choice_a: "x > 2",
      choice_b: "x > 5",
      choice_c: "x < 5",
      choice_d: "x > 10",
      correct_choice: "b",
      explanation: "2x − 3 > 7 → 2x > 10 → x > 5.",
      difficulty: 1,
    },
    {
      question_text: "What is the value of log₂(64)?",
      choice_a: "4",
      choice_b: "8",
      choice_c: "6",
      choice_d: "32",
      correct_choice: "c",
      explanation: "log₂(64) = x means 2ˣ = 64 = 2⁶, so x = 6.",
      difficulty: 2,
    },
    {
      question_text: "Simplify: (x² − 4) / (x − 2), x ≠ 2",
      choice_a: "x − 2",
      choice_b: "x + 2",
      choice_c: "x + 4",
      choice_d: "x² + 2",
      correct_choice: "b",
      explanation: "(x² − 4) = (x + 2)(x − 2). Divided by (x − 2), this simplifies to (x + 2).",
      difficulty: 2,
    },
    {
      question_text: "The sum of two numbers is 30 and their difference is 10. What is the larger number?",
      choice_a: "15",
      choice_b: "20",
      choice_c: "25",
      choice_d: "10",
      correct_choice: "b",
      explanation: "x + y = 30 and x − y = 10. Adding: 2x = 40, x = 20. So the larger number is 20.",
      difficulty: 1,
    },
    {
      question_text: "What is the 8th term of the arithmetic sequence 3, 7, 11, 15, …?",
      choice_a: "31",
      choice_b: "33",
      choice_c: "27",
      choice_d: "35",
      correct_choice: "a",
      explanation: "aₙ = a₁ + (n−1)d = 3 + (8−1)(4) = 3 + 28 = 31.",
      difficulty: 2,
    },
    {
      question_text: "A car rental costs ₱500 per day plus ₱5 per km. If someone paid ₱2,000, how many kilometers did they travel for a 1-day rental?",
      choice_a: "250 km",
      choice_b: "300 km",
      choice_c: "400 km",
      choice_d: "350 km",
      correct_choice: "b",
      explanation: "500 + 5d = 2000 → 5d = 1500 → d = 300 km.",
      difficulty: 2,
    },
  ],

  // ── Mathematics: Geometry ─────────────────────────────────────────────────
  geometry: [
    {
      question_text: "What is the area of a triangle with base 8 cm and height 5 cm?",
      choice_a: "40 cm²",
      choice_b: "20 cm²",
      choice_c: "13 cm²",
      choice_d: "80 cm²",
      correct_choice: "b",
      explanation: "Area = ½ × base × height = ½ × 8 × 5 = 20 cm².",
      difficulty: 1,
    },
    {
      question_text: "What is the sum of interior angles of a hexagon?",
      choice_a: "540°",
      choice_b: "720°",
      choice_c: "900°",
      choice_d: "360°",
      correct_choice: "b",
      explanation: "Sum of interior angles = (n − 2) × 180° = (6 − 2) × 180° = 720°.",
      difficulty: 1,
    },
    {
      question_text: "A right triangle has legs of 6 cm and 8 cm. What is the length of the hypotenuse?",
      choice_a: "14 cm",
      choice_b: "100 cm",
      choice_c: "10 cm",
      choice_d: "12 cm",
      correct_choice: "c",
      explanation: "By the Pythagorean theorem: c² = 6² + 8² = 36 + 64 = 100, so c = 10 cm.",
      difficulty: 1,
    },
    {
      question_text: "What is the circumference of a circle with radius 7 cm? (Use π ≈ 22/7)",
      choice_a: "44 cm",
      choice_b: "22 cm",
      choice_c: "154 cm",
      choice_d: "14 cm",
      correct_choice: "a",
      explanation: "C = 2πr = 2 × (22/7) × 7 = 44 cm.",
      difficulty: 1,
    },
    {
      question_text: "Two angles are supplementary. One measures 65°. What is the other?",
      choice_a: "25°",
      choice_b: "115°",
      choice_c: "125°",
      choice_d: "295°",
      correct_choice: "b",
      explanation: "Supplementary angles sum to 180°. 180° − 65° = 115°.",
      difficulty: 1,
    },
    {
      question_text: "What is the volume of a rectangular prism with length 5 cm, width 4 cm, and height 3 cm?",
      choice_a: "60 cm³",
      choice_b: "47 cm³",
      choice_c: "12 cm³",
      choice_d: "94 cm³",
      correct_choice: "a",
      explanation: "V = l × w × h = 5 × 4 × 3 = 60 cm³.",
      difficulty: 1,
    },
    {
      question_text: "In a circle, a chord that passes through the center is called:",
      choice_a: "Radius",
      choice_b: "Arc",
      choice_c: "Diameter",
      choice_d: "Tangent",
      correct_choice: "c",
      explanation: "A chord passing through the center of a circle is the diameter — the longest chord possible, equal to twice the radius.",
      difficulty: 1,
    },
    {
      question_text: "The area of a circle with diameter 10 cm is:",
      choice_a: "78.5 cm²",
      choice_b: "31.4 cm²",
      choice_c: "314 cm²",
      choice_d: "100 cm²",
      correct_choice: "a",
      explanation: "Radius = 5. Area = πr² = π(25) ≈ 3.14 × 25 = 78.5 cm².",
      difficulty: 1,
    },
    {
      question_text: "Two parallel lines are cut by a transversal. Alternate interior angles are:",
      choice_a: "Supplementary",
      choice_b: "Equal (congruent)",
      choice_c: "Complementary",
      choice_d: "Vertical",
      correct_choice: "b",
      explanation: "When parallel lines are cut by a transversal, alternate interior angles are congruent (equal in measure).",
      difficulty: 2,
    },
    {
      question_text: "What is the surface area of a cube with side length 4 cm?",
      choice_a: "64 cm²",
      choice_b: "16 cm²",
      choice_c: "96 cm²",
      choice_d: "48 cm²",
      correct_choice: "c",
      explanation: "A cube has 6 faces. Surface area = 6 × s² = 6 × 16 = 96 cm².",
      difficulty: 2,
    },
    {
      question_text: "ΔABC is similar to ΔDEF. If AB = 6, DE = 9, and BC = 8, what is EF?",
      choice_a: "12",
      choice_b: "10",
      choice_c: "6",
      choice_d: "9",
      correct_choice: "a",
      explanation: "Similar triangles have proportional sides: AB/DE = BC/EF → 6/9 = 8/EF → EF = 8 × 9/6 = 12.",
      difficulty: 2,
    },
    {
      question_text: "What is the midpoint of the line segment connecting (2, 4) and (6, 10)?",
      choice_a: "(4, 7)",
      choice_b: "(8, 14)",
      choice_c: "(3, 6)",
      choice_d: "(4, 6)",
      correct_choice: "a",
      explanation: "Midpoint = ((x₁+x₂)/2, (y₁+y₂)/2) = ((2+6)/2, (4+10)/2) = (4, 7).",
      difficulty: 2,
    },
    {
      question_text: "An inscribed angle in a circle intercepts an arc of 100°. What is the measure of the inscribed angle?",
      choice_a: "200°",
      choice_b: "100°",
      choice_c: "50°",
      choice_d: "25°",
      correct_choice: "c",
      explanation: "The Inscribed Angle Theorem: an inscribed angle is half the central angle that subtends the same arc. 100° ÷ 2 = 50°.",
      difficulty: 2,
    },
    {
      question_text: "What is the slope of a line perpendicular to y = 3x − 1?",
      choice_a: "3",
      choice_b: "−3",
      choice_c: "1/3",
      choice_d: "−1/3",
      correct_choice: "d",
      explanation: "Perpendicular lines have slopes that are negative reciprocals. Slope of given line = 3; perpendicular slope = −1/3.",
      difficulty: 2,
    },
    {
      question_text: "What is the distance between the points (1, 2) and (4, 6)?",
      choice_a: "5",
      choice_b: "7",
      choice_c: "25",
      choice_d: "√7",
      correct_choice: "a",
      explanation: "d = √((4−1)² + (6−2)²) = √(9 + 16) = √25 = 5.",
      difficulty: 2,
    },
  ],

  // ── Mathematics: Statistics ───────────────────────────────────────────────
  statistics: [
    {
      question_text: "What is the mean of the data set: 4, 8, 6, 10, 12?",
      choice_a: "7",
      choice_b: "8",
      choice_c: "10",
      choice_d: "6",
      correct_choice: "b",
      explanation: "Mean = (4 + 8 + 6 + 10 + 12) / 5 = 40 / 5 = 8.",
      difficulty: 1,
    },
    {
      question_text: "What is the median of: 3, 7, 5, 1, 9?",
      choice_a: "5",
      choice_b: "7",
      choice_c: "3",
      choice_d: "6",
      correct_choice: "a",
      explanation: "Arrange in order: 1, 3, 5, 7, 9. The middle value (3rd of 5) is 5.",
      difficulty: 1,
    },
    {
      question_text: "What is the mode of: 2, 3, 4, 4, 5, 4, 6?",
      choice_a: "2",
      choice_b: "4",
      choice_c: "5",
      choice_d: "6",
      correct_choice: "b",
      explanation: "The mode is the most frequently occurring value. 4 appears three times — more than any other value.",
      difficulty: 1,
    },
    {
      question_text: "A bag has 3 red balls and 5 blue balls. What is the probability of drawing a red ball?",
      choice_a: "3/8",
      choice_b: "5/8",
      choice_c: "3/5",
      choice_d: "1/3",
      correct_choice: "a",
      explanation: "P(red) = 3 / (3 + 5) = 3/8.",
      difficulty: 1,
    },
    {
      question_text: "A coin is tossed twice. What is the probability of getting two heads?",
      choice_a: "1/2",
      choice_b: "1/4",
      choice_c: "1/3",
      choice_d: "2/4",
      correct_choice: "b",
      explanation: "P(HH) = P(H) × P(H) = 1/2 × 1/2 = 1/4. The events are independent.",
      difficulty: 1,
    },
    {
      question_text: "What is the range of the data set: 15, 22, 8, 30, 17?",
      choice_a: "14",
      choice_b: "22",
      choice_c: "30",
      choice_d: "8",
      correct_choice: "b",
      explanation: "Range = maximum − minimum = 30 − 8 = 22.",
      difficulty: 1,
    },
    {
      question_text: "In a class of 30 students, 18 passed. What is the probability that a randomly chosen student failed?",
      choice_a: "3/5",
      choice_b: "2/5",
      choice_c: "18/30",
      choice_d: "1/2",
      correct_choice: "b",
      explanation: "Students who failed = 30 − 18 = 12. P(failed) = 12/30 = 2/5.",
      difficulty: 1,
    },
    {
      question_text: "A die is rolled. What is the probability of getting an even number?",
      choice_a: "1/6",
      choice_b: "1/3",
      choice_c: "1/2",
      choice_d: "2/3",
      correct_choice: "c",
      explanation: "Even numbers on a die: 2, 4, 6 — 3 out of 6 faces. P(even) = 3/6 = 1/2.",
      difficulty: 1,
    },
    {
      question_text: "Which measure of central tendency is MOST affected by extreme values (outliers)?",
      choice_a: "Mean",
      choice_b: "Median",
      choice_c: "Mode",
      choice_d: "Range",
      correct_choice: "a",
      explanation: "The mean uses all values in its calculation, so extreme values (outliers) significantly pull it up or down. The median and mode are more resistant to outliers.",
      difficulty: 2,
    },
    {
      question_text: "A bag has 4 green and 6 yellow marbles. Two marbles are drawn without replacement. What is the probability both are green?",
      choice_a: "4/25",
      choice_b: "2/15",
      choice_c: "4/15",
      choice_d: "1/6",
      correct_choice: "b",
      explanation: "P(1st green) = 4/10. P(2nd green | 1st green) = 3/9 = 1/3. P(both green) = 4/10 × 3/9 = 12/90 = 2/15.",
      difficulty: 2,
    },
    {
      question_text: "If the mean of 5 numbers is 12, what is their sum?",
      choice_a: "17",
      choice_b: "60",
      choice_c: "24",
      choice_d: "120",
      correct_choice: "b",
      explanation: "Mean = Sum / Count → Sum = Mean × Count = 12 × 5 = 60.",
      difficulty: 1,
    },
    {
      question_text: "What is the variance of the data set: 2, 4, 4, 4, 6? (Mean = 4)",
      choice_a: "4",
      choice_b: "2",
      choice_c: "1",
      choice_d: "8",
      correct_choice: "b",
      explanation: "Deviations: −2, 0, 0, 0, 2. Squared: 4, 0, 0, 0, 4. Sum = 8. Variance = 8/4 = 2 (population) or 8/5 = 1.6 (sample). The exact answer here uses population variance: 8/4 = 2.",
      difficulty: 3,
    },
    {
      question_text: "In a normal distribution, approximately what percentage of data falls within one standard deviation of the mean?",
      choice_a: "50%",
      choice_b: "68%",
      choice_c: "95%",
      choice_d: "99.7%",
      correct_choice: "b",
      explanation: "The empirical rule (68-95-99.7): about 68% of data falls within 1 standard deviation, 95% within 2, and 99.7% within 3 standard deviations of the mean.",
      difficulty: 2,
    },
    {
      question_text: "A number is chosen at random from 1 to 20. What is the probability it is divisible by 3?",
      choice_a: "1/4",
      choice_b: "3/20",
      choice_c: "3/10",
      choice_d: "1/5",
      correct_choice: "c",
      explanation: "Numbers from 1–20 divisible by 3: 3, 6, 9, 12, 15, 18 — that is 6 numbers. P = 6/20 = 3/10.",
      difficulty: 2,
    },
    {
      question_text: "How many ways can 5 people sit in a row of 5 chairs?",
      choice_a: "25",
      choice_b: "60",
      choice_c: "120",
      choice_d: "20",
      correct_choice: "c",
      explanation: "This is a permutation of 5 things taken 5 at a time: 5! = 5 × 4 × 3 × 2 × 1 = 120.",
      difficulty: 2,
    },
  ],
};

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱  Starting Libreview seed...\n");

  // Universities
  console.log("Seeding universities...");
  const { error: uniError } = await supabase
    .from("universities")
    .upsert(UNIVERSITIES, { onConflict: "slug" });
  if (uniError) throw new Error(`Universities: ${uniError.message}`);
  console.log(`  ✓ ${UNIVERSITIES.length} universities`);

  // Subtests
  console.log("Seeding subtests...");
  const { data: subtests, error: subtestError } = await supabase
    .from("subtests")
    .upsert(SUBTESTS, { onConflict: "slug" })
    .select("id, slug");
  if (subtestError) throw new Error(`Subtests: ${subtestError.message}`);
  console.log(`  ✓ ${subtests?.length} subtests`);

  const subtestMap: Record<string, string> = {};
  for (const s of subtests ?? []) subtestMap[s.slug] = s.id;

  // Topics + Questions
  for (const [subtestSlug, topicList] of Object.entries(TOPICS_BY_SUBTEST)) {
    const subtestId = subtestMap[subtestSlug];
    if (!subtestId) {
      console.warn(`  ⚠  No subtest found for slug: ${subtestSlug}`);
      continue;
    }

    for (const topic of topicList) {
      console.log(`Seeding topic: ${topic.name}...`);

      const { data: topicRow, error: topicError } = await supabase
        .from("topics")
        .upsert({ ...topic, subtest_id: subtestId }, { onConflict: "subtest_id,slug" })
        .select("id, slug")
        .single();
      if (topicError) throw new Error(`Topic ${topic.slug}: ${topicError.message}`);

      const questions = QUESTIONS[topic.slug];
      if (!questions || questions.length === 0) {
        console.warn(`  ⚠  No questions defined for topic: ${topic.slug}`);
        continue;
      }

      const questionRows = questions.map((q) => ({
        ...q,
        topic_id: topicRow.id,
        status: "approved" as const,
      }));

      const { error: qError } = await supabase.from("questions").insert(questionRows);
      if (qError) throw new Error(`Questions for ${topic.slug}: ${qError.message}`);
      console.log(`  ✓ ${questionRows.length} questions for "${topic.name}"`);
    }
  }

  console.log("\n✅  Seed complete!");
}

main().catch((err) => {
  console.error("❌  Seed failed:", err.message);
  process.exit(1);
});
