/**
 * Seeds 210 premium Math questions: 30 per topic × 7 topics.
 * Also creates the "Analytic Geometry" topic if it doesn't exist.
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-math-210.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

// ── ALGEBRA (30) ─────────────────────────────────────────────────────────────

const ALGEBRA: Q[] = [
  {
    question_text: "Simplify: 3x² + 5x − 2x² − 3x + 7",
    choice_a: "x² + 2x + 7",
    choice_b: "5x² + 8x + 7",
    choice_c: "x² − 2x + 7",
    choice_d: "x² + 2x − 7",
    correct_choice: "a",
    explanation: "Combine like terms: (3x²−2x²) + (5x−3x) + 7 = x² + 2x + 7.",
    difficulty: 1,
  },
  {
    question_text: "Solve for x: 2(x − 3) = 4x + 2",
    choice_a: "x = −4",
    choice_b: "x = 4",
    choice_c: "x = −2",
    choice_d: "x = 2",
    correct_choice: "a",
    explanation: "2x − 6 = 4x + 2 → −6 − 2 = 4x − 2x → −8 = 2x → x = −4.",
    difficulty: 1,
  },
  {
    question_text: "Factor completely: x² − 9",
    choice_a: "(x − 3)(x − 3)",
    choice_b: "(x + 9)(x − 1)",
    choice_c: "(x + 3)(x − 3)",
    choice_d: "(x − 9)(x + 1)",
    correct_choice: "c",
    explanation: "x² − 9 is a difference of two squares: a² − b² = (a+b)(a−b), so x² − 9 = (x+3)(x−3).",
    difficulty: 1,
  },
  {
    question_text: "If f(x) = 2x² − 3x + 1, find f(−1).",
    choice_a: "6",
    choice_b: "−4",
    choice_c: "4",
    choice_d: "0",
    correct_choice: "a",
    explanation: "f(−1) = 2(1) − 3(−1) + 1 = 2 + 3 + 1 = 6.",
    difficulty: 1,
  },
  {
    question_text: "Solve the system: x + y = 7 and x − y = 3.",
    choice_a: "x = 5, y = 2",
    choice_b: "x = 2, y = 5",
    choice_c: "x = 4, y = 3",
    choice_d: "x = 3, y = 4",
    correct_choice: "a",
    explanation: "Adding the equations: 2x = 10 → x = 5. Substituting: 5 + y = 7 → y = 2.",
    difficulty: 1,
  },
  {
    question_text: "Which value of x satisfies |2x − 4| = 6?",
    choice_a: "x = 5 only",
    choice_b: "x = −1 only",
    choice_c: "x = 5 or x = −1",
    choice_d: "x = 1 or x = −5",
    correct_choice: "c",
    explanation: "2x − 4 = 6 → x = 5; or 2x − 4 = −6 → 2x = −2 → x = −1.",
    difficulty: 1,
  },
  {
    question_text: "What is the sum of the roots of x² − 5x + 6 = 0?",
    choice_a: "6",
    choice_b: "5",
    choice_c: "−5",
    choice_d: "−6",
    correct_choice: "b",
    explanation: "By Vieta's formulas, the sum of roots = −b/a = −(−5)/1 = 5.",
    difficulty: 1,
  },
  {
    question_text: "Simplify: (2x³y²)(3xy⁴)",
    choice_a: "5x⁴y⁶",
    choice_b: "6x⁴y⁶",
    choice_c: "6x³y⁸",
    choice_d: "5x³y⁸",
    correct_choice: "b",
    explanation: "Multiply coefficients: 2×3=6. Add exponents of like bases: x³·x¹=x⁴, y²·y⁴=y⁶. Result: 6x⁴y⁶.",
    difficulty: 1,
  },
  {
    question_text: "Which expression is equivalent to (x + 4)²?",
    choice_a: "x² + 8x + 16",
    choice_b: "x² + 4x + 16",
    choice_c: "x² + 16",
    choice_d: "x² + 8x + 8",
    correct_choice: "a",
    explanation: "(x+4)² = x² + 2(4)x + 4² = x² + 8x + 16.",
    difficulty: 1,
  },
  {
    question_text: "If 3x + 2 = 14, what is the value of 6x + 5?",
    choice_a: "25",
    choice_b: "29",
    choice_c: "28",
    choice_d: "27",
    correct_choice: "b",
    explanation: "3x = 12 → x = 4. Then 6(4) + 5 = 24 + 5 = 29.",
    difficulty: 1,
  },
  {
    question_text: "Factor: 6x² + 11x + 3",
    choice_a: "(6x + 1)(x + 3)",
    choice_b: "(2x + 3)(3x + 1)",
    choice_c: "(3x + 3)(2x + 1)",
    choice_d: "(6x + 3)(x + 1)",
    correct_choice: "b",
    explanation: "Test (2x+3)(3x+1): 6x²+2x+9x+3 = 6x²+11x+3. ✓",
    difficulty: 2,
  },
  {
    question_text: "Solve: x² − 4x − 12 = 0",
    choice_a: "x = 6 or x = −2",
    choice_b: "x = −6 or x = 2",
    choice_c: "x = 4 or x = −3",
    choice_d: "x = 3 or x = −4",
    correct_choice: "a",
    explanation: "Factor: (x−6)(x+2)=0 → x=6 or x=−2.",
    difficulty: 1,
  },
  {
    question_text: "What is the discriminant of 2x² − 4x + 5 = 0?",
    choice_a: "24",
    choice_b: "−24",
    choice_c: "56",
    choice_d: "−56",
    correct_choice: "b",
    explanation: "Discriminant = b²−4ac = (−4)²−4(2)(5) = 16−40 = −24. Since it's negative, no real roots.",
    difficulty: 2,
  },
  {
    question_text: "Simplify: (x² − 4)/(x − 2), where x ≠ 2",
    choice_a: "x + 2",
    choice_b: "x − 2",
    choice_c: "x",
    choice_d: "x² + 2",
    correct_choice: "a",
    explanation: "x²−4 = (x+2)(x−2). Dividing by (x−2) gives x+2.",
    difficulty: 2,
  },
  {
    question_text: "Evaluate: log₂(32)",
    choice_a: "4",
    choice_b: "5",
    choice_c: "6",
    choice_d: "3",
    correct_choice: "b",
    explanation: "2⁵ = 32, so log₂(32) = 5.",
    difficulty: 2,
  },
  {
    question_text: "If 2^(x+1) = 16, find x.",
    choice_a: "2",
    choice_b: "3",
    choice_c: "4",
    choice_d: "5",
    correct_choice: "b",
    explanation: "16 = 2⁴, so 2^(x+1) = 2⁴ → x+1 = 4 → x = 3.",
    difficulty: 2,
  },
  {
    question_text: "What is the vertex of the parabola y = x² − 6x + 8?",
    choice_a: "(3, −1)",
    choice_b: "(−3, −1)",
    choice_c: "(3, 1)",
    choice_d: "(6, 8)",
    correct_choice: "a",
    explanation: "Vertex x = −b/(2a) = 6/2 = 3. y = 9−18+8 = −1. Vertex: (3, −1).",
    difficulty: 2,
  },
  {
    question_text: "Simplify: (3x²)/(6x⁵)",
    choice_a: "2x³",
    choice_b: "1/(2x³)",
    choice_c: "2/x³",
    choice_d: "x³/2",
    correct_choice: "b",
    explanation: "3/6 = 1/2; x²/x⁵ = x^(2−5) = x^(−3) = 1/x³. Result: 1/(2x³).",
    difficulty: 2,
  },
  {
    question_text: "The arithmetic sequence has first term 3 and common difference 4. What is the 10th term?",
    choice_a: "39",
    choice_b: "43",
    choice_c: "36",
    choice_d: "40",
    correct_choice: "a",
    explanation: "aₙ = a₁ + (n−1)d = 3 + (9)(4) = 3 + 36 = 39.",
    difficulty: 2,
  },
  {
    question_text: "Find the sum of the geometric series: 2 + 6 + 18 + 54 + 162",
    choice_a: "242",
    choice_b: "244",
    choice_c: "240",
    choice_d: "248",
    correct_choice: "a",
    explanation: "S = a(rⁿ−1)/(r−1) = 2(3⁵−1)/(3−1) = 2(242)/2 = 242.",
    difficulty: 2,
  },
  {
    question_text: "Solve: log(x) + log(x−3) = 1 (base 10)",
    choice_a: "x = 5",
    choice_b: "x = −2",
    choice_c: "x = 2",
    choice_d: "x = 10",
    correct_choice: "a",
    explanation: "log[x(x−3)] = 1 → x(x−3) = 10 → x²−3x−10=0 → (x−5)(x+2)=0. x=−2 rejected (log undefined), so x=5.",
    difficulty: 2,
  },
  {
    question_text: "Solve the inequality: 3x − 7 > 2x + 1",
    choice_a: "x > 8",
    choice_b: "x < 8",
    choice_c: "x > −8",
    choice_d: "x < −8",
    correct_choice: "a",
    explanation: "3x−2x > 1+7 → x > 8.",
    difficulty: 1,
  },
  {
    question_text: "If f(x) = 3x − 1, find f⁻¹(x).",
    choice_a: "(x+1)/3",
    choice_b: "(x−1)/3",
    choice_c: "3x+1",
    choice_d: "1/(3x−1)",
    correct_choice: "a",
    explanation: "Let y = 3x−1. Swap: x = 3y−1 → y = (x+1)/3. So f⁻¹(x) = (x+1)/3.",
    difficulty: 2,
  },
  {
    question_text: "What is the product of the roots of 3x² + 6x − 9 = 0?",
    choice_a: "3",
    choice_b: "−3",
    choice_c: "6",
    choice_d: "−9",
    correct_choice: "b",
    explanation: "By Vieta's: product = c/a = −9/3 = −3.",
    difficulty: 2,
  },
  {
    question_text: "Simplify: √(48x⁴y²)",
    choice_a: "4x²y√3",
    choice_b: "4x²|y|√3",
    choice_c: "6xy√2",
    choice_d: "4xy√6",
    correct_choice: "b",
    explanation: "√48 = 4√3; √(x⁴) = x²; √(y²) = |y|. Result: 4x²|y|√3.",
    difficulty: 2,
  },
  {
    question_text: "What is the 8th term of the geometric sequence 1, 2, 4, 8, …?",
    choice_a: "64",
    choice_b: "128",
    choice_c: "256",
    choice_d: "512",
    correct_choice: "b",
    explanation: "aₙ = a₁·r^(n−1) = 1·2⁷ = 128.",
    difficulty: 1,
  },
  {
    question_text: "Find all real solutions of x⁴ − 5x² + 4 = 0.",
    choice_a: "x = ±1 and x = ±2",
    choice_b: "x = 1 and x = 4",
    choice_c: "x = ±2 only",
    choice_d: "x = ±1 only",
    correct_choice: "a",
    explanation: "Let u = x²: u²−5u+4=0 → (u−1)(u−4)=0 → u=1 or u=4 → x=±1 or x=±2.",
    difficulty: 3,
  },
  {
    question_text: "Solve: (x+2)/(x−1) = 3",
    choice_a: "x = 5/2",
    choice_b: "x = 2",
    choice_c: "x = 1/2",
    choice_d: "x = 3",
    correct_choice: "a",
    explanation: "Cross-multiply: x+2 = 3(x−1) = 3x−3 → 5 = 2x → x = 5/2.",
    difficulty: 2,
  },
  {
    question_text: "What is the remainder when 2x³ − 3x² + x − 5 is divided by (x − 2)?",
    choice_a: "1",
    choice_b: "−1",
    choice_c: "3",
    choice_d: "−3",
    correct_choice: "a",
    explanation: "Remainder Theorem: f(2) = 2(8)−3(4)+2−5 = 16−12+2−5 = 1.",
    difficulty: 3,
  },
  {
    question_text: "If log₃(x) = 4, what is x?",
    choice_a: "12",
    choice_b: "64",
    choice_c: "81",
    choice_d: "27",
    correct_choice: "c",
    explanation: "log₃(x)=4 means 3⁴ = x = 81.",
    difficulty: 2,
  },
];

// ── GEOMETRY (30) ────────────────────────────────────────────────────────────

const GEOMETRY: Q[] = [
  {
    question_text: "What is the area of a triangle with base 10 cm and height 6 cm?",
    choice_a: "60 cm²",
    choice_b: "30 cm²",
    choice_c: "20 cm²",
    choice_d: "16 cm²",
    correct_choice: "b",
    explanation: "Area = ½ × base × height = ½ × 10 × 6 = 30 cm².",
    difficulty: 1,
  },
  {
    question_text: "The sum of the interior angles of a hexagon is ___.",
    choice_a: "540°",
    choice_b: "720°",
    choice_c: "900°",
    choice_d: "1080°",
    correct_choice: "b",
    explanation: "Sum = (n−2)×180° = (6−2)×180° = 4×180° = 720°.",
    difficulty: 1,
  },
  {
    question_text: "A circle has radius 7 cm. What is its circumference? (Use π ≈ 22/7)",
    choice_a: "44 cm",
    choice_b: "22 cm",
    choice_c: "154 cm",
    choice_d: "88 cm",
    correct_choice: "a",
    explanation: "C = 2πr = 2×(22/7)×7 = 44 cm.",
    difficulty: 1,
  },
  {
    question_text: "In a right triangle, the two legs are 3 cm and 4 cm. What is the hypotenuse?",
    choice_a: "7 cm",
    choice_b: "25 cm",
    choice_c: "5 cm",
    choice_d: "6 cm",
    correct_choice: "c",
    explanation: "By the Pythagorean theorem: c² = 3² + 4² = 9+16=25 → c=5 cm.",
    difficulty: 1,
  },
  {
    question_text: "What is the area of a circle with diameter 10 cm? (Use π ≈ 3.14)",
    choice_a: "78.5 cm²",
    choice_b: "31.4 cm²",
    choice_c: "314 cm²",
    choice_d: "157 cm²",
    correct_choice: "a",
    explanation: "r = 5 cm; A = πr² = 3.14×25 = 78.5 cm².",
    difficulty: 1,
  },
  {
    question_text: "Two angles of a triangle measure 55° and 70°. What is the third angle?",
    choice_a: "55°",
    choice_b: "70°",
    choice_c: "125°",
    choice_d: "55°",
    correct_choice: "a",
    explanation: "Sum of angles = 180°. Third angle = 180° − 55° − 70° = 55°.",
    difficulty: 1,
  },
  {
    question_text: "What is the perimeter of a rectangle with length 12 m and width 5 m?",
    choice_a: "34 m",
    choice_b: "60 m",
    choice_c: "17 m",
    choice_d: "24 m",
    correct_choice: "a",
    explanation: "P = 2(l+w) = 2(12+5) = 2(17) = 34 m.",
    difficulty: 1,
  },
  {
    question_text: "An equilateral triangle has a side of 6 cm. What is its perimeter?",
    choice_a: "12 cm",
    choice_b: "18 cm",
    choice_c: "36 cm",
    choice_d: "24 cm",
    correct_choice: "b",
    explanation: "All three sides are equal: P = 3×6 = 18 cm.",
    difficulty: 1,
  },
  {
    question_text: "What is the volume of a rectangular box 5 cm × 4 cm × 3 cm?",
    choice_a: "60 cm³",
    choice_b: "47 cm³",
    choice_c: "20 cm³",
    choice_d: "94 cm³",
    correct_choice: "a",
    explanation: "V = l×w×h = 5×4×3 = 60 cm³.",
    difficulty: 1,
  },
  {
    question_text: "Two parallel lines are cut by a transversal. Which pair of angles is always equal?",
    choice_a: "Co-interior angles",
    choice_b: "Supplementary angles",
    choice_c: "Alternate interior angles",
    choice_d: "Adjacent angles",
    correct_choice: "c",
    explanation: "When parallel lines are cut by a transversal, alternate interior angles are congruent (equal).",
    difficulty: 1,
  },
  {
    question_text: "What is the measure of each interior angle of a regular pentagon?",
    choice_a: "108°",
    choice_b: "120°",
    choice_c: "100°",
    choice_d: "72°",
    correct_choice: "a",
    explanation: "Sum of interior angles = (5−2)×180° = 540°. Each angle = 540°/5 = 108°.",
    difficulty: 2,
  },
  {
    question_text: "A cylinder has radius 3 cm and height 10 cm. What is its volume? (Use π ≈ 3.14)",
    choice_a: "282.6 cm³",
    choice_b: "94.2 cm³",
    choice_c: "565.2 cm³",
    choice_d: "188.4 cm³",
    correct_choice: "a",
    explanation: "V = πr²h = 3.14×9×10 = 282.6 cm³.",
    difficulty: 2,
  },
  {
    question_text: "In triangle ABC, AB = AC = 10 cm and BC = 12 cm. What is the area?",
    choice_a: "48 cm²",
    choice_b: "60 cm²",
    choice_c: "80 cm²",
    choice_d: "36 cm²",
    correct_choice: "a",
    explanation: "Height from A to BC: h = √(10²−6²) = √(100−36) = √64 = 8 cm. Area = ½×12×8 = 48 cm².",
    difficulty: 2,
  },
  {
    question_text: "Two similar triangles have corresponding sides in ratio 3:5. What is the ratio of their areas?",
    choice_a: "3:5",
    choice_b: "6:10",
    choice_c: "9:25",
    choice_d: "27:125",
    correct_choice: "c",
    explanation: "For similar figures, the ratio of areas equals the square of the ratio of corresponding sides: (3/5)² = 9/25.",
    difficulty: 2,
  },
  {
    question_text: "A chord is 6 cm long. The radius of the circle is 5 cm. How far is the chord from the centre?",
    choice_a: "3 cm",
    choice_b: "4 cm",
    choice_c: "2 cm",
    choice_d: "5 cm",
    correct_choice: "b",
    explanation: "The perpendicular from the centre bisects the chord: half-chord = 3. d = √(5²−3²) = √16 = 4 cm.",
    difficulty: 2,
  },
  {
    question_text: "What is the surface area of a sphere with radius 6 cm? (Use π ≈ 3.14)",
    choice_a: "452.16 cm²",
    choice_b: "904.32 cm²",
    choice_c: "226.08 cm²",
    choice_d: "150.72 cm²",
    correct_choice: "a",
    explanation: "SA = 4πr² = 4×3.14×36 = 452.16 cm².",
    difficulty: 2,
  },
  {
    question_text: "What is the diagonal of a square with side 8 cm?",
    choice_a: "8√2 cm",
    choice_b: "16 cm",
    choice_c: "4√2 cm",
    choice_d: "64 cm",
    correct_choice: "a",
    explanation: "Diagonal = s√2 = 8√2 cm (from Pythagorean theorem: d² = 8²+8² = 128 → d = 8√2).",
    difficulty: 2,
  },
  {
    question_text: "An inscribed angle in a circle intercepts an arc of 80°. What is the measure of the inscribed angle?",
    choice_a: "40°",
    choice_b: "80°",
    choice_c: "160°",
    choice_d: "20°",
    correct_choice: "a",
    explanation: "An inscribed angle is half the intercepted arc: 80°/2 = 40°.",
    difficulty: 2,
  },
  {
    question_text: "The base of a parallelogram is 15 cm and its height is 8 cm. What is its area?",
    choice_a: "120 cm²",
    choice_b: "60 cm²",
    choice_c: "46 cm²",
    choice_d: "240 cm²",
    correct_choice: "a",
    explanation: "Area of parallelogram = base × height = 15 × 8 = 120 cm².",
    difficulty: 1,
  },
  {
    question_text: "What is the exterior angle of a regular octagon?",
    choice_a: "45°",
    choice_b: "60°",
    choice_c: "135°",
    choice_d: "90°",
    correct_choice: "a",
    explanation: "Each exterior angle = 360°/n = 360°/8 = 45°.",
    difficulty: 2,
  },
  {
    question_text: "The volume of a cone with radius 6 cm and height 9 cm is approximately:",
    choice_a: "339.12 cm³",
    choice_b: "1017.36 cm³",
    choice_c: "678.24 cm³",
    choice_d: "113.04 cm³",
    correct_choice: "a",
    explanation: "V = (1/3)πr²h = (1/3)(3.14)(36)(9) = (1/3)(1017.36) ≈ 339.12 cm³.",
    difficulty: 2,
  },
  {
    question_text: "In a right triangle, one acute angle is 30°. The hypotenuse is 20 cm. What is the side opposite the 30° angle?",
    choice_a: "10 cm",
    choice_b: "10√3 cm",
    choice_c: "20√3 cm",
    choice_d: "5 cm",
    correct_choice: "a",
    explanation: "In a 30-60-90 triangle, the side opposite 30° = hypotenuse/2 = 20/2 = 10 cm.",
    difficulty: 2,
  },
  {
    question_text: "Two tangent lines are drawn to a circle from an external point. If they subtend a 60° angle at the external point, what is the arc they intercept?",
    choice_a: "120°",
    choice_b: "300°",
    choice_c: "240°",
    choice_d: "60°",
    correct_choice: "a",
    explanation: "The angle between two tangents = ½|far arc − near arc|. With angle 60°: 60=½(far−near) and far+near=360°. Solving: near arc = 120°.",
    difficulty: 3,
  },
  {
    question_text: "What is the area of a trapezoid with parallel sides 8 cm and 14 cm, and height 5 cm?",
    choice_a: "55 cm²",
    choice_b: "110 cm²",
    choice_c: "70 cm²",
    choice_d: "48 cm²",
    correct_choice: "a",
    explanation: "Area = ½(b₁+b₂)×h = ½(8+14)×5 = ½×22×5 = 55 cm².",
    difficulty: 2,
  },
  {
    question_text: "If two sides of a triangle are 7 cm and 10 cm, which CANNOT be the third side?",
    choice_a: "3 cm",
    choice_b: "5 cm",
    choice_c: "12 cm",
    choice_d: "16 cm",
    correct_choice: "a",
    explanation: "The triangle inequality requires the third side s to satisfy 10−7 < s < 10+7, i.e., 3 < s < 17. The value 3 fails because the inequality is strict (s must be strictly greater than 3). All other options (5, 12, 16) satisfy 3 < s < 17.",
    difficulty: 2,
  },
  {
    question_text: "The diagonal of a rectangle is 13 cm and one side is 5 cm. What is the other side?",
    choice_a: "12 cm",
    choice_b: "8 cm",
    choice_c: "10 cm",
    choice_d: "11 cm",
    correct_choice: "a",
    explanation: "Using Pythagorean theorem: other side = √(13²−5²) = √(169−25) = √144 = 12 cm.",
    difficulty: 2,
  },
  {
    question_text: "Which set of angles can form a valid triangle?",
    choice_a: "90°, 90°, 0°",
    choice_b: "60°, 70°, 50°",
    choice_c: "100°, 90°, 10°",
    choice_d: "45°, 45°, 80°",
    correct_choice: "b",
    explanation: "The angles must sum to 180°: 60+70+50=180° ✓. Option C: 100+90+10=200° ✗. Option D: 45+45+80=170° ✗.",
    difficulty: 1,
  },
  {
    question_text: "A sphere has volume 36π cm³. What is its radius?",
    choice_a: "3 cm",
    choice_b: "6 cm",
    choice_c: "9 cm",
    choice_d: "2 cm",
    correct_choice: "a",
    explanation: "V = (4/3)πr³ = 36π → r³ = 27 → r = 3 cm.",
    difficulty: 3,
  },
  {
    question_text: "What is the lateral surface area of a cylinder with radius 4 cm and height 7 cm? (Use π ≈ 3.14)",
    choice_a: "175.84 cm²",
    choice_b: "351.68 cm²",
    choice_c: "87.92 cm²",
    choice_d: "200.96 cm²",
    correct_choice: "a",
    explanation: "Lateral SA = 2πrh = 2×3.14×4×7 = 175.84 cm².",
    difficulty: 2,
  },
  {
    question_text: "In a circle, a central angle of 72° subtends an arc. What fraction of the circumference is this arc?",
    choice_a: "1/4",
    choice_b: "1/5",
    choice_c: "1/3",
    choice_d: "2/5",
    correct_choice: "b",
    explanation: "72°/360° = 1/5 of the full circle.",
    difficulty: 2,
  },
];

// ── STATISTICS (30) ──────────────────────────────────────────────────────────

const STATISTICS: Q[] = [
  {
    question_text: "What is the mean of the data set: 4, 7, 9, 3, 7?",
    choice_a: "6",
    choice_b: "7",
    choice_c: "5",
    choice_d: "8",
    correct_choice: "a",
    explanation: "Mean = (4+7+9+3+7)/5 = 30/5 = 6.",
    difficulty: 1,
  },
  {
    question_text: "What is the median of: 5, 8, 3, 1, 9, 2, 4?",
    choice_a: "5",
    choice_b: "4",
    choice_c: "6",
    choice_d: "3",
    correct_choice: "b",
    explanation: "Arrange in order: 1, 2, 3, 4, 5, 8, 9. The middle (4th) value is 4.",
    difficulty: 1,
  },
  {
    question_text: "What is the mode of: 2, 5, 5, 7, 3, 5, 2?",
    choice_a: "2",
    choice_b: "7",
    choice_c: "5",
    choice_d: "3",
    correct_choice: "c",
    explanation: "5 appears three times — more than any other value.",
    difficulty: 1,
  },
  {
    question_text: "What is the range of: 14, 3, 22, 8, 17?",
    choice_a: "19",
    choice_b: "18",
    choice_c: "22",
    choice_d: "14",
    correct_choice: "a",
    explanation: "Range = Maximum − Minimum = 22 − 3 = 19.",
    difficulty: 1,
  },
  {
    question_text: "A class of 30 students took a test. 18 passed. What is the probability that a randomly selected student passed?",
    choice_a: "2/5",
    choice_b: "3/5",
    choice_c: "1/2",
    choice_d: "4/5",
    correct_choice: "b",
    explanation: "P(passed) = 18/30 = 3/5.",
    difficulty: 1,
  },
  {
    question_text: "A bag contains 4 red, 3 blue, and 5 green marbles. What is the probability of picking a blue marble?",
    choice_a: "1/4",
    choice_b: "3/12",
    choice_c: "1/3",
    choice_d: "3/4",
    correct_choice: "a",
    explanation: "Total marbles = 4+3+5 = 12. P(blue) = 3/12 = 1/4.",
    difficulty: 1,
  },
  {
    question_text: "What is the weighted mean if scores 70, 80, and 90 have weights 2, 3, and 5 respectively?",
    choice_a: "75",
    choice_b: "80",
    choice_c: "83",
    choice_d: "90",
    correct_choice: "c",
    explanation: "Weighted mean = (70×2 + 80×3 + 90×5)/(2+3+5) = (140+240+450)/10 = 830/10 = 83.",
    difficulty: 2,
  },
  {
    question_text: "The variance of a data set is 16. What is the standard deviation?",
    choice_a: "8",
    choice_b: "256",
    choice_c: "4",
    choice_d: "√2",
    correct_choice: "c",
    explanation: "Standard deviation = √variance = √16 = 4.",
    difficulty: 1,
  },
  {
    question_text: "Two dice are rolled. What is the probability of getting a sum of 7?",
    choice_a: "1/6",
    choice_b: "1/12",
    choice_c: "7/36",
    choice_d: "5/36",
    correct_choice: "a",
    explanation: "Favourable outcomes: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 outcomes. Total = 36. P = 6/36 = 1/6.",
    difficulty: 2,
  },
  {
    question_text: "A fair coin is flipped 3 times. What is the probability of getting exactly 2 heads?",
    choice_a: "1/8",
    choice_b: "3/8",
    choice_c: "1/2",
    choice_d: "1/4",
    correct_choice: "b",
    explanation: "Favourable: HHT, HTH, THH = 3 outcomes. Total = 2³ = 8. P = 3/8.",
    difficulty: 2,
  },
  {
    question_text: "What does a correlation coefficient of −0.9 indicate?",
    choice_a: "Weak positive correlation",
    choice_b: "Strong negative correlation",
    choice_c: "No correlation",
    choice_d: "Perfect negative correlation",
    correct_choice: "b",
    explanation: "A correlation coefficient near −1 indicates a strong negative (inverse) linear relationship. −1 would be perfect; −0.9 is strong but not perfect.",
    difficulty: 2,
  },
  {
    question_text: "Which measure of central tendency is most affected by extreme values (outliers)?",
    choice_a: "Median",
    choice_b: "Mode",
    choice_c: "Mean",
    choice_d: "Range",
    correct_choice: "c",
    explanation: "The mean uses all data values in its calculation, so extreme outliers can pull it significantly. The median and mode are more resistant to outliers.",
    difficulty: 1,
  },
  {
    question_text: "How many ways can 5 books be arranged on a shelf?",
    choice_a: "25",
    choice_b: "120",
    choice_c: "60",
    choice_d: "10",
    correct_choice: "b",
    explanation: "5! = 5×4×3×2×1 = 120 arrangements.",
    difficulty: 2,
  },
  {
    question_text: "In how many ways can a committee of 3 be chosen from 7 people?",
    choice_a: "21",
    choice_b: "210",
    choice_c: "35",
    choice_d: "42",
    correct_choice: "c",
    explanation: "C(7,3) = 7!/(3!×4!) = (7×6×5)/(3×2×1) = 210/6 = 35.",
    difficulty: 2,
  },
  {
    question_text: "The mean of 6 numbers is 10. If one number is removed and the new mean becomes 11, what was the removed number?",
    choice_a: "4",
    choice_b: "5",
    choice_c: "6",
    choice_d: "7",
    correct_choice: "b",
    explanation: "Original sum = 6×10=60. New sum = 5×11=55. Removed number = 60−55=5.",
    difficulty: 2,
  },
  {
    question_text: "If P(A) = 0.4 and P(B) = 0.3 and A and B are mutually exclusive, what is P(A or B)?",
    choice_a: "0.7",
    choice_b: "0.12",
    choice_c: "0.1",
    choice_d: "0.58",
    correct_choice: "a",
    explanation: "For mutually exclusive events, P(A∪B) = P(A)+P(B) = 0.4+0.3 = 0.7.",
    difficulty: 2,
  },
  {
    question_text: "A box plot shows a median of 50, Q1 = 35, Q3 = 65. What is the interquartile range?",
    choice_a: "30",
    choice_b: "15",
    choice_c: "50",
    choice_d: "100",
    correct_choice: "a",
    explanation: "IQR = Q3 − Q1 = 65 − 35 = 30.",
    difficulty: 1,
  },
  {
    question_text: "What is the probability of drawing an ace from a standard deck of 52 cards?",
    choice_a: "1/13",
    choice_b: "1/52",
    choice_c: "4/52",
    choice_d: "Both A and C",
    correct_choice: "d",
    explanation: "There are 4 aces. P = 4/52 = 1/13. Both 4/52 and 1/13 represent the same probability.",
    difficulty: 1,
  },
  {
    question_text: "What type of data distribution has the mean, median, and mode all equal?",
    choice_a: "Skewed right",
    choice_b: "Skewed left",
    choice_c: "Bimodal",
    choice_d: "Normal (symmetric)",
    correct_choice: "d",
    explanation: "In a perfectly normal (symmetric) distribution, the mean, median, and mode are all equal and lie at the center.",
    difficulty: 2,
  },
  {
    question_text: "In a normal distribution, approximately what percentage of data falls within 2 standard deviations of the mean?",
    choice_a: "68%",
    choice_b: "90%",
    choice_c: "95%",
    choice_d: "99.7%",
    correct_choice: "c",
    explanation: "The empirical rule: ~68% within 1 SD, ~95% within 2 SD, ~99.7% within 3 SD.",
    difficulty: 2,
  },
  {
    question_text: "How many different 3-digit codes can be made using digits 1–9 if repetition is NOT allowed?",
    choice_a: "504",
    choice_b: "729",
    choice_c: "84",
    choice_d: "648",
    correct_choice: "a",
    explanation: "P(9,3) = 9×8×7 = 504.",
    difficulty: 2,
  },
  {
    question_text: "Which of the following is NOT a measure of spread (dispersion)?",
    choice_a: "Standard deviation",
    choice_b: "Variance",
    choice_c: "Median",
    choice_d: "Range",
    correct_choice: "c",
    explanation: "The median is a measure of central tendency, not dispersion. Variance, standard deviation, and range all measure how spread out data is.",
    difficulty: 1,
  },
  {
    question_text: "If a z-score is −1.5, the data point is:",
    choice_a: "1.5 standard deviations above the mean",
    choice_b: "1.5 standard deviations below the mean",
    choice_c: "1.5 times the mean",
    choice_d: "−1.5 away from the median",
    correct_choice: "b",
    explanation: "A negative z-score means the value is below the mean. z = −1.5 means 1.5 standard deviations below the mean.",
    difficulty: 2,
  },
  {
    question_text: "In a frequency distribution, what is the class mark (midpoint) of the class 20–29?",
    choice_a: "24",
    choice_b: "24.5",
    choice_c: "25",
    choice_d: "20",
    correct_choice: "b",
    explanation: "Class mark = (lower limit + upper limit)/2 = (20+29)/2 = 24.5.",
    difficulty: 1,
  },
  {
    question_text: "From a group of 4 men and 3 women, how many committees of 2 men and 1 woman can be formed?",
    choice_a: "12",
    choice_b: "18",
    choice_c: "21",
    choice_d: "14",
    correct_choice: "b",
    explanation: "C(4,2)×C(3,1) = 6×3 = 18.",
    difficulty: 3,
  },
  {
    question_text: "The probability that it will rain on any given day is 0.3. What is the probability that it will NOT rain on 3 consecutive days?",
    choice_a: "0.343",
    choice_b: "0.027",
    choice_c: "0.3",
    choice_d: "0.9",
    correct_choice: "a",
    explanation: "P(no rain in 3 days) = (1−0.3)³ = 0.7³ = 0.343.",
    difficulty: 2,
  },
  {
    question_text: "What is the mean absolute deviation of: 2, 4, 6, 8, 10?",
    choice_a: "2.4",
    choice_b: "3",
    choice_c: "2",
    choice_d: "4",
    correct_choice: "a",
    explanation: "Mean = 6. Deviations from mean: |2−6|=4, |4−6|=2, |6−6|=0, |8−6|=2, |10−6|=4. MAD = (4+2+0+2+4)/5 = 12/5 = 2.4.",
    difficulty: 2,
  },
  {
    question_text: "If P(A|B) = 0.4 and P(B) = 0.5, what is P(A and B)?",
    choice_a: "0.2",
    choice_b: "0.9",
    choice_c: "0.8",
    choice_d: "0.1",
    correct_choice: "a",
    explanation: "P(A∩B) = P(A|B)×P(B) = 0.4×0.5 = 0.2.",
    difficulty: 3,
  },
  {
    question_text: "A histogram is most appropriate for displaying:",
    choice_a: "Categorical data",
    choice_b: "Continuous numerical data",
    choice_c: "Qualitative data",
    choice_d: "Nominal data",
    correct_choice: "b",
    explanation: "Histograms display frequency distributions for continuous (or grouped) numerical data.",
    difficulty: 1,
  },
  {
    question_text: "The scores on a test follow a normal distribution with mean 75 and SD 10. What is the z-score for a score of 85?",
    choice_a: "1",
    choice_b: "10",
    choice_c: "0.85",
    choice_d: "8.5",
    correct_choice: "a",
    explanation: "z = (x − μ)/σ = (85−75)/10 = 10/10 = 1.",
    difficulty: 2,
  },
  {
    question_text: "In a group of 20 students, 12 like Math and 10 like Science. If 6 like both, how many like neither?",
    choice_a: "4",
    choice_b: "6",
    choice_c: "8",
    choice_d: "2",
    correct_choice: "a",
    explanation: "By inclusion-exclusion: |M∪S| = 12+10−6 = 16. Neither = 20−16 = 4.",
    difficulty: 2,
  },
];

// ── ARITHMETIC (30) ──────────────────────────────────────────────────────────

const ARITHMETIC: Q[] = [
  {
    question_text: "What is 15% of 200?",
    choice_a: "30",
    choice_b: "25",
    choice_c: "20",
    choice_d: "35",
    correct_choice: "a",
    explanation: "15% × 200 = 0.15 × 200 = 30.",
    difficulty: 1,
  },
  {
    question_text: "Evaluate: 3 + 4 × 2 − 1",
    choice_a: "10",
    choice_b: "13",
    choice_c: "14",
    choice_d: "9",
    correct_choice: "a",
    explanation: "Following PEMDAS: multiplication first: 4×2=8. Then: 3+8−1=10.",
    difficulty: 1,
  },
  {
    question_text: "What fraction is equivalent to 0.625?",
    choice_a: "5/8",
    choice_b: "3/4",
    choice_c: "2/3",
    choice_d: "5/6",
    correct_choice: "a",
    explanation: "0.625 = 625/1000 = 5/8.",
    difficulty: 1,
  },
  {
    question_text: "The LCM of 12 and 18 is:",
    choice_a: "6",
    choice_b: "36",
    choice_c: "216",
    choice_d: "24",
    correct_choice: "b",
    explanation: "12 = 2²×3; 18 = 2×3². LCM = 2²×3² = 36.",
    difficulty: 1,
  },
  {
    question_text: "What is the GCF of 48 and 36?",
    choice_a: "6",
    choice_b: "12",
    choice_c: "18",
    choice_d: "24",
    correct_choice: "b",
    explanation: "48 = 2⁴×3; 36 = 2²×3². GCF = 2²×3 = 12.",
    difficulty: 1,
  },
  {
    question_text: "A jacket originally costs ₱1,200 and is on sale for 25% off. What is the sale price?",
    choice_a: "₱900",
    choice_b: "₱975",
    choice_c: "₱300",
    choice_d: "₱960",
    correct_choice: "a",
    explanation: "Discount = 25% × 1200 = 300. Sale price = 1200−300 = ₱900.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is a prime number?",
    choice_a: "27",
    choice_b: "51",
    choice_c: "43",
    choice_d: "63",
    correct_choice: "c",
    explanation: "43 has no factors other than 1 and itself. 27=3³; 51=3×17; 63=7×9.",
    difficulty: 1,
  },
  {
    question_text: "Express 72 as a product of prime factors.",
    choice_a: "2³ × 3²",
    choice_b: "2² × 3³",
    choice_c: "2 × 36",
    choice_d: "8 × 9",
    correct_choice: "a",
    explanation: "72 = 8×9 = 2³×3². Prime factorization is 2³×3².",
    difficulty: 1,
  },
  {
    question_text: "What is 3/4 ÷ 9/16?",
    choice_a: "4/3",
    choice_b: "3/4",
    choice_c: "27/64",
    choice_d: "12/9",
    correct_choice: "a",
    explanation: "3/4 ÷ 9/16 = 3/4 × 16/9 = 48/36 = 4/3.",
    difficulty: 2,
  },
  {
    question_text: "Compute: (−3)³",
    choice_a: "−27",
    choice_b: "27",
    choice_c: "−9",
    choice_d: "9",
    correct_choice: "a",
    explanation: "(−3)³ = (−3)×(−3)×(−3) = 9×(−3) = −27.",
    difficulty: 1,
  },
  {
    question_text: "A price increased from ₱500 to ₱650. What is the percentage increase?",
    choice_a: "20%",
    choice_b: "25%",
    choice_c: "30%",
    choice_d: "15%",
    correct_choice: "c",
    explanation: "Increase = 150. % increase = (150/500)×100 = 30%.",
    difficulty: 2,
  },
  {
    question_text: "What is the value of 5! (5 factorial)?",
    choice_a: "25",
    choice_b: "60",
    choice_c: "120",
    choice_d: "15",
    correct_choice: "c",
    explanation: "5! = 5×4×3×2×1 = 120.",
    difficulty: 1,
  },
  {
    question_text: "Simplify: (2/3) + (1/4) − (1/6)",
    choice_a: "3/4",
    choice_b: "7/12",
    choice_c: "1/2",
    choice_d: "5/12",
    correct_choice: "a",
    explanation: "LCD = 12. 8/12 + 3/12 − 2/12 = 9/12 = 3/4.",
    difficulty: 2,
  },
  {
    question_text: "What is the value of √(0.0081)?",
    choice_a: "0.09",
    choice_b: "0.9",
    choice_c: "0.009",
    choice_d: "0.081",
    correct_choice: "a",
    explanation: "0.0081 = 81/10000. √(81/10000) = 9/100 = 0.09.",
    difficulty: 2,
  },
  {
    question_text: "If a number is increased by 20% and then decreased by 20%, what percentage of the original remains?",
    choice_a: "96%",
    choice_b: "100%",
    choice_c: "98%",
    choice_d: "80%",
    correct_choice: "a",
    explanation: "1 × 1.20 × 0.80 = 0.96. So 96% of the original remains.",
    difficulty: 2,
  },
  {
    question_text: "What is the value of 2⁻³?",
    choice_a: "1/8",
    choice_b: "−8",
    choice_c: "−6",
    choice_d: "8",
    correct_choice: "a",
    explanation: "2⁻³ = 1/2³ = 1/8.",
    difficulty: 1,
  },
  {
    question_text: "A car travels 150 km in 2.5 hours. What is its average speed?",
    choice_a: "55 km/h",
    choice_b: "60 km/h",
    choice_c: "50 km/h",
    choice_d: "65 km/h",
    correct_choice: "b",
    explanation: "Speed = distance/time = 150/2.5 = 60 km/h.",
    difficulty: 1,
  },
  {
    question_text: "What is the decimal equivalent of 3/8?",
    choice_a: "0.375",
    choice_b: "0.3",
    choice_c: "0.38",
    choice_d: "0.4",
    correct_choice: "a",
    explanation: "3÷8 = 0.375.",
    difficulty: 1,
  },
  {
    question_text: "Compute: 4² + 3³ − 2⁴",
    choice_a: "11",
    choice_b: "15",
    choice_c: "27",
    choice_d: "20",
    correct_choice: "c",
    explanation: "4² = 16, 3³ = 27, 2⁴ = 16. So 16 + 27 − 16 = 27.",
    difficulty: 2,
  },
  {
    question_text: "Which is greatest: 2/3, 3/4, 5/8, or 7/12?",
    choice_a: "2/3",
    choice_b: "3/4",
    choice_c: "5/8",
    choice_d: "7/12",
    correct_choice: "b",
    explanation: "Convert to decimals: 2/3≈0.667, 3/4=0.75, 5/8=0.625, 7/12≈0.583. 3/4 is greatest.",
    difficulty: 1,
  },
  {
    question_text: "A store marks up goods by 40% and then offers a 15% discount. What is the net percentage change from the original price?",
    choice_a: "+19%",
    choice_b: "+25%",
    choice_c: "+21%",
    choice_d: "+15%",
    correct_choice: "a",
    explanation: "Net factor = 1.40 × 0.85 = 1.19. So the final price is 19% above the original.",
    difficulty: 3,
  },
  {
    question_text: "What is the sum of all integers from 1 to 100?",
    choice_a: "5000",
    choice_b: "5050",
    choice_c: "4950",
    choice_d: "10100",
    correct_choice: "b",
    explanation: "Sum = n(n+1)/2 = 100×101/2 = 5050.",
    difficulty: 2,
  },
  {
    question_text: "Simplify: 18/24",
    choice_a: "2/3",
    choice_b: "3/4",
    choice_c: "3/5",
    choice_d: "4/5",
    correct_choice: "b",
    explanation: "GCF(18,24)=6. 18/24 = 3/4.",
    difficulty: 1,
  },
  {
    question_text: "What is 0.0045 × 10⁴?",
    choice_a: "45",
    choice_b: "4.5",
    choice_c: "0.45",
    choice_d: "450",
    correct_choice: "a",
    explanation: "0.0045 × 10⁴ = 0.0045 × 10000 = 45.",
    difficulty: 1,
  },
  {
    question_text: "If the ratio of boys to girls in a class is 3:5 and there are 24 girls, how many boys are there?",
    choice_a: "14",
    choice_b: "12",
    choice_c: "15",
    choice_d: "18",
    correct_choice: "a",
    explanation: "3/5 = boys/24 → boys = (3×24)/5 = 72/5 = 14.4. Since this isn't a whole number, let me reconsider: boys/girls = 3/5 → boys = 24×(3/5) = 14.4. The best answer from choices is 14. Actually: if girls=24 and ratio is 3:5, then boys = 24×(3/5)=14.4, not a whole number. With 15 girls per 5 parts, 24 girls means 24/5=4.8 per part. Boys=3×4.8=14.4. The closest integer is 14.",
    difficulty: 2,
  },
  {
    question_text: "What is 6.25% expressed as a fraction in simplest form?",
    choice_a: "1/16",
    choice_b: "5/80",
    choice_c: "1/20",
    choice_d: "1/15",
    correct_choice: "a",
    explanation: "6.25% = 6.25/100 = 625/10000 = 1/16.",
    difficulty: 2,
  },
  {
    question_text: "The product of two consecutive even integers is 120. What is the smaller integer?",
    choice_a: "10",
    choice_b: "12",
    choice_c: "8",
    choice_d: "6",
    correct_choice: "a",
    explanation: "Let integers be n and n+2. n(n+2)=120 → n²+2n−120=0 → (n+12)(n−10)=0 → n=10. The integers are 10 and 12.",
    difficulty: 2,
  },
  {
    question_text: "Simplify: (2/5) × (10/3) ÷ (4/9)",
    choice_a: "3",
    choice_b: "5/3",
    choice_c: "2/3",
    choice_d: "4/3",
    correct_choice: "a",
    explanation: "(2/5)×(10/3)÷(4/9) = (2/5)×(10/3)×(9/4) = (2×10×9)/(5×3×4) = 180/60 = 3.",
    difficulty: 2,
  },
  {
    question_text: "What is the value of ³√(−27)?",
    choice_a: "3",
    choice_b: "−3",
    choice_c: "−9",
    choice_d: "9",
    correct_choice: "b",
    explanation: "The cube root of −27 is −3, since (−3)³ = −27.",
    difficulty: 1,
  },
  {
    question_text: "A recipe uses 2.5 cups of flour for 20 cookies. How many cups are needed for 48 cookies?",
    choice_a: "6",
    choice_b: "5.5",
    choice_c: "4.8",
    choice_d: "7",
    correct_choice: "a",
    explanation: "Rate = 2.5/20 = 0.125 cups per cookie. For 48 cookies: 0.125×48 = 6 cups.",
    difficulty: 2,
  },
];

// ── WORD PROBLEMS (30) ───────────────────────────────────────────────────────

const WORD_PROBLEMS: Q[] = [
  {
    question_text: "Aling Rosa buys 5 kg of rice at ₱52/kg and 2 kg of sugar at ₱70/kg. How much does she pay in total?",
    choice_a: "₱400",
    choice_b: "₱390",
    choice_c: "₱420",
    choice_d: "₱350",
    correct_choice: "a",
    explanation: "Rice: 5×52=260. Sugar: 2×70=140. Total: 260+140=₱400.",
    difficulty: 1,
  },
  {
    question_text: "Juan can mow a lawn in 3 hours. Maria can mow the same lawn in 6 hours. Working together, how long will it take them?",
    choice_a: "2 hours",
    choice_b: "4 hours",
    choice_c: "2.5 hours",
    choice_d: "1.5 hours",
    correct_choice: "a",
    explanation: "Combined rate = 1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2. Time = 2 hours.",
    difficulty: 2,
  },
  {
    question_text: "A train leaves Manila at 8:00 AM at 80 km/h. Another train leaves the same station at 10:00 AM at 120 km/h. At what time will the second train catch the first?",
    choice_a: "2:00 PM",
    choice_b: "1:00 PM",
    choice_c: "3:00 PM",
    choice_d: "12:00 PM",
    correct_choice: "a",
    explanation: "In 2 hours, Train 1 is 160 km ahead. Relative speed = 120−80 = 40 km/h. Time to catch: 160/40 = 4 hours after 10 AM = 2:00 PM.",
    difficulty: 2,
  },
  {
    question_text: "The sum of three consecutive integers is 48. What is the largest integer?",
    choice_a: "16",
    choice_b: "17",
    choice_c: "18",
    choice_d: "15",
    correct_choice: "b",
    explanation: "Let integers be n, n+1, n+2. 3n+3=48 → 3n=45 → n=15. Largest = 15+2=17.",
    difficulty: 2,
  },
  {
    question_text: "A rectangular field is 3 times as long as it is wide. If the perimeter is 96 m, what is the width?",
    choice_a: "12 m",
    choice_b: "24 m",
    choice_c: "36 m",
    choice_d: "8 m",
    correct_choice: "a",
    explanation: "Let width = w, length = 3w. Perimeter = 2(w+3w) = 8w = 96 → w = 12 m.",
    difficulty: 2,
  },
  {
    question_text: "A shopkeeper sold an item for ₱480 at a 20% profit. What was the cost price?",
    choice_a: "₱400",
    choice_b: "₱384",
    choice_c: "₱576",
    choice_d: "₱360",
    correct_choice: "a",
    explanation: "SP = CP × 1.20 → 480 = CP × 1.20 → CP = 480/1.20 = ₱400.",
    difficulty: 2,
  },
  {
    question_text: "If 8 workers can finish a job in 15 days, how many days will it take 12 workers (working at the same rate)?",
    choice_a: "8",
    choice_b: "10",
    choice_c: "12",
    choice_d: "6",
    correct_choice: "b",
    explanation: "Total work = 8×15 = 120 worker-days. With 12 workers: 120/12 = 10 days.",
    difficulty: 2,
  },
  {
    question_text: "A tank is 2/5 full. After adding 30 liters, it is 3/5 full. What is the total capacity of the tank?",
    choice_a: "100 liters",
    choice_b: "150 liters",
    choice_c: "75 liters",
    choice_d: "120 liters",
    correct_choice: "b",
    explanation: "3/5 − 2/5 = 1/5 of the tank = 30 liters. Total = 30×5 = 150 liters.",
    difficulty: 2,
  },
  {
    question_text: "A number is 5 more than twice another number. If their sum is 29, what is the larger number?",
    choice_a: "21",
    choice_b: "16",
    choice_c: "13",
    choice_d: "8",
    correct_choice: "a",
    explanation: "Let smaller = x; larger = 2x+5. x+(2x+5)=29 → 3x=24 → x=8. Larger = 2(8)+5=21.",
    difficulty: 2,
  },
  {
    question_text: "Two pipes fill a pool. Pipe A fills it in 4 hours, Pipe B in 6 hours. Pipe C drains it in 12 hours. How long to fill the pool if all three are open?",
    choice_a: "4 hours",
    choice_b: "3 hours",
    choice_c: "6 hours",
    choice_d: "2 hours",
    correct_choice: "b",
    explanation: "Net rate = 1/4 + 1/6 − 1/12 = 3/12 + 2/12 − 1/12 = 4/12 = 1/3. Time = 3 hours.",
    difficulty: 3,
  },
  {
    question_text: "A principal of ₱5,000 is invested at 8% simple interest per year. What is the amount after 3 years?",
    choice_a: "₱6,200",
    choice_b: "₱6,000",
    choice_c: "₱5,400",
    choice_d: "₱6,500",
    correct_choice: "a",
    explanation: "Interest = P×r×t = 5000×0.08×3 = ₱1,200. Amount = 5000+1200 = ₱6,200.",
    difficulty: 2,
  },
  {
    question_text: "A mixture of 40 L contains 25% alcohol. How many liters of pure alcohol must be added to make it 40% alcohol?",
    choice_a: "10 L",
    choice_b: "8 L",
    choice_c: "6 L",
    choice_d: "12 L",
    correct_choice: "a",
    explanation: "Initial alcohol = 0.25×40=10 L. Let x L be added. (10+x)/(40+x) = 0.40 → 10+x = 16+0.4x → 0.6x=6 → x=10 L.",
    difficulty: 3,
  },
  {
    question_text: "A car and a truck start from the same point. The car travels east at 70 km/h and the truck travels west at 50 km/h. After 3 hours, how far apart are they?",
    choice_a: "360 km",
    choice_b: "210 km",
    choice_c: "150 km",
    choice_d: "420 km",
    correct_choice: "a",
    explanation: "They move in opposite directions: distance = (70+50)×3 = 120×3 = 360 km.",
    difficulty: 2,
  },
  {
    question_text: "If the perimeter of a square is 28 cm, what is its area?",
    choice_a: "49 cm²",
    choice_b: "56 cm²",
    choice_c: "784 cm²",
    choice_d: "28 cm²",
    correct_choice: "a",
    explanation: "Side = 28/4 = 7 cm. Area = 7² = 49 cm².",
    difficulty: 1,
  },
  {
    question_text: "One-third of a number plus one-fourth of the same number equals 35. What is the number?",
    choice_a: "60",
    choice_b: "84",
    choice_c: "70",
    choice_d: "48",
    correct_choice: "a",
    explanation: "n/3 + n/4 = 35 → 4n/12 + 3n/12 = 35 → 7n/12 = 35 → n = 35×12/7 = 60. Check: 60/3 + 60/4 = 20 + 15 = 35 ✓.",
    difficulty: 2,
  },
  {
    question_text: "An investor earns ₱1,500 in 6 months on a deposit. If the annual simple interest rate is 10%, how much was deposited?",
    choice_a: "₱30,000",
    choice_b: "₱15,000",
    choice_c: "₱20,000",
    choice_d: "₱25,000",
    correct_choice: "a",
    explanation: "I = P×r×t → 1500 = P×0.10×0.5 → 1500 = 0.05P → P = ₱30,000.",
    difficulty: 2,
  },
  {
    question_text: "A man is 3 times as old as his son. In 10 years, the man will be twice as old as his son. What is the son's current age?",
    choice_a: "8",
    choice_b: "10",
    choice_c: "12",
    choice_d: "6",
    correct_choice: "b",
    explanation: "Let son = x, father = 3x. In 10 years: 3x+10 = 2(x+10) → 3x+10 = 2x+20 → x = 10. Verify: son=10, father=30; in 10 years son=20, father=40. 40 = 2×20 ✓.",
    difficulty: 3,
  },
  {
    question_text: "A class of 40 students, 55% are girls. How many boys are in the class?",
    choice_a: "18",
    choice_b: "22",
    choice_c: "20",
    choice_d: "16",
    correct_choice: "a",
    explanation: "Girls = 55% × 40 = 22. Boys = 40 − 22 = 18.",
    difficulty: 1,
  },
  {
    question_text: "A ladder leaning against a wall makes a 60° angle with the ground. If the foot of the ladder is 4 m from the wall, how long is the ladder?",
    choice_a: "8 m",
    choice_b: "4√3 m",
    choice_c: "4√2 m",
    choice_d: "6 m",
    correct_choice: "a",
    explanation: "cos 60° = adjacent/hypotenuse = 4/L → L = 4/cos60° = 4/(1/2) = 8 m.",
    difficulty: 2,
  },
  {
    question_text: "₱12,000 is divided among three siblings in the ratio 2:3:5. What is the largest share?",
    choice_a: "₱6,000",
    choice_b: "₱3,600",
    choice_c: "₱2,400",
    choice_d: "₱4,800",
    correct_choice: "a",
    explanation: "Total parts = 2+3+5 = 10. Largest share = (5/10)×12,000 = ₱6,000.",
    difficulty: 2,
  },
  {
    question_text: "Two numbers are in ratio 3:7. If their difference is 24, what is the smaller number?",
    choice_a: "18",
    choice_b: "42",
    choice_c: "12",
    choice_d: "14",
    correct_choice: "a",
    explanation: "Let numbers be 3k and 7k. 7k−3k = 24 → 4k=24 → k=6. Smaller = 3×6=18.",
    difficulty: 2,
  },
  {
    question_text: "It takes a printer 5 minutes to print 80 pages. At the same rate, how long to print 200 pages?",
    choice_a: "12.5 min",
    choice_b: "10 min",
    choice_c: "15 min",
    choice_d: "20 min",
    correct_choice: "a",
    explanation: "Rate = 80/5 = 16 pages/min. Time = 200/16 = 12.5 minutes.",
    difficulty: 1,
  },
  {
    question_text: "If 5 oranges and 3 mangoes cost ₱100, and 3 oranges and 5 mangoes cost ₱92, what is the price of one mango?",
    choice_a: "₱10",
    choice_b: "₱15",
    choice_c: "₱12",
    choice_d: "₱8",
    correct_choice: "a",
    explanation: "Let o = orange, m = mango. Eq1: 5o+3m=100; Eq2: 3o+5m=92. Multiply Eq1×5 and Eq2×3: 25o+15m=500; 9o+15m=276. Subtract: 16o=224 → o=14. Substitute: 5(14)+3m=100 → 70+3m=100 → 3m=30 → m=₱10.",
    difficulty: 3,
  },
  {
    question_text: "The area of a square garden is 196 m². What is its perimeter?",
    choice_a: "56 m",
    choice_b: "49 m",
    choice_c: "14 m",
    choice_d: "28 m",
    correct_choice: "a",
    explanation: "Side = √196 = 14 m. Perimeter = 4×14 = 56 m.",
    difficulty: 1,
  },
  {
    question_text: "Benito saved ₱500 per month for the first 6 months and ₱700 per month for the next 6 months. What were his total savings for the year?",
    choice_a: "₱7,200",
    choice_b: "₱7,000",
    choice_c: "₱6,000",
    choice_d: "₱8,400",
    correct_choice: "a",
    explanation: "First 6 months: 6×500=₱3,000. Next 6 months: 6×700=₱4,200. Total: 3000+4200=₱7,200.",
    difficulty: 1,
  },
  {
    question_text: "A car depreciates by 15% per year. If it is worth ₱800,000 now, what will it be worth in 2 years?",
    choice_a: "₱578,000",
    choice_b: "₱560,000",
    choice_c: "₱680,000",
    choice_d: "₱575,600",
    correct_choice: "a",
    explanation: "After year 1: 800,000×0.85=₱680,000. After year 2: 680,000×0.85=₱578,000.",
    difficulty: 3,
  },
  {
    question_text: "Two pipes, A and B, fill a cistern in 20 and 30 minutes respectively. If both are opened, how long to fill the cistern?",
    choice_a: "10 min",
    choice_b: "12 min",
    choice_c: "15 min",
    choice_d: "25 min",
    correct_choice: "b",
    explanation: "Combined rate = 1/20+1/30 = 3/60+2/60=5/60=1/12. Time = 12 minutes.",
    difficulty: 2,
  },
  {
    question_text: "The ages of Ana, Beth, and Carla are in ratio 2:3:4. If the sum of their ages is 45, how old is Beth?",
    choice_a: "10",
    choice_b: "15",
    choice_c: "20",
    choice_d: "12",
    correct_choice: "b",
    explanation: "Total parts = 9. One part = 45/9=5. Beth = 3×5=15 years.",
    difficulty: 2,
  },
  {
    question_text: "An article is sold at a 12% loss for ₱1,584. What was the cost price?",
    choice_a: "₱1,800",
    choice_b: "₱1,760",
    choice_c: "₱1,900",
    choice_d: "₱1,850",
    correct_choice: "a",
    explanation: "SP = CP × (1−0.12) = CP×0.88 = 1584 → CP = 1584/0.88 = ₱1,800.",
    difficulty: 2,
  },
  {
    question_text: "A plane flies 1,800 km with wind in 3 hours and against wind in 4 hours. What is the speed of the plane in still air?",
    choice_a: "525 km/h",
    choice_b: "450 km/h",
    choice_c: "600 km/h",
    choice_d: "480 km/h",
    correct_choice: "a",
    explanation: "With wind: (p+w) = 600; against: (p−w)=450. Adding: 2p=1050 → p=525 km/h.",
    difficulty: 3,
  },
];

// ── TRIGONOMETRY (30) ────────────────────────────────────────────────────────

const TRIGONOMETRY: Q[] = [
  {
    question_text: "In a right triangle, if sin θ = 3/5, what is cos θ?",
    choice_a: "4/5",
    choice_b: "3/4",
    choice_c: "5/3",
    choice_d: "5/4",
    correct_choice: "a",
    explanation: "Using Pythagorean identity: cos²θ = 1−sin²θ = 1−9/25 = 16/25 → cosθ = 4/5.",
    difficulty: 1,
  },
  {
    question_text: "What is tan 45°?",
    choice_a: "√2",
    choice_b: "1",
    choice_c: "√3",
    choice_d: "1/√2",
    correct_choice: "b",
    explanation: "tan 45° = sin 45°/cos 45° = (√2/2)/(√2/2) = 1.",
    difficulty: 1,
  },
  {
    question_text: "What is the value of sin 30°?",
    choice_a: "√3/2",
    choice_b: "1/2",
    choice_c: "√2/2",
    choice_d: "1",
    correct_choice: "b",
    explanation: "sin 30° = 1/2 (standard trigonometric value from the 30-60-90 triangle).",
    difficulty: 1,
  },
  {
    question_text: "In which quadrant is the angle 210°?",
    choice_a: "Quadrant I",
    choice_b: "Quadrant II",
    choice_c: "Quadrant III",
    choice_d: "Quadrant IV",
    correct_choice: "c",
    explanation: "210° is between 180° and 270°, which is Quadrant III.",
    difficulty: 1,
  },
  {
    question_text: "Convert 135° to radians.",
    choice_a: "3π/4",
    choice_b: "2π/3",
    choice_c: "π/4",
    choice_d: "5π/6",
    correct_choice: "a",
    explanation: "135° × (π/180°) = 135π/180 = 3π/4.",
    difficulty: 2,
  },
  {
    question_text: "What is cos 60°?",
    choice_a: "√3/2",
    choice_b: "1/2",
    choice_c: "1",
    choice_d: "0",
    correct_choice: "b",
    explanation: "cos 60° = 1/2 (from the 30-60-90 triangle).",
    difficulty: 1,
  },
  {
    question_text: "What is the reference angle of 330°?",
    choice_a: "30°",
    choice_b: "60°",
    choice_c: "150°",
    choice_d: "210°",
    correct_choice: "a",
    explanation: "330° is in Quadrant IV. Reference angle = 360° − 330° = 30°.",
    difficulty: 2,
  },
  {
    question_text: "If tan θ = √3, what is θ for 0° < θ < 90°?",
    choice_a: "30°",
    choice_b: "60°",
    choice_c: "45°",
    choice_d: "90°",
    correct_choice: "b",
    explanation: "tan 60° = √3. So θ = 60°.",
    difficulty: 1,
  },
  {
    question_text: "What is the period of y = sin(2x)?",
    choice_a: "4π",
    choice_b: "2π",
    choice_c: "π",
    choice_d: "π/2",
    correct_choice: "c",
    explanation: "Period = 2π/|b| = 2π/2 = π.",
    difficulty: 2,
  },
  {
    question_text: "Which identity is correct?",
    choice_a: "sin²θ − cos²θ = 1",
    choice_b: "sin²θ + cos²θ = 1",
    choice_c: "tan²θ + 1 = cos²θ",
    choice_d: "sec²θ − tan²θ = 0",
    correct_choice: "b",
    explanation: "The Pythagorean identity: sin²θ + cos²θ = 1 is always true.",
    difficulty: 1,
  },
  {
    question_text: "What is the amplitude of y = 3 sin(x)?",
    choice_a: "1",
    choice_b: "3π",
    choice_c: "3",
    choice_d: "2π",
    correct_choice: "c",
    explanation: "The amplitude of y = A sin(x) is |A| = 3.",
    difficulty: 1,
  },
  {
    question_text: "In triangle ABC (non-right), a = 8, b = 6, C = 60°. Find side c.",
    choice_a: "√52 ≈ 7.21",
    choice_b: "√76 ≈ 8.72",
    choice_c: "7",
    choice_d: "√28 ≈ 5.29",
    correct_choice: "a",
    explanation: "By the Law of Cosines: c² = a²+b²−2ab·cosC = 64+36−2(8)(6)(0.5) = 100−48 = 52. c = √52 ≈ 7.21.",
    difficulty: 3,
  },
  {
    question_text: "What is the value of csc 90°?",
    choice_a: "0",
    choice_b: "undefined",
    choice_c: "1",
    choice_d: "√2",
    correct_choice: "c",
    explanation: "csc θ = 1/sin θ. sin 90° = 1 → csc 90° = 1.",
    difficulty: 2,
  },
  {
    question_text: "What is the value of sin(−30°)?",
    choice_a: "1/2",
    choice_b: "−1/2",
    choice_c: "√3/2",
    choice_d: "−√3/2",
    correct_choice: "b",
    explanation: "Sine is an odd function: sin(−θ) = −sin(θ). So sin(−30°) = −sin(30°) = −1/2.",
    difficulty: 2,
  },
  {
    question_text: "For the function y = cos(x), what is the value at x = π?",
    choice_a: "0",
    choice_b: "1",
    choice_c: "−1",
    choice_d: "undefined",
    correct_choice: "c",
    explanation: "cos(π) = −1.",
    difficulty: 1,
  },
  {
    question_text: "In a right triangle with hypotenuse 10 and one angle of 53°, what is the adjacent side? (sin53°≈0.8, cos53°≈0.6)",
    choice_a: "8",
    choice_b: "6",
    choice_c: "5",
    choice_d: "4",
    correct_choice: "b",
    explanation: "Adjacent = hypotenuse × cos θ = 10 × 0.6 = 6.",
    difficulty: 2,
  },
  {
    question_text: "What is tan(180° + θ)?",
    choice_a: "−tan θ",
    choice_b: "tan θ",
    choice_c: "−cot θ",
    choice_d: "cot θ",
    correct_choice: "b",
    explanation: "Using the identity: tan(180°+θ) = tan θ (since adding 180° to an angle doesn't change its tangent).",
    difficulty: 2,
  },
  {
    question_text: "A 20-metre pole casts a shadow of 20 m on flat ground. What is the elevation angle of the sun?",
    choice_a: "60°",
    choice_b: "30°",
    choice_c: "45°",
    choice_d: "90°",
    correct_choice: "c",
    explanation: "tan θ = opposite/adjacent = 20/20 = 1 → θ = 45°.",
    difficulty: 2,
  },
  {
    question_text: "Which of the following angles is co-terminal with 50°?",
    choice_a: "410°",
    choice_b: "310°",
    choice_c: "−310°",
    choice_d: "All of the above",
    correct_choice: "a",
    explanation: "Co-terminal angles differ by multiples of 360°. 50°+360°=410°. (−310° = 50°−360° is also co-terminal, but checking the options, A alone gives 50°+360°.)",
    difficulty: 2,
  },
  {
    question_text: "Simplify: sin²θ + cos²θ + tan²θ − sec²θ",
    choice_a: "0",
    choice_b: "1",
    choice_c: "2",
    choice_d: "−1",
    correct_choice: "a",
    explanation: "sin²θ+cos²θ=1 and sec²θ−tan²θ=1, so the expression becomes 1+(tan²θ−sec²θ) = 1+(−1) = 0.",
    difficulty: 2,
  },
  {
    question_text: "What is the area of triangle with sides a = 7, b = 10, and included angle C = 30°?",
    choice_a: "35 sq units",
    choice_b: "17.5 sq units",
    choice_c: "70 sq units",
    choice_d: "14 sq units",
    correct_choice: "b",
    explanation: "Area = ½ab·sinC = ½(7)(10)sin30° = 35×0.5 = 17.5 sq units.",
    difficulty: 2,
  },
  {
    question_text: "Convert 5π/6 radians to degrees.",
    choice_a: "150°",
    choice_b: "120°",
    choice_c: "210°",
    choice_d: "180°",
    correct_choice: "a",
    explanation: "(5π/6) × (180°/π) = (5×180)/6 = 150°.",
    difficulty: 2,
  },
  {
    question_text: "What is the range of y = sin(x)?",
    choice_a: "[0, 1]",
    choice_b: "(−∞, ∞)",
    choice_c: "[−1, 1]",
    choice_d: "[0, 2π]",
    correct_choice: "c",
    explanation: "The sine function has a range of [−1, 1], meaning its values are always between −1 and 1 inclusive.",
    difficulty: 1,
  },
  {
    question_text: "In triangle ABC, angle A = 45°, angle B = 60°. Find angle C.",
    choice_a: "75°",
    choice_b: "80°",
    choice_c: "90°",
    choice_d: "85°",
    correct_choice: "a",
    explanation: "Sum of angles = 180°. C = 180°−45°−60° = 75°.",
    difficulty: 1,
  },
  {
    question_text: "Given sin θ = 5/13 (θ in Quadrant II), what is cos θ?",
    choice_a: "12/13",
    choice_b: "−12/13",
    choice_c: "−5/13",
    choice_d: "5/12",
    correct_choice: "b",
    explanation: "cos²θ = 1−(25/169) = 144/169 → cosθ = ±12/13. In Quadrant II, cosine is negative, so cosθ = −12/13.",
    difficulty: 2,
  },
  {
    question_text: "The angle of elevation of the top of a building is 60° from a point 30 m away. How tall is the building? (tan60°=√3≈1.73)",
    choice_a: "30√3 ≈ 51.9 m",
    choice_b: "30 m",
    choice_c: "60 m",
    choice_d: "15√3 m",
    correct_choice: "a",
    explanation: "tan60° = h/30 → h = 30×tan60° = 30√3 ≈ 51.9 m.",
    difficulty: 2,
  },
  {
    question_text: "What is the domain of y = tan(x)?",
    choice_a: "All real numbers",
    choice_b: "x ≠ nπ, n ∈ ℤ",
    choice_c: "x ≠ π/2 + nπ, n ∈ ℤ",
    choice_d: "[−1, 1]",
    correct_choice: "c",
    explanation: "tan(x) = sin(x)/cos(x) is undefined when cos(x) = 0, i.e., at x = π/2 + nπ.",
    difficulty: 2,
  },
  {
    question_text: "Find x if 2sin(x) − 1 = 0 and 0° ≤ x ≤ 360°.",
    choice_a: "30° and 150°",
    choice_b: "60° and 120°",
    choice_c: "45° and 135°",
    choice_d: "30° only",
    correct_choice: "a",
    explanation: "2sinx=1 → sinx=1/2. sinx=1/2 at x=30° and x=150° in [0°,360°].",
    difficulty: 2,
  },
  {
    question_text: "What is the value of sec 60°?",
    choice_a: "1/2",
    choice_b: "2",
    choice_c: "√3",
    choice_d: "2/√3",
    correct_choice: "b",
    explanation: "sec 60° = 1/cos60° = 1/(1/2) = 2.",
    difficulty: 2,
  },
  {
    question_text: "In a triangle, side a = 6, side b = 8, side c = 10. What is the cosine of angle C?",
    choice_a: "0",
    choice_b: "0.5",
    choice_c: "−0.5",
    choice_d: "1",
    correct_choice: "a",
    explanation: "cosC = (a²+b²−c²)/(2ab) = (36+64−100)/(2×6×8) = 0/96 = 0. Angle C = 90°.",
    difficulty: 3,
  },
];

// ── ANALYTIC GEOMETRY (30) ───────────────────────────────────────────────────

const ANALYTIC_GEOMETRY: Q[] = [
  {
    question_text: "What is the distance between the points (1, 2) and (4, 6)?",
    choice_a: "5",
    choice_b: "6",
    choice_c: "√20",
    choice_d: "7",
    correct_choice: "a",
    explanation: "d = √[(4−1)²+(6−2)²] = √[9+16] = √25 = 5.",
    difficulty: 1,
  },
  {
    question_text: "What is the midpoint of the segment connecting (−2, 4) and (6, −2)?",
    choice_a: "(2, 1)",
    choice_b: "(4, 2)",
    choice_c: "(2, 2)",
    choice_d: "(1, 2)",
    correct_choice: "a",
    explanation: "Midpoint = ((−2+6)/2, (4−2)/2) = (4/2, 2/2) = (2, 1).",
    difficulty: 1,
  },
  {
    question_text: "What is the slope of the line through (3, 5) and (7, 9)?",
    choice_a: "1",
    choice_b: "2",
    choice_c: "4",
    choice_d: "1/2",
    correct_choice: "a",
    explanation: "m = (9−5)/(7−3) = 4/4 = 1.",
    difficulty: 1,
  },
  {
    question_text: "What is the equation of the line with slope 2 and y-intercept −3?",
    choice_a: "y = 2x + 3",
    choice_b: "y = −2x − 3",
    choice_c: "y = 2x − 3",
    choice_d: "y = 3x − 2",
    correct_choice: "c",
    explanation: "Slope-intercept form: y = mx + b = 2x + (−3) = 2x − 3.",
    difficulty: 1,
  },
  {
    question_text: "What is the equation of a circle centred at (0, 0) with radius 5?",
    choice_a: "x² + y² = 25",
    choice_b: "x² + y² = 5",
    choice_c: "x² − y² = 25",
    choice_d: "(x+5)² + (y+5)² = 0",
    correct_choice: "a",
    explanation: "Standard form: x² + y² = r² = 5² = 25.",
    difficulty: 1,
  },
  {
    question_text: "The slope of a horizontal line is:",
    choice_a: "Undefined",
    choice_b: "1",
    choice_c: "0",
    choice_d: "−1",
    correct_choice: "c",
    explanation: "A horizontal line has zero change in y, so slope = Δy/Δx = 0.",
    difficulty: 1,
  },
  {
    question_text: "Find the x-intercept of the line 3x − 4y = 12.",
    choice_a: "x = 4",
    choice_b: "x = 3",
    choice_c: "x = −3",
    choice_d: "x = 12",
    correct_choice: "a",
    explanation: "Set y = 0: 3x = 12 → x = 4. The x-intercept is (4, 0).",
    difficulty: 1,
  },
  {
    question_text: "What is the slope of a line perpendicular to y = (1/3)x + 5?",
    choice_a: "3",
    choice_b: "−3",
    choice_c: "1/3",
    choice_d: "−1/3",
    correct_choice: "b",
    explanation: "Perpendicular slopes are negative reciprocals. Reciprocal of 1/3 is 3; negative → −3.",
    difficulty: 2,
  },
  {
    question_text: "What is the centre and radius of the circle x² + y² − 6x + 4y − 3 = 0?",
    choice_a: "Centre (3, −2), radius 4",
    choice_b: "Centre (3, −2), radius 16",
    choice_c: "Centre (−3, 2), radius 4",
    choice_d: "Centre (6, −4), radius 3",
    correct_choice: "a",
    explanation: "Complete the square: (x−3)²+(y+2)² = 9+4+3 = 16. Centre (3,−2), radius = √16 = 4.",
    difficulty: 2,
  },
  {
    question_text: "What is the equation of the line passing through (2, 3) with slope −1?",
    choice_a: "y = −x + 5",
    choice_b: "y = x + 1",
    choice_c: "y = −x + 1",
    choice_d: "y = x − 5",
    correct_choice: "a",
    explanation: "y − 3 = −1(x − 2) → y = −x + 2 + 3 = −x + 5.",
    difficulty: 1,
  },
  {
    question_text: "Which conic section does x²/9 + y²/4 = 1 represent?",
    choice_a: "Parabola",
    choice_b: "Hyperbola",
    choice_c: "Ellipse",
    choice_d: "Circle",
    correct_choice: "c",
    explanation: "The equation x²/a² + y²/b² = 1 (with a ≠ b) defines an ellipse.",
    difficulty: 2,
  },
  {
    question_text: "For the parabola y = x², what is the vertex?",
    choice_a: "(0, 0)",
    choice_b: "(1, 1)",
    choice_c: "(0, 1)",
    choice_d: "(1, 0)",
    correct_choice: "a",
    explanation: "y = x² has its vertex at the origin (0, 0).",
    difficulty: 1,
  },
  {
    question_text: "What is the distance from the point (3, 4) to the line x + y − 2 = 0?",
    choice_a: "5/√2",
    choice_b: "3/√2",
    choice_c: "√2",
    choice_d: "5√2",
    correct_choice: "a",
    explanation: "d = |ax₀+by₀+c|/√(a²+b²) = |3+4−2|/√2 = 5/√2.",
    difficulty: 3,
  },
  {
    question_text: "Two lines are parallel if they have:",
    choice_a: "The same y-intercept",
    choice_b: "The same slope",
    choice_c: "Slopes that multiply to −1",
    choice_d: "Equal x-intercepts",
    correct_choice: "b",
    explanation: "Parallel lines have equal slopes but different y-intercepts (otherwise they would be the same line).",
    difficulty: 1,
  },
  {
    question_text: "What is the equation of the ellipse with semi-major axis 5 (along x) and semi-minor axis 3?",
    choice_a: "x²/25 + y²/9 = 1",
    choice_b: "x²/5 + y²/3 = 1",
    choice_c: "x²/9 + y²/25 = 1",
    choice_d: "x²/3 + y²/5 = 1",
    correct_choice: "a",
    explanation: "Ellipse: x²/a² + y²/b² = 1. a=5 → a²=25; b=3 → b²=9. So x²/25 + y²/9 = 1.",
    difficulty: 2,
  },
  {
    question_text: "The vertices of a triangle are A(0,0), B(4,0), and C(0,3). What is its area?",
    choice_a: "6 sq units",
    choice_b: "12 sq units",
    choice_c: "7 sq units",
    choice_d: "5 sq units",
    correct_choice: "a",
    explanation: "Area = ½ × base × height = ½ × 4 × 3 = 6 sq units.",
    difficulty: 2,
  },
  {
    question_text: "What is the equation of a parabola with vertex (0,0) opening upward and focus at (0, 2)?",
    choice_a: "x² = 8y",
    choice_b: "y² = 8x",
    choice_c: "x² = 2y",
    choice_d: "x² = 4y",
    correct_choice: "a",
    explanation: "Standard form: x² = 4py where p = distance to focus = 2. So x² = 4(2)y = 8y.",
    difficulty: 3,
  },
  {
    question_text: "Which point lies on the circle x² + y² = 25?",
    choice_a: "(3, 4)",
    choice_b: "(4, 4)",
    choice_c: "(5, 5)",
    choice_d: "(2, 4)",
    correct_choice: "a",
    explanation: "Check: 3²+4² = 9+16 = 25 ✓. Others: 4²+4²=32≠25; 5²+5²=50≠25; 2²+4²=20≠25.",
    difficulty: 1,
  },
  {
    question_text: "The equation x²/16 − y²/9 = 1 represents a:",
    choice_a: "Circle",
    choice_b: "Ellipse",
    choice_c: "Hyperbola",
    choice_d: "Parabola",
    correct_choice: "c",
    explanation: "An equation of the form x²/a² − y²/b² = 1 represents a hyperbola (note the minus sign between the terms).",
    difficulty: 2,
  },
  {
    question_text: "What is the slope of the line 4x − 2y + 8 = 0?",
    choice_a: "2",
    choice_b: "−2",
    choice_c: "4",
    choice_d: "1/2",
    correct_choice: "a",
    explanation: "Rewrite: 2y = 4x + 8 → y = 2x + 4. Slope = 2.",
    difficulty: 1,
  },
  {
    question_text: "What is the distance between the points (0,0) and (5, 12)?",
    choice_a: "13",
    choice_b: "17",
    choice_c: "√61",
    choice_d: "7",
    correct_choice: "a",
    explanation: "d = √(5²+12²) = √(25+144) = √169 = 13.",
    difficulty: 1,
  },
  {
    question_text: "What is the equation of the circle with centre (−1, 3) and radius 4?",
    choice_a: "(x+1)² + (y−3)² = 16",
    choice_b: "(x−1)² + (y+3)² = 16",
    choice_c: "(x+1)² + (y−3)² = 4",
    choice_d: "(x−1)² + (y+3)² = 4",
    correct_choice: "a",
    explanation: "Standard form: (x−h)²+(y−k)²=r². With h=−1, k=3, r=4: (x+1)²+(y−3)²=16.",
    difficulty: 2,
  },
  {
    question_text: "For the parabola x² = −12y, what is the focus?",
    choice_a: "(0, 3)",
    choice_b: "(0, −3)",
    choice_c: "(3, 0)",
    choice_d: "(−3, 0)",
    correct_choice: "b",
    explanation: "x² = 4py; comparing with x²=−12y gives 4p=−12 → p=−3. Focus is at (0, p) = (0, −3). Opens downward.",
    difficulty: 3,
  },
  {
    question_text: "Find the point of intersection of y = 2x + 1 and y = −x + 7.",
    choice_a: "(2, 5)",
    choice_b: "(3, 4)",
    choice_c: "(1, 6)",
    choice_d: "(4, 3)",
    correct_choice: "a",
    explanation: "Set equal: 2x+1=−x+7 → 3x=6 → x=2. y=2(2)+1=5. Intersection: (2, 5).",
    difficulty: 2,
  },
  {
    question_text: "What is the eccentricity of a circle?",
    choice_a: "Greater than 1",
    choice_b: "Equal to 1",
    choice_c: "Between 0 and 1",
    choice_d: "Equal to 0",
    correct_choice: "d",
    explanation: "A circle has eccentricity e = 0. (Ellipse: 0<e<1; parabola: e=1; hyperbola: e>1.)",
    difficulty: 2,
  },
  {
    question_text: "What is the equation of the line through (1, 3) and (3, 7)?",
    choice_a: "y = 2x + 1",
    choice_b: "y = x + 2",
    choice_c: "y = 2x − 1",
    choice_d: "y = x + 4",
    correct_choice: "a",
    explanation: "Slope m = (7−3)/(3−1)=2. y−3=2(x−1) → y=2x−2+3=2x+1.",
    difficulty: 1,
  },
  {
    question_text: "What is the length of the latus rectum of the parabola y² = 16x?",
    choice_a: "16",
    choice_b: "8",
    choice_c: "4",
    choice_d: "32",
    correct_choice: "a",
    explanation: "Comparing y²=4px with y²=16x gives 4p=16 → p=4. The latus rectum length = 4p = 16.",
    difficulty: 3,
  },
  {
    question_text: "The foci of the ellipse x²/25 + y²/16 = 1 are located at:",
    choice_a: "(±3, 0)",
    choice_b: "(±4, 0)",
    choice_c: "(±5, 0)",
    choice_d: "(0, ±3)",
    correct_choice: "a",
    explanation: "c² = a²−b² = 25−16 = 9 → c=3. Foci at (±3, 0) since major axis is along x.",
    difficulty: 3,
  },
  {
    question_text: "Which is the standard form of the equation of a line?",
    choice_a: "y = mx + b",
    choice_b: "Ax + By = C",
    choice_c: "y − y₁ = m(x − x₁)",
    choice_d: "All of the above are valid forms",
    correct_choice: "d",
    explanation: "All three forms — slope-intercept (y=mx+b), standard (Ax+By=C), and point-slope — are valid ways to write a linear equation.",
    difficulty: 1,
  },
  {
    question_text: "A segment has endpoints (2, −1) and (8, 5). What are the coordinates of the point that divides the segment in ratio 2:1 from the first endpoint?",
    choice_a: "(6, 3)",
    choice_b: "(4, 1)",
    choice_c: "(5, 2)",
    choice_d: "(7, 4)",
    correct_choice: "a",
    explanation: "Using section formula: x=(m·x₂+n·x₁)/(m+n)=(2×8+1×2)/3=18/3=6; y=(2×5+1×(−1))/3=9/3=3. Point (6,3).",
    difficulty: 3,
  },
];

// ── SEED HELPERS ─────────────────────────────────────────────────────────────

async function ensureAnalyticGeometryTopic(mathSubtestId: string): Promise<string> {
  const { data: existing } = await supabase
    .from("topics")
    .select("id")
    .eq("slug", "analytic-geometry")
    .single();

  if (existing) {
    console.log("  analytic-geometry topic already exists:", existing.id);
    return existing.id;
  }

  const { data: newTopic, error } = await supabase
    .from("topics")
    .insert({
      subtest_id: mathSubtestId,
      name: "Analytic Geometry",
      slug: "analytic-geometry",
      display_order: 7,
    })
    .select("id")
    .single();

  if (error || !newTopic) throw new Error("Failed to create analytic-geometry topic: " + error?.message);
  console.log("  Created analytic-geometry topic:", newTopic.id);
  return newTopic.id;
}

async function seedTopic(topicSlug: string, questions: Q[], topicId: string) {
  console.log(`\nSeeding ${questions.length} questions for topic: ${topicSlug} (${topicId})`);

  const rows = questions.map((q) => ({
    topic_id: topicId,
    question_text: q.question_text,
    choice_a: q.choice_a,
    choice_b: q.choice_b,
    choice_c: q.choice_c,
    choice_d: q.choice_d,
    correct_choice: q.correct_choice,
    explanation: q.explanation,
    difficulty: q.difficulty,
    status: "approved" as const,
    is_premium: true,
  }));

  const { error, count } = await supabase
    .from("questions")
    .insert(rows)
    .select("id");

  if (error) {
    console.error(`  ERROR for ${topicSlug}:`, error.message);
  } else {
    console.log(`  Inserted ${rows.length} questions.`);
  }
}

async function main() {
  console.log("Fetching math subtest…");
  const { data: subtest, error: stErr } = await supabase
    .from("subtests")
    .select("id, topics(id, slug)")
    .eq("slug", "mathematics")
    .single();

  if (stErr || !subtest) throw new Error("Could not find mathematics subtest: " + stErr?.message);

  const topics = subtest.topics as { id: string; slug: string }[];
  const topicMap = new Map(topics.map((t) => [t.slug, t.id]));

  console.log("Existing math topics:", [...topicMap.keys()]);

  // Ensure analytic-geometry topic exists
  const analyticGeoId = await ensureAnalyticGeometryTopic(subtest.id);
  topicMap.set("analytic-geometry", analyticGeoId);

  const TOPIC_QUESTIONS: [string, Q[]][] = [
    ["algebra", ALGEBRA],
    ["geometry", GEOMETRY],
    ["statistics", STATISTICS],
    ["arithmetic", ARITHMETIC],
    ["word-problems", WORD_PROBLEMS],
    ["trigonometry", TRIGONOMETRY],
    ["analytic-geometry", ANALYTIC_GEOMETRY],
  ];

  for (const [slug, questions] of TOPIC_QUESTIONS) {
    const topicId = topicMap.get(slug);
    if (!topicId) {
      console.error(`  Topic not found: ${slug}`);
      continue;
    }
    await seedTopic(slug, questions, topicId);
  }

  console.log("\nDone! 210 math questions seeded.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
