/**
 * Seeds 105 premium Reading Comprehension questions: 15 per topic × 7 topics.
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-reading-105.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

// ── MAIN IDEA AND DETAILS (15) ────────────────────────────────────────────────

const MAIN_IDEA: Q[] = [
  {
    question_text: "The Philippines contains about 22,549 square kilometers of coral reefs, ranking among the most diverse in the world. These reefs provide shelter and food for more than 2,500 species of fish and thousands of invertebrates. Despite their importance, about 70% of Philippine coral reefs are in poor or fair condition due to overfishing, pollution, and climate change. Conservation measures such as marine protected areas have helped some reefs recover, but sustained effort is still needed.\n\nWhat is the main idea of this passage?",
    choice_a: "Philippine coral reefs are the most diverse in the world.",
    choice_b: "Philippine coral reefs are ecologically vital but severely threatened.",
    choice_c: "Marine protected areas are the best solution for coral reef recovery.",
    choice_d: "Pollution is the leading cause of coral reef degradation in the Philippines.",
    correct_choice: "b",
    explanation: "The passage covers two equal ideas: the importance and diversity of the reefs, and the serious threats facing them. B captures both dimensions. A overstates the claim; C and D are single supporting details.",
    difficulty: 1,
  },
  {
    question_text: "The Philippine Eagle is one of the largest and most powerful birds of prey in the world. It is endemic to the Philippines, found mainly in Mindanao's old-growth forests. Classified as critically endangered, only an estimated 800 individuals remain in the wild. Threats include deforestation, which destroys nesting and hunting grounds, and illegal hunting. As the national bird of the Philippines, its protection is both an ecological responsibility and a matter of national pride.\n\nWhat is this passage mainly about?",
    choice_a: "The hunting habits of the Philippine Eagle.",
    choice_b: "The status and threats facing the Philippine Eagle.",
    choice_c: "Why the Philippine Eagle was chosen as the national bird.",
    choice_d: "The old-growth forests of Mindanao.",
    correct_choice: "b",
    explanation: "The passage covers the eagle's significance and the threats it faces. B captures both central elements. A, C, and D are narrow or secondary details.",
    difficulty: 1,
  },
  {
    question_text: "Mangrove forests grow along tropical coastlines and serve multiple ecological functions. They act as nurseries for fish, crabs, and shrimp, providing protected environments for juvenile marine life. Mangroves also protect coastal communities from storm surges and erosion, as their dense root systems absorb wave energy. Additionally, they store large quantities of carbon, earning them the title of 'blue carbon' ecosystems.\n\nAccording to the passage, mangroves are called 'blue carbon' ecosystems because they ___.",
    choice_a: "Grow along blue-colored coastlines.",
    choice_b: "Store large quantities of carbon.",
    choice_c: "Absorb blue light from the sun for photosynthesis.",
    choice_d: "Filter carbon pollutants from seawater.",
    correct_choice: "b",
    explanation: "The passage explicitly states: 'they store large quantities of carbon, earning them the title of blue carbon ecosystems.' This is a directly stated supporting detail.",
    difficulty: 1,
  },
  {
    question_text: "Overseas Filipino Workers (OFWs) are a vital economic force for the Philippines. In 2023, remittances from OFWs reached a record $36.1 billion, equivalent to about 9% of the country's GDP. These funds support millions of Filipino families, paying for food, education, housing, and healthcare. However, the social cost of overseas employment is significant — many OFW families face long separations, and children often grow up without one or both parents present.\n\nWhat does this passage primarily discuss?",
    choice_a: "The economic benefits of OFW remittances to the Philippines.",
    choice_b: "How OFWs spend their earnings while abroad.",
    choice_c: "The economic importance and social costs of OFW deployment.",
    choice_d: "Why the Philippine economy depends on OFWs for survival.",
    correct_choice: "c",
    explanation: "The passage addresses both the economic benefits (remittances, GDP contribution) and the social costs (family separation). C captures both sides. A only covers the economic dimension.",
    difficulty: 2,
  },
  {
    question_text: "Bamboo is one of the most versatile plants on Earth, used across a wide range of industries. In construction, it serves as scaffolding and flooring material, valued for its strength comparable to steel. Bamboo is also a key ingredient in paper production, textiles, and furniture making. Environmentally, bamboo grows rapidly — some species grow up to one meter per day — and sequesters carbon at rates higher than most trees.\n\nAccording to the passage, which of the following is a specific use of bamboo mentioned?",
    choice_a: "Medicine and pharmaceuticals.",
    choice_b: "Scaffolding and flooring in construction.",
    choice_c: "Fuel for electricity generation.",
    choice_d: "Feed for domestic animals.",
    correct_choice: "b",
    explanation: "The passage explicitly states bamboo is used 'as scaffolding and flooring material' in construction. The other options are not mentioned in the passage.",
    difficulty: 1,
  },
  {
    question_text: "The Philippines is considered one of the most climate-vulnerable countries in the world. Located in the Pacific typhoon belt, it experiences an average of 20 typhoons annually. Rising sea levels threaten low-lying coastal communities, while changes in rainfall patterns disrupt agriculture. Small island communities and subsistence farmers are especially at risk, often lacking resources to adapt to these changes.\n\nWhat is the main idea of the passage?",
    choice_a: "Typhoons are the biggest climate threat facing the Philippines.",
    choice_b: "The Philippines faces serious and widespread climate change impacts.",
    choice_c: "Small farmers suffer the most from climate change in the Philippines.",
    choice_d: "Sea level rise will eventually submerge low-lying areas in the Philippines.",
    correct_choice: "b",
    explanation: "The passage presents multiple climate risks — typhoons, sea level rise, rainfall changes — affecting different groups. B captures this broad, multi-faceted vulnerability. A, C, and D each focus on only one detail.",
    difficulty: 1,
  },
  {
    question_text: "When COVID-19 forced schools to close in 2020, the Philippine education system rapidly shifted to distance learning. Many students attended classes through printed modules, while others used online or television-based lessons. The transition exposed deep inequalities: students without internet access or devices struggled to keep up. Studies showed significant learning loss during this period, especially among students in rural and low-income communities.\n\nWhat is this passage primarily about?",
    choice_a: "The success of online learning during the pandemic.",
    choice_b: "How COVID-19 caused school closures across the Philippines.",
    choice_c: "The shift to distance learning and its unequal effects on students.",
    choice_d: "Why printed modules were the most effective distance learning solution.",
    correct_choice: "c",
    explanation: "The passage describes the shift to distance learning AND highlights its unequal effects. C captures both elements. A contradicts the passage (learning loss occurred). B is too narrow. D is not supported.",
    difficulty: 2,
  },
  {
    question_text: "Rice is the staple food of the Philippines, with over 17 million Filipinos directly involved in its production. The country has made significant advances through hybrid rice varieties that yield more grain per hectare. However, Filipino rice farmers face persistent challenges including small farm sizes, high production costs, and vulnerability to typhoons and drought. Despite record production levels in recent years, the Philippines still imports rice to meet domestic demand.\n\nAccording to the passage, which challenge do Filipino rice farmers face?",
    choice_a: "Lack of available land for rice cultivation.",
    choice_b: "Competition from foreign rice farmers in the local market.",
    choice_c: "High production costs and small farm sizes.",
    choice_d: "Unavailability of hybrid rice varieties.",
    correct_choice: "c",
    explanation: "The passage explicitly lists 'small farm sizes, high production costs' among the challenges. A is not mentioned; B is not mentioned; D contradicts the passage (hybrid varieties have been adopted).",
    difficulty: 1,
  },
  {
    question_text: "Access to clean water remains a critical challenge in many parts of the Philippines. Approximately 14 million Filipinos still lack access to safe drinking water. In remote areas, communities rely on rivers and unprotected wells contaminated with bacteria and agricultural chemicals. Waterborne diseases such as cholera and typhoid fever continue to claim lives each year. Investments in water infrastructure and sanitation are urgently needed to address this public health crisis.\n\nWhat is the main idea of this passage?",
    choice_a: "Cholera and typhoid fever are the most common waterborne diseases in the Philippines.",
    choice_b: "The Philippine government must invest more in water infrastructure.",
    choice_c: "Clean water scarcity is a serious and life-threatening problem in the Philippines.",
    choice_d: "Only remote communities in the Philippines are affected by water shortages.",
    correct_choice: "c",
    explanation: "The passage presents water scarcity as a serious public health problem affecting millions. C captures the overall message. A and B are supporting details; D contradicts the passage.",
    difficulty: 1,
  },
  {
    question_text: "Filipino women have made remarkable strides in science, technology, engineering, and mathematics (STEM). The Philippines ranks among the highest globally for gender parity in STEM education, with women comprising over half of all STEM graduates. Female scientists and engineers contribute significantly to pharmaceuticals, environmental research, and information technology. Despite these gains, women in STEM still face workplace challenges including gender bias and unequal pay.\n\nWhat does this passage mainly discuss?",
    choice_a: "The gender pay gap affecting women in STEM fields in the Philippines.",
    choice_b: "How Filipino women are leading all STEM fields globally.",
    choice_c: "The significant STEM gains made by Filipino women alongside remaining challenges.",
    choice_d: "Why STEM is the best career path for Filipino women.",
    correct_choice: "c",
    explanation: "The passage covers both the progress Filipino women have made in STEM and the challenges they still face. C captures both dimensions. A and B are partial; D is not discussed.",
    difficulty: 2,
  },
  {
    question_text: "In 2018, the Mental Health Act (Republic Act 11036) was signed into law, requiring mental health services in government offices, schools, and workplaces. The law also mandates the integration of mental health into the basic health care package. Advocates note that despite legal progress, many Filipinos still hesitate to seek mental health services due to stigma and limited access in rural areas.\n\nAccording to the passage, what does the Mental Health Act require?",
    choice_a: "Free therapy sessions for all Filipinos.",
    choice_b: "Mental health services in government offices, schools, and workplaces.",
    choice_c: "Mandatory mental health evaluations for all public officials.",
    choice_d: "The construction of mental health hospitals in every city.",
    correct_choice: "b",
    explanation: "The passage explicitly states the Mental Health Act requires 'mental health services in government offices, schools, and workplaces.' The other options are not mentioned.",
    difficulty: 1,
  },
  {
    question_text: "The Philippines is one of the world's 36 recognized biodiversity hotspots, harboring an extraordinary concentration of endemic species. More than 70% of the country's non-fish vertebrate species are found nowhere else on Earth. This biological wealth is distributed across diverse ecosystems — coral reefs, mangroves, rainforests, and grasslands. Unfortunately, rapid habitat loss due to deforestation, land conversion, and pollution threatens many of these unique species with extinction.\n\nWhat is the passage mainly about?",
    choice_a: "The different ecosystems found throughout the Philippine archipelago.",
    choice_b: "How deforestation is destroying Philippine endemic species.",
    choice_c: "The extraordinary biodiversity of the Philippines and the threats it faces.",
    choice_d: "Why the Philippines was designated as a global biodiversity hotspot.",
    correct_choice: "c",
    explanation: "The passage presents the Philippines' exceptional biodiversity and the serious threats to it. C captures both dimensions. A, B, and D are partial or secondary elements.",
    difficulty: 2,
  },
  {
    question_text: "The jeepney has long been an iconic symbol of Philippine culture. Originally repurposed from American military jeeps left after World War II, jeepneys became colorful vehicles adorned with religious images, bright paintwork, and chrome decorations. For decades, they served as the primary form of public transportation. In recent years, the government's PUV Modernization Program has pushed for their replacement with modern, environmentally compliant vehicles, sparking debate among drivers and commuters.\n\nWhat is the main idea of this passage?",
    choice_a: "The jeepney was originally a military vehicle used in World War II.",
    choice_b: "The jeepney is a cultural icon now undergoing a controversial transition.",
    choice_c: "The PUV Modernization Program will greatly improve transportation.",
    choice_d: "Jeepneys are being replaced because they are too old and unreliable.",
    correct_choice: "b",
    explanation: "The passage covers the jeepney's cultural history and the ongoing modernization debate. B captures both. A is only the origin story; C and D are one-sided or partial.",
    difficulty: 2,
  },
  {
    question_text: "The Philippines has significant potential for renewable energy, particularly solar, wind, geothermal, and hydropower. The country already generates a large portion of its electricity from geothermal energy, making it one of the world's leading geothermal producers. The government has set a target of 35% renewable energy in the power mix by 2030. However, high upfront costs, inconsistent policies, and grid infrastructure limitations continue to slow the transition away from coal-fired power plants.\n\nWhat does this passage primarily discuss?",
    choice_a: "Why the Philippines should immediately stop using coal for electricity.",
    choice_b: "The Philippines' renewable energy potential and the barriers to its development.",
    choice_c: "Geothermal energy as the ideal power source for the Philippines.",
    choice_d: "The government's 35% renewable energy target for 2030.",
    correct_choice: "b",
    explanation: "The passage presents the renewable energy potential and goals alongside the obstacles slowing progress. B captures this two-sided perspective. A, C, and D are partial details.",
    difficulty: 2,
  },
  {
    question_text: "Traditional Filipino medicine, known locally as 'gamot-gamutan,' has been practiced for centuries. Herbal plants such as lagundi, sambong, and tsaang gubat have been validated by the Philippine Department of Health and are now included in the National Formulary. Hilot, a traditional massage and healing practice, remains widely used in rural communities. Medical professionals caution, however, that traditional treatments should complement — not replace — evidence-based medicine.\n\nAccording to the passage, which herbal plants have been validated by the Philippine Department of Health?",
    choice_a: "Banaba, guava, and akapulco.",
    choice_b: "Lagundi, sambong, and tsaang gubat.",
    choice_c: "Ginger, turmeric, and moringa.",
    choice_d: "Neem, aloe vera, and eucalyptus.",
    correct_choice: "b",
    explanation: "The passage explicitly names 'lagundi, sambong, and tsaang gubat' as validated by the Philippine DOH. The other options are not mentioned.",
    difficulty: 1,
  },
];

// ── INFERENCE AND INTERPRETATION (15) ────────────────────────────────────────

const INFERENCE: Q[] = [
  {
    question_text: "Research shows that the average Filipino spends more than nine hours per day online, one of the highest rates in the world. Social media platforms are designed with algorithms that reward constant engagement, making it difficult for users to disconnect. Mental health professionals have noted a rise in anxiety, sleep disorders, and shortened attention spans among heavy internet users.\n\nWhat can be inferred from this passage?",
    choice_a: "All Filipinos are addicted to social media.",
    choice_b: "The design of social media platforms may be contributing to mental health problems.",
    choice_c: "Internet use should be banned to protect mental health.",
    choice_d: "Anxiety is caused solely by excessive internet use.",
    correct_choice: "b",
    explanation: "The passage connects platform design (engagement-rewarding algorithms) with rising mental health issues, implying a relationship between design and harm. A overgeneralizes; C and D go beyond what the passage supports.",
    difficulty: 2,
  },
  {
    question_text: "Maria, a 45-year-old nurse, has been working in Canada for twelve years. She sends money home monthly to pay for her children's tuition and her parents' medical expenses. Although her children video-call her regularly, her youngest daughter recently confided to a relative that she sometimes forgets what her mother's voice sounds like in person.\n\nWhat does this passage suggest about Maria's situation?",
    choice_a: "Maria is planning to return to the Philippines soon.",
    choice_b: "Maria earns far more money than her family needs.",
    choice_c: "Financial support does not fully substitute for a parent's physical presence.",
    choice_d: "Maria's children are ungrateful for her sacrifices.",
    correct_choice: "c",
    explanation: "The youngest daughter's comment implies that despite financial support, the emotional impact of her mother's absence is deeply felt. C captures this implied tension. A, B, and D are not supported by the passage.",
    difficulty: 2,
  },
  {
    question_text: "A fishing village in Palawan that once harvested abundant seafood now finds its nets nearly empty. The coral reef that once extended offshore has been bleached and broken. Fishermen report that they must travel much farther out to sea to find fish, spending more on fuel than they earn from the catch.\n\nWhat can be inferred from this passage?",
    choice_a: "Fishermen in Palawan have abandoned their traditional livelihoods.",
    choice_b: "The destruction of the coral reef has severely impacted the fishermen's livelihood.",
    choice_c: "Palawan's fishing industry has fully recovered after years of decline.",
    choice_d: "Fishermen are using bigger boats to increase their catch.",
    correct_choice: "b",
    explanation: "The bleached reef → empty nets → fishermen traveling farther at higher cost traces a clear causal chain. The reef's destruction has directly harmed the fishing community. A, C, and D are not supported.",
    difficulty: 1,
  },
  {
    question_text: "Despite passing the entrance exam with flying colors, Andres enrolled in an education course rather than the engineering program his parents had chosen for him. When asked why, he simply smiled and said, 'I want to make a difference where it matters most to me.'\n\nWhat does this passage most likely imply about Andres?",
    choice_a: "Andres is not academically qualified for engineering.",
    choice_b: "Andres prioritized his own values over his parents' expectations.",
    choice_c: "Andres plans to transfer to engineering after his first year.",
    choice_d: "Andres believes teaching pays better than engineering.",
    correct_choice: "b",
    explanation: "Andres passed the exam (ruling out A) but chose education for personal reasons. His statement implies personal values guided the decision over parental preference. C and D have no basis in the passage.",
    difficulty: 2,
  },
  {
    question_text: "A small municipality in the Cordillera region has seen its population shrink from 12,000 to 6,500 over the past two decades. Most of those who have left are between 18 and 35 years old. School enrollment has dropped by 40%, and several small businesses have closed. The remaining residents are mostly elderly.\n\nWhat can most reasonably be inferred from this passage?",
    choice_a: "The municipality regularly experiences natural disasters.",
    choice_b: "Young people are migrating elsewhere in search of opportunities, weakening the local economy.",
    choice_c: "The government has deliberately neglected this municipality.",
    choice_d: "Business closures caused young people to leave the town.",
    correct_choice: "b",
    explanation: "Population shrinkage concentrated among young adults, combined with falling school enrollment and business closures, implies youth outmigration in search of better opportunities. D reverses the likely cause-effect. A and C are not supported.",
    difficulty: 2,
  },
  {
    question_text: "José Rizal wrote both Noli Me Tangere and El Filibusterismo while living in Spain and Germany. Despite being far from his homeland, his novels vividly depicted Philippine society under Spanish colonial rule, exposing the abuses of the friars and the oppression of the colonial government. Spanish authorities considered his writings seditious, and Rizal was eventually arrested and executed in 1896.\n\nWhat can be concluded from the passage?",
    choice_a: "Rizal intended to overthrow the Spanish government through military means.",
    choice_b: "Rizal's writings were so powerful they were considered a threat to colonial rule.",
    choice_c: "Rizal's novels were only read by Filipinos living in Spain.",
    choice_d: "The Spanish government respected Rizal's freedom of expression.",
    correct_choice: "b",
    explanation: "The Spanish authorities declaring his works seditious and executing him implies the writings posed a genuine threat to colonial power. A is unsupported; C is not stated; D directly contradicts the passage.",
    difficulty: 1,
  },
  {
    question_text: "A 2023 survey found that teenagers who use social media for more than three hours daily report feeling lonelier and more anxious than peers who use it less. Paradoxically, these platforms are designed to connect people, yet heavy users often report weaker real-world relationships. Constant exposure to curated, idealized images of others' lives appears to fuel feelings of inadequacy.\n\nWhat does the author suggest about social media?",
    choice_a: "Social media should be banned for all users under 18.",
    choice_b: "Social media successfully achieves its goal of connecting people.",
    choice_c: "Despite being designed to connect people, social media may deepen feelings of isolation.",
    choice_d: "Only teenagers are negatively affected by social media use.",
    correct_choice: "c",
    explanation: "The word 'paradoxically' signals the contrast — platforms meant to connect are making heavy users lonelier. C captures this implied point. A goes beyond the passage; B contradicts it; D is too narrow.",
    difficulty: 2,
  },
  {
    question_text: "Mr. Reyes noticed that students who consistently sit at the back perform significantly lower on exams. He observed that back-row students frequently check phones, talk to neighbors, and arrive late. After rearranging seats so struggling students sat near the front, their grades improved noticeably.\n\nWhat can be inferred from this passage?",
    choice_a: "Students who sit at the back are naturally less intelligent.",
    choice_b: "Sitting at the front guarantees a student will pass all exams.",
    choice_c: "Engagement and proximity to instruction likely contribute to student performance.",
    choice_d: "Mr. Reyes is an exceptional teacher compared to his peers.",
    correct_choice: "c",
    explanation: "The pattern of disengagement in back rows and improvement after moving students forward implies engagement and proximity influence learning. A is unsupported and unfair; B is too absolute; D is not implied.",
    difficulty: 2,
  },
  {
    question_text: "A 65-year-old retired teacher began walking 30 minutes daily after his doctor warned him about high blood pressure. Within six months, his blood pressure normalized, he lost 8 kg, and he reports feeling more energetic than he did at 50.\n\nWhat does this passage most strongly imply?",
    choice_a: "Walking is the most effective form of exercise for everyone.",
    choice_b: "Regular physical activity can significantly improve health even when started later in life.",
    choice_c: "All patients with high blood pressure should walk rather than take medication.",
    choice_d: "It is too late for elderly people to improve their health through exercise.",
    correct_choice: "b",
    explanation: "The retired teacher started exercise at 65 and gained significant health benefits, implying it is not too late to benefit from physical activity. A overstates; C generalizes dangerously; D is the opposite of what the passage shows.",
    difficulty: 1,
  },
  {
    question_text: "Scientists studying a forest in Palawan discovered that when hunters removed large predators from one area, the populations of deer and wild pigs exploded. These animals overgrazed the undergrowth, preventing young trees from growing. Within a decade, the area showed significant signs of forest degradation.\n\nWhat does this passage imply about ecosystems?",
    choice_a: "All predators should be legally protected in Philippine forests.",
    choice_b: "Deer and wild pigs should be eliminated from forests.",
    choice_c: "The removal of predators can trigger a chain of negative effects in an ecosystem.",
    choice_d: "Large predators are the single most important element in any ecosystem.",
    correct_choice: "c",
    explanation: "The passage traces a causal chain: removing predators → prey overpopulation → overgrazing → forest degradation. This implies predator removal has cascading consequences. A and D go beyond the passage; B is extreme and unsupported.",
    difficulty: 2,
  },
  {
    question_text: "A company that shifted to a four-day work week reported that productivity did not decrease — and in some departments, it actually increased. Absenteeism fell by 30%, and employee satisfaction scores hit an all-time high. Customers noticed no drop in service quality.\n\nWhat can be inferred from this passage?",
    choice_a: "All companies should immediately adopt a four-day work week.",
    choice_b: "Employees always perform best when given more time off.",
    choice_c: "Fewer working hours can be compatible with — or even improve — employee output.",
    choice_d: "Five-day work week companies are always less productive.",
    correct_choice: "c",
    explanation: "The results show fewer work days did not reduce and sometimes improved productivity, implying fewer hours can be compatible with good output. A and D overgeneralize; B goes beyond the evidence.",
    difficulty: 2,
  },
  {
    question_text: "A rural high school began offering free after-school tutoring in mathematics and science. Within a year, the passing rate in these subjects rose from 58% to 82%. Students who attended at least twice a week showed the greatest improvement.\n\nBased on the passage, what would most likely happen if the tutoring program were discontinued?",
    choice_a: "Students would find other resources to maintain their performance.",
    choice_b: "Passing rates would likely decline again.",
    choice_c: "Teachers would automatically improve their classroom instruction.",
    choice_d: "The school would receive government funding for its program.",
    correct_choice: "b",
    explanation: "Since the tutoring program directly correlated with improved passing rates, removing it would most likely reverse those gains. A, C, and D are speculative and unsupported by the passage.",
    difficulty: 1,
  },
  {
    question_text: "In many Filipino households, adult children continue living with their parents even after marrying and having children of their own. Grandparents frequently serve as primary caregivers while parents work. This arrangement is rarely seen as burdensome — rather, it is viewed as a natural expression of family solidarity.\n\nWhat can be inferred from this passage?",
    choice_a: "Filipinos live with their parents only due to financial necessity.",
    choice_b: "The Filipino concept of family emphasizes interdependence and mutual care.",
    choice_c: "Nuclear family households are uncommon throughout Southeast Asia.",
    choice_d: "Grandparents in the Philippines universally prefer raising their grandchildren.",
    correct_choice: "b",
    explanation: "The passage frames multigenerational living as a positive expression of family solidarity, implying a cultural value of interdependence. A attributes it only to finances, which the passage contradicts. C and D make broader claims not supported.",
    difficulty: 2,
  },
  {
    question_text: "A new bridge connecting two towns cut travel time from three hours to twenty minutes. Within two years, a small market grew into a commercial hub, school enrollment increased as families moved in, and real estate values climbed. Local officials called it 'the best investment the province ever made.'\n\nWhat does the passage suggest about infrastructure development?",
    choice_a: "Building bridges is more important than investing in schools.",
    choice_b: "Infrastructure improvements can trigger broad social and economic development.",
    choice_c: "Real estate developers benefit most from government infrastructure projects.",
    choice_d: "All towns should prioritize bridge and road construction above other needs.",
    correct_choice: "b",
    explanation: "One bridge led to commercial growth, higher school enrollment, and rising property values — implying infrastructure has wide-ranging social and economic benefits. A, C, and D are not implied or are too narrow.",
    difficulty: 2,
  },
  {
    question_text: "A study followed 500 children from ages 3 to 18. Children read to daily by a parent in their early years scored significantly higher on reading comprehension and vocabulary tests in secondary school than those who were not. The gap was most pronounced among children from low-income families.\n\nWhat can be concluded from this study?",
    choice_a: "Reading to children guarantees academic success in all subjects.",
    choice_b: "Low-income families generally do not value their children's education.",
    choice_c: "Early parental reading habits appear to have lasting benefits for children's language skills.",
    choice_d: "Schools are less effective than parents at teaching reading comprehension.",
    correct_choice: "c",
    explanation: "The study shows a correlation between early parental reading and later language skills. C accurately reflects this conclusion. A overstates with 'guarantees'; B is a harmful stereotype; D makes an unsupported comparative claim.",
    difficulty: 2,
  },
];

// ── VOCABULARY IN CONTEXT (15) ────────────────────────────────────────────────

const VOCAB_IN_CONTEXT: Q[] = [
  {
    question_text: "The Philippine Tarsier is endemic to a small number of islands in the southern Philippines, including Bohol, Leyte, and Mindanao. Unlike many introduced species found across multiple countries, this tiny primate exists naturally nowhere else on Earth. Conservation programs focus on preserving its forest habitat.\n\nAs used in the passage, the word 'endemic' most nearly means ___.",
    choice_a: "Widely distributed across many regions.",
    choice_b: "Native and restricted to a specific geographic area.",
    choice_c: "In danger of becoming extinct.",
    choice_d: "Introduced by humans into a new environment.",
    correct_choice: "b",
    explanation: "'Exists naturally nowhere else on Earth' is the key context clue, confirming endemic means native and restricted to one specific area.",
    difficulty: 1,
  },
  {
    question_text: "Health officials warn that modern lifestyles have become increasingly sedentary, with many people spending most of their waking hours sitting at desks, watching television, or using mobile devices. This physical inactivity is linked to obesity, cardiovascular disease, and diabetes. Experts recommend at least 150 minutes of moderate exercise per week to counteract these effects.\n\nAs used in the passage, 'sedentary' most nearly means ___.",
    choice_a: "Characterized by little or no physical activity.",
    choice_b: "Harmful to one's mental health.",
    choice_c: "Related to a fast-paced urban lifestyle.",
    choice_d: "Involving excessive use of technology.",
    correct_choice: "a",
    explanation: "Context clues 'spending most waking hours sitting' and 'physical inactivity' define sedentary as involving little movement. Technology use is a detail, not the definition.",
    difficulty: 1,
  },
  {
    question_text: "The declaration of Martial Law in 1972 was a catalyst for a generation of Filipino activists, writers, and artists who channeled their outrage into protest literature and political organizing. Before the declaration, dissent was scattered; afterward, a unified opposition movement began to take shape.\n\nAs used in the passage, 'catalyst' most nearly means ___.",
    choice_a: "An obstacle that slows down progress.",
    choice_b: "A long and gradual historical process.",
    choice_c: "Something that triggers or accelerates change.",
    choice_d: "An explanation for past events.",
    correct_choice: "c",
    explanation: "'Before... scattered; afterward... unified' shows a change triggered by the Martial Law declaration. A catalyst sparks or accelerates a reaction, matching the passage's use.",
    difficulty: 2,
  },
  {
    question_text: "Senator Miriam Defensor Santiago was renowned for her eloquent speeches in the Philippine Senate. Her arguments were carefully structured, her language precise, and her delivery compelling — often leaving both supporters and critics unable to dispute the logic of her statements.\n\nAs used in the passage, 'eloquent' most nearly means ___.",
    choice_a: "Aggressive and confrontational in tone.",
    choice_b: "Fluent, persuasive, and well-expressed.",
    choice_c: "Brief and direct to the point.",
    choice_d: "Overly emotional and passionate.",
    correct_choice: "b",
    explanation: "Context clues — 'carefully structured,' 'precise language,' 'compelling delivery,' leaving critics unable to dispute — all describe articulate, persuasive expression. Eloquent means fluent and forceful in speech.",
    difficulty: 2,
  },
  {
    question_text: "The fishing cooperative adopted sustainable practices that allow fish populations to replenish naturally. Instead of using fine-mesh nets that catch juvenile fish, they switched to larger mesh sizes and implemented seasonal fishing bans. These measures ensure that future generations of fishermen will still have fish to catch.\n\nAs used in the passage, 'sustainable' most nearly means ___.",
    choice_a: "Highly profitable for fishermen in the short term.",
    choice_b: "Approved and regulated by the government.",
    choice_c: "Able to be maintained without depleting resources.",
    choice_d: "Harmful to the marine environment.",
    correct_choice: "c",
    explanation: "'Allow fish populations to replenish naturally' and 'future generations will still have fish' define sustainable as capable of continuing without exhausting resources.",
    difficulty: 1,
  },
  {
    question_text: "The once-magnificent colonial house on Calle Real had deteriorated badly over the decades. Its wooden walls had faded and rotted. The ornate carvings above the windows had fallen away, and sections of the roof had collapsed after years of neglect.\n\nAs used in the passage, 'deteriorated' most nearly means ___.",
    choice_a: "Improved and been restored over time.",
    choice_b: "Gained historical and cultural significance.",
    choice_c: "Declined sharply in quality or condition.",
    choice_d: "Been renovated for modern use.",
    correct_choice: "c",
    explanation: "Context clues 'faded and rotted,' 'fallen away,' 'collapsed' all describe a worsening condition. Deteriorated means became worse.",
    difficulty: 1,
  },
  {
    question_text: "The poem's ending is deliberately ambiguous — the poet provides no clear resolution, leaving the reader to decide whether the protagonist's departure represents escape or defeat. This open-endedness has led critics to offer contradictory interpretations, none of which can be definitively proven.\n\nAs used in the passage, 'ambiguous' most nearly means ___.",
    choice_a: "Clear and easy to understand.",
    choice_b: "Open to more than one interpretation.",
    choice_c: "Deliberately misleading to the reader.",
    choice_d: "Emotionally powerful and moving.",
    correct_choice: "b",
    explanation: "'No clear resolution,' 'contradictory interpretations,' 'cannot be definitively proven' — all describe something open to multiple readings. Ambiguous means having more than one possible meaning.",
    difficulty: 2,
  },
  {
    question_text: "Planting trees along riverbanks can help mitigate the effects of flooding. The roots hold soil in place, reducing erosion, while the canopy slows rainfall runoff. While not a complete solution, reforestation is an important tool for managing flood risk.\n\nAs used in the passage, 'mitigate' most nearly means ___.",
    choice_a: "Eliminate completely and permanently.",
    choice_b: "Cause or make worse.",
    choice_c: "Lessen the severity of.",
    choice_d: "Accurately predict in advance.",
    correct_choice: "c",
    explanation: "'Not a complete solution' rules out A (eliminate). The overall context — trees help manage flood risk — supports mitigate meaning to lessen severity, not remove entirely.",
    difficulty: 2,
  },
  {
    question_text: "Nick Joaquin was a prolific writer who produced dozens of short stories, several novels, plays, poetry collections, and countless journalistic pieces throughout his career spanning nearly six decades. He was awarded the National Artist title for Literature in 1976.\n\nAs used in the passage, 'prolific' most nearly means ___.",
    choice_a: "Having great depth of emotional expression.",
    choice_b: "Writing only for a small, specialized audience.",
    choice_c: "Controversial and widely debated.",
    choice_d: "Producing a large body of work.",
    correct_choice: "d",
    explanation: "Context clues: 'dozens of short stories, several novels, plays, poetry collections, countless journalistic pieces' spanning six decades — all indicate enormous output. Prolific means producing much work.",
    difficulty: 1,
  },
  {
    question_text: "The proposed construction of a dam in a protected watershed has become a contentious issue, with environmental groups, indigenous communities, and government agencies holding conflicting positions. Public hearings have turned into heated debates, and the matter has been elevated to the Supreme Court.\n\nAs used in the passage, 'contentious' most nearly means ___.",
    choice_a: "Easily and quickly resolved.",
    choice_b: "Widely celebrated by all groups.",
    choice_c: "Causing strong disagreement and argument.",
    choice_d: "Having legal and binding implications.",
    correct_choice: "c",
    explanation: "Context clues: 'conflicting positions,' 'heated debates,' 'elevated to the Supreme Court' — all indicate deep disagreement. Contentious means causing or likely to cause argument.",
    difficulty: 2,
  },
  {
    question_text: "Carabaos have long been integral to Philippine agriculture. Before motorized machinery, carabaos were essential for plowing rice paddies, transporting harvested crops, and performing heavy labor. Even today, in many rural communities, the carabao remains indispensable.\n\nAs used in the passage, 'integral' most nearly means ___.",
    choice_a: "Decorative and symbolic in nature.",
    choice_b: "Necessary and fundamental.",
    choice_c: "Dangerous and difficult to work with.",
    choice_d: "Imported from other countries.",
    correct_choice: "b",
    explanation: "'Essential' and 'indispensable' are context clues that confirm integral means necessary and fundamental — something that cannot be removed without great loss.",
    difficulty: 2,
  },
  {
    question_text: "The widespread adoption of smartphones has rendered many once-useful technologies virtually obsolete. Printed maps, physical encyclopedias, standalone GPS devices, and alarm clocks have been replaced by apps on a single handheld device. These technologies still exist but are rarely used by the general public.\n\nAs used in the passage, 'obsolete' most nearly means ___.",
    choice_a: "Improved and upgraded for modern use.",
    choice_b: "Expensive and out of reach for most people.",
    choice_c: "No longer in common use; outdated.",
    choice_d: "Prohibited from sale or manufacture.",
    correct_choice: "c",
    explanation: "'Replaced by apps' and 'rarely used by the general public' confirm that obsolete means no longer relevant or commonly used — outdated.",
    difficulty: 1,
  },
  {
    question_text: "The effects of the typhoon were exacerbated by years of unchecked urban development in Metro Manila. Waterways had been narrowed by informal settlements and commercial buildings. When unprecedented rainfall came, the compromised drainage system caused catastrophic flooding.\n\nAs used in the passage, 'exacerbated' most nearly means ___.",
    choice_a: "Caused entirely from scratch.",
    choice_b: "Made worse or more severe.",
    choice_c: "Accurately predicted in advance.",
    choice_d: "Reduced in overall impact.",
    correct_choice: "b",
    explanation: "Development didn't cause the typhoon (ruling out A) but it worsened its impact. Exacerbated means made an existing problem more severe.",
    difficulty: 2,
  },
  {
    question_text: "In years leading up to the 1986 EDSA Revolution, corruption was rampant within the government. Officials at all levels accepted bribes, and public funds were routinely diverted. The unchecked abuse of power had eroded public trust to near zero.\n\nAs used in the passage, 'rampant' most nearly means ___.",
    choice_a: "Secretly and carefully hidden.",
    choice_b: "Occurring only occasionally.",
    choice_c: "Widespread and uncontrolled.",
    choice_d: "Newly introduced into the system.",
    correct_choice: "c",
    explanation: "'At all levels,' 'routinely,' and 'unchecked' all signal that the corruption was widespread and out of control. Rampant means spreading unchecked.",
    difficulty: 1,
  },
  {
    question_text: "The effects of Typhoon Ondoy were exacerbated by urban sprawl, but the response of ordinary Filipinos was exemplary. Neighbors rescued strangers from rooftops, communities opened their doors to evacuees, and volunteers from across Metro Manila delivered relief goods without being asked. Their spontaneous generosity embodied the Filipino spirit of bayanihan.\n\nAs used in the passage, 'exemplary' most nearly means ___.",
    choice_a: "Surprising and unexpected.",
    choice_b: "Worth punishing or penalizing.",
    choice_c: "Serving as a warning to others.",
    choice_d: "Deserving to be imitated; outstandingly good.",
    correct_choice: "d",
    explanation: "The passage describes the response positively — rescuing strangers, opening doors, delivering goods — embodying the spirit of bayanihan. Exemplary means outstandingly good and worthy of being copied.",
    difficulty: 2,
  },
];

// ── LITERARY ANALYSIS (15) ────────────────────────────────────────────────────

const LITERARY_ANALYSIS: Q[] = [
  {
    question_text: "\"Her voice was like a bamboo flute playing in an empty church — pure, haunting, and echoing long after the sound itself had stopped.\"\n\nWhich literary device is used in this sentence?",
    choice_a: "Metaphor",
    choice_b: "Personification",
    choice_c: "Simile",
    choice_d: "Hyperbole",
    correct_choice: "c",
    explanation: "The sentence compares her voice to a bamboo flute using the word 'like,' which is the defining feature of a simile. A metaphor would make the comparison directly (her voice IS a flute).",
    difficulty: 1,
  },
  {
    question_text: "\"The classroom was a battlefield that morning. Papers flew, voices clashed, and every student seemed to be fighting a private war against confusion and fear.\"\n\nWhich literary device is primarily used in this passage?",
    choice_a: "Simile",
    choice_b: "Metaphor",
    choice_c: "Irony",
    choice_d: "Onomatopoeia",
    correct_choice: "b",
    explanation: "The classroom IS called a battlefield — a direct comparison without 'like' or 'as.' This is a metaphor. Extended metaphorical language ('clashed,' 'fighting') reinforces it.",
    difficulty: 1,
  },
  {
    question_text: "\"The sun lazily stretched its golden arms across the mountain tops, reluctant to begin another day.\"\n\nWhat literary device is used in this sentence?",
    choice_a: "Hyperbole",
    choice_b: "Alliteration",
    choice_c: "Simile",
    choice_d: "Personification",
    correct_choice: "d",
    explanation: "The sun is given human characteristics — 'lazily stretched its arms' and 'reluctant to begin another day.' Attributing human qualities to a non-human subject is personification.",
    difficulty: 1,
  },
  {
    question_text: "The city's most celebrated traffic enforcer was caught on camera driving on a sidewalk to avoid the very traffic jam he was supposed to prevent.\n\nWhat type of irony is illustrated in this situation?",
    choice_a: "Verbal irony",
    choice_b: "Dramatic irony",
    choice_c: "Situational irony",
    choice_d: "Tragic irony",
    correct_choice: "c",
    explanation: "Situational irony occurs when what happens is the opposite of what is expected. We expect a traffic enforcer to follow road rules — instead, he breaks them. Verbal irony involves saying the opposite of what one means.",
    difficulty: 2,
  },
  {
    question_text: "\"Six silver swallows swooped silently over the still sea.\"\n\nWhich literary device is used in this sentence?",
    choice_a: "Assonance",
    choice_b: "Onomatopoeia",
    choice_c: "Alliteration",
    choice_d: "Consonance",
    correct_choice: "c",
    explanation: "Alliteration is the repetition of the same initial consonant sound in nearby words. Here, 'Six, silver, swallows, swooped, silently, still, sea' all begin with the 's' sound.",
    difficulty: 1,
  },
  {
    question_text: "\"He walked through the emptied house one final time. The rooms, once alive with the noise of children and the smell of cooking, now offered nothing but silence and the faint echo of footsteps. He closed the door behind him without looking back.\"\n\nWhat is the tone of this passage?",
    choice_a: "Joyful and celebratory",
    choice_b: "Angry and resentful",
    choice_c: "Melancholy and reflective",
    choice_d: "Tense and suspenseful",
    correct_choice: "c",
    explanation: "The empty house, memories of a lively past, silence, and the act of leaving without looking back all create a tone of sadness and quiet reflection — melancholy.",
    difficulty: 2,
  },
  {
    question_text: "\"Every summer, the smell of ripe mangoes and the sound of children splashing in the nearby river take me back to simpler days — long, unhurried afternoons when the biggest worry was whether we'd have enough time to play before dark.\"\n\nWhat mood does this passage create?",
    choice_a: "Fear and unease",
    choice_b: "Nostalgia and warmth",
    choice_c: "Anger and frustration",
    choice_d: "Excitement and anticipation",
    correct_choice: "b",
    explanation: "Sensory details (smell of mangoes, splashing children), the reference to 'simpler days,' and carefree childhood memories create a warm, nostalgic mood — longing for the past.",
    difficulty: 1,
  },
  {
    question_text: "\"The mayor delivered a rousing speech on the importance of cleanliness, standing before a podium decorated with plastic flowers and surrounded by aides busily sweeping confetti under the stage.\"\n\nWhat is the tone of this passage?",
    choice_a: "Sincere and inspirational",
    choice_b: "Sad and sympathetic",
    choice_c: "Satirical and ironic",
    choice_d: "Neutral and informative",
    correct_choice: "c",
    explanation: "A mayor speaking about cleanliness while surrounded by hidden mess creates a satirical contrast — the passage mocks hypocrisy with ironic detail.",
    difficulty: 2,
  },
  {
    question_text: "\"Every minute, the equivalent of a garbage truck's worth of plastic enters the world's oceans. By 2050, scientists warn, there will be more plastic in the sea than fish. We are running out of time to act.\"\n\nWhat tone does the author use?",
    choice_a: "Hopeful and optimistic",
    choice_b: "Humorous and lighthearted",
    choice_c: "Urgent and alarming",
    choice_d: "Detached and academic",
    correct_choice: "c",
    explanation: "Stark statistics, a dire prediction for 2050, and the direct call to action ('running out of time') all create a tone of urgency and alarm.",
    difficulty: 1,
  },
  {
    question_text: "\"The Philippine Crocodile (Crocodylus mindorensis) is one of the world's most endangered crocodile species, with fewer than 250 mature individuals remaining in the wild. It is endemic to the Philippines, found in freshwater rivers and lakes. Conservation programs are working to protect nesting sites and increase captive breeding.\"\n\nWhat is the author's primary purpose?",
    choice_a: "To entertain readers with dramatic crocodile stories.",
    choice_b: "To persuade readers to adopt crocodiles as pets.",
    choice_c: "To inform readers about the Philippine Crocodile and its conservation status.",
    choice_d: "To argue that crocodiles deserve legal rights.",
    correct_choice: "c",
    explanation: "The passage presents factual information — scientific name, population count, habitat, and conservation efforts — with no narrative or argument. The purpose is purely informative.",
    difficulty: 1,
  },
  {
    question_text: "\"It is time for the Philippine government to declare a full moratorium on all forms of plastic packaging. The oceans cannot absorb any more of our waste. Future generations will inherit a poisoned planet unless we act now. The inconvenience of changing our habits is nothing compared to the catastrophe of inaction.\"\n\nWhat is the author's primary purpose?",
    choice_a: "To describe the science behind plastic pollution.",
    choice_b: "To persuade readers and government to ban plastic packaging.",
    choice_c: "To explain how plastic packaging is manufactured.",
    choice_d: "To share a personal experience with ocean pollution.",
    correct_choice: "b",
    explanation: "The use of 'It is time,' direct calls to action, and moral urgency ('catastrophe of inaction') clearly show the author's purpose is to persuade.",
    difficulty: 1,
  },
  {
    question_text: "\"Old Mang Tasio sat beneath the balete tree every afternoon, telling stories of aswangs and tikbalangs to a circle of wide-eyed children. He embellished each tale with pauses, sudden whispers, and occasional slaps on his knee that made the children jump and then dissolve into laughter.\"\n\nWhat is the author's primary purpose?",
    choice_a: "To academically analyze Filipino folklore.",
    choice_b: "To warn readers about supernatural creatures.",
    choice_c: "To persuade readers to preserve oral storytelling traditions.",
    choice_d: "To entertain readers with a vivid scene of storytelling.",
    correct_choice: "d",
    explanation: "The passage uses sensory detail and imagery to paint a lively, engaging scene — its purpose is entertainment and vivid portrayal, not analysis, warning, or argument.",
    difficulty: 2,
  },
  {
    question_text: "\"I had never imagined I would one day stand on the stage of the Cultural Center of the Philippines. Yet there I was, violin in hand, my heart pounding, staring at five hundred expectant faces.\"\n\nFrom what point of view is this passage written?",
    choice_a: "Second person",
    choice_b: "Third person limited",
    choice_c: "Third person omniscient",
    choice_d: "First person",
    correct_choice: "d",
    explanation: "The use of 'I' throughout ('I had never imagined,' 'there I was,' 'my heart') identifies this as first person narration — the narrator is directly experiencing the events.",
    difficulty: 1,
  },
  {
    question_text: "\"Ana clutched her test paper and walked to the teacher's desk. She could not bring herself to look at the grade until she was safely in her seat. When she finally flipped the page, she exhaled slowly — 98%. She allowed herself one small smile before folding the paper carefully into her notebook.\"\n\nWhat point of view is used?",
    choice_a: "First person",
    choice_b: "Second person",
    choice_c: "Third person omniscient",
    choice_d: "Third person limited",
    correct_choice: "d",
    explanation: "The narrator uses 'she' (third person) and reveals only Ana's thoughts and feelings, not those of other characters. This is third person limited — we are limited to one character's perspective.",
    difficulty: 2,
  },
  {
    question_text: "\"Throughout the novel, the young scholar struggles to balance duty to his family with personal ambition. In the end, he returns to his province and uses his education to serve his community — not because he abandons his dreams, but because he redefines them.\"\n\nWhich theme is most clearly expressed?",
    choice_a: "Education is more important than family obligation.",
    choice_b: "Personal success is impossible without great sacrifice.",
    choice_c: "True fulfillment comes from serving one's community.",
    choice_d: "Ambition always leads to internal conflict.",
    correct_choice: "c",
    explanation: "The scholar's final choice — using education to serve his community and redefining success in communal terms — directly expresses the theme that fulfillment comes from community service, not personal achievement alone.",
    difficulty: 3,
  },
];

// ── CONTEXT CLUES (15) ────────────────────────────────────────────────────────

const CONTEXT_CLUES: Q[] = [
  {
    question_text: "\"The caterpillar was a voracious eater, consuming several times its own body weight in leaves each day. Nothing in the garden was safe from its appetite.\"\n\nBased on context clues, 'voracious' means ___.",
    choice_a: "Selective and picky about food.",
    choice_b: "Extremely hungry and consuming a great amount.",
    choice_c: "Small and delicate in size.",
    choice_d: "Slow-moving and cautious.",
    correct_choice: "b",
    explanation: "'Consuming several times its own body weight' and 'nothing was safe from its appetite' are context clues indicating an extremely hungry, ravenous eater.",
    difficulty: 1,
  },
  {
    question_text: "\"The lumad communities are indigenous to Mindanao, having lived on these lands for thousands of years before the arrival of Malay settlers and Spanish colonizers. Their culture and traditions evolved separately from the lowland Filipino majority.\"\n\nBased on context clues, 'indigenous' means ___.",
    choice_a: "Recently migrating from other islands.",
    choice_b: "Living in urban and metropolitan areas.",
    choice_c: "Originally from and belonging naturally to a specific place.",
    choice_d: "Educated in foreign institutions.",
    correct_choice: "c",
    explanation: "'Having lived on these lands for thousands of years before the arrival of' others is the key context clue — indigenous means originally native to a specific place.",
    difficulty: 1,
  },
  {
    question_text: "\"The calligrapher was meticulous in her work, measuring every stroke with a ruler, mixing her ink to an exact consistency, and discarding any piece that showed even the slightest imperfection. Each finished page took hours to complete.\"\n\nBased on context clues, 'meticulous' means ___.",
    choice_a: "Quick and highly efficient.",
    choice_b: "Creative and highly imaginative.",
    choice_c: "Traditional and old-fashioned.",
    choice_d: "Showing great care and attention to detail.",
    correct_choice: "d",
    explanation: "'Measuring every stroke,' 'exact consistency,' and 'discarding any piece with the slightest imperfection' all point to extreme care and precision — the definition of meticulous.",
    difficulty: 1,
  },
  {
    question_text: "\"The journey to the remote mountain village was arduous — six hours on unpaved roads, followed by a three-hour hike through dense forest and steep ravines. Many volunteers were exhausted before they even reached their destination.\"\n\nBased on context clues, 'arduous' means ___.",
    choice_a: "Exciting and full of adventure.",
    choice_b: "Short and very convenient.",
    choice_c: "Requiring great effort; very difficult.",
    choice_d: "Peaceful and enjoyable throughout.",
    correct_choice: "c",
    explanation: "Six hours on bad roads plus a three-hour mountain hike causing exhaustion are context clues confirming arduous means extremely difficult and demanding.",
    difficulty: 1,
  },
  {
    question_text: "\"Schools located in proximity to industrial areas reported higher rates of respiratory illness among students. The closer a school was to a factory, the more students suffered from asthma and bronchitis.\"\n\nBased on context clues, 'proximity' means ___.",
    choice_a: "Danger or threat.",
    choice_b: "Opposition or resistance.",
    choice_c: "Nearness; closeness.",
    choice_d: "Distance or separation.",
    correct_choice: "c",
    explanation: "'The closer a school was to a factory' paraphrases 'proximity to industrial areas.' This parallel structure confirms proximity means nearness or closeness.",
    difficulty: 2,
  },
  {
    question_text: "\"The benevolent landowner donated a portion of his land for a school and regularly funded scholarships for children from poor families. He asked nothing in return, seeking only to improve the lives of those around him.\"\n\nBased on context clues, 'benevolent' means ___.",
    choice_a: "Wealthy and politically influential.",
    choice_b: "Strict and demanding of others.",
    choice_c: "Kind and generous toward others.",
    choice_d: "Selfish and calculating in his motives.",
    correct_choice: "c",
    explanation: "Donating land, funding scholarships, asking nothing in return, and seeking only to help others — all these context clues define benevolent as kind and generous.",
    difficulty: 1,
  },
  {
    question_text: "\"Despite losing their home to a typhoon, the family rebuilt within six months. Their resilience was evident: they wasted no time mourning what was lost and instead focused all their energy on recovery. Neighbors remarked that they seemed stronger after the storm than before it.\"\n\nBased on context clues, 'resilience' means ___.",
    choice_a: "Stubbornness and refusal to accept outside help.",
    choice_b: "Wealth and access to material resources.",
    choice_c: "Community support and the bayanihan spirit.",
    choice_d: "The ability to recover quickly from hardship.",
    correct_choice: "d",
    explanation: "'Wasted no time mourning' and 'focused on recovery,' resulting in seeming 'stronger after the storm,' are context clues confirming resilience means bouncing back from difficulty.",
    difficulty: 1,
  },
  {
    question_text: "\"Years of protest and sacrifice culminated in the signing of the 1987 Philippine Constitution, which restored democratic institutions suppressed under Martial Law.\"\n\nBased on context clues, 'culminated' means ___.",
    choice_a: "Failed or ended in disappointment.",
    choice_b: "Was unexpectedly interrupted.",
    choice_c: "Reached its highest or final point.",
    choice_d: "Was quickly forgotten over time.",
    correct_choice: "c",
    explanation: "Years of struggle reaching their endpoint in the signing of the Constitution shows culminated means arriving at a final, significant conclusion.",
    difficulty: 2,
  },
  {
    question_text: "\"The peace talks produced only a tentative agreement — both sides acknowledged it as a starting point rather than a final resolution. Officials cautioned that many details still needed to be negotiated before any deal could be made permanent.\"\n\nBased on context clues, 'tentative' means ___.",
    choice_a: "Final and legally binding.",
    choice_b: "Quickly and informally arranged.",
    choice_c: "Not yet definite; subject to change.",
    choice_d: "Publicly announced and celebrated.",
    correct_choice: "c",
    explanation: "'Starting point rather than final resolution' and 'still needed to be negotiated' are context clues confirming tentative means provisional and not yet settled.",
    difficulty: 2,
  },
  {
    question_text: "\"The free medical mission aimed to alleviate the suffering of poor residents who could not afford hospital care. Hundreds of patients received free medicines and procedures, providing relief they could not otherwise access.\"\n\nBased on context clues, 'alleviate' means ___.",
    choice_a: "Increase or intensify suffering.",
    choice_b: "Study and document for research.",
    choice_c: "Make less severe; reduce suffering.",
    choice_d: "Ignore or overlook entirely.",
    correct_choice: "c",
    explanation: "'Providing relief' is the key context clue — the mission's purpose was to reduce suffering, which is what alleviate means.",
    difficulty: 1,
  },
  {
    question_text: "\"The students were fervent supporters of their team, arriving hours before the game to secure the best seats, painting their faces in school colors, and cheering at the top of their voices throughout the match.\"\n\nBased on context clues, 'fervent' means ___.",
    choice_a: "Reluctant and unenthusiastic.",
    choice_b: "Intensely enthusiastic and passionate.",
    choice_c: "Well-organized and disciplined.",
    choice_d: "Occasionally and mildly interested.",
    correct_choice: "b",
    explanation: "Arriving hours early, painting faces, and cheering throughout are all extreme expressions of enthusiasm. These context clues confirm fervent means deeply passionate and enthusiastic.",
    difficulty: 1,
  },
  {
    question_text: "\"The interior of the island was surprisingly sparse — only a few scrub trees and patches of dry grass, nothing like the lush tropical forests the explorers had expected. Water was scarce and the ground was cracked from months without rain.\"\n\nBased on context clues, 'sparse' means ___.",
    choice_a: "Dense and overgrown with vegetation.",
    choice_b: "Beautiful and colorful.",
    choice_c: "Thinly spread; meager in quantity.",
    choice_d: "Well-irrigated and fertile.",
    correct_choice: "c",
    explanation: "'Nothing like the lush forests expected,' 'only a few scrub trees,' and 'cracked ground' contrast with abundance, confirming sparse means thinly distributed and scarce.",
    difficulty: 2,
  },
  {
    question_text: "\"Dr. Santos has long been an advocate for indigenous rights, speaking at international forums, publishing research on ancestral land claims, and assisting communities in filing legal cases to protect their territories.\"\n\nBased on context clues, 'advocate' means ___.",
    choice_a: "A critic or opponent of a cause.",
    choice_b: "A government official in charge of policy.",
    choice_c: "A historian studying indigenous cultures.",
    choice_d: "A person who publicly supports or champions a cause.",
    correct_choice: "d",
    explanation: "Speaking, publishing, and providing legal assistance all in support of indigenous rights — these actions define advocate as someone who actively supports a cause.",
    difficulty: 1,
  },
  {
    question_text: "\"Telling children they are 'just naturally bad at math' can perpetuate a damaging belief that may follow them throughout their education. Such labels become self-fulfilling prophecies, limiting what students believe they can achieve.\"\n\nBased on context clues, 'perpetuate' means ___.",
    choice_a: "Challenge and ultimately change.",
    choice_b: "Gradually weaken over time.",
    choice_c: "Cause something to continue or persist.",
    choice_d: "Introduce something for the very first time.",
    correct_choice: "c",
    explanation: "'May follow them throughout their education' and 'self-fulfilling prophecies' show the belief continues and is maintained. Perpetuate means to make something last or keep it going.",
    difficulty: 2,
  },
  {
    question_text: "\"After three days without food, the hikers were ravenous. They ate everything in sight the moment they reached the base camp, consuming meals meant for twice their number without slowing down.\"\n\nBased on context clues, 'ravenous' means ___.",
    choice_a: "Exhausted and unable to move.",
    choice_b: "Extremely grateful and relieved.",
    choice_c: "Intensely hungry; famished.",
    choice_d: "Cautious and selective about food.",
    correct_choice: "c",
    explanation: "'Three days without food,' 'ate everything in sight,' and 'consuming meals meant for twice their number' are strong context clues showing ravenous means extremely hungry.",
    difficulty: 1,
  },
];

// ── FACT VS OPINION (15) ──────────────────────────────────────────────────────

const FACT_VS_OPINION: Q[] = [
  {
    question_text: "Which of the following is a FACT?",
    choice_a: "The Philippines is the most beautiful country in Asia.",
    choice_b: "Manila is the capital city of the Philippines.",
    choice_c: "Filipino food is better than any other Asian cuisine.",
    choice_d: "Filipinos are the friendliest people in the world.",
    correct_choice: "b",
    explanation: "B is objectively verifiable — Manila is indeed the capital of the Philippines. A, C, and D express subjective judgments that cannot be measured or proven objectively.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "The Philippines experiences an average of 20 typhoons annually.",
    choice_b: "Typhoon Yolanda (Haiyan) made landfall in November 2013.",
    choice_c: "The government should do more to protect communities from typhoons.",
    choice_d: "The Philippines is located in the Pacific typhoon belt.",
    correct_choice: "c",
    explanation: "C contains 'should,' expressing a personal belief about what ought to happen — a value judgment. A, B, and D are verifiable facts.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is a FACT?",
    choice_a: "The Philippine Eagle is the greatest bird in the animal kingdom.",
    choice_b: "The Philippine Eagle measures up to 102 centimeters in length.",
    choice_c: "Its extinction would be the saddest event in Philippine history.",
    choice_d: "No meaningful conservation effort is being made for the eagle.",
    correct_choice: "b",
    explanation: "B is a measurable, verifiable biological fact. A and C contain subjective superlatives ('greatest,' 'saddest'). D is a false and subjective claim.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "Rice is the staple food of most Filipinos.",
    choice_b: "The Philippines produces over 19 million metric tons of rice annually.",
    choice_c: "Rice farming is the most important occupation in the Philippines.",
    choice_d: "The Philippines imports rice when domestic production falls short.",
    correct_choice: "c",
    explanation: "'Most important' is a subjective ranking that expresses a value judgment. A, B, and D are verifiable facts.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is a FACT?",
    choice_a: "José Rizal is the greatest Filipino who ever lived.",
    choice_b: "Rizal's writings were more powerful than those of any other Filipino.",
    choice_c: "Rizal's novel Noli Me Tangere was published in 1887.",
    choice_d: "The Philippines should have more holidays honoring Rizal.",
    correct_choice: "c",
    explanation: "C is historically verifiable — Noli Me Tangere was indeed published in 1887 in Berlin. A and B are subjective value judgments; D is a prescriptive opinion.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "The Pasig River flows through Metro Manila.",
    choice_b: "Government programs have been implemented to rehabilitate the Pasig River.",
    choice_c: "Restoring the Pasig River is the most urgent environmental priority in the Philippines.",
    choice_d: "The Pasig River connects Laguna de Bay to Manila Bay.",
    correct_choice: "c",
    explanation: "'Most urgent priority' reflects a personal judgment about relative importance. A, B, and D are verifiable geographic and historical facts.",
    difficulty: 2,
  },
  {
    question_text: "Read the following passage: \"Social media has completely destroyed the quality of communication among young Filipinos. Studies show that Filipino youth spend an average of four hours daily on social media platforms. This excessive use is clearly making young people less capable of meaningful interaction. The government must impose strict limits on social media use.\"\n\nWhich sentence from the passage is a FACT?",
    choice_a: "\"Social media has completely destroyed the quality of communication among young Filipinos.\"",
    choice_b: "\"Filipino youth spend an average of four hours daily on social media platforms.\"",
    choice_c: "\"This excessive use is clearly making young people less capable of meaningful interaction.\"",
    choice_d: "\"The government must impose strict limits on social media use.\"",
    correct_choice: "b",
    explanation: "B is based on a study and is empirically verifiable. A contains 'completely destroyed' — an absolute and subjective claim. C is an interpretation. D is a prescription ('must').",
    difficulty: 2,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "The EDSA People Power Revolution took place in February 1986.",
    choice_b: "Ferdinand Marcos declared Martial Law in 1972.",
    choice_c: "The EDSA Revolution was the most inspiring event in Philippine history.",
    choice_d: "Corazon Aquino was sworn in as president after the EDSA Revolution.",
    correct_choice: "c",
    explanation: "'Most inspiring' is a subjective evaluation — different people may rank historical events differently. A, B, and D are historical facts that can be verified.",
    difficulty: 1,
  },
  {
    question_text: "Which of the following is a FACT?",
    choice_a: "Tagalog is the most beautiful language in Asia.",
    choice_b: "The Philippines has over 180 languages and dialects.",
    choice_c: "Filipino is easier to learn than any other Asian language.",
    choice_d: "English should remain the primary medium of instruction in Philippine schools.",
    correct_choice: "b",
    explanation: "B is a linguistically documented fact — the Philippines is one of the world's most linguistically diverse nations with over 180 languages. A, C, and D express subjective judgments.",
    difficulty: 1,
  },
  {
    question_text: "Read the following passage: \"Mount Apo, located in Mindanao, is the highest peak in the Philippines at 2,954 meters above sea level. Climbing Mount Apo is undoubtedly the most rewarding outdoor experience any Filipino can have. The mountain is home to several endemic species, including the Philippine Eagle. Every Filipino should climb Mount Apo at least once.\"\n\nWhich statement from the passage is an OPINION?",
    choice_a: "Mount Apo is located in Mindanao.",
    choice_b: "Mount Apo stands 2,954 meters above sea level.",
    choice_c: "Climbing Mount Apo is the most rewarding outdoor experience any Filipino can have.",
    choice_d: "The mountain is home to endemic species including the Philippine Eagle.",
    correct_choice: "c",
    explanation: "'Undoubtedly the most rewarding' is a subjective superlative — people have different outdoor experiences. A, B, and D are verifiable factual claims.",
    difficulty: 2,
  },
  {
    question_text: "Which of the following is a FACT?",
    choice_a: "The Philippine government handles typhoon disasters better than any other country.",
    choice_b: "Typhoon Yolanda (Haiyan) is the strongest tropical cyclone ever recorded at landfall.",
    choice_c: "Filipinos are naturally resilient and do not need international assistance after disasters.",
    choice_d: "International organizations should always respond faster to Philippine disasters.",
    correct_choice: "b",
    explanation: "B is a meteorological record — Haiyan holds the record for the highest sustained wind speeds at landfall. A, C, and D all contain subjective or prescriptive claims.",
    difficulty: 2,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "The Philippines ranked among the top countries in global surveys of social media usage.",
    choice_b: "The K-12 curriculum was implemented beginning in 2012.",
    choice_c: "The K-12 program is the best education reform ever introduced in the Philippines.",
    choice_d: "Mother tongue-based instruction begins in kindergarten under the K-12 system.",
    correct_choice: "c",
    explanation: "'Best reform ever' is a superlative judgment reflecting a personal evaluation. A, B, and D are verifiable educational and statistical facts.",
    difficulty: 1,
  },
  {
    question_text: "Read the following passage: \"Jeepneys have been a part of Philippine street life since the late 1940s. They are undoubtedly the most colorful and creative form of transportation in the world. Each jeepney is uniquely decorated, making them moving works of art. The government's plan to phase them out is a tragic mistake.\"\n\nWhich sentence is a FACT?",
    choice_a: "\"They are undoubtedly the most colorful and creative form of transportation in the world.\"",
    choice_b: "\"Jeepneys have been a part of Philippine street life since the late 1940s.\"",
    choice_c: "\"The government's plan to phase them out is a tragic mistake.\"",
    choice_d: "\"Each jeepney is uniquely decorated, making them moving works of art.\"",
    correct_choice: "b",
    explanation: "B is historically verifiable — jeepneys emerged in the post-WWII late 1940s. A and D contain subjective evaluations ('most colorful,' 'works of art'). C is a value judgment.",
    difficulty: 2,
  },
  {
    question_text: "Which of the following is an OPINION?",
    choice_a: "The Philippines exports significant quantities of coconut products annually.",
    choice_b: "The Philippine coconut industry employs approximately 3.5 million farmers.",
    choice_c: "Coconut water is healthier than any commercially produced sports drink.",
    choice_d: "Coconut oil is derived from the dried meat of the coconut.",
    correct_choice: "c",
    explanation: "'Healthier than any' is a comparative claim that requires scientific evidence and is often disputed. A, B, and D are verifiable factual statements.",
    difficulty: 2,
  },
  {
    question_text: "Read the two statements:\nI. 'The average surface temperature of Earth has risen by about 1.1°C since the pre-industrial era.'\nII. 'Developed countries are entirely to blame for climate change and should pay for all damages.'\n\nWhich best describes these statements?",
    choice_a: "Both are facts.",
    choice_b: "Both are opinions.",
    choice_c: "Statement I is a fact; Statement II is an opinion.",
    choice_d: "Statement I is an opinion; Statement II is a fact.",
    correct_choice: "c",
    explanation: "Statement I is a scientific measurement documented by climate agencies — verifiable. Statement II contains 'entirely to blame' and 'should pay for all' — moral and political value judgments that are opinions.",
    difficulty: 2,
  },
];

// ── READING MATERIALS (15) ────────────────────────────────────────────────────

const READING_MATERIALS: Q[] = [
  {
    question_text: "ANNOUNCEMENT\nSan Jose National High School will hold its Annual Recognition Day on June 15, 2026, at 8:00 AM in the school gymnasium. All graduating students are required to wear their complete school uniform with white shoes. Parents and guests are welcome to attend. Seats will be assigned on a first-come, first-served basis. The program is expected to conclude by 12:00 NN.\n\nBased on the announcement, at what time will the program end?",
    choice_a: "8:00 AM",
    choice_b: "10:00 AM",
    choice_c: "12:00 NN",
    choice_d: "3:00 PM",
    correct_choice: "c",
    explanation: "The announcement explicitly states 'The program is expected to conclude by 12:00 NN.'",
    difficulty: 1,
  },
  {
    question_text: "NOTICE: Wet Floor\nMaintenance is currently cleaning the hallway near Room 205. Kindly use the alternate route through the covered walkway behind the library. We apologize for the inconvenience. The area will be open again at 10:30 AM.\n\nWhat should people do while the hallway near Room 205 is being cleaned?",
    choice_a: "Wait outside Room 205 until 10:30 AM.",
    choice_b: "Enter through the main school gate.",
    choice_c: "Use the covered walkway behind the library.",
    choice_d: "Ask a security guard for an alternate route.",
    correct_choice: "c",
    explanation: "The notice specifically directs people to 'use the alternate route through the covered walkway behind the library.'",
    difficulty: 1,
  },
  {
    question_text: "BARANGAY ANNOUNCEMENT\nAttention: Barangay Maliwanag residents. A scheduled brownout on May 30, 2026 (Saturday) will run from 8:00 AM to 5:00 PM due to maintenance work on power lines. Residents are advised to store water in advance, as water pumps will be affected. For emergencies, call the barangay hotline at 09XX-XXX-XXXX.\n\nWhy should residents store water before the brownout?",
    choice_a: "The water pipes will be repaired during the same period.",
    choice_b: "Water pumps run on electricity and will not operate during the brownout.",
    choice_c: "The local water district will suspend service on that day.",
    choice_d: "The barangay water supply depends on a shared generator.",
    correct_choice: "b",
    explanation: "The announcement states 'water pumps will be affected' by the brownout. Since pumps require electricity, they will not work when power is out.",
    difficulty: 1,
  },
  {
    question_text: "JOB VACANCY — Customer Service Representative\nRequirements: College graduate in any course; excellent English communication skills; willing to work on shifting schedules; at least 1 year BPO experience preferred but not required.\nBenefits: Competitive salary, HMO upon regularization, 15 days vacation leave, 15 days sick leave.\nDeadline: May 31, 2026. Walk-in applications accepted Monday–Friday, 9:00 AM to 4:00 PM.\n\nWhich requirement is listed as preferred but NOT required?",
    choice_a: "College graduate in any course.",
    choice_b: "Excellent English communication skills.",
    choice_c: "At least 1 year of BPO experience.",
    choice_d: "Willingness to work on shifting schedules.",
    correct_choice: "c",
    explanation: "The posting states 'at least 1 year BPO experience preferred but not required.' The other items are listed as actual requirements.",
    difficulty: 1,
  },
  {
    question_text: "FREE MEDICAL MISSION\nDate: June 7, 2026 (Saturday) | Time: 7:00 AM – 3:00 PM\nVenue: Barangay Hall, Brgy. Masagana\nServices: General check-up, blood pressure monitoring, blood sugar testing, free medicines, dental extraction\nNote: Bring a valid ID. Children below 12 must be accompanied by a parent or guardian.\n\nWhich service is NOT offered at the medical mission?",
    choice_a: "General check-up",
    choice_b: "Blood sugar testing",
    choice_c: "Eye examination",
    choice_d: "Dental extraction",
    correct_choice: "c",
    explanation: "Eye examination is not listed among the services. The flyer mentions general check-up, blood pressure monitoring, blood sugar testing, free medicines, and dental extraction.",
    difficulty: 1,
  },
  {
    question_text: "MEDICINE LABEL — PARACETAMOL 500mg Tablets\nDirection for use: Adults and children 12 years and above: 1–2 tablets every 4–6 hours. Do not exceed 8 tablets in 24 hours.\nWarning: Do not use if allergic to paracetamol. Consult a doctor if fever persists for more than 3 days. Keep out of reach of children.\n\nWhat is the maximum number of tablets an adult may take in 24 hours?",
    choice_a: "4 tablets",
    choice_b: "6 tablets",
    choice_c: "8 tablets",
    choice_d: "12 tablets",
    correct_choice: "c",
    explanation: "The label clearly states: 'Do not exceed 8 tablets in 24 hours.'",
    difficulty: 1,
  },
  {
    question_text: "ADVERTISEMENT — SUMMER SALE at TechStore!\nGet up to 50% OFF on selected laptops, tablets, and accessories!\nSale runs May 28 – June 10, 2026.\n• Buy any laptop and get a FREE laptop bag (worth ₱1,500)\n• Free delivery for purchases above ₱15,000\n• 0% installment for 6 months with partner banks\nVisit any TechStore branch or shop at techstore.com.ph\n\nWhat free item will a customer receive when buying a laptop?",
    choice_a: "A free USB flash drive.",
    choice_b: "A free laptop bag worth ₱1,500.",
    choice_c: "A free six-month warranty.",
    choice_d: "A free software installation.",
    correct_choice: "b",
    explanation: "The advertisement states: 'Buy any laptop and get a FREE laptop bag (worth ₱1,500).'",
    difficulty: 1,
  },
  {
    question_text: "WARNING — CLEANING PRODUCT\nDANGER: Contains strong acid. Keep away from children. Avoid contact with skin and eyes. In case of contact, flush immediately with large amounts of water for at least 15 minutes and seek medical attention. Do not mix with bleach or other household chemicals. Use in well-ventilated areas only.\n\nWhat should you do FIRST if the product gets into your eyes?",
    choice_a: "Apply a neutralizing cream to the affected area.",
    choice_b: "Seek a doctor immediately before doing anything else.",
    choice_c: "Flush immediately with large amounts of water for at least 15 minutes.",
    choice_d: "Cover the eye with a clean cloth and lie down.",
    correct_choice: "c",
    explanation: "The label states: 'In case of contact, flush immediately with large amounts of water for at least 15 minutes and seek medical attention.' Flushing comes first.",
    difficulty: 1,
  },
  {
    question_text: "NUTRITION FACTS — Per serving (50g)\nCalories: 180 kcal | Total Fat: 7g | Saturated Fat: 3g | Sodium: 420mg | Total Carbohydrates: 24g | Sugars: 5g | Protein: 6g\nIngredients: Wheat flour, vegetable oil, salt, sugar, yeast\nContains: Wheat (gluten)\n\nHow much sodium does one serving of this product contain?",
    choice_a: "180mg",
    choice_b: "7g",
    choice_c: "24g",
    choice_d: "420mg",
    correct_choice: "d",
    explanation: "The nutrition label lists 'Sodium: 420mg' per serving.",
    difficulty: 1,
  },
  {
    question_text: "PROGRAM OF ACTIVITIES — Linggo ng Wika Celebration\n8:00 AM — Opening Program and National Anthem\n8:30 AM — Panatang Makabayan Recitation\n9:00 AM — Spoken Word Poetry Competition (Juniors)\n10:30 AM — Talumpati Competition (Seniors)\n12:00 NN — Lunch Break\n1:00 PM — Sayaw sa Bangko Competition\n3:00 PM — Awarding of Winners\n4:00 PM — Closing Remarks\n\nAt what time does the Sayaw sa Bangko competition begin?",
    choice_a: "10:30 AM",
    choice_b: "12:00 NN",
    choice_c: "1:00 PM",
    choice_d: "3:00 PM",
    correct_choice: "c",
    explanation: "The program lists '1:00 PM — Sayaw sa Bangko Competition.'",
    difficulty: 1,
  },
  {
    question_text: "BUS SCHEDULE — Cubao to Baguio\nDeparture Times: 8:00 AM | 10:00 AM | 12:00 NN | 3:00 PM | 9:00 PM (overnight)\nTravel Time: Approximately 6 hours\nFare: Regular — ₱600 | Student (with valid ID) — ₱480 | Senior Citizen/PWD — ₱420\nNote: Arrive at least 30 minutes before departure. Book online or at the terminal window.\n\nHow much is the discounted fare for senior citizens?",
    choice_a: "₱600",
    choice_b: "₱480",
    choice_c: "₱420",
    choice_d: "₱360",
    correct_choice: "c",
    explanation: "The schedule lists 'Senior Citizen/PWD — ₱420.'",
    difficulty: 1,
  },
  {
    question_text: "LIBRARY GUIDELINES\n1. Present your library card or school ID upon entry.\n2. Maintain silence at all times inside the library.\n3. Mobile phones must be set to silent mode.\n4. Food and drinks are strictly prohibited inside.\n5. Books must be returned within 3 days. A fine of ₱5.00 per day will be charged for overdue books.\n6. Reference books and periodicals may not be borrowed and must be used inside the library only.\n\nAccording to the guidelines, which type of material CANNOT be borrowed?",
    choice_a: "Fiction novels.",
    choice_b: "Textbooks on loan.",
    choice_c: "Reference books and periodicals.",
    choice_d: "Any book with an overdue fine.",
    correct_choice: "c",
    explanation: "Guideline 6 explicitly states: 'Reference books and periodicals may not be borrowed and must be used inside the library only.'",
    difficulty: 1,
  },
  {
    question_text: "PHILIPPINE POPULATION GROWTH\nYear | Population\n2000 | 76.5 million\n2010 | 92.3 million\n2020 | 109.0 million\n2025 (est.) | 116.8 million\n\nBetween which period did the Philippine population increase the most?",
    choice_a: "2000 to 2010",
    choice_b: "2010 to 2020",
    choice_c: "2020 to 2025",
    choice_d: "The increase was equal in each period.",
    correct_choice: "b",
    explanation: "2000–2010: +15.8M; 2010–2020: +16.7M; 2020–2025: +7.8M. The greatest single-period increase was from 2010 to 2020.",
    difficulty: 2,
  },
  {
    question_text: "SCHOLARSHIP APPLICATION REQUIREMENTS\n1. Certified True Copy of Grades (last 2 semesters) with a general average of at least 87\n2. Proof of family income (latest ITR or Certificate of Indigency)\n3. Two 2x2 ID photos with white background\n4. Original and photocopy of PSA Birth Certificate\n5. Recommendation letter from school principal or barangay captain\nDeadline: June 30, 2026 | Submit to: Student Affairs Office, Room 101\n\nWhat minimum grade average must applicants meet?",
    choice_a: "At least 80.",
    choice_b: "At least 85.",
    choice_c: "At least 87.",
    choice_d: "At least 90.",
    correct_choice: "c",
    explanation: "Requirement 1 states: 'Certified True Copy of Grades with a general average of at least 87.'",
    difficulty: 1,
  },
  {
    question_text: "SIGN AT A NATURE RESERVE\nWelcome to Tubbataha Reef Natural Park\n• Entry is restricted to authorized vessels only.\n• Fishing, collecting marine specimens, and anchoring on coral are strictly prohibited.\n• All visitors must be accompanied by a licensed guide.\n• Littering is punishable by a fine of ₱5,000.\n• Operating hours: 6:00 AM to 5:00 PM daily.\n\nWhich activity is explicitly PROHIBITED according to the sign?",
    choice_a: "Photography inside the park.",
    choice_b: "Swimming in designated areas.",
    choice_c: "Fishing within the park.",
    choice_d: "Hiking on marked trails.",
    correct_choice: "c",
    explanation: "The sign explicitly states: 'Fishing, collecting marine specimens, and anchoring on coral are strictly prohibited.' Fishing is directly listed.",
    difficulty: 1,
  },
];

// ── SEED HELPERS ──────────────────────────────────────────────────────────────

async function seedTopic(topicSlug: string, questions: Q[], topicId: string) {
  console.log(`\nSeeding ${questions.length} questions for topic: ${topicSlug} (${topicId})`);
  const rows = questions.map((q) => ({
    topic_id: topicId,
    question_text: q.question_text,
    choice_a: q.choice_a,
    choice_b: q.choice_b,
    choice_c: q.choice_c,
    choice_d: q.choice_d,
    correct_choice: q.correct_choice,
    explanation: q.explanation,
    difficulty: q.difficulty,
    status: "approved" as const,
    is_premium: true,
  }));

  const { error } = await supabase.from("questions").insert(rows);
  if (error) {
    console.error(`  ERROR for ${topicSlug}:`, error.message);
  } else {
    console.log(`  Inserted ${rows.length} questions.`);
  }
}

async function main() {
  console.log("Fetching reading-comprehension subtest…");
  const { data: subtest, error: stErr } = await supabase
    .from("subtests")
    .select("id, topics(id, slug)")
    .eq("slug", "reading-comprehension")
    .single();

  if (stErr || !subtest) throw new Error("Could not find reading-comprehension subtest: " + stErr?.message);

  const topics = subtest.topics as { id: string; slug: string }[];
  const topicMap = new Map(topics.map((t) => [t.slug, t.id]));
  console.log("Topics found:", [...topicMap.keys()]);

  const TOPIC_QUESTIONS: [string, Q[]][] = [
    ["main-idea", MAIN_IDEA],
    ["inference", INFERENCE],
    ["vocab-in-context", VOCAB_IN_CONTEXT],
    ["literary-analysis", LITERARY_ANALYSIS],
    ["context-clues", CONTEXT_CLUES],
    ["fact-vs-opinion", FACT_VS_OPINION],
    ["reading-materials", READING_MATERIALS],
  ];

  for (const [slug, questions] of TOPIC_QUESTIONS) {
    const topicId = topicMap.get(slug);
    if (!topicId) {
      console.error(`  Topic not found: ${slug}`);
      continue;
    }
    await seedTopic(slug, questions, topicId);
  }

  console.log("\nDone! 105 Reading Comprehension questions seeded.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
