/**
 * Seeds 100 original Science questions: 25 Biology, 25 Chemistry, 25 Physics, 25 Earth Science.
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-science-100.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

// ── BIOLOGY (25) ─────────────────────────────────────────────────────────────

const BIOLOGY: Q[] = [
  {
    question_text: "Which organelle is the primary site of ATP production through aerobic respiration?",
    choice_a: "Nucleus",
    choice_b: "Ribosome",
    choice_c: "Mitochondrion",
    choice_d: "Golgi apparatus",
    correct_choice: "c",
    explanation: "Mitochondria carry out the Krebs cycle and oxidative phosphorylation, producing the majority of a cell's ATP. They are often called the 'powerhouse of the cell.' The ribosome makes proteins; the nucleus stores DNA; the Golgi apparatus processes and packages proteins.",
    difficulty: 1,
  },
  {
    question_text: "During meiosis, the chromosome number in daughter cells is _____ compared to the parent cell.",
    choice_a: "Doubled",
    choice_b: "Maintained",
    choice_c: "Halved",
    choice_d: "Quadrupled",
    correct_choice: "c",
    explanation: "Meiosis reduces the chromosome number by half (2n → n), producing haploid gametes. When two gametes fuse during fertilization, the diploid number is restored. Mitosis, by contrast, maintains the chromosome number in daughter cells.",
    difficulty: 1,
  },
  {
    question_text: "Which nitrogenous base is found in RNA but NOT in DNA?",
    choice_a: "Adenine",
    choice_b: "Cytosine",
    choice_c: "Guanine",
    choice_d: "Uracil",
    correct_choice: "d",
    explanation: "RNA contains uracil instead of thymine. Uracil pairs with adenine just as thymine does in DNA. Adenine, cytosine, and guanine are present in both nucleic acids.",
    difficulty: 1,
  },
  {
    question_text: "The synthesis of mRNA from a DNA template is called:",
    choice_a: "Translation",
    choice_b: "Transcription",
    choice_c: "Replication",
    choice_d: "Transduction",
    correct_choice: "b",
    explanation: "Transcription is catalyzed by RNA polymerase, which reads the DNA template strand and synthesizes a complementary mRNA strand. Translation is the subsequent process where the ribosome reads mRNA to build a protein. Replication duplicates the entire DNA molecule.",
    difficulty: 1,
  },
  {
    question_text: "A testcross between a heterozygous tall plant (Tt) and a short plant (tt) produces offspring in what phenotypic ratio?",
    choice_a: "All tall",
    choice_b: "3 tall : 1 short",
    choice_c: "1 tall : 1 short",
    choice_d: "All short",
    correct_choice: "c",
    explanation: "Tt × tt produces Tt (tall) and tt (short) in equal numbers — a 1:1 ratio. This testcross is used to determine whether an individual showing the dominant phenotype is homozygous (TT) or heterozygous (Tt).",
    difficulty: 2,
  },
  {
    question_text: "Which blood type is considered the universal donor for red blood cell transfusions?",
    choice_a: "A",
    choice_b: "B",
    choice_c: "AB",
    choice_d: "O",
    correct_choice: "d",
    explanation: "Type O negative red blood cells lack A, B, and Rh antigens, making them compatible with all blood types. AB positive is the universal recipient. The ABO system is based on antigens on red blood cells and corresponding antibodies in plasma.",
    difficulty: 1,
  },
  {
    question_text: "The light-dependent reactions of photosynthesis occur in the:",
    choice_a: "Stroma",
    choice_b: "Thylakoid membrane",
    choice_c: "Cytoplasm",
    choice_d: "Outer chloroplast membrane",
    correct_choice: "b",
    explanation: "Light-dependent reactions occur in the thylakoid membranes, where chlorophyll absorbs light to split water, produce ATP, and generate NADPH. The Calvin cycle (light-independent reactions) occurs in the stroma, using these products to fix CO₂ into sugar.",
    difficulty: 2,
  },
  {
    question_text: "A relationship in which one organism benefits and the other is neither helped nor harmed is called:",
    choice_a: "Mutualism",
    choice_b: "Parasitism",
    choice_c: "Commensalism",
    choice_d: "Competition",
    correct_choice: "c",
    explanation: "Commensalism: one species benefits, the other is unaffected. Example: barnacles on a whale gain transportation; the whale is unharmed. Mutualism benefits both; parasitism harms one; competition is negative for both organisms.",
    difficulty: 1,
  },
  {
    question_text: "The basic structural and functional unit of the human kidney is the:",
    choice_a: "Glomerulus",
    choice_b: "Nephron",
    choice_c: "Villus",
    choice_d: "Alveolus",
    correct_choice: "b",
    explanation: "Each kidney contains about one million nephrons, responsible for filtering blood and producing urine. The glomerulus is a capillary cluster within the nephron. Villi are in the small intestine; alveoli are air sacs in the lungs.",
    difficulty: 1,
  },
  {
    question_text: "Which brain region initiates voluntary skeletal movement?",
    choice_a: "Medulla oblongata",
    choice_b: "Cerebellum",
    choice_c: "Motor cortex",
    choice_d: "Hypothalamus",
    correct_choice: "c",
    explanation: "The motor cortex (in the frontal lobe of the cerebrum) sends signals that initiate voluntary movement. The cerebellum coordinates balance and fine motor control. The medulla regulates heart rate and breathing. The hypothalamus maintains homeostasis and controls the endocrine system.",
    difficulty: 2,
  },
  {
    question_text: "The passive movement of water across a semi-permeable membrane toward higher solute concentration is called:",
    choice_a: "Diffusion",
    choice_b: "Active transport",
    choice_c: "Osmosis",
    choice_d: "Endocytosis",
    correct_choice: "c",
    explanation: "Osmosis is the passive movement of water from low solute concentration (high water potential) to high solute concentration (low water potential) through a semi-permeable membrane. It requires no energy, unlike active transport, which moves molecules against the concentration gradient.",
    difficulty: 1,
  },
  {
    question_text: "Which enzyme unwinds the DNA double helix at the replication fork?",
    choice_a: "DNA polymerase",
    choice_b: "Ligase",
    choice_c: "Primase",
    choice_d: "Helicase",
    correct_choice: "d",
    explanation: "Helicase breaks hydrogen bonds between base pairs and unwinds the double helix. DNA polymerase then synthesizes new strands (5'→3'), ligase joins Okazaki fragments on the lagging strand, and primase synthesizes short RNA primers to start synthesis.",
    difficulty: 2,
  },
  {
    question_text: "Natural selection acts directly on an organism's:",
    choice_a: "Genotype",
    choice_b: "Phenotype",
    choice_c: "Allele frequency",
    choice_d: "Mutation rate",
    correct_choice: "b",
    explanation: "Natural selection acts on observable phenotypes — individuals with phenotypes better suited to their environment survive and reproduce more. This indirectly shifts allele frequencies (genotype) in the population over generations, the mechanism underlying evolution.",
    difficulty: 2,
  },
  {
    question_text: "Binomial nomenclature assigns each species a scientific name consisting of its:",
    choice_a: "Kingdom and phylum",
    choice_b: "Family and genus",
    choice_c: "Genus and specific epithet",
    choice_d: "Order and class",
    correct_choice: "c",
    explanation: "Developed by Linnaeus, binomial nomenclature uses two Latin words: the genus (capitalized) and the specific epithet (lowercase). Example: Homo sapiens. Scientific names are italicized and universally recognized, avoiding language barriers in communication.",
    difficulty: 1,
  },
  {
    question_text: "Vaccination provides immunity by stimulating:",
    choice_a: "Innate immune responses only",
    choice_b: "Passive transfer of antibodies",
    choice_c: "Active acquired immunity through memory cells",
    choice_d: "Non-specific inflammatory responses",
    correct_choice: "c",
    explanation: "Vaccines expose the immune system to antigens (weakened/inactivated pathogens or their proteins), triggering antibody production and long-lived memory B and T cells. Future exposure to the real pathogen triggers a rapid secondary immune response. This is active acquired immunity.",
    difficulty: 2,
  },
  {
    question_text: "Glycolysis, the first stage of cellular respiration, occurs in the:",
    choice_a: "Mitochondrial matrix",
    choice_b: "Thylakoid membrane",
    choice_c: "Cytoplasm",
    choice_d: "Nucleus",
    correct_choice: "c",
    explanation: "Glycolysis occurs in the cytoplasm and does not require oxygen. One glucose (6C) is converted into two pyruvate (3C) molecules, producing a net gain of 2 ATP and 2 NADH. It is the common first step for both aerobic and anaerobic respiration.",
    difficulty: 1,
  },
  {
    question_text: "Which hormone lowers blood glucose by promoting uptake of glucose into cells?",
    choice_a: "Glucagon",
    choice_b: "Cortisol",
    choice_c: "Adrenaline",
    choice_d: "Insulin",
    correct_choice: "d",
    explanation: "Insulin, secreted by pancreatic beta cells, lowers blood glucose by promoting glucose uptake into cells and glycogen synthesis in the liver. Glucagon (from alpha cells) raises blood glucose by promoting glycogen breakdown. This antagonistic pair maintains blood glucose homeostasis.",
    difficulty: 1,
  },
  {
    question_text: "Which sequence correctly represents ecological organization from smallest to largest?",
    choice_a: "Organism → Community → Population → Ecosystem",
    choice_b: "Organism → Population → Community → Ecosystem",
    choice_c: "Population → Organism → Ecosystem → Community",
    choice_d: "Community → Population → Organism → Ecosystem",
    correct_choice: "b",
    explanation: "Correct hierarchy: Organism → Population (same species in an area) → Community (all populations in an area) → Ecosystem (community + abiotic environment) → Biosphere. Each level encompasses all lower levels.",
    difficulty: 1,
  },
  {
    question_text: "Crossing over during prophase I of meiosis results in:",
    choice_a: "Identical gametes",
    choice_b: "Reduced chromosome number",
    choice_c: "Genetic recombination",
    choice_d: "Non-disjunction",
    correct_choice: "c",
    explanation: "Crossing over (recombination) occurs when homologous chromosomes exchange segments at chiasmata during prophase I. This creates new combinations of alleles on chromosomes, generating genetic diversity in gametes. It is a major source of variation distinct from independent assortment.",
    difficulty: 2,
  },
  {
    question_text: "A cell placed in a hypertonic solution will:",
    choice_a: "Swell and lyse",
    choice_b: "Remain unchanged",
    choice_c: "Shrink due to water loss",
    choice_d: "Divide rapidly",
    correct_choice: "c",
    explanation: "In a hypertonic solution (higher solute concentration outside), water leaves the cell by osmosis, causing it to shrink (crenation in animal cells; plasmolysis in plant cells). In a hypotonic solution, water enters and the cell swells. In an isotonic solution, there is no net water movement.",
    difficulty: 1,
  },
  {
    question_text: "Archaea are classified separately from Bacteria because they:",
    choice_a: "Are multicellular organisms",
    choice_b: "Have membrane-bound nuclei",
    choice_c: "Have distinct biochemistry and are more closely related to eukaryotes",
    choice_d: "Cannot survive in extreme environments",
    correct_choice: "c",
    explanation: "Although archaea are structurally prokaryotic (no nucleus), their biochemistry — including ribosomal RNA sequences, membrane lipids, and RNA polymerase structure — is more similar to eukaryotes. This led to the three-domain classification: Bacteria, Archaea, and Eukarya.",
    difficulty: 3,
  },
  {
    question_text: "The primary role of decomposers in an ecosystem is to:",
    choice_a: "Convert sunlight into chemical energy",
    choice_b: "Consume primary producers",
    choice_c: "Recycle nutrients by breaking down dead organic matter",
    choice_d: "Transfer energy from prey to predators",
    correct_choice: "c",
    explanation: "Decomposers (bacteria and fungi) break down dead organisms and waste, releasing nutrients (nitrogen, phosphorus, carbon) back into the soil and atmosphere for producers to use. Without decomposers, nutrients would remain locked in dead organisms, halting nutrient cycling.",
    difficulty: 1,
  },
  {
    question_text: "Which structure is considered vestigial in humans, serving as evidence for evolution?",
    choice_a: "Femur",
    choice_b: "Cornea",
    choice_c: "Appendix",
    choice_d: "Diaphragm",
    correct_choice: "c",
    explanation: "The human appendix is a remnant of the larger cecum that herbivorous ancestors used to digest cellulose-rich plant material. Its reduced size and function today suggest it lost its original role through evolution — a classic example of a vestigial structure.",
    difficulty: 1,
  },
  {
    question_text: "Which domain contains organisms that are prokaryotic but distinct from Bacteria, often thriving in extreme environments?",
    choice_a: "Protista",
    choice_b: "Fungi",
    choice_c: "Archaea",
    choice_d: "Eukarya",
    correct_choice: "c",
    explanation: "Archaea are prokaryotes found in extreme environments (hot springs, salt lakes, deep-sea vents) as well as normal environments. They differ from bacteria in cell wall composition, membrane lipid structure, and ribosomal RNA. The three domains of life are Bacteria, Archaea, and Eukarya.",
    difficulty: 2,
  },
  {
    question_text: "Which component of blood carries oxygen to body tissues?",
    choice_a: "Plasma",
    choice_b: "Platelets",
    choice_c: "White blood cells",
    choice_d: "Red blood cells",
    correct_choice: "d",
    explanation: "Red blood cells (erythrocytes) contain hemoglobin, an iron-based protein that binds oxygen in the lungs and releases it in tissues. Plasma transports dissolved nutrients, hormones, and wastes. Platelets are involved in clotting. White blood cells defend against pathogens.",
    difficulty: 1,
  },
];

// ── CHEMISTRY (25) ───────────────────────────────────────────────────────────

const CHEMISTRY: Q[] = [
  {
    question_text: "Which quantum number determines the shape of an atomic orbital?",
    choice_a: "Principal quantum number (n)",
    choice_b: "Angular momentum quantum number (l)",
    choice_c: "Magnetic quantum number (ml)",
    choice_d: "Spin quantum number (ms)",
    correct_choice: "b",
    explanation: "The angular momentum quantum number (l) determines orbital shape: l=0 → s (spherical); l=1 → p (dumbbell); l=2 → d (cloverleaf). The principal quantum number n determines energy level/size. ml describes spatial orientation; ms describes electron spin direction.",
    difficulty: 2,
  },
  {
    question_text: "A reaction in which two ionic compounds exchange ions to form two new compounds is a:",
    choice_a: "Synthesis reaction",
    choice_b: "Single replacement reaction",
    choice_c: "Double replacement reaction",
    choice_d: "Decomposition reaction",
    correct_choice: "c",
    explanation: "In double replacement (metathesis): AB + CD → AD + CB. The ions swap partners. These reactions often produce a precipitate, water, or a gas, driving the reaction forward. Example: AgNO₃ + NaCl → AgCl↓ + NaNO₃.",
    difficulty: 1,
  },
  {
    question_text: "According to the Arrhenius definition, a base produces _____ ions when dissolved in water.",
    choice_a: "H⁺",
    choice_b: "H₃O⁺",
    choice_c: "OH⁻",
    choice_d: "O²⁻",
    correct_choice: "c",
    explanation: "Arrhenius defined bases as substances that produce OH⁻ (hydroxide) ions in aqueous solution (e.g., NaOH → Na⁺ + OH⁻). Arrhenius acids produce H⁺. The Arrhenius definition is limited to water; Brønsted-Lowry and Lewis definitions are broader.",
    difficulty: 1,
  },
  {
    question_text: "What is the oxidation state of sulfur in H₂SO₄?",
    choice_a: "+2",
    choice_b: "+4",
    choice_c: "+6",
    choice_d: "-2",
    correct_choice: "c",
    explanation: "In H₂SO₄: H is +1 (×2 = +2) and O is -2 (×4 = -8). For the compound to be neutral: +2 + S + (-8) = 0 → S = +6. Sulfur's oxidation state ranges from -2 (H₂S) to +6 (H₂SO₄).",
    difficulty: 2,
  },
  {
    question_text: "In an electrolytic cell, reduction occurs at the:",
    choice_a: "Anode",
    choice_b: "Cathode",
    choice_c: "Salt bridge",
    choice_d: "Electrode of higher mass",
    correct_choice: "b",
    explanation: "In all electrochemical cells (galvanic or electrolytic), reduction occurs at the cathode and oxidation at the anode. The mnemonic 'RED CAT, AN OX' helps remember: REDuction at CAThode; ANOde is OXidation. In electrolytic cells, the cathode is the negative electrode.",
    difficulty: 1,
  },
  {
    question_text: "An exothermic reaction is characterized by a:",
    choice_a: "Positive ΔH value",
    choice_b: "Negative ΔH value",
    choice_c: "Zero ΔH value",
    choice_d: "Positive ΔS value",
    correct_choice: "b",
    explanation: "Exothermic reactions release heat to the surroundings (ΔH < 0). Products are at lower energy than reactants. The energy released when new bonds form exceeds the energy absorbed breaking existing bonds. Examples: combustion, neutralization reactions.",
    difficulty: 1,
  },
  {
    question_text: "According to Le Chatelier's Principle, adding more reactant to a system at equilibrium causes the equilibrium to shift:",
    choice_a: "To the left",
    choice_b: "To the right",
    choice_c: "No shift occurs",
    choice_d: "The equilibrium constant changes",
    correct_choice: "b",
    explanation: "Adding reactant increases the forward reaction rate, shifting equilibrium to the right (toward products) to relieve the stress. The equilibrium constant Kc remains unchanged at constant temperature — only temperature changes alter Kc.",
    difficulty: 2,
  },
  {
    question_text: "Which factor does NOT directly affect the rate of a chemical reaction?",
    choice_a: "Concentration of reactants",
    choice_b: "Temperature",
    choice_c: "State of equilibrium",
    choice_d: "Surface area of solid reactants",
    correct_choice: "c",
    explanation: "The state of equilibrium is the result of balanced forward and reverse rates — it is not a factor that influences rate. Concentration, temperature, surface area, catalyst presence, and pressure (for gases) all directly affect how fast reactants are converted to products.",
    difficulty: 2,
  },
  {
    question_text: "An alpha (α) particle emitted during radioactive decay consists of:",
    choice_a: "1 proton and 1 neutron",
    choice_b: "2 protons and 2 neutrons",
    choice_c: "0 protons and 1 neutron",
    choice_d: "1 proton and 0 neutrons",
    correct_choice: "b",
    explanation: "An alpha particle is identical to a helium-4 nucleus: 2 protons + 2 neutrons. Alpha decay decreases atomic number by 2 and mass number by 4. Alpha particles have the lowest penetration power and can be stopped by a sheet of paper or a few centimeters of air.",
    difficulty: 1,
  },
  {
    question_text: "Which functional group is characteristic of carboxylic acids?",
    choice_a: "–OH",
    choice_b: "–CHO",
    choice_c: "–COOH",
    choice_d: "–NH₂",
    correct_choice: "c",
    explanation: "The carboxyl group (–COOH) is a carbonyl (C=O) bonded to a hydroxyl (–OH) on the same carbon. –OH alone = alcohol; –CHO = aldehyde; –NH₂ = amine. Carboxylic acids are weak acids that donate a proton from the –OH group.",
    difficulty: 1,
  },
  {
    question_text: "Structural isomers are compounds that have the same _____ but different _____ arrangements.",
    choice_a: "Structural formula; molecular masses",
    choice_b: "Molecular formula; structural",
    choice_c: "Molecular formula; molecular masses",
    choice_d: "Physical properties; chemical properties",
    correct_choice: "b",
    explanation: "Structural (constitutional) isomers share the same molecular formula but differ in connectivity of atoms. Example: n-butane and isobutane both have C₄H₁₀. They have different physical and chemical properties despite identical molecular formulas.",
    difficulty: 2,
  },
  {
    question_text: "Nylon is classified as a:",
    choice_a: "Addition polymer",
    choice_b: "Natural polymer",
    choice_c: "Condensation polymer",
    choice_d: "Polysaccharide",
    correct_choice: "c",
    explanation: "Nylon is a polyamide formed by condensation polymerization, where monomers (a diamine and a diacid) link by releasing water molecules. Addition polymers (polyethylene, PVC) form by monomers adding to each other without losing atoms. Polysaccharides are biological macromolecules.",
    difficulty: 2,
  },
  {
    question_text: "Freezing point depression is directly proportional to the _____ of the solute.",
    choice_a: "Molar mass",
    choice_b: "Molarity",
    choice_c: "Molality",
    choice_d: "Volume fraction",
    correct_choice: "c",
    explanation: "ΔTf = Kf × m, where Kf is the cryoscopic constant and m is molality (mol solute per kg solvent). Colligative properties depend on the number of solute particles, not their identity. Molality (not molarity) is used because it is temperature-independent.",
    difficulty: 2,
  },
  {
    question_text: "A buffer solution resists pH changes because it contains:",
    choice_a: "Only a strong acid",
    choice_b: "A weak acid and its conjugate base",
    choice_c: "Only a neutral salt",
    choice_d: "Equal volumes of two strong acids",
    correct_choice: "b",
    explanation: "A buffer consists of a weak acid (neutralizes added base) and its conjugate base (neutralizes added acid). Example: CH₃COOH/CH₃COO⁻. The Henderson-Hasselbalch equation describes buffer pH. Buffers are critical in biological systems (e.g., blood pH ~7.4).",
    difficulty: 2,
  },
  {
    question_text: "Which compound is insoluble in water at room temperature?",
    choice_a: "NaCl",
    choice_b: "KNO₃",
    choice_c: "AgCl",
    choice_d: "CuSO₄",
    correct_choice: "c",
    explanation: "AgCl (silver chloride) is insoluble (Ksp ≈ 1.8 × 10⁻¹⁰), forming a white precipitate in precipitation reactions. Solubility rules: most chlorides are soluble except those of Ag⁺, Pb²⁺, and Hg₂²⁺. NaCl, KNO₃, and CuSO₄ are all water-soluble.",
    difficulty: 2,
  },
  {
    question_text: "What is the pH of a solution with [H⁺] = 1 × 10⁻³ M?",
    choice_a: "3",
    choice_b: "4",
    choice_c: "11",
    choice_d: "0.001",
    correct_choice: "a",
    explanation: "pH = -log[H⁺] = -log(1 × 10⁻³) = 3. A pH of 3 is acidic (pH < 7). The corresponding [OH⁻] = 1 × 10⁻¹¹ M, and pOH = 11, since pH + pOH = 14 at 25°C.",
    difficulty: 1,
  },
  {
    question_text: "A positive standard cell potential (E°cell > 0) indicates a reaction that is:",
    choice_a: "Non-spontaneous",
    choice_b: "At equilibrium",
    choice_c: "Spontaneous",
    choice_d: "Endothermic",
    correct_choice: "c",
    explanation: "E°cell > 0 indicates a spontaneous redox reaction (ΔG° = -nFE°cell < 0 when E° is positive). Galvanic (voltaic) cells harness spontaneous reactions to generate electrical energy. Electrolytic cells drive non-spontaneous reactions using external electrical energy.",
    difficulty: 2,
  },
  {
    question_text: "Hess's Law states that the total enthalpy change of a reaction is:",
    choice_a: "Always negative (exothermic)",
    choice_b: "Dependent on the reaction pathway",
    choice_c: "Independent of the reaction pathway",
    choice_d: "Equal to the activation energy",
    correct_choice: "c",
    explanation: "Hess's Law states ΔH is path-independent because enthalpy is a state function — only initial and final states matter. This allows calculation of ΔH for reactions that cannot be measured directly by algebraically combining ΔH values of known reactions.",
    difficulty: 2,
  },
  {
    question_text: "The equilibrium constant expression Kc for A + 2B ⇌ C is:",
    choice_a: "[A][B]² / [C]",
    choice_b: "[C] / [A][B]",
    choice_c: "[C] / [A][B]²",
    choice_d: "[C]² / [A][B]",
    correct_choice: "c",
    explanation: "Kc = [products] / [reactants], with each concentration raised to its stoichiometric coefficient. For A + 2B ⇌ C: Kc = [C] / ([A][B]²). Pure solids and liquids are excluded. A large Kc means equilibrium favors products; small Kc favors reactants.",
    difficulty: 2,
  },
  {
    question_text: "Optical isomers (enantiomers) are compounds that are:",
    choice_a: "Identical in all properties",
    choice_b: "Non-superimposable mirror images of each other",
    choice_c: "Different in molecular formula only",
    choice_d: "Identical molecules in different conformations",
    correct_choice: "b",
    explanation: "Enantiomers are non-superimposable mirror images (like hands) arising from a chiral center (carbon with 4 different groups). They have identical physical properties except for rotating plane-polarized light in opposite directions. They can differ in biological activity — important in pharmaceuticals.",
    difficulty: 3,
  },
  {
    question_text: "The laboratory technique used to determine an unknown concentration using a known concentration solution is:",
    choice_a: "Dilution",
    choice_b: "Extraction",
    choice_c: "Titration",
    choice_d: "Filtration",
    correct_choice: "c",
    explanation: "In titration, a standard solution (titrant) of known concentration is added to an unknown solution until the equivalence point is reached (shown by an indicator's color change). The unknown concentration is calculated from M₁V₁ = M₂V₂ at the equivalence point.",
    difficulty: 2,
  },
  {
    question_text: "Water's unusually high surface tension and boiling point are primarily due to:",
    choice_a: "Covalent bonding within water molecules",
    choice_b: "London dispersion forces",
    choice_c: "Ionic character",
    choice_d: "Hydrogen bonding between water molecules",
    correct_choice: "d",
    explanation: "Hydrogen bonding (O–H···O) between water molecules creates strong intermolecular attractions, giving water its high surface tension, high specific heat, high boiling point (100°C vs. expected ~-80°C), and solid-less-dense-than-liquid property.",
    difficulty: 2,
  },
  {
    question_text: "A spontaneous process is thermodynamically characterized by:",
    choice_a: "Positive ΔG",
    choice_b: "Negative ΔG",
    choice_c: "Zero entropy change",
    choice_d: "Negative enthalpy only",
    correct_choice: "b",
    explanation: "Spontaneous processes have ΔG < 0 (Gibbs free energy decreases), where ΔG = ΔH - TΔS. A process can be spontaneous even if endothermic (ΔH > 0), provided TΔS is large enough. At equilibrium, ΔG = 0. Activation energy may still be required even for thermodynamically spontaneous reactions.",
    difficulty: 3,
  },
  {
    question_text: "Which type of reaction involves the joining of two molecules to form a larger molecule with the release of a small molecule (often water)?",
    choice_a: "Addition reaction",
    choice_b: "Substitution reaction",
    choice_c: "Condensation reaction",
    choice_d: "Elimination reaction",
    correct_choice: "c",
    explanation: "Condensation (dehydration synthesis) reactions join two molecules by releasing a small molecule, typically water. This is how biological polymers are formed: amino acids linked into proteins, monosaccharides into polysaccharides, and nucleotides into nucleic acids.",
    difficulty: 2,
  },
  {
    question_text: "Which intermolecular force is responsible for the temporary dipoles that form in nonpolar molecules?",
    choice_a: "Dipole-dipole interaction",
    choice_b: "Hydrogen bonding",
    choice_c: "London dispersion force",
    choice_d: "Ionic interaction",
    correct_choice: "c",
    explanation: "London dispersion forces (van der Waals forces) arise from instantaneous, temporary dipoles caused by fluctuating electron distribution in nonpolar molecules. They are present in all molecules but are the only intermolecular force in nonpolar molecules (e.g., noble gases, hydrocarbons). Larger molecules with more electrons have stronger London forces.",
    difficulty: 2,
  },
];

// ── PHYSICS (25) ─────────────────────────────────────────────────────────────

const PHYSICS: Q[] = [
  {
    question_text: "A car accelerates from rest to 20 m/s in 4 seconds. What is its acceleration?",
    choice_a: "4 m/s²",
    choice_b: "5 m/s²",
    choice_c: "80 m/s²",
    choice_d: "0.2 m/s²",
    correct_choice: "b",
    explanation: "a = Δv / Δt = (20 - 0) / 4 = 5 m/s². Acceleration is the rate of change of velocity. Starting from rest means v₀ = 0, simplifying the equation to a = v_f / t.",
    difficulty: 1,
  },
  {
    question_text: "Newton's Third Law states that:",
    choice_a: "Force equals mass times acceleration",
    choice_b: "An object at rest stays at rest unless acted upon by a net force",
    choice_c: "For every action force, there is an equal and opposite reaction force",
    choice_d: "Net force is proportional to the rate of change of momentum",
    correct_choice: "c",
    explanation: "Newton's Third Law: action-reaction pairs are equal in magnitude and opposite in direction, but act on different objects. Example: a rocket expels gas downward (action), gas pushes rocket upward (reaction). The first law describes inertia; the second relates force, mass, and acceleration.",
    difficulty: 1,
  },
  {
    question_text: "Which statement is TRUE about projectile motion (ignoring air resistance)?",
    choice_a: "Horizontal velocity increases due to gravity",
    choice_b: "Vertical acceleration is zero",
    choice_c: "Horizontal and vertical motions are independent",
    choice_d: "The path of the projectile is a straight line",
    correct_choice: "c",
    explanation: "In projectile motion, horizontal and vertical components are independent. Gravity provides constant downward acceleration (~9.8 m/s²) affecting only vertical motion, while horizontal velocity remains constant. The combined result is a parabolic path.",
    difficulty: 2,
  },
  {
    question_text: "To double the kinetic energy of an object, its speed must be multiplied by:",
    choice_a: "2",
    choice_b: "4",
    choice_c: "√2",
    choice_d: "0.5",
    correct_choice: "c",
    explanation: "KE = ½mv². If KE doubles: ½mv'² = 2(½mv²), so v'² = 2v², giving v' = v√2 ≈ 1.414v. Doubling speed quadruples KE; tripling speed increases KE ninefold — KE increases as the square of speed.",
    difficulty: 2,
  },
  {
    question_text: "The period of a simple pendulum depends primarily on:",
    choice_a: "Mass of the bob",
    choice_b: "Amplitude of the swing",
    choice_c: "Length of the pendulum",
    choice_d: "Material of the bob",
    correct_choice: "c",
    explanation: "T = 2π√(L/g), where L = length and g = gravitational acceleration. Period is independent of mass and amplitude (for small angles). A longer pendulum has a longer period. This principle was used in early clocks.",
    difficulty: 2,
  },
  {
    question_text: "The law of conservation of momentum states that in an isolated system, total momentum:",
    choice_a: "Increases over time",
    choice_b: "Decreases over time",
    choice_c: "Is always zero",
    choice_d: "Remains constant",
    correct_choice: "d",
    explanation: "In a closed system with no external forces, total momentum before = total momentum after any interaction. This applies to both elastic (KE conserved) and inelastic (KE not conserved) collisions. It is derived from Newton's Third Law.",
    difficulty: 1,
  },
  {
    question_text: "A wave has a frequency of 50 Hz and a wavelength of 2 m. Its speed is:",
    choice_a: "25 m/s",
    choice_b: "52 m/s",
    choice_c: "100 m/s",
    choice_d: "48 m/s",
    correct_choice: "c",
    explanation: "v = fλ = 50 Hz × 2 m = 100 m/s. This universal wave equation applies to all wave types: sound, light, water waves, etc. Frequency (Hz) = cycles per second; wavelength (m) = distance per cycle.",
    difficulty: 1,
  },
  {
    question_text: "The Doppler effect is observed when a source and observer are in _____ relative to each other.",
    choice_a: "The same medium",
    choice_b: "Relative motion",
    choice_c: "The same phase",
    choice_d: "Equal resonance",
    correct_choice: "b",
    explanation: "The Doppler effect is the change in perceived frequency when source and observer are in relative motion. Approaching → higher frequency (shorter wavelength); receding → lower frequency (longer wavelength). It applies to all waves including sound (pitch) and light (redshift/blueshift).",
    difficulty: 1,
  },
  {
    question_text: "Light bends when it passes from one medium to another because its _____ changes.",
    choice_a: "Frequency",
    choice_b: "Amplitude",
    choice_c: "Speed",
    choice_d: "Color",
    correct_choice: "c",
    explanation: "Refraction occurs because light changes speed when crossing the boundary between media with different refractive indices (n = c/v). The frequency remains constant; wavelength and speed change proportionally. The bending angle is described by Snell's Law: n₁sinθ₁ = n₂sinθ₂.",
    difficulty: 2,
  },
  {
    question_text: "A converging (convex) lens forms a real image only when the object is placed:",
    choice_a: "Inside the focal point",
    choice_b: "At the focal point",
    choice_c: "Beyond the focal point",
    choice_d: "At the lens surface",
    correct_choice: "c",
    explanation: "Objects beyond the focal point produce real, inverted images on the opposite side of the lens. Objects inside the focal point produce virtual, upright, magnified images (magnifying glass). At the focal point, parallel rays exit and no image is formed.",
    difficulty: 2,
  },
  {
    question_text: "According to Coulomb's Law, two positive charges placed near each other will:",
    choice_a: "Attract each other",
    choice_b: "Repel each other",
    choice_c: "Experience no electrostatic force",
    choice_d: "Attract briefly then repel",
    correct_choice: "b",
    explanation: "Like charges repel; unlike charges attract. Coulomb's Law: F = kq₁q₂/r². The force is directly proportional to the product of charges and inversely proportional to the square of the distance between them. This is the electrostatic analogue of Newton's Law of Gravitation.",
    difficulty: 1,
  },
  {
    question_text: "In a series circuit with three resistors, the total resistance equals:",
    choice_a: "The smallest resistor value",
    choice_b: "The largest resistor value",
    choice_c: "The sum of all three resistances",
    choice_d: "The product of all three resistances",
    correct_choice: "c",
    explanation: "In series: R_total = R₁ + R₂ + R₃. Current is equal through all components; voltage divides across them. In parallel circuits, total resistance is less than the smallest individual resistance. Adding resistors in series always increases total resistance.",
    difficulty: 1,
  },
  {
    question_text: "Ohm's Law states that the voltage across a conductor is:",
    choice_a: "V = I + R",
    choice_b: "V = I / R",
    choice_c: "V = IR",
    choice_d: "V = I² R",
    correct_choice: "c",
    explanation: "Ohm's Law: V = IR. Voltage (V) equals current (I) multiplied by resistance (R). Rearrangements: I = V/R and R = V/I. Note: P = I²R is power, not Ohm's Law. Ohm's Law applies to ohmic conductors where resistance is constant.",
    difficulty: 1,
  },
  {
    question_text: "Magnetic fields are produced by:",
    choice_a: "Static electric charges",
    choice_b: "Moving electric charges",
    choice_c: "Gravitational fields",
    choice_d: "Temperature differences",
    correct_choice: "b",
    explanation: "Moving electric charges (current) produce magnetic fields — the fundamental link between electricity and magnetism. This principle underlies electromagnets, motors, and generators. Static charges produce only electric fields. Permanent magnets have magnetic fields due to aligned electron spins (a form of moving charge).",
    difficulty: 1,
  },
  {
    question_text: "Faraday's Law of Electromagnetic Induction states that induced EMF is proportional to the rate of change of:",
    choice_a: "Electric charge",
    choice_b: "Voltage",
    choice_c: "Magnetic flux",
    choice_d: "Resistance",
    correct_choice: "c",
    explanation: "Faraday's Law: ε = -dΦ/dt. Induced EMF equals the negative rate of change of magnetic flux through a circuit. This is the principle behind electric generators (converting mechanical energy to electrical) and transformers. The negative sign reflects Lenz's Law (opposition to change).",
    difficulty: 2,
  },
  {
    question_text: "In an isothermal process for an ideal gas, which quantity remains constant?",
    choice_a: "Pressure",
    choice_b: "Volume",
    choice_c: "Temperature",
    choice_d: "Entropy",
    correct_choice: "c",
    explanation: "Isothermal means constant temperature (iso = same, thermal = heat). For an ideal gas: PV = nRT = constant at fixed T, meaning Boyle's Law applies (P₁V₁ = P₂V₂). Internal energy (ΔU = 0) is also constant since internal energy of an ideal gas depends only on temperature.",
    difficulty: 2,
  },
  {
    question_text: "Which method of heat transfer does NOT require a material medium?",
    choice_a: "Conduction",
    choice_b: "Convection",
    choice_c: "Radiation",
    choice_d: "Both conduction and convection",
    correct_choice: "c",
    explanation: "Radiation transfers heat via electromagnetic waves (primarily infrared) and can travel through a vacuum. This is how the Sun's energy reaches Earth. Conduction requires direct molecular contact; convection requires a fluid medium (liquid or gas) for circulation.",
    difficulty: 1,
  },
  {
    question_text: "Pascal's Principle states that pressure applied to an enclosed fluid is transmitted:",
    choice_a: "Only downward",
    choice_b: "Only upward",
    choice_c: "Equally in all directions",
    choice_d: "Along the direction of applied force only",
    correct_choice: "c",
    explanation: "Pascal's Principle: pressure applied to an enclosed, incompressible fluid is transmitted equally in all directions throughout the fluid. This is the basis for hydraulic systems (car brakes, hydraulic lifts), where a small force applied over a small area produces a large force over a large area.",
    difficulty: 1,
  },
  {
    question_text: "Archimedes' Principle states that the buoyant force on a submerged object equals:",
    choice_a: "The weight of the object",
    choice_b: "The weight of fluid displaced by the object",
    choice_c: "The mass of the fluid",
    choice_d: "The pressure at the bottom of the container",
    correct_choice: "b",
    explanation: "Archimedes' Principle: buoyant force = weight of fluid displaced. An object floats if its average density is less than the fluid's (buoyant force ≥ object's weight). This explains why steel ships float: their hollow shape displaces enough water to create a large buoyant force.",
    difficulty: 1,
  },
  {
    question_text: "Mechanical advantage (MA) is defined as:",
    choice_a: "Input force minus output force",
    choice_b: "Input distance divided by output distance",
    choice_c: "Output force divided by input force",
    choice_d: "Input force multiplied by output distance",
    correct_choice: "c",
    explanation: "MA = F_output / F_input. If MA > 1, the machine multiplies force (trade-off: input distance > output distance). Simple machines (levers, pulleys, inclined planes) all have a mechanical advantage. Ideal MA ignores friction; actual MA is always somewhat less.",
    difficulty: 1,
  },
  {
    question_text: "A 10 kg object is lifted 5 m in 10 seconds. The power expended is: (use g = 10 m/s²)",
    choice_a: "5 W",
    choice_b: "50 W",
    choice_c: "500 W",
    choice_d: "5000 W",
    correct_choice: "b",
    explanation: "Work = mgh = 10 kg × 10 m/s² × 5 m = 500 J. Power = Work / time = 500 J / 10 s = 50 W. Power measures the rate of doing work. 1 watt = 1 joule per second. Horsepower is another unit: 1 hp ≈ 746 W.",
    difficulty: 1,
  },
  {
    question_text: "According to Newton's Law of Universal Gravitation, gravitational force is directly proportional to:",
    choice_a: "The square of the distance between objects",
    choice_b: "The product of the masses of both objects",
    choice_c: "The difference in masses of the objects",
    choice_d: "The sum of the volumes of both objects",
    correct_choice: "b",
    explanation: "F = Gm₁m₂/r². Force is directly proportional to the product of masses (m₁ × m₂) and inversely proportional to the square of the distance (r²). Doubling either mass doubles the force; doubling distance reduces force to one-fourth.",
    difficulty: 1,
  },
  {
    question_text: "The speed of light in a vacuum is approximately:",
    choice_a: "3 × 10⁶ m/s",
    choice_b: "3 × 10⁸ m/s",
    choice_c: "3 × 10¹⁰ m/s",
    choice_d: "3 × 10⁵ m/s",
    correct_choice: "b",
    explanation: "The speed of light in vacuum (c) ≈ 3 × 10⁸ m/s (exactly 299,792,458 m/s). It is a universal constant and the cosmic speed limit per Einstein's Special Relativity. Light slows when passing through a medium (glass, water), with the ratio described by the refractive index.",
    difficulty: 1,
  },
  {
    question_text: "The photoelectric effect demonstrates that light behaves as:",
    choice_a: "Only a wave",
    choice_b: "Only a particle",
    choice_c: "Both a wave and a particle (wave-particle duality)",
    choice_d: "A stream of electrons",
    correct_choice: "c",
    explanation: "Einstein (1905) explained the photoelectric effect by treating light as discrete photons (particles) with energy E = hf. Yet light also shows wave properties (interference, diffraction). This wave-particle duality is fundamental to quantum mechanics and applies to matter as well (de Broglie).",
    difficulty: 2,
  },
  {
    question_text: "When a sound source moves toward a stationary observer, the observer perceives the sound as having a:",
    choice_a: "Lower frequency and longer wavelength",
    choice_b: "Higher frequency and shorter wavelength",
    choice_c: "Same frequency but higher amplitude",
    choice_d: "Same frequency but lower amplitude",
    correct_choice: "b",
    explanation: "This is the Doppler effect for sound. As the source approaches, successive wave crests are compressed (shorter wavelength → higher frequency/pitch). As it recedes, crests spread out (longer wavelength → lower frequency). Ambulance sirens are a common example.",
    difficulty: 2,
  },
];

// ── EARTH SCIENCE (25) ───────────────────────────────────────────────────────

const EARTH_SCIENCE: Q[] = [
  {
    question_text: "Which rock type forms from the cooling and solidification of magma or lava?",
    choice_a: "Sedimentary",
    choice_b: "Metamorphic",
    choice_c: "Igneous",
    choice_d: "Alluvial",
    correct_choice: "c",
    explanation: "Igneous rocks crystallize from molten rock. Intrusive (plutonic) rocks like granite cool slowly underground, forming large crystals. Extrusive (volcanic) rocks like basalt cool rapidly at the surface, forming small crystals or glass. The word 'igneous' comes from Latin for 'fire.'",
    difficulty: 1,
  },
  {
    question_text: "The comprehensive theory that explains the movement of Earth's lithospheric plates, including earthquakes, volcanoes, and mountain formation, is called:",
    choice_a: "Continental Drift",
    choice_b: "Seafloor Spreading",
    choice_c: "Plate Tectonics",
    choice_d: "Isostasy",
    correct_choice: "c",
    explanation: "Plate tectonics integrates Wegener's continental drift (1912) and Hess's seafloor spreading (1960s) into a comprehensive theory. It explains why earthquakes and volcanoes cluster along plate boundaries, how mountains form at convergent boundaries, and why fossil/geological patterns match across continents.",
    difficulty: 1,
  },
  {
    question_text: "Earthquakes occur due to the sudden release of energy along:",
    choice_a: "Volcanic craters only",
    choice_b: "Fault lines",
    choice_c: "Changes in atmospheric pressure",
    choice_d: "Ocean floor sediment layers",
    correct_choice: "b",
    explanation: "Stress builds up along fault lines (fractures in rock) as tectonic plates move. When the stress exceeds the rock's strength, energy releases suddenly as seismic waves. The focus (hypocenter) is the underground point of rupture; the epicenter is directly above on the surface.",
    difficulty: 1,
  },
  {
    question_text: "Highly explosive volcanic eruptions are associated with magma that has:",
    choice_a: "Low silica and low viscosity",
    choice_b: "High silica and high viscosity",
    choice_c: "High iron and high temperature",
    choice_d: "Low gas content and slow flow",
    correct_choice: "b",
    explanation: "High-silica (rhyolitic) magma is very viscous, trapping gases that build up enormous pressure. When released, the result is an explosive eruption (e.g., Mt. Pinatubo, 1991 — Plinian type). Low-silica basaltic magma is fluid, allowing gentle effusive Hawaiian-type eruptions with lava flows.",
    difficulty: 2,
  },
  {
    question_text: "The breakdown of rocks in place, without transportation of material, is called:",
    choice_a: "Erosion",
    choice_b: "Deposition",
    choice_c: "Weathering",
    choice_d: "Metamorphism",
    correct_choice: "c",
    explanation: "Weathering breaks rocks down in place — physical weathering (freeze-thaw, abrasion) reduces rock size without changing composition; chemical weathering (oxidation, hydrolysis, carbonation) alters mineral composition. Erosion is the transport of weathered material by wind, water, or ice.",
    difficulty: 1,
  },
  {
    question_text: "Metamorphic rocks form when existing rocks are subjected to:",
    choice_a: "Compaction and cementation of sediments",
    choice_b: "Rapid cooling of lava",
    choice_c: "Intense heat and pressure below Earth's surface",
    choice_d: "Dissolution by groundwater",
    correct_choice: "c",
    explanation: "Metamorphism occurs when rocks are subjected to extreme heat and/or pressure without melting, causing mineral recrystallization and structural changes. Examples: limestone → marble; shale → slate; granite → gneiss. Regional metamorphism occurs at plate boundaries; contact metamorphism occurs near magma intrusions.",
    difficulty: 1,
  },
  {
    question_text: "The geologic time scale is divided primarily based on:",
    choice_a: "Changes in rock color and composition",
    choice_b: "Major shifts in the fossil record",
    choice_c: "Mountain-building events",
    choice_d: "Changes in global sea level",
    correct_choice: "b",
    explanation: "The geologic time scale uses major changes in the fossil record — particularly mass extinctions and the appearance of new life forms — to define eons, eras, periods, and epochs. The Cretaceous-Paleogene (K-Pg) boundary marks the dinosaur extinction ~66 million years ago.",
    difficulty: 2,
  },
  {
    question_text: "The outermost layer of Earth's atmosphere is the:",
    choice_a: "Troposphere",
    choice_b: "Stratosphere",
    choice_c: "Mesosphere",
    choice_d: "Exosphere",
    correct_choice: "d",
    explanation: "From the surface outward: Troposphere (weather; 0-12 km) → Stratosphere (ozone layer; 12-50 km) → Mesosphere (50-80 km) → Thermosphere (80-700 km) → Exosphere (outermost; gradually merges with space). Most weather occurs in the troposphere.",
    difficulty: 1,
  },
  {
    question_text: "In the Northern Hemisphere, winds around a low-pressure system rotate:",
    choice_a: "Clockwise",
    choice_b: "Counterclockwise",
    choice_c: "North to south",
    choice_d: "Outward from the center",
    correct_choice: "b",
    explanation: "The Coriolis effect (caused by Earth's rotation) deflects moving air to the right in the Northern Hemisphere. This makes winds around low-pressure systems (cyclones) rotate counterclockwise. In the Southern Hemisphere, rotation is clockwise. High-pressure systems rotate in the opposite direction.",
    difficulty: 2,
  },
  {
    question_text: "Which process is NOT part of the water (hydrological) cycle?",
    choice_a: "Evaporation",
    choice_b: "Condensation",
    choice_c: "Photosynthesis",
    choice_d: "Precipitation",
    correct_choice: "c",
    explanation: "The water cycle involves evaporation, transpiration, condensation, precipitation, infiltration, runoff, and groundwater flow — all physical processes involving water movement. Photosynthesis is a biological chemical process that uses water but is not a component of the hydrological cycle.",
    difficulty: 1,
  },
  {
    question_text: "Major ocean surface currents (gyres) are primarily driven by:",
    choice_a: "Differences in ocean floor depth",
    choice_b: "Global wind patterns and the Coriolis effect",
    choice_c: "Variations in ocean water color",
    choice_d: "The gravitational pull of the Moon",
    correct_choice: "b",
    explanation: "Surface ocean currents are driven by global wind belts (trade winds, westerlies) and shaped into circular gyres by the Coriolis effect. Deep ocean thermohaline circulation is driven by density differences from temperature and salinity. Ocean currents distribute heat globally, moderating climate.",
    difficulty: 2,
  },
  {
    question_text: "Most coastal areas experience how many high tides in approximately 24 hours?",
    choice_a: "One",
    choice_b: "Two",
    choice_c: "Four",
    choice_d: "Six",
    correct_choice: "b",
    explanation: "Most coastal locations experience two high tides and two low tides every ~24.8 hours (one lunar day). Tides are primarily caused by the Moon's gravitational pull creating a tidal bulge on the side facing the Moon and the opposite side. Spring tides (strongest) occur during new/full moons.",
    difficulty: 1,
  },
  {
    question_text: "Which planet is called the 'Red Planet' due to the iron oxide on its surface?",
    choice_a: "Venus",
    choice_b: "Jupiter",
    choice_c: "Mercury",
    choice_d: "Mars",
    correct_choice: "d",
    explanation: "Mars appears reddish because its surface is covered with iron oxide (rust). Mars has the solar system's largest volcano (Olympus Mons) and longest canyon (Valles Marineris). It has a thin CO₂ atmosphere and two small moons (Phobos and Deimos), and is a primary target for human exploration.",
    difficulty: 1,
  },
  {
    question_text: "A medium-mass star like our Sun is expected to end its life cycle as a:",
    choice_a: "Neutron star",
    choice_b: "Black hole",
    choice_c: "White dwarf",
    choice_d: "Pulsar",
    correct_choice: "c",
    explanation: "When the Sun exhausts its hydrogen fuel (~5 billion years), it will expand into a red giant, then shed its outer layers as a planetary nebula, leaving a white dwarf — a dense, slowly cooling stellar remnant. Only massive stars (>8 solar masses) end as neutron stars or black holes.",
    difficulty: 2,
  },
  {
    question_text: "A New Moon occurs when the Moon is positioned:",
    choice_a: "Opposite the Sun as seen from Earth",
    choice_b: "Between Earth and the Sun",
    choice_c: "At 90° from the Sun as seen from Earth",
    choice_d: "Behind Earth's shadow",
    correct_choice: "b",
    explanation: "During a New Moon, the Moon is between Earth and the Sun; the side facing Earth is unlit, making it invisible from Earth. A Full Moon occurs when Earth is between the Moon and Sun. Solar eclipses can only occur during a new moon when the Moon, Earth, and Sun are precisely aligned.",
    difficulty: 1,
  },
  {
    question_text: "Earth's seasons are caused by:",
    choice_a: "Variations in Earth's distance from the Sun",
    choice_b: "The tilt of Earth's rotational axis (23.5°) relative to its orbital plane",
    choice_c: "The Moon's gravitational influence on Earth",
    choice_d: "Variations in the Sun's energy output",
    correct_choice: "b",
    explanation: "Earth's 23.5° axial tilt causes seasons: when the Northern Hemisphere tilts toward the Sun, it receives more direct sunlight and longer days (summer). Earth is actually closest to the Sun in January (Northern Hemisphere winter), proving distance is not the primary cause of seasons.",
    difficulty: 1,
  },
  {
    question_text: "A solar eclipse occurs when:",
    choice_a: "Earth passes through the Moon's shadow",
    choice_b: "The Moon passes through Earth's shadow",
    choice_c: "The Moon moves between Earth and the Sun",
    choice_d: "Earth moves between the Moon and the Sun",
    correct_choice: "c",
    explanation: "A solar eclipse occurs when the Moon aligns between Earth and the Sun, blocking sunlight. A total solar eclipse is visible along a narrow path (umbra). A lunar eclipse occurs when Earth's shadow falls on the Moon (Earth between Moon and Sun). Solar eclipses only occur during new moons.",
    difficulty: 1,
  },
  {
    question_text: "The Mohs Hardness Scale measures a mineral's resistance to:",
    choice_a: "Heat",
    choice_b: "Chemical weathering",
    choice_c: "Scratching",
    choice_d: "Fracturing under pressure",
    correct_choice: "c",
    explanation: "The Mohs scale (1-10) measures scratch resistance. A mineral can scratch any mineral with a lower Mohs number. Talc (1) is the softest; diamond (10) is the hardest. Hardness is one of the key physical properties used to identify minerals in the field.",
    difficulty: 1,
  },
  {
    question_text: "Which factor is NOT directly involved in soil formation (pedogenesis)?",
    choice_a: "Parent rock material",
    choice_b: "Climate",
    choice_c: "Living organisms",
    choice_d: "Ocean currents",
    correct_choice: "d",
    explanation: "The five soil-forming factors (Jenny, 1941): parent material, climate, organisms, topography, and time. Ocean currents influence regional climate, which in turn affects weathering, but ocean currents are not a direct soil-forming factor. Climate is the most influential factor in most soil types.",
    difficulty: 2,
  },
  {
    question_text: "Glaciers form when:",
    choice_a: "Lakes freeze over in winter",
    choice_b: "Snow accumulates and compacts into dense ice over many years",
    choice_c: "Seawater freezes at the poles",
    choice_d: "Underground water freezes in permafrost",
    correct_choice: "b",
    explanation: "Glaciers form where annual snowfall exceeds melting. Snow compresses under its own weight into firn (granular ice) and eventually into glacial ice. As ice thickens, it begins to flow downhill. Glaciers shape landscapes through erosion (U-shaped valleys, fjords) and deposition (moraines).",
    difficulty: 1,
  },
  {
    question_text: "The ozone layer, which shields Earth from harmful UV radiation, is located in the:",
    choice_a: "Troposphere",
    choice_b: "Stratosphere",
    choice_c: "Mesosphere",
    choice_d: "Thermosphere",
    correct_choice: "b",
    explanation: "The ozone layer (15-35 km altitude) is in the stratosphere. Ozone (O₃) absorbs most UV-B and UV-C radiation. Depletion by CFCs (chlorofluorocarbons) creates the 'ozone hole' over Antarctica, increasing UV radiation reaching Earth's surface and raising skin cancer risk.",
    difficulty: 1,
  },
  {
    question_text: "Which evidence did Alfred Wegener NOT use to support his continental drift hypothesis?",
    choice_a: "Matching coastlines of South America and Africa",
    choice_b: "Identical fossils found on now-separated continents",
    choice_c: "Matching rock formations across continents",
    choice_d: "Direct observation of seafloor spreading",
    correct_choice: "d",
    explanation: "Wegener (1912) used: matching coastlines, similar fossils (Mesosaurus, Glossopteris), and matching rock formations. Seafloor spreading was discovered in the 1960s by Harry Hess using echo-sounding — decades after Wegener's hypothesis. It provided the mechanism that transformed drift into the plate tectonics theory.",
    difficulty: 2,
  },
  {
    question_text: "New oceanic crust is created at which type of plate boundary?",
    choice_a: "Convergent boundary",
    choice_b: "Transform boundary",
    choice_c: "Divergent boundary",
    choice_d: "Subduction zone",
    correct_choice: "c",
    explanation: "At divergent boundaries, plates move apart and magma rises to fill the gap, solidifying into new basaltic oceanic crust — seafloor spreading. The Mid-Atlantic Ridge is a major example. At convergent boundaries, older oceanic crust subducts into the mantle and is destroyed.",
    difficulty: 1,
  },
  {
    question_text: "Fossils are most commonly found in which rock type?",
    choice_a: "Igneous",
    choice_b: "Metamorphic",
    choice_c: "Sedimentary",
    choice_d: "Volcanic glass",
    correct_choice: "c",
    explanation: "Fossils form when organisms are rapidly buried by sediment (sand, mud, silt), which gradually compacts into sedimentary rock, preserving hard parts or leaving impressions. Igneous and metamorphic rocks form under extreme heat and/or pressure that destroys organic material, making fossils extremely rare.",
    difficulty: 1,
  },
  {
    question_text: "El Niño refers to the periodic:",
    choice_a: "Cooling of Pacific Ocean surface temperatures",
    choice_b: "Warming of central and eastern Pacific Ocean surface temperatures",
    choice_c: "Volcanic eruption pattern in the Pacific Ring of Fire",
    choice_d: "Seasonal reversal of monsoon winds over the Indian Ocean",
    correct_choice: "b",
    explanation: "El Niño is the periodic warming of central/eastern Pacific surface waters, disrupting normal trade winds and ocean circulation. Effects include droughts in Southeast Asia/Australia and increased rainfall in South America. La Niña is the opposite cooling phase. Together they constitute ENSO (El Niño-Southern Oscillation).",
    difficulty: 2,
  },
];

// ── SEED FUNCTION ─────────────────────────────────────────────────────────────

async function seedTopic(slug: string, questions: Q[]) {
  const { data: topic, error: topicErr } = await supabase
    .from("topics")
    .select("id")
    .eq("slug", slug)
    .single();

  if (topicErr || !topic) {
    console.error(`Topic not found: ${slug}`, topicErr?.message);
    return;
  }

  const rows = questions.map((q) => ({
    topic_id: topic.id,
    question_text: q.question_text,
    choice_a: q.choice_a,
    choice_b: q.choice_b,
    choice_c: q.choice_c,
    choice_d: q.choice_d,
    correct_choice: q.correct_choice,
    explanation: q.explanation,
    difficulty: q.difficulty,
    status: "approved" as const,
    is_premium: true,
  }));

  const { error } = await supabase.from("questions").insert(rows);
  if (error) {
    console.error(`Error inserting ${slug} questions:`, error.message);
  } else {
    console.log(`✓ ${slug}: inserted ${rows.length} questions`);
  }
}

async function main() {
  console.log("Seeding 100 Science questions…\n");
  await seedTopic("biology", BIOLOGY);
  await seedTopic("chemistry", CHEMISTRY);
  await seedTopic("physics", PHYSICS);
  await seedTopic("earth-science", EARTH_SCIENCE);
  console.log("\nDone.");
}

main().catch(console.error);
