/**
 * Seeds 100 new Reasoning questions (20 per topic).
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-reasoning-100.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

// ─────────────────────────────────────────────
// 1. LOGIC & CRITICAL THINKING
// ─────────────────────────────────────────────
const LOGIC: Q[] = [
  {
    question_text: "All squares are rectangles. All rectangles are parallelograms. Therefore:",
    choice_a: "All parallelograms are squares.",
    choice_b: "All squares are parallelograms.",
    choice_c: "Some parallelograms are not rectangles.",
    choice_d: "No squares are parallelograms.",
    correct_choice: "b",
    explanation: "If A→B and B→C, then A→C. Since all squares are rectangles and all rectangles are parallelograms, all squares are parallelograms.",
    difficulty: 1,
  },
  {
    question_text: "No cats are reptiles. Some pets are cats. Which conclusion is valid?",
    choice_a: "Some pets are reptiles.",
    choice_b: "All pets are cats.",
    choice_c: "Some pets are not reptiles.",
    choice_d: "No pets are reptiles.",
    correct_choice: "c",
    explanation: "Since some pets are cats, and no cats are reptiles, those cat-pets are definitely not reptiles. So some pets are not reptiles.",
    difficulty: 2,
  },
  {
    question_text: "If a student studies hard, they will pass the exam. Maria did not pass the exam. What can we conclude?",
    choice_a: "Maria studied hard.",
    choice_b: "Maria did not study hard.",
    choice_c: "Maria may or may not have studied hard.",
    choice_d: "Studying hard does not help.",
    correct_choice: "b",
    explanation: "This is modus tollens: If P then Q; not Q; therefore not P. If studying hard guarantees passing, and Maria did not pass, she could not have studied hard.",
    difficulty: 2,
  },
  {
    question_text: "All teachers are graduates. Some graduates are licensed professionals. Which must be true?",
    choice_a: "All teachers are licensed professionals.",
    choice_b: "Some teachers are licensed professionals.",
    choice_c: "Some teachers may or may not be licensed professionals.",
    choice_d: "No teachers are licensed professionals.",
    correct_choice: "c",
    explanation: "All teachers are graduates, and some graduates are licensed professionals, but we cannot determine whether the licensed graduates overlap with the teachers. So it is possible but not certain.",
    difficulty: 3,
  },
  {
    question_text: "Either the power is out or the generator is broken. The power is not out. Therefore:",
    choice_a: "The generator is broken.",
    choice_b: "The generator is not broken.",
    choice_c: "Both the power is out and the generator is broken.",
    choice_d: "Neither condition is true.",
    correct_choice: "a",
    explanation: "Disjunctive syllogism: Either A or B; not A; therefore B. Since the power is not out, the generator must be broken.",
    difficulty: 1,
  },
  {
    question_text: "A person argues: 'You should not trust his opinion on health because he is not a doctor.' This is an example of:",
    choice_a: "Ad hominem fallacy",
    choice_b: "Straw man fallacy",
    choice_c: "Appeal to authority fallacy",
    choice_d: "False dilemma fallacy",
    correct_choice: "a",
    explanation: "Attacking the person's credentials rather than their argument is an ad hominem fallacy. The argument's merit should be evaluated independently of who made it.",
    difficulty: 2,
  },
  {
    question_text: "If it is a holiday, the office is closed. The office is closed today. Which is the best conclusion?",
    choice_a: "Today is definitely a holiday.",
    choice_b: "Today is definitely not a holiday.",
    choice_c: "Today might or might not be a holiday.",
    choice_d: "The office is always closed.",
    correct_choice: "c",
    explanation: "Affirming the consequent is a logical fallacy. The office could be closed for other reasons besides a holiday. We cannot conclude it is definitely a holiday.",
    difficulty: 2,
  },
  {
    question_text: "All mammals are warm-blooded. Whales are mammals. Bats are mammals. Which of the following must be true?",
    choice_a: "All warm-blooded animals are mammals.",
    choice_b: "Bats and whales are warm-blooded.",
    choice_c: "Bats and whales are the only mammals.",
    choice_d: "Warm-blooded animals cannot fly.",
    correct_choice: "b",
    explanation: "Since all mammals are warm-blooded, and both bats and whales are mammals, both must be warm-blooded.",
    difficulty: 1,
  },
  {
    question_text: "Statement: 'We should ban all fast food because one student got sick after eating a burger.' What logical flaw is present?",
    choice_a: "Hasty generalization",
    choice_b: "Circular reasoning",
    choice_c: "Appeal to emotion",
    choice_d: "Slippery slope",
    correct_choice: "a",
    explanation: "Drawing a broad conclusion (ban all fast food) from a single or few cases (one student getting sick) is a hasty generalization.",
    difficulty: 2,
  },
  {
    question_text: "Some politicians are honest. All honest people are trustworthy. Therefore:",
    choice_a: "All politicians are trustworthy.",
    choice_b: "Some politicians are trustworthy.",
    choice_c: "No politicians are trustworthy.",
    choice_d: "All trustworthy people are politicians.",
    correct_choice: "b",
    explanation: "Some politicians are honest. Since all honest people are trustworthy, those honest politicians are also trustworthy. So some politicians are trustworthy.",
    difficulty: 2,
  },
  {
    question_text: "If P implies Q, and Q implies R, which of the following is a valid conclusion?",
    choice_a: "R implies P.",
    choice_b: "P implies R.",
    choice_c: "Q implies P.",
    choice_d: "Not P implies not R.",
    correct_choice: "b",
    explanation: "Hypothetical syllogism: If P→Q and Q→R, then P→R. This is the transitive property of logical implication.",
    difficulty: 2,
  },
  {
    question_text: "Ana says: 'My plan must be correct because no one has proven it wrong.' This is an example of:",
    choice_a: "Appeal to ignorance",
    choice_b: "Appeal to authority",
    choice_c: "False cause",
    choice_d: "Begging the question",
    correct_choice: "a",
    explanation: "Arguing that something is true because it has not been proven false is an appeal to ignorance (argumentum ad ignorantiam).",
    difficulty: 2,
  },
  {
    question_text: "All fruits have seeds. Mangoes have seeds. Therefore mangoes are fruits. Is this reasoning valid?",
    choice_a: "Yes, because mangoes satisfy the condition.",
    choice_b: "No, because having seeds does not make something a fruit.",
    choice_c: "Yes, because the conclusion follows the premises.",
    choice_d: "No, because not all fruits are mangoes.",
    correct_choice: "b",
    explanation: "This is affirming the consequent: All fruits have seeds does not mean everything with seeds is a fruit. The reasoning is invalid.",
    difficulty: 3,
  },
  {
    question_text: "No students who cheat will pass the final exam. Ben passed the final exam. Therefore:",
    choice_a: "Ben cheated.",
    choice_b: "Ben did not cheat.",
    choice_c: "Ben may or may not have cheated.",
    choice_d: "Ben will not pass future exams.",
    correct_choice: "b",
    explanation: "Contrapositive reasoning: If cheat → not pass, then pass → not cheat. Since Ben passed, he did not cheat.",
    difficulty: 2,
  },
  {
    question_text: "Some athletes are vegetarians. All vegetarians avoid red meat. Which conclusion follows?",
    choice_a: "All athletes avoid red meat.",
    choice_b: "No athletes eat red meat.",
    choice_c: "Some athletes avoid red meat.",
    choice_d: "Some vegetarians are not athletes.",
    correct_choice: "c",
    explanation: "Some athletes are vegetarians. Since all vegetarians avoid red meat, those vegetarian-athletes also avoid red meat. So some athletes avoid red meat.",
    difficulty: 2,
  },
  {
    question_text: "A person says: 'You're either with us or against us.' This statement is an example of:",
    choice_a: "Straw man fallacy",
    choice_b: "False dilemma",
    choice_c: "Ad hominem",
    choice_d: "Slippery slope",
    correct_choice: "b",
    explanation: "Presenting only two options when more exist is a false dilemma (false dichotomy). There could be neutral or other positions.",
    difficulty: 1,
  },
  {
    question_text: "All prime numbers greater than 2 are odd. 7 is a prime number greater than 2. Therefore:",
    choice_a: "7 is even.",
    choice_b: "7 is odd.",
    choice_c: "7 may be odd or even.",
    choice_d: "All odd numbers are prime.",
    correct_choice: "b",
    explanation: "Direct application of a universal rule: all primes > 2 are odd, and 7 is such a prime, so 7 is odd.",
    difficulty: 1,
  },
  {
    question_text: "If a shape is a circle, it has no corners. Shape X has no corners. Therefore shape X is a circle. Is this valid?",
    choice_a: "Yes, because it satisfies the definition of a circle.",
    choice_b: "No, because other shapes (like ellipses) also have no corners.",
    choice_c: "Yes, because the premises support the conclusion.",
    choice_d: "No, because circles always have corners.",
    correct_choice: "b",
    explanation: "This is the fallacy of affirming the consequent. Having no corners is a property of circles but also of other shapes (ovals, ellipses). We cannot conclude X is a circle.",
    difficulty: 3,
  },
  {
    question_text: "All roses are flowers. Some flowers are red. Which of the following is a valid conclusion?",
    choice_a: "All roses are red.",
    choice_b: "Some roses are red.",
    choice_c: "No roses are red.",
    choice_d: "None of the above can be concluded with certainty.",
    correct_choice: "d",
    explanation: "We know all roses are flowers, but the red flowers may not overlap with roses at all. We cannot determine from the given statements whether any roses are red.",
    difficulty: 3,
  },
  {
    question_text: "Ben argues: 'We've always done it this way, so it must be the right way.' This is an example of:",
    choice_a: "Appeal to tradition",
    choice_b: "Appeal to authority",
    choice_c: "Hasty generalization",
    choice_d: "Red herring",
    correct_choice: "a",
    explanation: "Arguing that something is correct because it is traditional or has always been done that way is an appeal to tradition (argumentum ad antiquitatem).",
    difficulty: 2,
  },
];

// ─────────────────────────────────────────────
// 2. NUMERICAL ABILITY
// ─────────────────────────────────────────────
const NUMERICAL: Q[] = [
  {
    question_text: "What is the next number in the sequence: 2, 5, 10, 17, 26, ___?",
    choice_a: "35",
    choice_b: "37",
    choice_c: "36",
    choice_d: "38",
    correct_choice: "b",
    explanation: "The differences are 3, 5, 7, 9, 11 (odd numbers increasing by 2). The next difference is 11, so 26 + 11 = 37.",
    difficulty: 2,
  },
  {
    question_text: "A car travels 240 km in 4 hours. At the same speed, how far will it travel in 7 hours?",
    choice_a: "400 km",
    choice_b: "420 km",
    choice_c: "380 km",
    choice_d: "440 km",
    correct_choice: "b",
    explanation: "Speed = 240 ÷ 4 = 60 km/h. Distance in 7 hours = 60 × 7 = 420 km.",
    difficulty: 1,
  },
  {
    question_text: "If 3 workers can complete a task in 12 days, how many days will 9 workers take to complete the same task?",
    choice_a: "3 days",
    choice_b: "4 days",
    choice_c: "6 days",
    choice_d: "9 days",
    correct_choice: "b",
    explanation: "Total work = 3 × 12 = 36 worker-days. With 9 workers: 36 ÷ 9 = 4 days.",
    difficulty: 2,
  },
  {
    question_text: "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, 13, ___?",
    choice_a: "18",
    choice_b: "20",
    choice_c: "21",
    choice_d: "23",
    correct_choice: "c",
    explanation: "This is the Fibonacci sequence where each term is the sum of the two preceding terms: 8 + 13 = 21.",
    difficulty: 1,
  },
  {
    question_text: "A store offers 25% discount on an item originally priced at ₱1,600. What is the sale price?",
    choice_a: "₱1,100",
    choice_b: "₱1,200",
    choice_c: "₱1,250",
    choice_d: "₱1,300",
    correct_choice: "b",
    explanation: "Discount = 25% × 1,600 = ₱400. Sale price = 1,600 − 400 = ₱1,200.",
    difficulty: 1,
  },
  {
    question_text: "Find the missing number: 4, 9, 16, 25, ___, 49",
    choice_a: "30",
    choice_b: "36",
    choice_c: "32",
    choice_d: "34",
    correct_choice: "b",
    explanation: "These are perfect squares: 2², 3², 4², 5², 6², 7². The missing number is 6² = 36.",
    difficulty: 1,
  },
  {
    question_text: "Ana is 3 times as old as her son. In 12 years, she will be twice as old as her son. How old is Ana now?",
    choice_a: "36",
    choice_b: "42",
    choice_c: "48",
    choice_d: "30",
    correct_choice: "a",
    explanation: "Let son's age = x, Ana's age = 3x. In 12 years: 3x + 12 = 2(x + 12) → 3x + 12 = 2x + 24 → x = 12. Ana's age = 3 × 12 = 36.",
    difficulty: 2,
  },
  {
    question_text: "What is the next term in the sequence: 3, 6, 12, 24, 48, ___?",
    choice_a: "72",
    choice_b: "84",
    choice_c: "96",
    choice_d: "100",
    correct_choice: "c",
    explanation: "Each term is multiplied by 2 (geometric sequence with ratio 2). The next term = 48 × 2 = 96.",
    difficulty: 1,
  },
  {
    question_text: "A tank is 2/5 full. After adding 60 liters, it becomes 4/5 full. What is the total capacity of the tank?",
    choice_a: "120 liters",
    choice_b: "150 liters",
    choice_c: "160 liters",
    choice_d: "200 liters",
    correct_choice: "b",
    explanation: "4/5 − 2/5 = 2/5 of the tank = 60 liters. Full capacity = 60 ÷ (2/5) = 60 × 5/2 = 150 liters.",
    difficulty: 2,
  },
  {
    question_text: "What is the next number in the sequence: 100, 91, 83, 76, 70, ___?",
    choice_a: "64",
    choice_b: "65",
    choice_c: "63",
    choice_d: "66",
    correct_choice: "b",
    explanation: "Differences: −9, −8, −7, −6, −5. The next difference is −5, so 70 − 5 = 65.",
    difficulty: 2,
  },
  {
    question_text: "A salesperson earns a base salary of ₱15,000 plus 5% commission on sales. If total earnings were ₱21,500, what were total sales?",
    choice_a: "₱120,000",
    choice_b: "₱130,000",
    choice_c: "₱125,000",
    choice_d: "₱140,000",
    correct_choice: "b",
    explanation: "Commission = 21,500 − 15,000 = 6,500. Sales = 6,500 ÷ 0.05 = ₱130,000.",
    difficulty: 2,
  },
  {
    question_text: "Find the missing number: 2, 6, 18, ___, 162",
    choice_a: "36",
    choice_b: "54",
    choice_c: "72",
    choice_d: "48",
    correct_choice: "b",
    explanation: "Geometric sequence with ratio 3: 2 × 3 = 6, 6 × 3 = 18, 18 × 3 = 54, 54 × 3 = 162.",
    difficulty: 1,
  },
  {
    question_text: "If 60% of a number is 90, what is 75% of the same number?",
    choice_a: "112.5",
    choice_b: "120",
    choice_c: "125",
    choice_d: "105",
    correct_choice: "a",
    explanation: "The number = 90 ÷ 0.60 = 150. Then 75% of 150 = 0.75 × 150 = 112.5.",
    difficulty: 2,
  },
  {
    question_text: "A train 200 m long passes a pole in 10 seconds. What is the train's speed in km/h?",
    choice_a: "60 km/h",
    choice_b: "72 km/h",
    choice_c: "80 km/h",
    choice_d: "64 km/h",
    correct_choice: "b",
    explanation: "Speed = 200 m ÷ 10 s = 20 m/s. Convert: 20 × 3600 ÷ 1000 = 72 km/h.",
    difficulty: 2,
  },
  {
    question_text: "What value of x satisfies: 5x − 3 = 2x + 12?",
    choice_a: "3",
    choice_b: "4",
    choice_c: "5",
    choice_d: "6",
    correct_choice: "c",
    explanation: "5x − 2x = 12 + 3 → 3x = 15 → x = 5.",
    difficulty: 1,
  },
  {
    question_text: "Two pipes can fill a tank in 6 hours and 9 hours respectively. How long will they take together?",
    choice_a: "3 hours",
    choice_b: "3.4 hours",
    choice_c: "3.6 hours",
    choice_d: "4 hours",
    correct_choice: "c",
    explanation: "Combined rate = 1/6 + 1/9 = 3/18 + 2/18 = 5/18 per hour. Time = 18/5 = 3.6 hours.",
    difficulty: 3,
  },
  {
    question_text: "The ratio of boys to girls in a class is 3:4. If there are 28 girls, how many students are in the class?",
    choice_a: "42",
    choice_b: "49",
    choice_c: "56",
    choice_d: "35",
    correct_choice: "b",
    explanation: "If 4 parts = 28 girls, then 1 part = 7. Boys = 3 × 7 = 21. Total = 21 + 28 = 49.",
    difficulty: 1,
  },
  {
    question_text: "Find the next term: 7, 14, 28, 56, ___",
    choice_a: "98",
    choice_b: "100",
    choice_c: "112",
    choice_d: "124",
    correct_choice: "c",
    explanation: "Each term is doubled (×2): 7, 14, 28, 56, 112.",
    difficulty: 1,
  },
  {
    question_text: "A jacket costs ₱2,400 after a 20% discount. What was the original price?",
    choice_a: "₱2,880",
    choice_b: "₱3,000",
    choice_c: "₱2,800",
    choice_d: "₱3,200",
    correct_choice: "b",
    explanation: "If 80% of original = 2,400, then original = 2,400 ÷ 0.80 = ₱3,000.",
    difficulty: 2,
  },
  {
    question_text: "What is the sum of the first 10 positive integers?",
    choice_a: "45",
    choice_b: "50",
    choice_c: "55",
    choice_d: "60",
    correct_choice: "c",
    explanation: "Sum = n(n+1)/2 = 10 × 11 / 2 = 55. Or simply: 1+2+3+4+5+6+7+8+9+10 = 55.",
    difficulty: 1,
  },
];

// ─────────────────────────────────────────────
// 3. VERBAL ABILITY
// ─────────────────────────────────────────────
const VERBAL: Q[] = [
  {
    question_text: "BOOK is to LIBRARY as PAINTING is to ___.",
    choice_a: "Artist",
    choice_b: "Canvas",
    choice_c: "Museum",
    choice_d: "Frame",
    correct_choice: "c",
    explanation: "A book is stored/displayed in a library; a painting is stored/displayed in a museum. The relationship is object to the place where it is exhibited.",
    difficulty: 1,
  },
  {
    question_text: "SURGEON is to SCALPEL as CARPENTER is to ___.",
    choice_a: "Wood",
    choice_b: "Nail",
    choice_c: "Hammer",
    choice_d: "Blueprint",
    correct_choice: "c",
    explanation: "A surgeon's primary cutting tool is a scalpel; a carpenter's primary driving tool is a hammer. The relationship is professional to their primary tool.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word most similar in meaning to BENEVOLENT.",
    choice_a: "Hostile",
    choice_b: "Generous",
    choice_c: "Cautious",
    choice_d: "Stubborn",
    correct_choice: "b",
    explanation: "Benevolent means well-meaning and kindly. Generous is its closest synonym among the choices.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word most opposite in meaning to VERBOSE.",
    choice_a: "Talkative",
    choice_b: "Concise",
    choice_c: "Wordy",
    choice_d: "Elaborate",
    correct_choice: "b",
    explanation: "Verbose means using more words than necessary. Its antonym is concise, meaning brief and to the point.",
    difficulty: 2,
  },
  {
    question_text: "ISLAND is to OCEAN as OASIS is to ___.",
    choice_a: "Water",
    choice_b: "Desert",
    choice_c: "Forest",
    choice_d: "Mountain",
    correct_choice: "b",
    explanation: "An island is a landmass surrounded by ocean; an oasis is a fertile area surrounded by desert. The relationship is surrounded-by.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word that does NOT belong: Oak, Pine, Maple, Fern, Birch",
    choice_a: "Oak",
    choice_b: "Fern",
    choice_c: "Maple",
    choice_d: "Birch",
    correct_choice: "b",
    explanation: "Oak, Pine, Maple, and Birch are all trees. Fern is a non-woody plant (pteridophyte), not a tree.",
    difficulty: 1,
  },
  {
    question_text: "LIGHT is to PHOTON as SOUND is to ___.",
    choice_a: "Decibel",
    choice_b: "Echo",
    choice_c: "Phonon",
    choice_d: "Wave",
    correct_choice: "c",
    explanation: "A photon is the quantum particle of light; a phonon is the quantum of sound energy. The relationship is phenomenon to its quantum unit.",
    difficulty: 3,
  },
  {
    question_text: "Choose the word most similar in meaning to DILIGENT.",
    choice_a: "Lazy",
    choice_b: "Careless",
    choice_c: "Hardworking",
    choice_d: "Reckless",
    correct_choice: "c",
    explanation: "Diligent means having or showing care and conscientiousness in one's work. Hardworking is its closest synonym.",
    difficulty: 1,
  },
  {
    question_text: "THERMOMETER is to TEMPERATURE as BAROMETER is to ___.",
    choice_a: "Wind",
    choice_b: "Humidity",
    choice_c: "Rainfall",
    choice_d: "Pressure",
    correct_choice: "d",
    explanation: "A thermometer measures temperature; a barometer measures atmospheric pressure. The relationship is instrument to what it measures.",
    difficulty: 1,
  },
  {
    question_text: "Select the word that best completes the analogy: PRIDE is to LION as FLOCK is to ___.",
    choice_a: "Dog",
    choice_b: "Fish",
    choice_c: "Sheep",
    choice_d: "Elephant",
    correct_choice: "c",
    explanation: "A group of lions is called a pride; a group of sheep (or birds) is called a flock. The relationship is collective noun to animal.",
    difficulty: 2,
  },
  {
    question_text: "Choose the word most opposite in meaning to TRANSPARENT.",
    choice_a: "Clear",
    choice_b: "Visible",
    choice_c: "Opaque",
    choice_d: "Bright",
    correct_choice: "c",
    explanation: "Transparent means allowing light to pass through. Its antonym is opaque, which means not transparent.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word that does NOT belong: Violin, Cello, Trumpet, Guitar, Harp",
    choice_a: "Violin",
    choice_b: "Trumpet",
    choice_c: "Cello",
    choice_d: "Guitar",
    correct_choice: "b",
    explanation: "Violin, Cello, Guitar, and Harp are all string instruments. Trumpet is a brass wind instrument.",
    difficulty: 1,
  },
  {
    question_text: "AUTHOR is to NOVEL as COMPOSER is to ___.",
    choice_a: "Orchestra",
    choice_b: "Symphony",
    choice_c: "Instrument",
    choice_d: "Concert",
    correct_choice: "b",
    explanation: "An author creates a novel; a composer creates a symphony. The relationship is creator to their created work.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word most similar in meaning to EPHEMERAL.",
    choice_a: "Eternal",
    choice_b: "Temporary",
    choice_c: "Significant",
    choice_d: "Ancient",
    correct_choice: "b",
    explanation: "Ephemeral means lasting for a very short time. Temporary is its closest synonym.",
    difficulty: 2,
  },
  {
    question_text: "DEMOCRACY is to CITIZENS as MONARCHY is to ___.",
    choice_a: "Government",
    choice_b: "Parliament",
    choice_c: "Subjects",
    choice_d: "Soldiers",
    correct_choice: "c",
    explanation: "In a democracy, political power rests with citizens; in a monarchy, people under royal rule are called subjects.",
    difficulty: 2,
  },
  {
    question_text: "Choose the word that does NOT belong: Nitrogen, Oxygen, Hydrogen, Carbon dioxide, Argon",
    choice_a: "Nitrogen",
    choice_b: "Carbon dioxide",
    choice_c: "Hydrogen",
    choice_d: "Argon",
    correct_choice: "b",
    explanation: "Nitrogen, Oxygen, Hydrogen, and Argon are all elements (monatomic or diatomic molecules). Carbon dioxide (CO₂) is a compound made of two different elements.",
    difficulty: 2,
  },
  {
    question_text: "DROUGHT is to RAIN as FAMINE is to ___.",
    choice_a: "Hunger",
    choice_b: "Food",
    choice_c: "War",
    choice_d: "Poverty",
    correct_choice: "b",
    explanation: "Drought is caused by the absence of rain; famine is caused by the absence of food. The relationship is problem to its missing solution.",
    difficulty: 2,
  },
  {
    question_text: "Choose the word most opposite in meaning to FRUGAL.",
    choice_a: "Thrifty",
    choice_b: "Careful",
    choice_c: "Wasteful",
    choice_d: "Simple",
    correct_choice: "c",
    explanation: "Frugal means sparing or economical with money. Its antonym is wasteful, meaning using resources carelessly.",
    difficulty: 2,
  },
  {
    question_text: "CATERPILLAR is to BUTTERFLY as TADPOLE is to ___.",
    choice_a: "Fish",
    choice_b: "Salamander",
    choice_c: "Frog",
    choice_d: "Newt",
    correct_choice: "c",
    explanation: "A caterpillar is the larval stage of a butterfly; a tadpole is the larval stage of a frog. The relationship is juvenile form to adult form.",
    difficulty: 1,
  },
  {
    question_text: "Choose the word most similar in meaning to AMBIGUOUS.",
    choice_a: "Clear",
    choice_b: "Vague",
    choice_c: "Definite",
    choice_d: "Precise",
    correct_choice: "b",
    explanation: "Ambiguous means open to more than one interpretation. Vague is its closest synonym, meaning not clearly expressed.",
    difficulty: 2,
  },
];

// ─────────────────────────────────────────────
// 4. DATA ANALYSIS
// ─────────────────────────────────────────────
const DATA: Q[] = [
  {
    question_text: "A survey of 200 students shows: 80 prefer Math, 60 prefer Science, 40 prefer English, 20 prefer History. What percentage prefer Science?",
    choice_a: "25%",
    choice_b: "30%",
    choice_c: "35%",
    choice_d: "40%",
    correct_choice: "b",
    explanation: "Percentage = (60 ÷ 200) × 100 = 30%.",
    difficulty: 1,
  },
  {
    question_text: "In a class, test scores are: 75, 80, 85, 90, 70. What is the average (mean) score?",
    choice_a: "78",
    choice_b: "80",
    choice_c: "82",
    choice_d: "85",
    correct_choice: "b",
    explanation: "Sum = 75 + 80 + 85 + 90 + 70 = 400. Mean = 400 ÷ 5 = 80.",
    difficulty: 1,
  },
  {
    question_text: "Monthly sales (in thousands): Jan=50, Feb=60, Mar=55, Apr=70, May=65. What is the median?",
    choice_a: "55",
    choice_b: "60",
    choice_c: "65",
    choice_d: "70",
    correct_choice: "b",
    explanation: "Arrange in order: 50, 55, 60, 65, 70. The middle (3rd) value is 60.",
    difficulty: 2,
  },
  {
    question_text: "In a pie chart, a sector representing 'Transportation' covers 72°. What percentage of the total does this represent?",
    choice_a: "15%",
    choice_b: "18%",
    choice_c: "20%",
    choice_d: "25%",
    correct_choice: "c",
    explanation: "Percentage = (72° ÷ 360°) × 100 = 20%.",
    difficulty: 2,
  },
  {
    question_text: "Data set: 4, 7, 7, 9, 11, 7, 3. What is the mode?",
    choice_a: "4",
    choice_b: "7",
    choice_c: "9",
    choice_d: "11",
    correct_choice: "b",
    explanation: "The mode is the value that appears most frequently. 7 appears 3 times, more than any other value.",
    difficulty: 1,
  },
  {
    question_text: "A company's profits over 4 years (in millions): Year 1: ₱2M, Year 2: ₱4M, Year 3: ₱3M, Year 4: ₱5M. What is the average annual profit?",
    choice_a: "₱3M",
    choice_b: "₱3.5M",
    choice_c: "₱4M",
    choice_d: "₱3.75M",
    correct_choice: "b",
    explanation: "Total = 2 + 4 + 3 + 5 = 14M. Average = 14 ÷ 4 = ₱3.5M.",
    difficulty: 1,
  },
  {
    question_text: "Test scores of 7 students: 82, 91, 78, 95, 88, 72, 85. What is the range?",
    choice_a: "20",
    choice_b: "23",
    choice_c: "25",
    choice_d: "18",
    correct_choice: "b",
    explanation: "Range = highest − lowest = 95 − 72 = 23.",
    difficulty: 1,
  },
  {
    question_text: "A table shows school enrollment: Grade 7: 320, Grade 8: 295, Grade 9: 280, Grade 10: 305. Which grade has the least enrollment?",
    choice_a: "Grade 7",
    choice_b: "Grade 8",
    choice_c: "Grade 9",
    choice_d: "Grade 10",
    correct_choice: "c",
    explanation: "Grade 9 has 280 students, which is the lowest among the four grades.",
    difficulty: 1,
  },
  {
    question_text: "A bar graph shows monthly rainfall (mm): Jan=120, Feb=80, Mar=50, Apr=30, May=20. How much more rain fell in January than in May?",
    choice_a: "80 mm",
    choice_b: "90 mm",
    choice_c: "100 mm",
    choice_d: "110 mm",
    correct_choice: "c",
    explanation: "Difference = 120 − 20 = 100 mm.",
    difficulty: 1,
  },
  {
    question_text: "Sales data: Q1=₱120K, Q2=₱150K, Q3=₱130K, Q4=₱200K. What percent of annual sales came from Q4?",
    choice_a: "30%",
    choice_b: "32%",
    choice_c: "33.3%",
    choice_d: "35%",
    correct_choice: "c",
    explanation: "Total = 120 + 150 + 130 + 200 = ₱600K. Q4 percentage = 200/600 × 100 = 33.3%.",
    difficulty: 2,
  },
  {
    question_text: "Data: 15, 20, 20, 25, 30, 35, 35, 35, 40. What is the mode?",
    choice_a: "20",
    choice_b: "25",
    choice_c: "35",
    choice_d: "30",
    correct_choice: "c",
    explanation: "35 appears 3 times, which is more than any other value in the data set.",
    difficulty: 1,
  },
  {
    question_text: "In a frequency table, 40 out of 160 respondents chose 'Strongly Agree'. What is the relative frequency?",
    choice_a: "20%",
    choice_b: "25%",
    choice_c: "30%",
    choice_d: "35%",
    correct_choice: "b",
    explanation: "Relative frequency = 40/160 × 100 = 25%.",
    difficulty: 1,
  },
  {
    question_text: "A line graph shows a student's scores over 5 tests: 65, 72, 78, 85, 90. What is the overall trend?",
    choice_a: "Decreasing",
    choice_b: "No trend",
    choice_c: "Fluctuating",
    choice_d: "Increasing",
    correct_choice: "d",
    explanation: "Each successive score is higher than the previous one: 65 < 72 < 78 < 85 < 90. This shows a consistently increasing trend.",
    difficulty: 1,
  },
  {
    question_text: "Population of a city: 2020=500K, 2021=520K, 2022=545K, 2023=572K. What was the average annual increase?",
    choice_a: "22K",
    choice_b: "24K",
    choice_c: "26K",
    choice_d: "28K",
    correct_choice: "b",
    explanation: "Total increase = 572K − 500K = 72K over 3 years. Average = 72/3 = 24K per year.",
    difficulty: 2,
  },
  {
    question_text: "A pie chart shows budget allocation: Food 40%, Transport 25%, Savings 20%, Entertainment 15%. If the total budget is ₱20,000, how much is allocated to Savings?",
    choice_a: "₱3,500",
    choice_b: "₱4,000",
    choice_c: "₱4,500",
    choice_d: "₱5,000",
    correct_choice: "b",
    explanation: "Savings = 20% × ₱20,000 = ₱4,000.",
    difficulty: 1,
  },
  {
    question_text: "Scores: 55, 60, 65, 70, 75, 80. What is the median?",
    choice_a: "65",
    choice_b: "67.5",
    choice_c: "70",
    choice_d: "72.5",
    correct_choice: "b",
    explanation: "With 6 values (even), median = average of 3rd and 4th values = (65 + 70)/2 = 67.5.",
    difficulty: 2,
  },
  {
    question_text: "A student scored 88, 92, 79, and 85 on four tests. What score must they get on the 5th test to achieve an average of 87?",
    choice_a: "89",
    choice_b: "90",
    choice_c: "91",
    choice_d: "92",
    correct_choice: "c",
    explanation: "Required total = 87 × 5 = 435. Current total = 88 + 92 + 79 + 85 = 344. Required 5th score = 435 − 344 = 91.",
    difficulty: 2,
  },
  {
    question_text: "A table shows absence rates by month: Jan=5, Feb=8, Mar=3, Apr=6, May=4. Which month had the highest absence rate?",
    choice_a: "January",
    choice_b: "February",
    choice_c: "March",
    choice_d: "April",
    correct_choice: "b",
    explanation: "February had 8 absences, which is the highest value in the table.",
    difficulty: 1,
  },
  {
    question_text: "From a sample of 500 people, 350 prefer Brand A. What is the probability that a randomly selected person prefers Brand A?",
    choice_a: "0.60",
    choice_b: "0.65",
    choice_c: "0.70",
    choice_d: "0.75",
    correct_choice: "c",
    explanation: "Probability = 350/500 = 0.70.",
    difficulty: 1,
  },
  {
    question_text: "Exports (in billion USD): 2019=5.2, 2020=4.8, 2021=5.5, 2022=6.1. Which year showed the greatest increase from the previous year?",
    choice_a: "2020",
    choice_b: "2021",
    choice_c: "2022",
    choice_d: "2019",
    correct_choice: "c",
    explanation: "Changes: 2020: −0.4, 2021: +0.7, 2022: +0.6. The greatest increase was in 2022 (+0.6B). Wait — 2021 shows +0.7 which is actually larger. 2021 is correct.",
    difficulty: 2,
  },
];

// ─────────────────────────────────────────────
// 5. VISUAL & PATTERN RECOGNITION
// ─────────────────────────────────────────────
const VISUAL: Q[] = [
  {
    question_text: "What comes next in the pattern: A, C, E, G, ___?",
    choice_a: "H",
    choice_b: "I",
    choice_c: "J",
    choice_d: "K",
    correct_choice: "b",
    explanation: "The pattern skips every other letter (alternating): A, C, E, G, I (every odd-positioned letter of the alphabet).",
    difficulty: 1,
  },
  {
    question_text: "What comes next: AZ, BY, CX, DW, ___?",
    choice_a: "EV",
    choice_b: "EU",
    choice_c: "FV",
    choice_d: "FW",
    correct_choice: "a",
    explanation: "First letter goes A, B, C, D, E (forward). Second letter goes Z, Y, X, W, V (backward). Next pair: EV.",
    difficulty: 2,
  },
  {
    question_text: "Find the odd one out in the number set: 8, 27, 64, 100, 125",
    choice_a: "8",
    choice_b: "27",
    choice_c: "100",
    choice_d: "125",
    correct_choice: "c",
    explanation: "8=2³, 27=3³, 64=4³, 125=5³ are all perfect cubes. 100 = 10² is a perfect square but not a perfect cube.",
    difficulty: 2,
  },
  {
    question_text: "What is next in the sequence: 1, 4, 9, 16, 25, ___?",
    choice_a: "30",
    choice_b: "36",
    choice_c: "32",
    choice_d: "49",
    correct_choice: "b",
    explanation: "These are perfect squares: 1², 2², 3², 4², 5², 6² = 36.",
    difficulty: 1,
  },
  {
    question_text: "Complete the pattern: 2, 3, 5, 8, 12, 17, ___",
    choice_a: "22",
    choice_b: "23",
    choice_c: "24",
    choice_d: "25",
    correct_choice: "b",
    explanation: "Differences: +1, +2, +3, +4, +5, +6. The next difference is +6, so 17 + 6 = 23.",
    difficulty: 2,
  },
  {
    question_text: "What letter comes next: Z, X, V, T, R, ___?",
    choice_a: "P",
    choice_b: "Q",
    choice_c: "O",
    choice_d: "N",
    correct_choice: "a",
    explanation: "The letters decrease by 2 each step (skip one letter backward): Z, X, V, T, R, P.",
    difficulty: 1,
  },
  {
    question_text: "Find the missing number: 3, 9, ___, 81, 243",
    choice_a: "18",
    choice_b: "27",
    choice_c: "36",
    choice_d: "45",
    correct_choice: "b",
    explanation: "Each number is multiplied by 3: 3, 9, 27, 81, 243. The missing number is 3 × 9 = 27.",
    difficulty: 1,
  },
  {
    question_text: "In a matrix: Row 1: 2, 4, 6 / Row 2: 3, 6, 9 / Row 3: 4, 8, ___. What is the missing value?",
    choice_a: "10",
    choice_b: "12",
    choice_c: "14",
    choice_d: "16",
    correct_choice: "b",
    explanation: "Each row multiplies the first number by 1, 2, 3. Row 3: 4×1=4, 4×2=8, 4×3=12.",
    difficulty: 2,
  },
  {
    question_text: "What comes next: 1, 2, 4, 7, 11, 16, ___?",
    choice_a: "21",
    choice_b: "22",
    choice_c: "23",
    choice_d: "24",
    correct_choice: "b",
    explanation: "Differences: +1, +2, +3, +4, +5, +6. The next difference is +6, so 16 + 6 = 22.",
    difficulty: 2,
  },
  {
    question_text: "Find the odd one out: 16, 25, 36, 48, 64",
    choice_a: "16",
    choice_b: "25",
    choice_c: "48",
    choice_d: "64",
    correct_choice: "c",
    explanation: "16=4², 25=5², 36=6², 64=8² are all perfect squares. 48 is not a perfect square.",
    difficulty: 2,
  },
  {
    question_text: "Complete the letter sequence: B, E, H, K, ___",
    choice_a: "M",
    choice_b: "N",
    choice_c: "O",
    choice_d: "P",
    correct_choice: "b",
    explanation: "Each letter advances by 3 positions: B(2), E(5), H(8), K(11), N(14).",
    difficulty: 2,
  },
  {
    question_text: "What number should replace the question mark: 5, 10, 20, 40, ?, 160",
    choice_a: "60",
    choice_b: "70",
    choice_c: "80",
    choice_d: "90",
    correct_choice: "c",
    explanation: "Geometric sequence with ratio 2: 5, 10, 20, 40, 80, 160.",
    difficulty: 1,
  },
  {
    question_text: "Find the missing term: 144, 121, 100, 81, ___",
    choice_a: "64",
    choice_b: "72",
    choice_c: "70",
    choice_d: "60",
    correct_choice: "a",
    explanation: "Descending perfect squares: 12², 11², 10², 9², 8². The next term is 8² = 64.",
    difficulty: 2,
  },
  {
    question_text: "What comes next: AB, DE, GH, JK, ___?",
    choice_a: "MN",
    choice_b: "LM",
    choice_c: "NO",
    choice_d: "NP",
    correct_choice: "a",
    explanation: "Each pair skips 2 letters then takes 2 consecutive: AB (skip C), DE (skip F), GH (skip I), JK (skip L), MN.",
    difficulty: 2,
  },
  {
    question_text: "What is the missing number: 7, 14, 21, 28, ___, 42?",
    choice_a: "32",
    choice_b: "33",
    choice_c: "35",
    choice_d: "36",
    correct_choice: "c",
    explanation: "Multiples of 7: 7×1=7, 7×2=14, 7×3=21, 7×4=28, 7×5=35, 7×6=42.",
    difficulty: 1,
  },
  {
    question_text: "In the pattern 1, 8, 27, 64, 125, which of the following does NOT belong?",
    choice_a: "1",
    choice_b: "27",
    choice_c: "64",
    choice_d: "All belong",
    correct_choice: "d",
    explanation: "1=1³, 8=2³, 27=3³, 64=4³, 125=5³ — all are perfect cubes. All belong.",
    difficulty: 2,
  },
  {
    question_text: "Find the next pair: 1A, 2B, 3C, 4D, ___",
    choice_a: "5D",
    choice_b: "5E",
    choice_c: "6E",
    choice_d: "4E",
    correct_choice: "b",
    explanation: "Numbers increase by 1; letters advance sequentially: 1A, 2B, 3C, 4D, 5E.",
    difficulty: 1,
  },
  {
    question_text: "What is the missing number: 2, 6, 12, 20, 30, ___?",
    choice_a: "36",
    choice_b: "40",
    choice_c: "42",
    choice_d: "44",
    correct_choice: "c",
    explanation: "These are n(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.",
    difficulty: 3,
  },
  {
    question_text: "Complete the sequence: Z, W, T, Q, ___",
    choice_a: "M",
    choice_b: "N",
    choice_c: "O",
    choice_d: "P",
    correct_choice: "b",
    explanation: "Letters decrease by 3 positions each time: Z(26), W(23), T(20), Q(17), N(14).",
    difficulty: 2,
  },
  {
    question_text: "Find the odd one out: 2, 3, 5, 7, 9, 11, 13",
    choice_a: "2",
    choice_b: "5",
    choice_c: "9",
    choice_d: "13",
    correct_choice: "c",
    explanation: "2, 3, 5, 7, 11, 13 are all prime numbers. 9 = 3 × 3 is composite, not prime.",
    difficulty: 2,
  },
];

// Fix the data analysis Q19 explanation
DATA[18].explanation = "Changes: 2020: −0.4, 2021: +0.7, 2022: +0.6. The greatest increase was in 2021 (+0.7B).";
DATA[18].correct_choice = "b";

const TOPICS = [
  { slug: "logic",          questions: LOGIC   },
  { slug: "numerical",      questions: NUMERICAL },
  { slug: "verbal",         questions: VERBAL  },
  { slug: "data-analysis",  questions: DATA    },
  { slug: "visual-pattern", questions: VISUAL  },
];

async function main() {
  // Fetch the reasoning subtest
  const { data: subtest, error: subtestError } = await supabase
    .from("subtests")
    .select("id")
    .eq("slug", "reasoning")
    .single();

  if (subtestError || !subtest) {
    console.error("Could not find reasoning subtest. Make sure it is seeded first.");
    process.exit(1);
  }

  let totalInserted = 0;

  for (const topic of TOPICS) {
    const { data: topicRow, error: topicError } = await supabase
      .from("topics")
      .select("id")
      .eq("slug", topic.slug)
      .eq("subtest_id", subtest.id)
      .single();

    if (topicError || !topicRow) {
      console.error(`Could not find topic: ${topic.slug}`);
      continue;
    }

    const rows = topic.questions.map((q) => ({
      topic_id: topicRow.id,
      question_text: q.question_text,
      choice_a: q.choice_a,
      choice_b: q.choice_b,
      choice_c: q.choice_c,
      choice_d: q.choice_d,
      correct_choice: q.correct_choice,
      explanation: q.explanation,
      difficulty: q.difficulty,
      status: "approved",
      is_premium: true,
      image_url: null,
    }));

    const { error: insertError } = await supabase.from("questions").insert(rows);

    if (insertError) {
      console.error(`Error inserting questions for ${topic.slug}:`, insertError.message);
    } else {
      console.log(`✓ Inserted ${rows.length} questions for topic: ${topic.slug}`);
      totalInserted += rows.length;
    }
  }

  console.log(`\nDone! Total questions inserted: ${totalInserted}`);
}

main();
