/**
 * Adds 150 new questions across all 13 topics.
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-more-questions.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

const NEW_QUESTIONS: Record<string, Q[]> = {
  // ── Language Proficiency: Grammar and Usage (12) ─────────────────────────
  "grammar-usage": [
    {
      question_text: "Choose the sentence that uses 'who' or 'whom' correctly.",
      choice_a: "Whom shall I say is calling?",
      choice_b: "Who did you speak to at the office?",
      choice_c: "To whom should I address the letter?",
      choice_d: "Whom do you trust the most?",
      correct_choice: "c",
      explanation: "'Whom' is used when it functions as an object. 'To whom' — 'whom' is the object of the preposition 'to.' Option A is incorrect because 'who' is the subject of 'is calling.'",
      difficulty: 2,
    },
    {
      question_text: "Choose the correct comparative form: 'Of the two candidates, Maria is ___ qualified.'",
      choice_a: "most",
      choice_b: "more",
      choice_c: "much",
      choice_d: "better",
      correct_choice: "b",
      explanation: "When comparing exactly two things, use the comparative form ('more'), not the superlative ('most'). 'More qualified' is correct for comparing two candidates.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence is grammatically correct?",
      choice_a: "I don't have no money.",
      choice_b: "She can't hardly wait.",
      choice_c: "He didn't say nothing.",
      choice_d: "They couldn't find anything.",
      correct_choice: "d",
      explanation: "Standard English avoids double negatives. 'Couldn't find anything' uses a single negative correctly. All other options combine two negatives, creating a grammatical error.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence uses a semicolon correctly?",
      choice_a: "I studied hard; but I still failed.",
      choice_b: "She loves music; painting; and dancing.",
      choice_c: "The weather was cold; nevertheless, we went hiking.",
      choice_d: "He ran quickly; to catch the bus.",
      correct_choice: "c",
      explanation: "A semicolon precedes a conjunctive adverb like 'nevertheless' when joining two independent clauses. Option A incorrectly uses a semicolon before a coordinating conjunction.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence uses a colon correctly?",
      choice_a: "She brought: apples, oranges, and bananas.",
      choice_b: "The rule is simple: always tell the truth.",
      choice_c: "He went: to the store and bought milk.",
      choice_d: "I want: to go home now.",
      correct_choice: "b",
      explanation: "A colon correctly follows a complete independent clause and introduces an explanation. Option A incorrectly interrupts the verb 'brought' and its object.",
      difficulty: 2,
    },
    {
      question_text: "Select the correct form: 'The quality of the reports ___ been declining.'",
      choice_a: "have",
      choice_b: "has",
      choice_c: "are",
      choice_d: "were",
      correct_choice: "b",
      explanation: "The subject is 'quality' (singular), not 'reports.' A prepositional phrase between subject and verb does not change agreement. 'Has been declining' is correct.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence demonstrates correct pronoun-antecedent agreement?",
      choice_a: "Everyone must submit their forms by Friday.",
      choice_b: "Everyone must submit his or her forms by Friday.",
      choice_c: "Everyone must submit its forms by Friday.",
      choice_d: "Everyone must submit our forms by Friday.",
      correct_choice: "b",
      explanation: "Formally, 'everyone' is singular. 'His or her' is the traditional singular form. ('Their' is increasingly accepted informally as a gender-neutral singular.)",
      difficulty: 2,
    },
    {
      question_text: "Identify the sentence where 'only' is correctly placed to mean 'she eats nothing but vegetables on weekdays.'",
      choice_a: "She only eats vegetables on weekdays.",
      choice_b: "Only she eats vegetables on weekdays.",
      choice_c: "She eats only vegetables on weekdays.",
      choice_d: "She eats vegetables only on weekdays.",
      correct_choice: "c",
      explanation: "'Only' should be placed immediately before the word it modifies. To indicate she eats nothing but vegetables, 'only' must directly precede 'vegetables.'",
      difficulty: 3,
    },
    {
      question_text: "Which of the following is a run-on sentence?",
      choice_a: "She left early; she had a prior commitment.",
      choice_b: "He studied hard, and he passed the exam.",
      choice_c: "I was tired I went to bed.",
      choice_d: "Although tired, she kept working.",
      correct_choice: "c",
      explanation: "A run-on sentence joins two independent clauses without proper punctuation or a conjunction. 'I was tired I went to bed' has no connector between the two clauses.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence uses the preposition correctly?",
      choice_a: "She is good in mathematics.",
      choice_b: "He is different than his brother in every way.",
      choice_c: "She is good at mathematics.",
      choice_d: "He is different to his brother.",
      correct_choice: "c",
      explanation: "The correct collocation is 'good at' when referring to skill. 'Good in' is non-standard for expressing ability.",
      difficulty: 2,
    },
    {
      question_text: "A comma splice is an error in which:",
      choice_a: "a comma replaces a necessary period between two complete sentences",
      choice_b: "two independent clauses are joined with only a comma and no conjunction",
      choice_c: "a comma is missing from a list of three or more items",
      choice_d: "a semicolon is used instead of a comma in a list",
      correct_choice: "b",
      explanation: "A comma splice joins two complete independent clauses with only a comma instead of a comma + coordinating conjunction or a semicolon.",
      difficulty: 2,
    },
    {
      question_text: "Select the grammatically correct sentence.",
      choice_a: "He ran quick to catch the bus.",
      choice_b: "She feels badly about the mistake.",
      choice_c: "The soup smells wonderfully.",
      choice_d: "She sings beautifully in the choir.",
      correct_choice: "d",
      explanation: "'Beautifully' is an adverb correctly modifying the verb 'sings.' Option A needs 'quickly'; option B needs 'bad' (adjective after linking verb); option C needs 'wonderful.'",
      difficulty: 2,
    },
  ],

  // ── Language Proficiency: Vocabulary (12) ───────────────────────────────
  vocabulary: [
    {
      question_text: "The word 'sanguine' most nearly means:",
      choice_a: "gloomy and pessimistic",
      choice_b: "optimistic, especially in difficult situations",
      choice_c: "bloodthirsty and violent",
      choice_d: "pale and physically weak",
      correct_choice: "b",
      explanation: "'Sanguine' means having an optimistic outlook despite difficulties. Though it shares a Latin root with sanguinary (bloodthirsty), its modern meaning is cheerfully confident.",
      difficulty: 2,
    },
    {
      question_text: "The best synonym for 'reticent' is:",
      choice_a: "outspoken and vocal",
      choice_b: "reluctant to speak or reveal information",
      choice_c: "extremely enthusiastic",
      choice_d: "persistently indecisive",
      correct_choice: "b",
      explanation: "'Reticent' means not revealing one's thoughts readily; reserved or uncommunicative in speech.",
      difficulty: 2,
    },
    {
      question_text: "Something described as 'inimical' is:",
      choice_a: "friendly and welcoming to others",
      choice_b: "strangely unfamiliar",
      choice_c: "hostile or harmful in nature",
      choice_d: "extremely ancient",
      correct_choice: "c",
      explanation: "'Inimical' means tending to obstruct or harm; unfriendly and adverse. 'Inimical to progress' means directly harmful to advancement.",
      difficulty: 3,
    },
    {
      question_text: "To 'vacillate' means to:",
      choice_a: "move decisively toward a specific goal",
      choice_b: "waver indecisively between different opinions or actions",
      choice_c: "speak very rapidly and fluently",
      choice_d: "remain completely motionless",
      correct_choice: "b",
      explanation: "To vacillate is to go back and forth between options, unable to commit. From Latin 'vacillare' (to sway).",
      difficulty: 2,
    },
    {
      question_text: "The word 'contrite' means:",
      choice_a: "confident and self-assured",
      choice_b: "angry and deeply resentful",
      choice_c: "genuinely remorseful and penitent",
      choice_d: "carefree and unconcerned",
      correct_choice: "c",
      explanation: "'Contrite' means feeling or expressing genuine remorse for wrongdoing. A contrite apology is sincere and guilt-filled.",
      difficulty: 2,
    },
    {
      question_text: "A 'magnanimous' person is one who is:",
      choice_a: "exceptionally intelligent",
      choice_b: "very large in physical size",
      choice_c: "generous and forgiving, especially toward rivals or enemies",
      choice_d: "proud and arrogant in manner",
      correct_choice: "c",
      explanation: "'Magnanimous' comes from Latin 'magna anima' (great spirit) — generous in spirit, especially in forgiving rivals or being gracious in victory.",
      difficulty: 2,
    },
    {
      question_text: "The word 'perspicacious' most nearly means:",
      choice_a: "extremely persistent and stubborn",
      choice_b: "having keen, sharp insight and understanding",
      choice_c: "visibly perspiring",
      choice_d: "visually impaired",
      correct_choice: "b",
      explanation: "'Perspicacious' means having a ready insight into things; shrewd and discerning. A perspicacious observer notices what others miss.",
      difficulty: 3,
    },
    {
      question_text: "An 'intransigent' person is:",
      choice_a: "very easy to persuade",
      choice_b: "quiet and socially withdrawn",
      choice_c: "unwilling to compromise or change position",
      choice_d: "highly analytical and logical",
      correct_choice: "c",
      explanation: "'Intransigent' means refusing to agree or compromise. Often used in political or negotiation contexts for someone who holds firm regardless of pressure.",
      difficulty: 3,
    },
    {
      question_text: "To 'amalgamate' means to:",
      choice_a: "separate something into its distinct parts",
      choice_b: "combine or unite to form one organization or structure",
      choice_c: "destroy something completely",
      choice_d: "study something thoroughly",
      correct_choice: "b",
      explanation: "'Amalgamate' means to combine or unite. Companies that merge are said to amalgamate into a single entity.",
      difficulty: 2,
    },
    {
      question_text: "When used as an adjective, 'precipitate' means:",
      choice_a: "caused by unusual weather conditions",
      choice_b: "done suddenly and without careful consideration; rash",
      choice_c: "slow and deliberately planned",
      choice_d: "extremely costly",
      correct_choice: "b",
      explanation: "As an adjective, 'precipitate' means hasty and rash. A precipitate decision is made without sufficient thought.",
      difficulty: 3,
    },
    {
      question_text: "The word 'dissonance' refers to:",
      choice_a: "a pleasing harmony of sounds or ideas",
      choice_b: "a lack of agreement or harmony; discord",
      choice_c: "a specific musical key or scale",
      choice_d: "a state of perfect balance",
      correct_choice: "b",
      explanation: "'Dissonance' means lack of harmony. 'Cognitive dissonance' is the psychological discomfort of holding contradictory beliefs simultaneously.",
      difficulty: 2,
    },
    {
      question_text: "An 'acrimonious' debate is characterized by:",
      choice_a: "calm, reasoned discussion between parties",
      choice_b: "bitter, sharp, and angry words or feelings",
      choice_c: "friendly agreement among participants",
      choice_d: "precise academic language",
      correct_choice: "b",
      explanation: "'Acrimonious' means angry and bitter, with harsh, cutting remarks. An acrimonious dispute involves deep resentment on both sides.",
      difficulty: 2,
    },
  ],

  // ── Language Proficiency: Analogy (12) ──────────────────────────────────
  analogy: [
    {
      question_text: "DEHYDRATION : WATER :: ANEMIA : ___",
      choice_a: "sleep",
      choice_b: "iron",
      choice_c: "oxygen",
      choice_d: "food",
      correct_choice: "b",
      explanation: "Dehydration is caused by a deficiency of water; anemia is caused by a deficiency of iron (or hemoglobin). Both are deficiency-to-missing-substance relationships.",
      difficulty: 2,
    },
    {
      question_text: "MANUSCRIPT : AUTHOR :: BLUEPRINT : ___",
      choice_a: "builder",
      choice_b: "architect",
      choice_c: "engineer",
      choice_d: "contractor",
      correct_choice: "b",
      explanation: "An author creates a manuscript; an architect creates a blueprint. Both are original design documents produced by specific professionals.",
      difficulty: 1,
    },
    {
      question_text: "ABRIDGED : COMPLETE :: EXCERPT : ___",
      choice_a: "summary",
      choice_b: "fragment",
      choice_c: "whole text",
      choice_d: "paraphrase",
      correct_choice: "c",
      explanation: "An abridged work is a shortened version of a complete work; an excerpt is a portion of a whole text. Both are part-to-whole relationships.",
      difficulty: 2,
    },
    {
      question_text: "CARTOGRAPHER : MAPS :: LEXICOGRAPHER : ___",
      choice_a: "novels",
      choice_b: "dictionaries",
      choice_c: "laws",
      choice_d: "photographs",
      correct_choice: "b",
      explanation: "A cartographer makes maps; a lexicographer compiles dictionaries. Both are creators of specialized reference works in their domains.",
      difficulty: 2,
    },
    {
      question_text: "INDIFFERENT : APATHY :: ZEALOUS : ___",
      choice_a: "passion",
      choice_b: "anger",
      choice_c: "calmness",
      choice_d: "hatred",
      correct_choice: "a",
      explanation: "Indifference is characterized by apathy; being zealous is characterized by passion. Both describe a person and their dominant emotional state.",
      difficulty: 2,
    },
    {
      question_text: "TELESCOPE : DISTANT :: MICROSCOPE : ___",
      choice_a: "small",
      choice_b: "bright",
      choice_c: "invisible",
      choice_d: "ancient",
      correct_choice: "a",
      explanation: "A telescope makes distant objects visible; a microscope makes small objects visible. Both instruments extend human vision in a specific direction.",
      difficulty: 1,
    },
    {
      question_text: "LION : PRIDE :: WOLF : ___",
      choice_a: "herd",
      choice_b: "pack",
      choice_c: "flock",
      choice_d: "colony",
      correct_choice: "b",
      explanation: "A group of lions is called a pride; a group of wolves is called a pack. Both are collective nouns for social predatory animals.",
      difficulty: 1,
    },
    {
      question_text: "PROLIFIC : OUTPUT :: DILIGENT : ___",
      choice_a: "creativity",
      choice_b: "effort",
      choice_c: "money",
      choice_d: "speed",
      correct_choice: "b",
      explanation: "A prolific person is defined by abundant output; a diligent person is defined by sustained effort. Both describe a person and the quality that characterizes their work.",
      difficulty: 2,
    },
    {
      question_text: "PERJURY : TESTIMONY :: PLAGIARISM : ___",
      choice_a: "research",
      choice_b: "writing",
      choice_c: "citation",
      choice_d: "speech",
      correct_choice: "b",
      explanation: "Perjury is dishonesty in testimony; plagiarism is dishonesty in writing. Both are forms of deception in specific communication contexts.",
      difficulty: 2,
    },
    {
      question_text: "TAUTOLOGY : REPETITION :: HYPERBOLE : ___",
      choice_a: "understatement",
      choice_b: "exaggeration",
      choice_c: "comparison",
      choice_d: "substitution",
      correct_choice: "b",
      explanation: "Tautology is a figure of speech involving unnecessary repetition; hyperbole involves deliberate exaggeration. Both name a type of rhetorical device.",
      difficulty: 3,
    },
    {
      question_text: "DROUGHT : ARID :: FLOOD : ___",
      choice_a: "cold",
      choice_b: "wet",
      choice_c: "inundated",
      choice_d: "stormy",
      correct_choice: "c",
      explanation: "A drought results in arid (dry) conditions; a flood results in inundated (overwhelmed by water) conditions. Both are cause-to-resulting-condition relationships.",
      difficulty: 2,
    },
    {
      question_text: "AMENDMENT : CONSTITUTION :: FOOTNOTE : ___",
      choice_a: "chapter",
      choice_b: "bibliography",
      choice_c: "text",
      choice_d: "index",
      correct_choice: "c",
      explanation: "An amendment adds to or modifies a constitution; a footnote adds supplementary information to a main text. Both are supplementary additions to a primary document.",
      difficulty: 2,
    },
  ],

  // ── Reading Comprehension: Main Idea (11) ───────────────────────────────
  "main-idea": [
    {
      question_text: "Which of the following best describes the purpose of a topic sentence?",
      choice_a: "It provides evidence and statistics for the main argument.",
      choice_b: "It introduces the main idea that the paragraph will develop.",
      choice_c: "It concludes the paragraph with a brief summary.",
      choice_d: "It provides a transition connecting this paragraph to the next.",
      correct_choice: "b",
      explanation: "A topic sentence introduces the controlling idea that all other sentences in the paragraph support or develop.",
      difficulty: 1,
    },
    {
      question_text: "A passage begins with statistics on plastic waste, discusses its impact on marine life, and ends with a call for government policy. The main purpose is most likely to:",
      choice_a: "entertain readers with animal stories",
      choice_b: "inform readers about the history of plastic manufacturing",
      choice_c: "persuade readers that urgent action on plastic waste is necessary",
      choice_d: "describe the chemical composition of plastics",
      correct_choice: "c",
      explanation: "The structure — problem, impact, call to action — is classic persuasive writing designed to motivate the reader toward a specific response.",
      difficulty: 2,
    },
    {
      question_text: "A paragraph that ends with 'In summary, regular exercise improves both physical and mental health' is most likely using which structure?",
      choice_a: "Problem-solution",
      choice_b: "Cause-effect",
      choice_c: "General-to-specific (deductive)",
      choice_d: "Specific-to-general (inductive)",
      correct_choice: "d",
      explanation: "In an inductive paragraph, specific examples come first and the main idea appears at the end as a concluding generalization.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Bees pollinate crops that feed billions. Without them, many fruits, vegetables, and nuts would disappear from our diet.' What is the main idea?",
      choice_a: "Bees produce honey for human consumption.",
      choice_b: "Many crops depend on insects for reproduction.",
      choice_c: "Bees are essential to the human food supply.",
      choice_d: "Fruits and vegetables are the most nutritious foods.",
      correct_choice: "c",
      explanation: "Both sentences focus on bees' role in pollination and the consequence for human food — the main idea is their critical importance to our food supply.",
      difficulty: 1,
    },
    {
      question_text: "Which technique best helps a reader identify the main idea in a long passage?",
      choice_a: "Focus on the longest sentence in each paragraph.",
      choice_b: "Read only the first and last sentences of each paragraph.",
      choice_c: "Count the most frequently repeated word.",
      choice_d: "Count the number of examples given in the passage.",
      correct_choice: "b",
      explanation: "Topic sentences and concluding sentences often contain key ideas. Reading the opening and closing sentences of each paragraph quickly reveals main points.",
      difficulty: 2,
    },
    {
      question_text: "A scientific article opens: 'Climate change is reshaping ecosystems worldwide,' then provides biome-by-biome examples. This structure is:",
      choice_a: "specific-to-general",
      choice_b: "chronological",
      choice_c: "general-to-specific",
      choice_d: "compare-and-contrast",
      correct_choice: "c",
      explanation: "Opening with a broad claim and supporting it with specific examples from different biomes is the general-to-specific (deductive) structure.",
      difficulty: 2,
    },
    {
      question_text: "A passage discussing multiple viewpoints on a topic without reaching a firm conclusion is most likely:",
      choice_a: "a personal narrative",
      choice_b: "an expository or analytical essay",
      choice_c: "a persuasive argument",
      choice_d: "a personal letter",
      correct_choice: "b",
      explanation: "Expository or analytical writing presents multiple perspectives or aspects of a topic to inform or analyze, without necessarily advocating one position.",
      difficulty: 2,
    },
    {
      question_text: "In informational texts, boldface type typically signals:",
      choice_a: "a direct quotation from an authority",
      choice_b: "a key term or important concept",
      choice_c: "background or supplementary information",
      choice_d: "a transitional phrase",
      correct_choice: "b",
      explanation: "In academic and textbook writing, boldface type conventionally highlights key vocabulary terms, definitions, or especially important concepts.",
      difficulty: 1,
    },
    {
      question_text: "An effective summary of a passage should:",
      choice_a: "include every statistic and date mentioned",
      choice_b: "include the reader's personal opinion to strengthen it",
      choice_c: "capture only the most important points without personal commentary",
      choice_d: "rewrite the passage in a different chronological order",
      correct_choice: "c",
      explanation: "An effective summary condenses the essential meaning of a text, omitting minor details and personal opinions.",
      difficulty: 1,
    },
    {
      question_text: "Which statement about a thesis statement is CORRECT?",
      choice_a: "It should always be phrased as a question.",
      choice_b: "It is always found in the conclusion of an essay.",
      choice_c: "It presents an arguable claim that the essay will support.",
      choice_d: "It lists all the facts the essay will present.",
      correct_choice: "c",
      explanation: "A thesis is the central, arguable claim of an essay, typically in the introduction, that guides the entire paper's argument.",
      difficulty: 1,
    },
    {
      question_text: "The 'controlling idea' of a paragraph refers to:",
      choice_a: "the last sentence that wraps up the paragraph",
      choice_b: "the central claim that all other sentences in the paragraph support",
      choice_c: "a transitional phrase connecting paragraphs",
      choice_d: "the most interesting fact or statistic in the paragraph",
      correct_choice: "b",
      explanation: "The controlling idea is the central argument or assertion in the topic sentence that every supporting sentence in the paragraph develops.",
      difficulty: 2,
    },
  ],

  // ── Reading Comprehension: Inference (11) ───────────────────────────────
  inference: [
    {
      question_text: "Read: 'The room fell silent as he walked in.' What can you most reasonably infer?",
      choice_a: "The person who entered is very tall.",
      choice_b: "The person who entered has a significant or intimidating presence.",
      choice_c: "Everyone in the room is hearing-impaired.",
      choice_d: "The room has excellent sound insulation.",
      correct_choice: "b",
      explanation: "People falling silent when someone enters typically signals that the person commands respect, authority, fear, or significant attention.",
      difficulty: 1,
    },
    {
      question_text: "A character in a novel gives away her most prized possessions before a long journey. What can you infer?",
      choice_a: "She is an unusually generous person.",
      choice_b: "She does not expect to return from the journey.",
      choice_c: "She is moving to a much larger home.",
      choice_d: "She is going on a short vacation.",
      correct_choice: "b",
      explanation: "Giving away prized possessions before departing suggests the person believes they will not return — a sign of impending danger or a one-way journey.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Despite being the youngest person in the room, she was the one everyone turned to for answers.' What can be inferred?",
      choice_a: "The others in the room were disrespectful toward elders.",
      choice_b: "She is exceptionally knowledgeable or wise beyond her years.",
      choice_c: "The others in the room do not know how to solve problems.",
      choice_d: "She holds the official title of supervisor.",
      correct_choice: "b",
      explanation: "Being the youngest yet the go-to expert implies exceptional competence that transcends the expectation tied to age.",
      difficulty: 1,
    },
    {
      question_text: "An advertisement says: 'Nine out of ten dentists recommend Brand X toothpaste.' A careful reader can reasonably infer:",
      choice_a: "Brand X is proven to prevent all dental problems.",
      choice_b: "The tenth dentist recommends a different brand or no brand.",
      choice_c: "Brand X is the most expensive toothpaste on the market.",
      choice_d: "All dentists are required by law to recommend Brand X.",
      correct_choice: "b",
      explanation: "'9 out of 10' implicitly means 1 out of 10 does not recommend it. A careful reader recognizes the qualification embedded in this common advertising claim.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'He spoke for two hours, but said very little.' The author most likely wants to suggest that:",
      choice_a: "The speaker was deeply passionate about his topic.",
      choice_b: "The speech was verbose and lacked meaningful content.",
      choice_c: "Two hours was too short for such an important subject.",
      choice_d: "The audience was simply uninterested in the topic.",
      correct_choice: "b",
      explanation: "'Spoke for two hours but said very little' is a paradox suggesting the speech was full of empty words — a commentary on ineffective communication.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'By 1944, the empire that had seemed invincible now clung desperately to its remaining territories.' What can be inferred?",
      choice_a: "The empire was at the peak of its power in 1944.",
      choice_b: "The empire had suffered significant military defeats by 1944.",
      choice_c: "The empire was expanding aggressively in 1944.",
      choice_d: "The empire peacefully surrendered its territories in 1944.",
      correct_choice: "b",
      explanation: "The contrast between 'seemed invincible' and 'clinging desperately' implies major military reversals and defeats had occurred between then and 1944.",
      difficulty: 2,
    },
    {
      question_text: "A reader notices that a news article includes quotes from only one side of a political debate. What can be inferred?",
      choice_a: "The other side definitively refused to be interviewed.",
      choice_b: "The article may be biased or incomplete in its reporting.",
      choice_c: "The news outlet is the most credible source available.",
      choice_d: "The debate is not significant enough to cover fully.",
      correct_choice: "b",
      explanation: "Presenting only one perspective without explaining why the other side is absent is a common indicator of potential bias or incomplete journalism.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The scientist had dedicated thirty years to this theory, and now her hands trembled as she read the results.' What can be inferred?",
      choice_a: "The scientist is elderly and physically weak.",
      choice_b: "The scientist is experiencing intense emotional anticipation or anxiety.",
      choice_c: "The scientist has never worked with laboratory equipment before.",
      choice_d: "The results were clearly negative.",
      correct_choice: "b",
      explanation: "Trembling hands after thirty years of dedicated work are a classic physical manifestation of intense emotion — anticipation or anxiety about pivotal results.",
      difficulty: 2,
    },
    {
      question_text: "A story mentions: 'The factory had been quiet for three years.' What can be inferred?",
      choice_a: "The factory operates exclusively on weekends.",
      choice_b: "The factory manufactures noise-reduction products.",
      choice_c: "The factory has been inactive or shut down for three years.",
      choice_d: "The factory workers are especially disciplined and quiet.",
      correct_choice: "c",
      explanation: "A 'quiet factory' for three years most logically means it has been shut down — factories produce noise during normal operation.",
      difficulty: 1,
    },
    {
      question_text: "An author describes a character who always arrives early, prepares thoroughly, and double-checks her work. What can be inferred?",
      choice_a: "She is chronically anxious and fearful.",
      choice_b: "She is meticulous and places high value on precision.",
      choice_c: "She has too much free time on her hands.",
      choice_d: "She does not trust her colleagues.",
      correct_choice: "b",
      explanation: "Arriving early, thorough preparation, and double-checking collectively imply a meticulous, detail-oriented personality who values accuracy.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following BEST describes a 'logical inference'?",
      choice_a: "A guess based on personal preference or opinion",
      choice_b: "A statement copied directly from the text",
      choice_c: "A conclusion drawn from available evidence and reasoning",
      choice_d: "An emotional reaction to what has been read",
      correct_choice: "c",
      explanation: "A logical inference is a reasoned conclusion drawn from evidence — distinct from guessing, personal opinion, or direct quotation.",
      difficulty: 1,
    },
  ],

  // ── Reading Comprehension: Vocabulary in Context (11) ───────────────────
  "vocab-in-context": [
    {
      question_text: "Read: 'The ambassador's measured response defused the crisis.' 'Measured' most likely means:",
      choice_a: "calculated and carefully considered",
      choice_b: "determined with a ruler",
      choice_c: "brief and dismissive",
      choice_d: "emotional and heartfelt",
      correct_choice: "a",
      explanation: "In context, 'measured' means carefully thought out and controlled — the kind of response that prevents escalation.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Critics called the new policy draconian, arguing it punished minor offenses with excessively harsh penalties.' 'Draconian' most likely means:",
      choice_a: "related to dragons or mythology",
      choice_b: "outdated and no longer effective",
      choice_c: "excessively strict and severe",
      choice_d: "democratic and fair to all parties",
      correct_choice: "c",
      explanation: "'Draconian' comes from Draco, an ancient Athenian lawmaker known for harsh laws. It means extremely severe or strict, especially in punishment.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Her argument, while eloquent, was entirely specious — it sounded convincing but could not withstand scrutiny.' 'Specious' most likely means:",
      choice_a: "highly detailed and thorough",
      choice_b: "superficially plausible but actually flawed",
      choice_c: "simple and straightforward",
      choice_d: "legally valid and binding",
      correct_choice: "b",
      explanation: "The context ('sounded convincing but could not withstand scrutiny') defines 'specious' directly — seeming correct on the surface but actually wrong.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'Despite widespread protests, the government remained intractable on the issue.' 'Intractable' most likely means:",
      choice_a: "willing to negotiate with protesters",
      choice_b: "completely disorganized in its response",
      choice_c: "hard to control or deal with; stubbornly resistant",
      choice_d: "transparent and open to scrutiny",
      correct_choice: "c",
      explanation: "A government that remains unchanged despite protests is stubborn and resistant — 'intractable' means difficult to manage or persuade.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The new drug proved efficacious in 90% of patients in the trial.' 'Efficacious' most likely means:",
      choice_a: "dangerous and unpredictable in effects",
      choice_b: "extremely expensive to produce",
      choice_c: "producing the desired result; effective",
      choice_d: "widely available in pharmacies",
      correct_choice: "c",
      explanation: "'Efficacious' means successfully producing a desired result. In medicine, it means the drug achieves its intended therapeutic effect.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The journalist wrote a scathing review that eviscerated the author's latest novel.' 'Eviscerated' in this context means:",
      choice_a: "praised with great enthusiasm",
      choice_b: "summarized carefully and fairly",
      choice_c: "destroyed or criticized with extreme harshness",
      choice_d: "misunderstood or misrepresented",
      correct_choice: "c",
      explanation: "'Eviscerate' literally means to remove organs; figuratively it means to utterly destroy or undermine through harsh criticism.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'Scientists believe the species went extinct because of a precipitous decline in its food source.' 'Precipitous' most likely means:",
      choice_a: "gradual and steady over many years",
      choice_b: "sudden and extremely steep",
      choice_c: "planned and entirely predictable",
      choice_d: "related to heavy precipitation",
      correct_choice: "b",
      explanation: "A 'precipitous decline' is a sudden, sharp drop — from the same root as 'precipice' (a steep cliff face).",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The teacher used an innocuous remark to redirect the student's behavior without embarrassing him.' 'Innocuous' most likely means:",
      choice_a: "highly sarcastic",
      choice_b: "not harmful or offensive",
      choice_c: "technically complex",
      choice_d: "publicly humiliating",
      correct_choice: "b",
      explanation: "An 'innocuous' remark causes no harm or offense — the teacher's choice was deliberately gentle and non-confrontational.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The documentary gave a poignant account of the refugees' journey.' 'Poignant' most likely means:",
      choice_a: "factually accurate and well-documented",
      choice_b: "evoking a keen sense of sadness or sympathy",
      choice_c: "entertaining and occasionally humorous",
      choice_d: "very long and detailed",
      correct_choice: "b",
      explanation: "'Poignant' describes something that evokes sharp, touching emotion — especially sadness or sympathy. A poignant account moves the audience deeply.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'His furtive glance toward the door suggested he was waiting for an opportunity to escape.' 'Furtive' most likely means:",
      choice_a: "hopeful and expectant",
      choice_b: "sad and melancholy",
      choice_c: "done in a secretive, sneaky manner",
      choice_d: "angry and resentful",
      correct_choice: "c",
      explanation: "A 'furtive glance' is a secretive, stealthy look done to avoid being noticed. The context (wanting to escape) reinforces the secretive quality.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'Despite the team's tenacious effort, they lost the championship by a single point.' 'Tenacious' most nearly means:",
      choice_a: "careless and poorly prepared",
      choice_b: "talented but consistently unlucky",
      choice_c: "exhausted from overtraining",
      choice_d: "persistent and refusing to give up",
      correct_choice: "d",
      explanation: "'Tenacious' means holding firm despite adversity; refusing to yield. Despite a near-miss loss, the team's persistent effort is the notable quality.",
      difficulty: 1,
    },
  ],

  // ── Science: Biology (12) ────────────────────────────────────────────────
  biology: [
    {
      question_text: "Which of the following is NOT a function of the liver?",
      choice_a: "Detoxification of the blood",
      choice_b: "Production of bile for digestion",
      choice_c: "Regulation of blood glucose via glycogen",
      choice_d: "Production of insulin",
      correct_choice: "d",
      explanation: "Insulin is produced by the beta cells of the pancreas, not the liver. The liver detoxifies blood, produces bile, and stores/releases glycogen.",
      difficulty: 2,
    },
    {
      question_text: "During cellular respiration, in which correct sequence does glucose get broken down?",
      choice_a: "Krebs cycle → Electron transport chain → Glycolysis",
      choice_b: "Glycolysis → Krebs cycle → Electron transport chain",
      choice_c: "Electron transport chain → Glycolysis → Krebs cycle",
      choice_d: "Glycolysis → Electron transport chain → Krebs cycle",
      correct_choice: "b",
      explanation: "The sequence is: Glycolysis (cytoplasm) → Pyruvate oxidation → Krebs cycle (mitochondrial matrix) → Electron transport chain (inner mitochondrial membrane).",
      difficulty: 2,
    },
    {
      question_text: "Which type of mutation involves the addition of an extra nucleotide to a DNA sequence?",
      choice_a: "Substitution",
      choice_b: "Deletion",
      choice_c: "Insertion",
      choice_d: "Inversion",
      correct_choice: "c",
      explanation: "Insertion occurs when one or more extra nucleotides are added to the sequence, causing a frameshift that alters all subsequent codons.",
      difficulty: 2,
    },
    {
      question_text: "Which component of blood is primarily responsible for clotting?",
      choice_a: "Red blood cells (erythrocytes)",
      choice_b: "White blood cells (leukocytes)",
      choice_c: "Plasma proteins",
      choice_d: "Platelets (thrombocytes)",
      correct_choice: "d",
      explanation: "Platelets (thrombocytes) are cell fragments in blood that aggregate at wound sites to form clots and stop bleeding.",
      difficulty: 1,
    },
    {
      question_text: "The term 'allele' refers to:",
      choice_a: "a complete chromosome set",
      choice_b: "an alternative form of a gene at a given chromosomal locus",
      choice_c: "a specific type of RNA molecule",
      choice_d: "a mutation found in mitochondrial DNA",
      correct_choice: "b",
      explanation: "Alleles are different versions of the same gene occupying the same position (locus) on homologous chromosomes. They account for variation in traits.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following best describes the role of ribosomes?",
      choice_a: "They store the cell's genetic information.",
      choice_b: "They produce ATP energy for the cell.",
      choice_c: "They synthesize proteins from mRNA templates.",
      choice_d: "They transport molecules in and out of the nucleus.",
      correct_choice: "c",
      explanation: "Ribosomes are molecular machines that translate mRNA sequences into polypeptide chains (proteins) through the process of translation.",
      difficulty: 1,
    },
    {
      question_text: "What is the correct difference between osmosis and diffusion?",
      choice_a: "Osmosis involves solute particles; diffusion involves solvent only.",
      choice_b: "Osmosis is the diffusion of water across a semipermeable membrane; diffusion is any movement from high to low concentration.",
      choice_c: "Diffusion requires ATP energy; osmosis does not.",
      choice_d: "Osmosis occurs only in plant cells; diffusion occurs in all cell types.",
      correct_choice: "b",
      explanation: "Diffusion is the general movement of any substance from high to low concentration. Osmosis is specifically the diffusion of water through a selectively permeable membrane.",
      difficulty: 2,
    },
    {
      question_text: "Which hormone is primarily responsible for the 'fight-or-flight' response?",
      choice_a: "Insulin",
      choice_b: "Thyroxine",
      choice_c: "Adrenaline (epinephrine)",
      choice_d: "Cortisol",
      correct_choice: "c",
      explanation: "Adrenaline (epinephrine), released by the adrenal medulla, triggers fight-or-flight: increased heart rate, dilated pupils, and blood flow redirected to muscles.",
      difficulty: 1,
    },
    {
      question_text: "The process by which genetic information flows from DNA to RNA to protein is described by:",
      choice_a: "The cell theory",
      choice_b: "The central dogma of molecular biology",
      choice_c: "Mendel's laws of inheritance",
      choice_d: "Darwin's theory of natural selection",
      correct_choice: "b",
      explanation: "The central dogma (Crick, 1958) describes genetic information flow: DNA replication, transcription (DNA → RNA), and translation (RNA → protein).",
      difficulty: 2,
    },
    {
      question_text: "What is the function of the nephron in the kidney?",
      choice_a: "To produce red blood cells",
      choice_b: "To filter blood and produce urine",
      choice_c: "To regulate blood hormone levels",
      choice_d: "To produce digestive enzymes",
      correct_choice: "b",
      explanation: "The nephron is the functional unit of the kidney. It filters blood, reabsorbs useful substances, and excretes waste products as urine.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is an example of negative feedback in the human body?",
      choice_a: "Blood clotting accelerating when more clotting factors are released",
      choice_b: "Childbirth contractions intensifying with more oxytocin",
      choice_c: "Sweating triggered when body temperature rises above normal",
      choice_d: "Inflammation increasing as more immune cells arrive",
      correct_choice: "c",
      explanation: "Negative feedback opposes the original stimulus. When body temperature rises, sweating cools it back — counteracting the change. Options A, B, and D are positive feedback.",
      difficulty: 3,
    },
    {
      question_text: "In an ecosystem, which organisms are the primary producers?",
      choice_a: "Herbivores",
      choice_b: "Carnivores",
      choice_c: "Decomposers",
      choice_d: "Autotrophs such as plants and algae",
      correct_choice: "d",
      explanation: "Primary producers (autotrophs) convert sunlight or chemical energy into organic matter. Plants and algae form the base of most food chains.",
      difficulty: 1,
    },
  ],

  // ── Science: Chemistry (12) ──────────────────────────────────────────────
  chemistry: [
    {
      question_text: "What is the pH of a neutral solution at 25°C?",
      choice_a: "0",
      choice_b: "7",
      choice_c: "14",
      choice_d: "1",
      correct_choice: "b",
      explanation: "At 25°C, a neutral solution has equal concentrations of H⁺ and OH⁻. This corresponds to pH = 7. pH < 7 is acidic; pH > 7 is basic.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following is a physical change?",
      choice_a: "Burning wood in a fire",
      choice_b: "Rusting of an iron nail",
      choice_c: "Melting of ice into water",
      choice_d: "Digestion of food in the stomach",
      correct_choice: "c",
      explanation: "Physical changes alter appearance but not chemical composition. Melting ice changes solid to liquid water — both are still H₂O.",
      difficulty: 1,
    },
    {
      question_text: "What is an isotope?",
      choice_a: "An element with a different number of electrons",
      choice_b: "An atom of the same element with a different number of neutrons",
      choice_c: "A compound of two different elements bonded together",
      choice_d: "An ion with a positive electrical charge",
      correct_choice: "b",
      explanation: "Isotopes are atoms of the same element (same proton count) that differ in neutron count, giving them different atomic masses. Example: Carbon-12 and Carbon-14.",
      difficulty: 2,
    },
    {
      question_text: "Which gas law states that volume is directly proportional to absolute temperature at constant pressure?",
      choice_a: "Boyle's Law",
      choice_b: "Charles's Law",
      choice_c: "Gay-Lussac's Law",
      choice_d: "Avogadro's Law",
      correct_choice: "b",
      explanation: "Charles's Law: V₁/T₁ = V₂/T₂ at constant pressure, meaning volume and absolute temperature are directly proportional.",
      difficulty: 2,
    },
    {
      question_text: "What type of reaction is: 2KClO₃ → 2KCl + 3O₂?",
      choice_a: "Synthesis",
      choice_b: "Single displacement",
      choice_c: "Double displacement",
      choice_d: "Decomposition",
      correct_choice: "d",
      explanation: "A decomposition reaction has a single compound breaking down into two or more simpler substances. KClO₃ decomposes into KCl and O₂.",
      difficulty: 2,
    },
    {
      question_text: "The modern periodic table arranges elements in order of increasing:",
      choice_a: "Atomic mass",
      choice_b: "Atomic radius",
      choice_c: "Atomic number",
      choice_d: "Electronegativity",
      correct_choice: "c",
      explanation: "The modern periodic table (based on Moseley's work) arranges elements by increasing atomic number (number of protons), not atomic mass.",
      difficulty: 1,
    },
    {
      question_text: "Which of the following best describes an ionic compound?",
      choice_a: "Atoms sharing electrons equally between them",
      choice_b: "A compound held together by metallic bonds",
      choice_c: "A compound formed by transfer of electrons, creating oppositely charged ions",
      choice_d: "Molecules held together by hydrogen bonds",
      correct_choice: "c",
      explanation: "Ionic compounds form when electrons transfer from a metal to a nonmetal, creating cations (+) and anions (−) that attract each other electrostatically.",
      difficulty: 2,
    },
    {
      question_text: "If the molar mass of water (H₂O) is 18 g/mol, how many moles are in 36 grams?",
      choice_a: "18 mol",
      choice_b: "1 mol",
      choice_c: "2 mol",
      choice_d: "0.5 mol",
      correct_choice: "c",
      explanation: "moles = mass ÷ molar mass = 36 g ÷ 18 g/mol = 2 mol.",
      difficulty: 1,
    },
    {
      question_text: "Which functional group is present in all alcohols?",
      choice_a: "Carboxyl group (-COOH)",
      choice_b: "Hydroxyl group (-OH)",
      choice_c: "Carbonyl group (C=O)",
      choice_d: "Amino group (-NH₂)",
      correct_choice: "b",
      explanation: "Alcohols are characterized by the hydroxyl functional group (-OH) attached to a carbon. Example: ethanol (CH₃CH₂OH).",
      difficulty: 2,
    },
    {
      question_text: "What are the main products of the complete combustion of a hydrocarbon?",
      choice_a: "Carbon monoxide and water vapor",
      choice_b: "Carbon dioxide and water",
      choice_c: "Carbon and hydrogen gas",
      choice_d: "Carbon dioxide and nitrogen",
      correct_choice: "b",
      explanation: "Complete combustion of hydrocarbons in excess oxygen produces only CO₂ and H₂O. Incomplete combustion (limited O₂) produces CO.",
      difficulty: 1,
    },
    {
      question_text: "In terms of electron transfer, 'oxidation' means:",
      choice_a: "gain of electrons by an atom or ion",
      choice_b: "loss of protons from a nucleus",
      choice_c: "loss of electrons by an atom or ion",
      choice_d: "gain of protons by an atom or ion",
      correct_choice: "c",
      explanation: "Oxidation is defined as the loss of electrons. Reduction is the gain of electrons. Mnemonic: OIL RIG — Oxidation Is Loss, Reduction Is Gain.",
      difficulty: 1,
    },
    {
      question_text: "What does the law of conservation of mass state?",
      choice_a: "Energy cannot be created or destroyed in any process.",
      choice_b: "Mass is always lost during chemical reactions.",
      choice_c: "In a chemical reaction, the total mass of reactants equals the total mass of products.",
      choice_d: "Matter can be fully converted to energy.",
      correct_choice: "c",
      explanation: "Lavoisier's law of conservation of mass: matter is neither created nor destroyed in chemical reactions — atoms are rearranged, not lost.",
      difficulty: 1,
    },
  ],

  // ── Science: Physics (11) ────────────────────────────────────────────────
  physics: [
    {
      question_text: "What is the SI unit of force?",
      choice_a: "Joule",
      choice_b: "Watt",
      choice_c: "Newton",
      choice_d: "Pascal",
      correct_choice: "c",
      explanation: "The SI unit of force is the Newton (N), defined as the force needed to accelerate 1 kg by 1 m/s². Named after Isaac Newton.",
      difficulty: 1,
    },
    {
      question_text: "An object moving in a circle at constant speed is:",
      choice_a: "Not accelerating because its speed is constant",
      choice_b: "Accelerating because the direction of velocity is continuously changing",
      choice_c: "Decelerating because it keeps changing direction",
      choice_d: "In a state of complete equilibrium",
      correct_choice: "b",
      explanation: "Acceleration involves any change in velocity, including direction. Circular motion constantly changes direction, so centripetal acceleration always exists.",
      difficulty: 2,
    },
    {
      question_text: "Which statement best describes the concept of inertia?",
      choice_a: "The gravitational force acting on an object due to Earth",
      choice_b: "The resistance of an object to changes in its state of motion",
      choice_c: "The momentum of a moving object",
      choice_d: "The energy stored in a compressed spring",
      correct_choice: "b",
      explanation: "Inertia is the property of matter resisting changes in its state of rest or motion — described by Newton's First Law.",
      difficulty: 1,
    },
    {
      question_text: "In a series circuit with a 12V battery and two 6Ω resistors, what is the total current?",
      choice_a: "2 A",
      choice_b: "1 A",
      choice_c: "4 A",
      choice_d: "0.5 A",
      correct_choice: "b",
      explanation: "Series circuit: total resistance = 6 + 6 = 12 Ω. Using Ohm's Law: I = V/R = 12/12 = 1 A.",
      difficulty: 2,
    },
    {
      question_text: "The work done by a force is calculated as:",
      choice_a: "Force × time",
      choice_b: "Force × velocity",
      choice_c: "Force × displacement × cos θ",
      choice_d: "Mass × acceleration",
      correct_choice: "c",
      explanation: "W = Fd cos θ, where F is force, d is displacement, and θ is the angle between them. When force and displacement are parallel (θ = 0°), W = Fd.",
      difficulty: 2,
    },
    {
      question_text: "What happens to the gravitational force between two objects if the distance between them is doubled?",
      choice_a: "It doubles.",
      choice_b: "It is halved.",
      choice_c: "It is reduced to one-quarter.",
      choice_d: "It remains the same.",
      correct_choice: "c",
      explanation: "Newton's law of gravitation: F ∝ 1/r². If r doubles, F becomes 1/(2²) = 1/4 of the original force.",
      difficulty: 2,
    },
    {
      question_text: "A transformer has 100 turns in the primary coil and 500 in the secondary. If primary voltage is 20V, what is the secondary voltage?",
      choice_a: "4 V",
      choice_b: "100 V",
      choice_c: "500 V",
      choice_d: "2500 V",
      correct_choice: "b",
      explanation: "Transformer equation: Vs/Vp = Ns/Np → Vs = 20 × (500/100) = 100 V. This is a step-up transformer.",
      difficulty: 2,
    },
    {
      question_text: "Which type of wave requires a material medium to travel through?",
      choice_a: "Radio waves",
      choice_b: "X-rays",
      choice_c: "Sound waves",
      choice_d: "Gamma rays",
      correct_choice: "c",
      explanation: "Sound waves are mechanical waves requiring a medium (solid, liquid, or gas). Electromagnetic waves (radio, X-ray, gamma) can travel through a vacuum.",
      difficulty: 1,
    },
    {
      question_text: "What is the kinetic energy of a 4 kg object moving at 3 m/s?",
      choice_a: "12 J",
      choice_b: "18 J",
      choice_c: "6 J",
      choice_d: "36 J",
      correct_choice: "b",
      explanation: "KE = ½mv² = ½ × 4 × 3² = ½ × 4 × 9 = 18 J.",
      difficulty: 1,
    },
    {
      question_text: "What phenomenon explains why a straw appears bent when placed in a glass of water?",
      choice_a: "Reflection",
      choice_b: "Refraction",
      choice_c: "Diffraction",
      choice_d: "Polarization",
      correct_choice: "b",
      explanation: "Light bends (refracts) when passing from denser water into less dense air at the surface, making the straw appear bent or displaced.",
      difficulty: 1,
    },
    {
      question_text: "A machine has an input force of 50 N over 2 m and lifts a load of 100 N over 0.5 m. What is its mechanical advantage?",
      choice_a: "2",
      choice_b: "0.5",
      choice_c: "4",
      choice_d: "1",
      correct_choice: "a",
      explanation: "Mechanical advantage (MA) = output force ÷ input force = 100 ÷ 50 = 2. The machine doubles the applied force.",
      difficulty: 2,
    },
  ],

  // ── Science: Earth Science (11) ──────────────────────────────────────────
  "earth-science": [
    {
      question_text: "What is the term for the boundary between Earth's crust and the mantle?",
      choice_a: "Gutenberg discontinuity",
      choice_b: "Lehmann discontinuity",
      choice_c: "Mohorovičić discontinuity (Moho)",
      choice_d: "Conrad discontinuity",
      correct_choice: "c",
      explanation: "The Mohorovičić discontinuity (Moho) is the boundary between Earth's crust and mantle, identified by seismic wave analysis.",
      difficulty: 3,
    },
    {
      question_text: "The process by which oceanic crust is pulled beneath continental plate at a convergent boundary is called:",
      choice_a: "Divergence",
      choice_b: "Transform faulting",
      choice_c: "Subduction",
      choice_d: "Rifting",
      correct_choice: "c",
      explanation: "Subduction occurs at convergent plate boundaries where denser oceanic crust sinks into the mantle under lighter continental crust, forming trenches and volcanic arcs.",
      difficulty: 2,
    },
    {
      question_text: "Which cloud type is most associated with thunderstorms?",
      choice_a: "Cirrus",
      choice_b: "Stratus",
      choice_c: "Cumulonimbus",
      choice_d: "Altocumulus",
      correct_choice: "c",
      explanation: "Cumulonimbus clouds are towering storm clouds associated with heavy rain, lightning, thunder, and hail. They can extend from near ground level to the upper troposphere.",
      difficulty: 1,
    },
    {
      question_text: "The 'Ring of Fire' refers to:",
      choice_a: "The zone of highest volcanic activity encircling the Pacific Ocean",
      choice_b: "The region near the equator with the highest average temperatures",
      choice_c: "A belt of earthquakes concentrated around Africa",
      choice_d: "The ozone hole located above the polar regions",
      correct_choice: "a",
      explanation: "The Pacific Ring of Fire is a horseshoe-shaped zone where 75% of Earth's volcanoes and 90% of earthquakes occur due to plate tectonic activity.",
      difficulty: 1,
    },
    {
      question_text: "What is the primary difference between weather and climate?",
      choice_a: "Weather describes long-term patterns; climate describes short-term conditions.",
      choice_b: "Weather describes short-term atmospheric conditions; climate describes long-term averages.",
      choice_c: "Weather refers only to temperature; climate encompasses all atmospheric elements.",
      choice_d: "They describe identical concepts used in different geographic regions.",
      correct_choice: "b",
      explanation: "Weather is the short-term state of the atmosphere at a specific time and place. Climate is the average conditions over a long period (30+ years) in a region.",
      difficulty: 1,
    },
    {
      question_text: "Which layer of the atmosphere is where most weather occurs?",
      choice_a: "Stratosphere",
      choice_b: "Troposphere",
      choice_c: "Mesosphere",
      choice_d: "Thermosphere",
      correct_choice: "b",
      explanation: "The troposphere (0–12 km altitude) contains most atmospheric water vapor and is where weather phenomena such as rain, wind, and storms occur.",
      difficulty: 1,
    },
    {
      question_text: "What is the approximate age of Earth, based on radiometric dating?",
      choice_a: "4.6 thousand years",
      choice_b: "4.6 million years",
      choice_c: "4.6 billion years",
      choice_d: "46 billion years",
      correct_choice: "c",
      explanation: "Using radiometric dating of meteorites and Earth's oldest rocks, scientists estimate Earth is approximately 4.6 billion years old.",
      difficulty: 1,
    },
    {
      question_text: "What causes the aurora borealis (Northern Lights)?",
      choice_a: "Reflection of sunlight off polar ice caps",
      choice_b: "Refraction of light through ice crystals in the atmosphere",
      choice_c: "Charged solar particles interacting with Earth's magnetic field and atmosphere",
      choice_d: "Fires from volcanic eruptions near the polar regions",
      correct_choice: "c",
      explanation: "The aurora results from charged solar wind particles being channeled by Earth's magnetic field into polar regions, where they excite atmospheric gases to emit light.",
      difficulty: 2,
    },
    {
      question_text: "Limestone is classified as which type of rock?",
      choice_a: "Igneous",
      choice_b: "Metamorphic",
      choice_c: "Sedimentary",
      choice_d: "Volcanic extrusive",
      correct_choice: "c",
      explanation: "Limestone is a sedimentary rock composed mainly of calcium carbonate, typically formed from accumulated marine organism shells and skeletons.",
      difficulty: 1,
    },
    {
      question_text: "The 'epicenter' of an earthquake is defined as:",
      choice_a: "The point underground where the earthquake originates",
      choice_b: "The point on Earth's surface directly above the earthquake's focus",
      choice_c: "The most severely damaged area during the earthquake",
      choice_d: "The center of the seismic wave pattern on a seismograph",
      correct_choice: "b",
      explanation: "The epicenter is the point on Earth's surface directly above the focus (hypocenter) underground. Ground shaking is typically strongest at the epicenter.",
      difficulty: 1,
    },
    {
      question_text: "Which principle states that in undisturbed rock layers, older strata lie below younger ones?",
      choice_a: "Uniformitarianism",
      choice_b: "Principle of lateral continuity",
      choice_c: "Law of superposition",
      choice_d: "Principle of cross-cutting relationships",
      correct_choice: "c",
      explanation: "Steno's Law of Superposition: in undisturbed sedimentary sequences, older layers are always found beneath younger layers.",
      difficulty: 2,
    },
  ],

  // ── Mathematics: Algebra (12) ────────────────────────────────────────────
  algebra: [
    {
      question_text: "Evaluate: 3² + 4 × 2 − 6 ÷ 3",
      choice_a: "13",
      choice_b: "15",
      choice_c: "11",
      choice_d: "17",
      correct_choice: "b",
      explanation: "Using order of operations (PEMDAS): 3² = 9; 4×2 = 8; 6÷3 = 2. Then 9 + 8 − 2 = 15.",
      difficulty: 1,
    },
    {
      question_text: "Simplify: (2x³)² × x",
      choice_a: "4x⁷",
      choice_b: "4x⁶",
      choice_c: "2x⁷",
      choice_d: "4x⁵",
      correct_choice: "a",
      explanation: "(2x³)² = 4x⁶. Then 4x⁶ × x¹ = 4x⁷.",
      difficulty: 2,
    },
    {
      question_text: "If 4 more than twice a number is 20, what is the number?",
      choice_a: "6",
      choice_b: "8",
      choice_c: "7",
      choice_d: "10",
      correct_choice: "b",
      explanation: "Let n = number. 2n + 4 = 20 → 2n = 16 → n = 8.",
      difficulty: 1,
    },
    {
      question_text: "What is the slope of the line passing through (2, 3) and (6, 7)?",
      choice_a: "2",
      choice_b: "1",
      choice_c: "0.5",
      choice_d: "4",
      correct_choice: "b",
      explanation: "slope m = (y₂ − y₁)/(x₂ − x₁) = (7 − 3)/(6 − 2) = 4/4 = 1.",
      difficulty: 1,
    },
    {
      question_text: "Solve: |2x − 4| = 6",
      choice_a: "x = 5 or x = −1",
      choice_b: "x = 5 or x = 1",
      choice_c: "x = −1 or x = −5",
      choice_d: "x = 3 or x = −3",
      correct_choice: "a",
      explanation: "|2x − 4| = 6 gives two cases: 2x − 4 = 6 → x = 5, or 2x − 4 = −6 → x = −1.",
      difficulty: 2,
    },
    {
      question_text: "A geometric sequence begins 2, 6, 18, 54, … What is the 6th term?",
      choice_a: "162",
      choice_b: "486",
      choice_c: "324",
      choice_d: "972",
      correct_choice: "b",
      explanation: "Common ratio r = 3. a₆ = 2 × 3⁵ = 2 × 243 = 486.",
      difficulty: 2,
    },
    {
      question_text: "Which set of ordered pairs represents a function?",
      choice_a: "{(1, 2), (1, 3), (2, 4)}",
      choice_b: "{(1, 2), (2, 3), (3, 4)}",
      choice_c: "{(0, 1), (0, 2), (1, 3)}",
      choice_d: "{(2, 3), (2, 4), (2, 5)}",
      correct_choice: "b",
      explanation: "A function assigns exactly one output to each input. Option B has unique x-values. Options A, C, and D all have repeated x-values with different outputs.",
      difficulty: 2,
    },
    {
      question_text: "Simplify: (3 + √5)(3 − √5)",
      choice_a: "9 − 5",
      choice_b: "4",
      choice_c: "6 − √5",
      choice_d: "14",
      correct_choice: "b",
      explanation: "Using difference of squares: (a + b)(a − b) = a² − b². So (3)² − (√5)² = 9 − 5 = 4.",
      difficulty: 2,
    },
    {
      question_text: "The product of two consecutive even integers is 48. What are the integers?",
      choice_a: "4 and 6",
      choice_b: "6 and 8",
      choice_c: "8 and 10",
      choice_d: "2 and 4",
      correct_choice: "b",
      explanation: "Let integers be n and n+2. n(n+2) = 48 → n² + 2n − 48 = 0 → (n+8)(n−6) = 0 → n = 6. Check: 6 × 8 = 48.",
      difficulty: 2,
    },
    {
      question_text: "How many real solutions does 4x² + 4x + 1 = 0 have?",
      choice_a: "Two distinct real solutions",
      choice_b: "No real solutions",
      choice_c: "One repeated real solution",
      choice_d: "Infinitely many real solutions",
      correct_choice: "c",
      explanation: "Discriminant = 4² − 4(4)(1) = 16 − 16 = 0. Zero discriminant means exactly one repeated real solution.",
      difficulty: 2,
    },
    {
      question_text: "Simplify: (x² − x − 6) ÷ (x + 2)",
      choice_a: "x − 3",
      choice_b: "x + 3",
      choice_c: "x − 2",
      choice_d: "x + 2",
      correct_choice: "a",
      explanation: "Factor: x² − x − 6 = (x − 3)(x + 2). Dividing by (x + 2) gives (x − 3).",
      difficulty: 2,
    },
    {
      question_text: "If 2^x = 32, what is x?",
      choice_a: "4",
      choice_b: "5",
      choice_c: "6",
      choice_d: "16",
      correct_choice: "b",
      explanation: "2^x = 32 = 2^5. Therefore x = 5.",
      difficulty: 1,
    },
  ],

  // ── Mathematics: Geometry (11) ───────────────────────────────────────────
  geometry: [
    {
      question_text: "What is the area of a trapezoid with bases 6 cm and 10 cm and height 4 cm?",
      choice_a: "32 cm²",
      choice_b: "240 cm²",
      choice_c: "64 cm²",
      choice_d: "16 cm²",
      correct_choice: "a",
      explanation: "Area = ½(b₁ + b₂) × h = ½(6 + 10) × 4 = ½ × 16 × 4 = 32 cm².",
      difficulty: 2,
    },
    {
      question_text: "In a 30-60-90 triangle, if the side opposite 30° is 5 cm, what is the hypotenuse?",
      choice_a: "5√2 cm",
      choice_b: "10 cm",
      choice_c: "5√3 cm",
      choice_d: "15 cm",
      correct_choice: "b",
      explanation: "In a 30-60-90 triangle, sides are in ratio 1 : √3 : 2. The hypotenuse is twice the shortest side: 2 × 5 = 10 cm.",
      difficulty: 2,
    },
    {
      question_text: "What is the sum of the exterior angles of any convex polygon?",
      choice_a: "180°",
      choice_b: "360°",
      choice_c: "540°",
      choice_d: "It depends on the number of sides.",
      correct_choice: "b",
      explanation: "The sum of exterior angles of any convex polygon is always 360°, regardless of the number of sides.",
      difficulty: 1,
    },
    {
      question_text: "A cylinder has radius 3 cm and height 7 cm. What is its volume? (Use π ≈ 3.14)",
      choice_a: "65.94 cm³",
      choice_b: "197.82 cm³",
      choice_c: "263.76 cm³",
      choice_d: "131.88 cm³",
      correct_choice: "b",
      explanation: "V = πr²h = 3.14 × 9 × 7 = 3.14 × 63 = 197.82 cm³.",
      difficulty: 2,
    },
    {
      question_text: "Two complementary angles are in the ratio 1:2. What is the measure of the larger angle?",
      choice_a: "30°",
      choice_b: "45°",
      choice_c: "60°",
      choice_d: "90°",
      correct_choice: "c",
      explanation: "Complementary angles sum to 90°. With ratio 1:2, angles are 30° and 60°. The larger angle is 60°.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is a property unique to a rhombus (but not necessarily a square)?",
      choice_a: "All angles measure 90°",
      choice_b: "All four sides are equal in length",
      choice_c: "Diagonals are equal in length",
      choice_d: "All angles are equal",
      correct_choice: "b",
      explanation: "A rhombus has all four sides equal. Unlike a square, its angles need not be 90°. The diagonals of a rhombus bisect each other at right angles but are not necessarily equal.",
      difficulty: 2,
    },
    {
      question_text: "What is the equation of a circle with center (3, −2) and radius 5?",
      choice_a: "(x − 3)² + (y + 2)² = 25",
      choice_b: "(x + 3)² + (y − 2)² = 25",
      choice_c: "(x − 3)² + (y − 2)² = 5",
      choice_d: "(x + 3)² + (y + 2)² = 25",
      correct_choice: "a",
      explanation: "Standard form: (x − h)² + (y − k)² = r². Center (3, −2): (x − 3)² + (y − (−2))² = (x − 3)² + (y + 2)² = 25.",
      difficulty: 2,
    },
    {
      question_text: "Triangle ABC has angles in the ratio 2:3:5. What is the measure of the largest angle?",
      choice_a: "72°",
      choice_b: "54°",
      choice_c: "90°",
      choice_d: "108°",
      correct_choice: "c",
      explanation: "Total ratio = 10. Each part = 180°/10 = 18°. Largest angle = 5 × 18° = 90°.",
      difficulty: 2,
    },
    {
      question_text: "In a circle with radius 9 cm, a central angle measures 80°. What is the arc length? (Use π ≈ 3.14)",
      choice_a: "12.56 cm",
      choice_b: "6.28 cm",
      choice_c: "9.42 cm",
      choice_d: "25.12 cm",
      correct_choice: "a",
      explanation: "Arc length = (θ/360) × 2πr = (80/360) × 2 × 3.14 × 9 = (2/9) × 56.52 ≈ 12.56 cm.",
      difficulty: 3,
    },
    {
      question_text: "Diagonals of rectangle ABCD are equal. If AC = 2x + 3 and BD = 5x − 9, what is the length of each diagonal?",
      choice_a: "11",
      choice_b: "4",
      choice_c: "9",
      choice_d: "13",
      correct_choice: "a",
      explanation: "Diagonals of a rectangle are equal: 2x + 3 = 5x − 9 → 3x = 12 → x = 4. Length = 2(4) + 3 = 11.",
      difficulty: 2,
    },
    {
      question_text: "What is the distance between points (1, 2) and (4, 6)?",
      choice_a: "5",
      choice_b: "7",
      choice_c: "25",
      choice_d: "√7",
      correct_choice: "a",
      explanation: "d = √((4−1)² + (6−2)²) = √(9 + 16) = √25 = 5.",
      difficulty: 2,
    },
  ],

  // ── Mathematics: Statistics and Probability (12) ─────────────────────────
  statistics: [
    {
      question_text: "A data set has mean 25 and standard deviation 5. The value 35 is how many standard deviations above the mean?",
      choice_a: "1",
      choice_b: "2",
      choice_c: "3",
      choice_d: "10",
      correct_choice: "b",
      explanation: "z = (x − μ)/σ = (35 − 25)/5 = 10/5 = 2. The value 35 is 2 standard deviations above the mean.",
      difficulty: 2,
    },
    {
      question_text: "In a box-and-whisker plot, the box itself represents:",
      choice_a: "The full range of all data values",
      choice_b: "The middle 50% of data (interquartile range, Q1 to Q3)",
      choice_c: "The mean and median of the data",
      choice_d: "All data within two standard deviations",
      correct_choice: "b",
      explanation: "The box in a box plot spans from Q1 to Q3, containing the middle 50% of data. The line inside marks the median (Q2).",
      difficulty: 2,
    },
    {
      question_text: "Two dice are rolled. What is the probability that the sum equals 7?",
      choice_a: "1/12",
      choice_b: "7/36",
      choice_c: "1/6",
      choice_d: "7/12",
      correct_choice: "c",
      explanation: "Favorable outcomes: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) — 6 outcomes out of 36 total. P = 6/36 = 1/6.",
      difficulty: 2,
    },
    {
      question_text: "What does a correlation coefficient of r = −0.9 indicate?",
      choice_a: "No relationship between the two variables",
      choice_b: "A weak positive relationship",
      choice_c: "A strong positive relationship",
      choice_d: "A strong negative relationship",
      correct_choice: "d",
      explanation: "r ranges from −1 to 1. r = −0.9 indicates a strong negative linear relationship: as one variable increases, the other strongly decreases.",
      difficulty: 2,
    },
    {
      question_text: "A survey finds 60% of students prefer online learning. In a sample of 200 students, how many would be expected to prefer it?",
      choice_a: "60",
      choice_b: "100",
      choice_c: "120",
      choice_d: "140",
      correct_choice: "c",
      explanation: "Expected count = probability × sample size = 0.60 × 200 = 120 students.",
      difficulty: 1,
    },
    {
      question_text: "How many ways can 3 students be chosen from a class of 10 (order does not matter)?",
      choice_a: "30",
      choice_b: "120",
      choice_c: "720",
      choice_d: "1000",
      correct_choice: "b",
      explanation: "C(10,3) = 10! / (3! × 7!) = (10 × 9 × 8) / (3 × 2 × 1) = 720/6 = 120.",
      difficulty: 2,
    },
    {
      question_text: "If P(A) = 0.4 and P(B) = 0.3 and A and B are mutually exclusive, what is P(A or B)?",
      choice_a: "0.12",
      choice_b: "0.7",
      choice_c: "0.1",
      choice_d: "0.4",
      correct_choice: "b",
      explanation: "For mutually exclusive events: P(A or B) = P(A) + P(B) = 0.4 + 0.3 = 0.7. They cannot both occur, so no subtraction needed.",
      difficulty: 2,
    },
    {
      question_text: "A class has scores: 85, 90, 78, 92, 88. What is the median score?",
      choice_a: "88",
      choice_b: "90",
      choice_c: "85",
      choice_d: "86.6",
      correct_choice: "a",
      explanation: "Arrange in order: 78, 85, 88, 90, 92. The middle value (3rd of 5) is 88.",
      difficulty: 1,
    },
    {
      question_text: "Standard deviation is a measure of:",
      choice_a: "The central tendency or average of a data set",
      choice_b: "The spread or variability of data values around the mean",
      choice_c: "The total sum of all values in the data set",
      choice_d: "The count of values in the data set",
      correct_choice: "b",
      explanation: "Standard deviation quantifies how spread out values are around the mean. Low standard deviation means values cluster near the mean.",
      difficulty: 1,
    },
    {
      question_text: "Events A and B are statistically independent if:",
      choice_a: "They cannot happen at the same time",
      choice_b: "The occurrence of one does not affect the probability of the other",
      choice_c: "Their probabilities sum to 1",
      choice_d: "They always occur together",
      correct_choice: "b",
      explanation: "Statistical independence means P(A|B) = P(A). For independent events, P(A and B) = P(A) × P(B).",
      difficulty: 2,
    },
    {
      question_text: "What is the probability of drawing a king or a heart from a standard deck of 52 cards?",
      choice_a: "4/52",
      choice_b: "13/52",
      choice_c: "16/52",
      choice_d: "17/52",
      correct_choice: "c",
      explanation: "P(king) = 4/52. P(heart) = 13/52. P(king of hearts) = 1/52. By inclusion-exclusion: 4/52 + 13/52 − 1/52 = 16/52 = 4/13.",
      difficulty: 3,
    },
    {
      question_text: "What is the variance of the data set 2, 4, 4, 4, 6? (Mean = 4)",
      choice_a: "4",
      choice_b: "2",
      choice_c: "1",
      choice_d: "8",
      correct_choice: "b",
      explanation: "Deviations from mean: −2, 0, 0, 0, 2. Squared: 4, 0, 0, 0, 4. Sum = 8. Population variance = 8/4 = 2.",
      difficulty: 3,
    },
  ],
};

async function main() {
  console.log("Starting additional questions seed...\n");

  // Fetch all topic slugs and their IDs
  const { data: topics, error } = await supabase
    .from("topics")
    .select("id, slug");
  if (error) throw new Error(`Failed to fetch topics: ${error.message}`);

  const topicMap = new Map((topics ?? []).map((t) => [t.slug, t.id]));

  let totalInserted = 0;

  for (const [slug, questions] of Object.entries(NEW_QUESTIONS)) {
    const topicId = topicMap.get(slug);
    if (!topicId) {
      console.warn(`  ⚠  Topic not found for slug: ${slug}`);
      continue;
    }

    const rows = questions.map((q) => ({
      ...q,
      topic_id: topicId,
      status: "approved" as const,
    }));

    const { error: insertError } = await supabase
      .from("questions")
      .insert(rows);

    if (insertError) {
      throw new Error(`Insert failed for ${slug}: ${insertError.message}`);
    }

    console.log(`  ✓ ${rows.length} questions → ${slug}`);
    totalInserted += rows.length;
  }

  console.log(`\n✅  Done! Inserted ${totalInserted} new questions.`);
}

main().catch((err) => {
  console.error("❌  Seed failed:", err.message);
  process.exit(1);
});
