/**
 * Seeds subtests, topics, and questions for ACET, DCAT, and USTET.
 * Run: npx ts-node --project tsconfig.seed.json scripts/seed-other-schools.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.join(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

type Q = {
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: 1 | 2 | 3;
};

// ── School definitions ────────────────────────────────────────────────────────

const SCHOOLS = [
  {
    exam_type: "acet",
    subtests: [
      { name: "Language Proficiency", slug: "acet-language-proficiency", display_order: 1, mock_item_count: 20, description: "English grammar, vocabulary, and language use." },
      { name: "Reading Comprehension", slug: "acet-reading-comprehension", display_order: 2, mock_item_count: 15, description: "Critical reading and text analysis." },
      { name: "Science", slug: "acet-science", display_order: 3, mock_item_count: 15, description: "Integrated concepts across physics, chemistry, and biology." },
      { name: "Mathematics", slug: "acet-mathematics", display_order: 4, mock_item_count: 10, description: "Algebraic reasoning and problem solving." },
    ],
    topics: [
      { subtestSlug: "acet-language-proficiency", name: "Grammar and Vocabulary", slug: "acet-grammar-vocab", display_order: 1 },
      { subtestSlug: "acet-reading-comprehension", name: "Reading Analysis", slug: "acet-reading-analysis", display_order: 1 },
      { subtestSlug: "acet-science", name: "Integrated Science", slug: "acet-integrated-science", display_order: 1 },
      { subtestSlug: "acet-mathematics", name: "Algebraic Reasoning", slug: "acet-algebraic-reasoning", display_order: 1 },
    ],
  },
  {
    exam_type: "dlsu",
    subtests: [
      { name: "Language Proficiency", slug: "dlsu-language-proficiency", display_order: 1, mock_item_count: 15, description: "English language arts and grammar." },
      { name: "Reading Comprehension", slug: "dlsu-reading-comprehension", display_order: 2, mock_item_count: 10, description: "Reading comprehension and critical thinking." },
      { name: "Mathematics", slug: "dlsu-mathematics", display_order: 3, mock_item_count: 25, description: "Advanced algebra, statistics, and problem solving." },
      { name: "Science", slug: "dlsu-science", display_order: 4, mock_item_count: 10, description: "Physics and chemistry concepts." },
    ],
    topics: [
      { subtestSlug: "dlsu-language-proficiency", name: "Language Arts", slug: "dlsu-language-arts", display_order: 1 },
      { subtestSlug: "dlsu-reading-comprehension", name: "Comprehension Skills", slug: "dlsu-comprehension", display_order: 1 },
      { subtestSlug: "dlsu-mathematics", name: "Advanced Algebra", slug: "dlsu-advanced-algebra", display_order: 1 },
      { subtestSlug: "dlsu-science", name: "Physical Sciences", slug: "dlsu-physical-sciences", display_order: 1 },
    ],
  },
  {
    exam_type: "ust",
    subtests: [
      { name: "Language Proficiency", slug: "ust-language-proficiency", display_order: 1, mock_item_count: 15, description: "English and Filipino language proficiency." },
      { name: "Reading Comprehension", slug: "ust-reading-comprehension", display_order: 2, mock_item_count: 15, description: "Medical and scientific reading comprehension." },
      { name: "Science", slug: "ust-science", display_order: 3, mock_item_count: 15, description: "Life sciences with emphasis on biology and health." },
      { name: "Mathematics", slug: "ust-mathematics", display_order: 4, mock_item_count: 15, description: "General mathematics and problem solving." },
    ],
    topics: [
      { subtestSlug: "ust-language-proficiency", name: "Language Proficiency", slug: "ust-language-topic", display_order: 1 },
      { subtestSlug: "ust-reading-comprehension", name: "Reading Skills", slug: "ust-reading-skills", display_order: 1 },
      { subtestSlug: "ust-science", name: "Life Sciences", slug: "ust-life-sciences", display_order: 1 },
      { subtestSlug: "ust-mathematics", name: "Mathematics", slug: "ust-math-topic", display_order: 1 },
    ],
  },
];

// ── Questions ─────────────────────────────────────────────────────────────────

const QUESTIONS: Record<string, Q[]> = {

  // ── ACET: Grammar and Vocabulary ─────────────────────────────────────────
  "acet-grammar-vocab": [
    {
      question_text: "Which sentence uses the subjunctive mood correctly?",
      choice_a: "If I was taller, I would play basketball.",
      choice_b: "If I were taller, I would play basketball.",
      choice_c: "If I am taller, I would play basketball.",
      choice_d: "If I be taller, I would play basketball.",
      correct_choice: "b",
      explanation: "The subjunctive 'were' is used in contrary-to-fact conditional clauses.",
      difficulty: 2,
    },
    {
      question_text: "The word 'ephemeral' most nearly means:",
      choice_a: "Eternal",
      choice_b: "Mysterious",
      choice_c: "Short-lived",
      choice_d: "Colorful",
      correct_choice: "c",
      explanation: "'Ephemeral' describes something lasting for only a very short time.",
      difficulty: 2,
    },
    {
      question_text: "Choose the sentence with correct parallel structure:",
      choice_a: "She enjoys swimming, to run, and cycling.",
      choice_b: "She enjoys swimming, running, and cycling.",
      choice_c: "She enjoys to swim, running, and to cycle.",
      choice_d: "She enjoys swim, run, and cycling.",
      correct_choice: "b",
      explanation: "Parallel structure requires items in a series to share the same grammatical form.",
      difficulty: 1,
    },
    {
      question_text: "Identify the sentence with a dangling modifier:",
      choice_a: "Running to class, Maria dropped her books.",
      choice_b: "Maria, running to class, dropped her books.",
      choice_c: "While running to class, Maria's bag fell.",
      choice_d: "Maria ran to class and dropped her books.",
      correct_choice: "c",
      explanation: "In C, 'while running to class' implies Maria's bag was running, which is illogical.",
      difficulty: 2,
    },
    {
      question_text: "The word closest in meaning to 'gregarious' is:",
      choice_a: "Solitary",
      choice_b: "Hostile",
      choice_c: "Aggressive",
      choice_d: "Sociable",
      correct_choice: "d",
      explanation: "'Gregarious' means fond of the company of others; sociable.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is the correct plural of 'criterion'?",
      choice_a: "Criterions",
      choice_b: "Criterias",
      choice_c: "Criteria",
      choice_d: "Critera",
      correct_choice: "c",
      explanation: "'Criteria' is the correct Latin-derived plural of 'criterion'.",
      difficulty: 1,
    },
    {
      question_text: "Select the word that does NOT belong with the others:",
      choice_a: "Apprehensive",
      choice_b: "Anxious",
      choice_c: "Nonchalant",
      choice_d: "Fearful",
      correct_choice: "c",
      explanation: "'Nonchalant' means casually calm, while the others suggest worry or fear.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence is grammatically correct?",
      choice_a: "Neither the students nor the teacher are ready.",
      choice_b: "Neither the students nor the teacher were ready.",
      choice_c: "Neither the students nor the teacher is ready.",
      choice_d: "Neither the students nor the teacher have been ready.",
      correct_choice: "c",
      explanation: "With 'neither...nor', the verb agrees with the noun closest to it ('teacher' is singular).",
      difficulty: 3,
    },
    {
      question_text: "The phrase 'to burn bridges' means:",
      choice_a: "To work very hard",
      choice_b: "To permanently damage a relationship",
      choice_c: "To cross a difficult obstacle",
      choice_d: "To start a new project",
      correct_choice: "b",
      explanation: "'To burn bridges' means to permanently damage relationships or foreclose future options.",
      difficulty: 1,
    },
    {
      question_text: "Which word correctly completes the sentence: 'The policy will ___ affect all employees'?",
      choice_a: "Adverse",
      choice_b: "Adversely",
      choice_c: "Adversity",
      choice_d: "Adversarial",
      correct_choice: "b",
      explanation: "An adverb is needed to modify the verb 'affect'. 'Adversely' is the correct adverb form.",
      difficulty: 2,
    },
    {
      question_text: "Choose the sentence with the correct pronoun case:",
      choice_a: "Between you and I, this plan will fail.",
      choice_b: "Between you and me, this plan will fail.",
      choice_c: "Between you and myself, this plan will fail.",
      choice_d: "Between you and mine, this plan will fail.",
      correct_choice: "b",
      explanation: "'Between' is a preposition and requires object pronouns. 'Me' is the object form of 'I'.",
      difficulty: 2,
    },
    {
      question_text: "The word 'laconic' describes someone who:",
      choice_a: "Speaks excessively",
      choice_b: "Uses few words",
      choice_c: "Tells many stories",
      choice_d: "Speaks loudly",
      correct_choice: "b",
      explanation: "'Laconic' means using very few words; brief and concise in speech.",
      difficulty: 3,
    },
  ],

  // ── ACET: Reading Analysis ────────────────────────────────────────────────
  "acet-reading-analysis": [
    {
      question_text: "Read the passage: 'Technology has transformed education by making information more accessible than ever. However, the ability to find information is not the same as the ability to understand or evaluate it.' What is the author's main point?",
      choice_a: "Technology has made education worse.",
      choice_b: "Access to information does not guarantee critical understanding.",
      choice_c: "Students should not use the internet for research.",
      choice_d: "Teachers are no longer necessary.",
      correct_choice: "b",
      explanation: "The author contrasts accessibility of information with the deeper skill of understanding and evaluating it.",
      difficulty: 2,
    },
    {
      question_text: "In the passage above, the word 'accessible' most nearly means:",
      choice_a: "Complicated",
      choice_b: "Expensive",
      choice_c: "Easily obtained",
      choice_d: "Hidden",
      correct_choice: "c",
      explanation: "'Accessible' means easily reached or obtained.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'Despite record rainfall last year, the city's water reservoirs remain dangerously low due to increased consumption and aging infrastructure.' Which inference is best supported?",
      choice_a: "Water conservation is unnecessary this year.",
      choice_b: "The city's water problems are caused by weather alone.",
      choice_c: "Multiple factors beyond rainfall affect water supply.",
      choice_d: "The infrastructure was recently repaired.",
      correct_choice: "c",
      explanation: "The passage explicitly mentions both increased consumption and aging infrastructure alongside rainfall, indicating multiple causes.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The novel's protagonist spends the entire story chasing recognition but ends the story alone, surrounded by trophies.' What is the likely theme?",
      choice_a: "Hard work always leads to success.",
      choice_b: "External achievement cannot substitute for meaningful relationships.",
      choice_c: "Collecting trophies is a worthwhile goal.",
      choice_d: "Fame is easily achieved.",
      correct_choice: "b",
      explanation: "The contrast between material success (trophies) and loneliness suggests the story critiques the pursuit of recognition over human connection.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'While critics praised the film's cinematography, audiences found the pacing too slow and the plot convoluted.' Which statement best summarizes the reception?",
      choice_a: "Both critics and audiences loved the film.",
      choice_b: "Critics and audiences agreed the plot was weak.",
      choice_c: "Critics focused on visuals while audiences were disappointed by storytelling.",
      choice_d: "The film was a commercial and critical failure.",
      correct_choice: "c",
      explanation: "Critics praised cinematography (visual); audiences criticized pacing and plot (storytelling). These are distinct concerns.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Every generation believes it faces uniquely difficult challenges. Yet history shows that each era has navigated hardship and emerged changed but resilient.' What is the author's tone?",
      choice_a: "Dismissive and sarcastic",
      choice_b: "Alarmist and fearful",
      choice_c: "Measured and reassuring",
      choice_d: "Indifferent and detached",
      correct_choice: "c",
      explanation: "The author acknowledges difficulty but emphasizes historical resilience, conveying a balanced, reassuring tone.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence best describes a logical fallacy in argument?",
      choice_a: "This policy worked in Singapore, so it will work here.",
      choice_b: "Studies show that this vaccine is 95% effective.",
      choice_c: "Both sides agree that clean water is essential.",
      choice_d: "The proposal was rejected after a full committee review.",
      correct_choice: "a",
      explanation: "This is a false analogy — assuming that because something worked in one context, it will automatically work in a different one.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'The scientist published her findings despite pressure from her funding body to suppress them.' What does this suggest about the scientist?",
      choice_a: "She valued financial support over truth.",
      choice_b: "She prioritized integrity over convenience.",
      choice_c: "She acted irresponsibly.",
      choice_d: "She was forced to publish by the government.",
      correct_choice: "b",
      explanation: "Publishing despite pressure to suppress indicates the scientist placed truth and integrity above financial or institutional convenience.",
      difficulty: 2,
    },
    {
      question_text: "Which organizational pattern does an essay use when it presents a problem and then offers solutions?",
      choice_a: "Chronological order",
      choice_b: "Compare and contrast",
      choice_c: "Problem-solution",
      choice_d: "Cause and effect",
      correct_choice: "c",
      explanation: "The problem-solution pattern presents an issue and then discusses ways to address it.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The committee's report, buried in footnotes, acknowledged that the original study had a flawed sample size.' What can be inferred?",
      choice_a: "The committee was transparent about the flaw.",
      choice_b: "The committee tried to minimize attention to the flaw.",
      choice_c: "The flawed data was corrected before publication.",
      choice_d: "The study's conclusions were withdrawn.",
      correct_choice: "b",
      explanation: "'Buried in footnotes' implies the disclosure was deliberately made inconspicuous.",
      difficulty: 3,
    },
    {
      question_text: "What is the purpose of a thesis statement in an essay?",
      choice_a: "To summarize research findings",
      choice_b: "To provide background information",
      choice_c: "To state the central argument or claim",
      choice_d: "To list supporting evidence",
      correct_choice: "c",
      explanation: "A thesis statement presents the main argument or claim that the essay will support.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'She spoke softly but with precision, choosing each word as carefully as a surgeon selects instruments.' What literary device is used?",
      choice_a: "Hyperbole",
      choice_b: "Simile",
      choice_c: "Personification",
      choice_d: "Onomatopoeia",
      correct_choice: "b",
      explanation: "The comparison using 'as...as a surgeon' is a simile — a direct comparison using 'like' or 'as'.",
      difficulty: 1,
    },
  ],

  // ── ACET: Integrated Science ─────────────────────────────────────────────
  "acet-integrated-science": [
    {
      question_text: "A car decelerates from 30 m/s to 0 m/s over 6 seconds. What is the deceleration?",
      choice_a: "3 m/s²",
      choice_b: "5 m/s²",
      choice_c: "6 m/s²",
      choice_d: "180 m/s²",
      correct_choice: "b",
      explanation: "Deceleration = change in velocity / time = 30 / 6 = 5 m/s².",
      difficulty: 2,
    },
    {
      question_text: "Which type of chemical bond involves the sharing of electrons between atoms?",
      choice_a: "Ionic bond",
      choice_b: "Covalent bond",
      choice_c: "Metallic bond",
      choice_d: "Hydrogen bond",
      correct_choice: "b",
      explanation: "Covalent bonds form when atoms share electrons, as in water (H₂O) and carbon dioxide (CO₂).",
      difficulty: 1,
    },
    {
      question_text: "Which organelle is responsible for producing ATP in eukaryotic cells?",
      choice_a: "Nucleus",
      choice_b: "Ribosome",
      choice_c: "Mitochondria",
      choice_d: "Golgi apparatus",
      correct_choice: "c",
      explanation: "The mitochondria is the site of cellular respiration and produces most of the cell's ATP.",
      difficulty: 1,
    },
    {
      question_text: "According to Newton's Third Law, when a person pushes a wall:",
      choice_a: "The wall exerts no force on the person.",
      choice_b: "The wall exerts an equal and opposite force on the person.",
      choice_c: "The person exerts more force than the wall.",
      choice_d: "The forces cancel out and nothing moves.",
      correct_choice: "b",
      explanation: "Newton's Third Law states that for every action there is an equal and opposite reaction.",
      difficulty: 1,
    },
    {
      question_text: "What is the pH of a neutral solution at 25°C?",
      choice_a: "0",
      choice_b: "5",
      choice_c: "7",
      choice_d: "14",
      correct_choice: "c",
      explanation: "A neutral solution has a pH of 7, where the concentration of H⁺ and OH⁻ ions are equal.",
      difficulty: 1,
    },
    {
      question_text: "In which phase of mitosis do chromosomes align along the cell's equatorial plane?",
      choice_a: "Prophase",
      choice_b: "Metaphase",
      choice_c: "Anaphase",
      choice_d: "Telophase",
      correct_choice: "b",
      explanation: "During metaphase, chromosomes align along the metaphase plate (cell equator) before being pulled apart.",
      difficulty: 2,
    },
    {
      question_text: "Which electromagnetic wave has the highest frequency?",
      choice_a: "Radio waves",
      choice_b: "Visible light",
      choice_c: "X-rays",
      choice_d: "Gamma rays",
      correct_choice: "d",
      explanation: "Gamma rays have the highest frequency (and shortest wavelength) in the electromagnetic spectrum.",
      difficulty: 2,
    },
    {
      question_text: "What type of reaction releases energy to the surroundings?",
      choice_a: "Endothermic",
      choice_b: "Catalytic",
      choice_c: "Exothermic",
      choice_d: "Equilibrium",
      correct_choice: "c",
      explanation: "Exothermic reactions release energy (heat) to the surroundings; endothermic reactions absorb it.",
      difficulty: 1,
    },
    {
      question_text: "A Punnett square shows that two heterozygous parents (Aa × Aa) will produce offspring in which ratio?",
      choice_a: "1 AA : 2 Aa : 1 aa",
      choice_b: "3 AA : 1 aa",
      choice_c: "All Aa",
      choice_d: "1 AA : 1 aa",
      correct_choice: "a",
      explanation: "Crossing Aa × Aa yields 1 AA : 2 Aa : 1 aa (1/4 dominant homozygous, 2/4 heterozygous, 1/4 recessive homozygous).",
      difficulty: 2,
    },
    {
      question_text: "What is the primary function of the large intestine?",
      choice_a: "Protein digestion",
      choice_b: "Nutrient absorption",
      choice_c: "Water absorption and waste formation",
      choice_d: "Bile production",
      correct_choice: "c",
      explanation: "The large intestine primarily absorbs water and electrolytes from indigestible food matter and forms feces.",
      difficulty: 2,
    },
    {
      question_text: "Which gas law states that at constant temperature, pressure and volume of a gas are inversely proportional?",
      choice_a: "Charles's Law",
      choice_b: "Avogadro's Law",
      choice_c: "Boyle's Law",
      choice_d: "Gay-Lussac's Law",
      correct_choice: "c",
      explanation: "Boyle's Law: P₁V₁ = P₂V₂ at constant temperature — pressure and volume are inversely proportional.",
      difficulty: 2,
    },
    {
      question_text: "Which process converts light energy into chemical energy in plants?",
      choice_a: "Cellular respiration",
      choice_b: "Transpiration",
      choice_c: "Fermentation",
      choice_d: "Photosynthesis",
      correct_choice: "d",
      explanation: "Photosynthesis uses light energy to convert CO₂ and water into glucose and oxygen.",
      difficulty: 1,
    },
  ],

  // ── ACET: Algebraic Reasoning ─────────────────────────────────────────────
  "acet-algebraic-reasoning": [
    {
      question_text: "Solve for x: 3x − 7 = 14",
      choice_a: "x = 3",
      choice_b: "x = 5",
      choice_c: "x = 7",
      choice_d: "x = 9",
      correct_choice: "c",
      explanation: "3x = 14 + 7 = 21, so x = 7.",
      difficulty: 1,
    },
    {
      question_text: "If f(x) = 2x² − 3x + 1, what is f(−1)?",
      choice_a: "6",
      choice_b: "0",
      choice_c: "−4",
      choice_d: "2",
      correct_choice: "a",
      explanation: "f(−1) = 2(1) − 3(−1) + 1 = 2 + 3 + 1 = 6.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is a factor of x² − 5x + 6?",
      choice_a: "(x − 1)",
      choice_b: "(x − 2)",
      choice_c: "(x + 3)",
      choice_d: "(x + 6)",
      correct_choice: "b",
      explanation: "x² − 5x + 6 = (x − 2)(x − 3). Both (x − 2) and (x − 3) are factors.",
      difficulty: 2,
    },
    {
      question_text: "Solve the system: x + y = 10 and x − y = 4. What is x?",
      choice_a: "3",
      choice_b: "5",
      choice_c: "7",
      choice_d: "9",
      correct_choice: "c",
      explanation: "Adding both equations: 2x = 14, so x = 7. Then y = 3.",
      difficulty: 2,
    },
    {
      question_text: "What is the value of 2⁻³?",
      choice_a: "−6",
      choice_b: "−8",
      choice_c: "1/8",
      choice_d: "8",
      correct_choice: "c",
      explanation: "2⁻³ = 1/2³ = 1/8.",
      difficulty: 2,
    },
    {
      question_text: "Simplify: (3a²b)(2ab³)",
      choice_a: "5a³b⁴",
      choice_b: "6a³b⁴",
      choice_c: "6a²b⁴",
      choice_d: "5a²b³",
      correct_choice: "b",
      explanation: "Multiply coefficients: 3 × 2 = 6. Add exponents: a^(2+1) = a³, b^(1+3) = b⁴. Result: 6a³b⁴.",
      difficulty: 2,
    },
    {
      question_text: "If the slope of a line is −2 and it passes through (0, 5), what is the equation of the line?",
      choice_a: "y = −2x − 5",
      choice_b: "y = 2x + 5",
      choice_c: "y = −2x + 5",
      choice_d: "y = 5x − 2",
      correct_choice: "c",
      explanation: "Using slope-intercept form y = mx + b with m = −2 and b = 5: y = −2x + 5.",
      difficulty: 1,
    },
    {
      question_text: "The roots of 2x² − 8x = 0 are:",
      choice_a: "x = 0 and x = 2",
      choice_b: "x = 0 and x = 4",
      choice_c: "x = 2 and x = 4",
      choice_d: "x = −4 and x = 4",
      correct_choice: "b",
      explanation: "Factor: 2x(x − 4) = 0. So x = 0 or x = 4.",
      difficulty: 2,
    },
    {
      question_text: "How many solutions does the equation |2x − 3| = 7 have?",
      choice_a: "0",
      choice_b: "1",
      choice_c: "2",
      choice_d: "3",
      correct_choice: "c",
      explanation: "|2x − 3| = 7 gives 2x − 3 = 7 (x = 5) and 2x − 3 = −7 (x = −2). Two solutions.",
      difficulty: 2,
    },
    {
      question_text: "If 5 is subtracted from three times a number, the result is 22. What is the number?",
      choice_a: "7",
      choice_b: "8",
      choice_c: "9",
      choice_d: "11",
      correct_choice: "c",
      explanation: "3n − 5 = 22 → 3n = 27 → n = 9.",
      difficulty: 1,
    },
    {
      question_text: "Simplify: (x² − 9) / (x − 3), where x ≠ 3",
      choice_a: "x − 3",
      choice_b: "x + 3",
      choice_c: "x²",
      choice_d: "x − 9",
      correct_choice: "b",
      explanation: "x² − 9 = (x+3)(x−3). Dividing by (x−3) gives x + 3.",
      difficulty: 2,
    },
    {
      question_text: "For which values of k does kx² + 4x + 1 = 0 have exactly one solution?",
      choice_a: "k = 1",
      choice_b: "k = 2",
      choice_c: "k = 4",
      choice_d: "k = 16",
      correct_choice: "c",
      explanation: "One solution when discriminant = 0: 16 − 4k = 0 → k = 4.",
      difficulty: 3,
    },
  ],

  // ── DLSU: Language Arts ───────────────────────────────────────────────────
  "dlsu-language-arts": [
    {
      question_text: "Choose the sentence that is grammatically correct:",
      choice_a: "Each of the students have submitted their project.",
      choice_b: "Each of the students has submitted their project.",
      choice_c: "Each of the students have submitted his project.",
      choice_d: "Each of the students has submitted his or her project.",
      correct_choice: "d",
      explanation: "'Each' is singular and takes a singular verb ('has') and singular pronoun ('his or her').",
      difficulty: 2,
    },
    {
      question_text: "Which word means the same as 'tenacious'?",
      choice_a: "Flexible",
      choice_b: "Persistent",
      choice_c: "Timid",
      choice_d: "Reckless",
      correct_choice: "b",
      explanation: "'Tenacious' means holding firmly to something; not giving up — synonymous with persistent.",
      difficulty: 2,
    },
    {
      question_text: "Identify the misplaced modifier in: 'I almost drove my children to school every day last year.'",
      choice_a: "Almost",
      choice_b: "Every day",
      choice_c: "Last year",
      choice_d: "To school",
      correct_choice: "a",
      explanation: "'Almost' is misplaced — it modifies 'drove' but should modify 'every day'. Correct: 'I drove my children to school almost every day last year.'",
      difficulty: 3,
    },
    {
      question_text: "Which sentence uses a semicolon correctly?",
      choice_a: "I went to the store; and bought milk.",
      choice_b: "She was tired; however, she finished the report.",
      choice_c: "He likes; apples, oranges, and grapes.",
      choice_d: "They left; because it was raining.",
      correct_choice: "b",
      explanation: "A semicolon correctly joins two independent clauses, especially with a conjunctive adverb like 'however'.",
      difficulty: 2,
    },
    {
      question_text: "The antonym of 'magnanimous' is:",
      choice_a: "Generous",
      choice_b: "Petty",
      choice_c: "Courageous",
      choice_d: "Wise",
      correct_choice: "b",
      explanation: "'Magnanimous' means generous and forgiving. Its antonym is 'petty' — small-minded or ungenerous.",
      difficulty: 3,
    },
    {
      question_text: "Which of the following is an example of an oxymoron?",
      choice_a: "The stars danced in the sky.",
      choice_b: "She ran as fast as a cheetah.",
      choice_c: "It was a deafening silence.",
      choice_d: "The wind whispered through the trees.",
      correct_choice: "c",
      explanation: "'Deafening silence' is an oxymoron — two contradictory terms placed together.",
      difficulty: 2,
    },
    {
      question_text: "In formal writing, which should replace 'kind of' or 'sort of'?",
      choice_a: "Somewhat",
      choice_b: "Kinda",
      choice_c: "A bit",
      choice_d: "Pretty much",
      correct_choice: "a",
      explanation: "'Somewhat' is the formal equivalent of the informal 'kind of' or 'sort of'.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence is in passive voice?",
      choice_a: "The teacher graded the exams quickly.",
      choice_b: "The exams were graded by the teacher.",
      choice_c: "The teacher has been grading the exams.",
      choice_d: "The teacher will grade the exams tomorrow.",
      correct_choice: "b",
      explanation: "Passive voice is formed with be + past participle ('were graded'). The subject receives the action.",
      difficulty: 1,
    },
    {
      question_text: "Choose the word with the correct spelling:",
      choice_a: "Accomodate",
      choice_b: "Accommodate",
      choice_c: "Acommodate",
      choice_d: "Accomadate",
      correct_choice: "b",
      explanation: "'Accommodate' has two c's and two m's — one of the most commonly misspelled English words.",
      difficulty: 1,
    },
    {
      question_text: "Which sentence uses the word 'affect' correctly?",
      choice_a: "The medicine had no affect on the patient.",
      choice_b: "What affect did the news have on you?",
      choice_c: "The cold weather will affect the harvest.",
      choice_d: "The storm had a negative affect on travel.",
      correct_choice: "c",
      explanation: "'Affect' is a verb meaning to influence. 'Effect' is usually the noun. Option C uses 'affect' correctly as a verb.",
      difficulty: 2,
    },
    {
      question_text: "What is an 'appositive' in grammar?",
      choice_a: "A word that modifies a verb",
      choice_b: "A noun phrase that renames or explains another noun",
      choice_c: "A conjunction joining two clauses",
      choice_d: "A verb form used as a noun",
      correct_choice: "b",
      explanation: "An appositive is a noun or noun phrase placed next to another noun to identify or describe it (e.g., 'My friend, a doctor, lives nearby').",
      difficulty: 3,
    },
    {
      question_text: "Select the sentence with correct subject-verb agreement:",
      choice_a: "The news are shocking.",
      choice_b: "The news is shocking.",
      choice_c: "The news were shocking.",
      choice_d: "The news have been shocking.",
      correct_choice: "b",
      explanation: "'News' is an uncountable noun that always takes a singular verb.",
      difficulty: 1,
    },
  ],

  // ── DLSU: Comprehension Skills ────────────────────────────────────────────
  "dlsu-comprehension": [
    {
      question_text: "Read: 'Urbanization has led to both unprecedented economic growth and widening inequality, challenging cities to balance development with social equity.' What is the central tension described?",
      choice_a: "Rural vs. urban migration",
      choice_b: "Economic growth vs. social equity",
      choice_c: "Public vs. private development",
      choice_d: "National vs. local governance",
      correct_choice: "b",
      explanation: "The passage explicitly identifies economic growth and social equity as the two conflicting forces in urbanization.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Renewable energy capacity grew by 10% globally last year, yet coal still accounts for 38% of electricity generation.' What can be concluded?",
      choice_a: "Renewables will replace coal within a decade.",
      choice_b: "Coal is declining faster than expected.",
      choice_c: "Significant growth in renewables has not displaced coal dominance.",
      choice_d: "Energy generation is increasingly clean.",
      correct_choice: "c",
      explanation: "Despite renewable growth, coal still dominates at 38% of electricity generation, indicating renewables have not yet displaced it.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following best defines 'implicit bias' as used in social science writing?",
      choice_a: "A conscious preference for a group",
      choice_b: "An unconscious attitude affecting judgment",
      choice_c: "An openly stated prejudice",
      choice_d: "A deliberate act of discrimination",
      correct_choice: "b",
      explanation: "Implicit bias refers to unconscious attitudes or stereotypes that affect decisions without the person's awareness.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The author argues that social media amplifies outrage because platforms optimize for engagement, and outrage generates more engagement than nuanced discourse.' What rhetorical strategy is being used?",
      choice_a: "Appeal to authority",
      choice_b: "Causal reasoning",
      choice_c: "Emotional appeal",
      choice_d: "False analogy",
      correct_choice: "b",
      explanation: "The author establishes a cause-and-effect chain: optimization for engagement → more outrage → more engagement.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'Critics of standardized testing argue it measures test-taking skill more than true academic potential.' What assumption underlies this claim?",
      choice_a: "Standardized tests are too expensive.",
      choice_b: "Test-taking skill and academic potential are distinct.",
      choice_c: "All students have equal access to test preparation.",
      choice_d: "Schools prioritize test preparation over learning.",
      correct_choice: "b",
      explanation: "The argument only makes sense if one assumes that test-taking skill and true academic potential are different things.",
      difficulty: 3,
    },
    {
      question_text: "A paragraph that begins with its topic sentence and ends with a concluding sentence that restates it uses which structure?",
      choice_a: "Inverted pyramid",
      choice_b: "Block format",
      choice_c: "Deductive structure",
      choice_d: "Climactic order",
      correct_choice: "c",
      explanation: "Deductive structure presents the main idea first (topic sentence), then supports it, then restates it — general to specific.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'She had crossed oceans for this moment, and now that it had arrived, she felt nothing.' What effect does the contrast create?",
      choice_a: "It emphasizes her exhaustion from travel.",
      choice_b: "It suggests her great effort yielded unexpected emptiness.",
      choice_c: "It shows she was relieved the journey was over.",
      choice_d: "It indicates she had already achieved her goal before.",
      correct_choice: "b",
      explanation: "The contrast between enormous effort ('crossed oceans') and emotional emptiness ('felt nothing') creates dramatic irony.",
      difficulty: 2,
    },
    {
      question_text: "Which transition word signals a contrast between two ideas?",
      choice_a: "Furthermore",
      choice_b: "Therefore",
      choice_c: "Nevertheless",
      choice_d: "Similarly",
      correct_choice: "c",
      explanation: "'Nevertheless' signals contrast (despite what was said, the opposite is true). 'Furthermore' adds, 'therefore' concludes, 'similarly' compares.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The study found a correlation between screen time and sleep disruption but stopped short of claiming causation.' Why is this distinction important?",
      choice_a: "Correlation proves that one thing causes another.",
      choice_b: "Causation is easier to demonstrate than correlation.",
      choice_c: "A correlation does not mean one variable causes the other.",
      choice_d: "The study results are therefore invalid.",
      correct_choice: "c",
      explanation: "Correlation shows two variables move together; causation means one directly causes the other. These are distinct scientific claims.",
      difficulty: 2,
    },
    {
      question_text: "Read an argument: 'My grandfather smoked all his life and lived to 95, so smoking cannot be that harmful.' What fallacy is this?",
      choice_a: "Slippery slope",
      choice_b: "Ad hominem",
      choice_c: "Anecdotal evidence",
      choice_d: "Straw man",
      correct_choice: "c",
      explanation: "Using a single personal story to contradict broad scientific evidence is the anecdotal evidence fallacy.",
      difficulty: 2,
    },
  ],

  // ── DLSU: Advanced Algebra ────────────────────────────────────────────────
  "dlsu-advanced-algebra": [
    {
      question_text: "What is the sum of the arithmetic series 2 + 5 + 8 + ... + 50?",
      choice_a: "368",
      choice_b: "432",
      choice_c: "442",
      choice_d: "452",
      correct_choice: "c",
      explanation: "Number of terms: (50−2)/3 + 1 = 17. Sum = (17/2)(2 + 50) = (17/2)(52) = 442.",
      difficulty: 3,
    },
    {
      question_text: "Simplify: log₂ 32",
      choice_a: "4",
      choice_b: "5",
      choice_c: "6",
      choice_d: "8",
      correct_choice: "b",
      explanation: "log₂ 32 = log₂ (2⁵) = 5.",
      difficulty: 2,
    },
    {
      question_text: "The mean of 5 numbers is 12. If four of the numbers are 10, 14, 8, and 16, what is the fifth?",
      choice_a: "10",
      choice_b: "12",
      choice_c: "14",
      choice_d: "16",
      correct_choice: "b",
      explanation: "Total = 5 × 12 = 60. Sum of four = 48. Fifth = 60 − 48 = 12.",
      difficulty: 2,
    },
    {
      question_text: "How many ways can 4 students be selected from a group of 10?",
      choice_a: "40",
      choice_b: "210",
      choice_c: "5040",
      choice_d: "10000",
      correct_choice: "b",
      explanation: "C(10,4) = 10! / (4! × 6!) = (10×9×8×7)/(4×3×2×1) = 210.",
      difficulty: 3,
    },
    {
      question_text: "If f(x) = 3x + 2 and g(x) = x², what is (f ∘ g)(3)?",
      choice_a: "11",
      choice_b: "29",
      choice_c: "81",
      choice_d: "121",
      correct_choice: "b",
      explanation: "g(3) = 9. f(g(3)) = f(9) = 3(9) + 2 = 29.",
      difficulty: 2,
    },
    {
      question_text: "Which is the equation of a line perpendicular to y = 3x − 5 passing through (0, 2)?",
      choice_a: "y = 3x + 2",
      choice_b: "y = −(1/3)x + 2",
      choice_c: "y = (1/3)x − 2",
      choice_d: "y = −3x + 2",
      correct_choice: "b",
      explanation: "Perpendicular slope is the negative reciprocal of 3, which is −1/3. With y-intercept 2: y = −(1/3)x + 2.",
      difficulty: 2,
    },
    {
      question_text: "Find the inverse of f(x) = (2x − 1) / 3.",
      choice_a: "f⁻¹(x) = (3x + 1) / 2",
      choice_b: "f⁻¹(x) = 3x + 1",
      choice_c: "f⁻¹(x) = (3x − 1) / 2",
      choice_d: "f⁻¹(x) = 3 / (2x − 1)",
      correct_choice: "a",
      explanation: "Let y = (2x−1)/3. Solve for x: 3y = 2x − 1 → x = (3y + 1)/2. So f⁻¹(x) = (3x + 1)/2.",
      difficulty: 3,
    },
    {
      question_text: "What is the probability of rolling a sum of 7 with two standard dice?",
      choice_a: "1/6",
      choice_b: "1/9",
      choice_c: "7/36",
      choice_d: "1/12",
      correct_choice: "a",
      explanation: "Combinations: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 outcomes out of 36. P = 6/36 = 1/6.",
      difficulty: 2,
    },
    {
      question_text: "Solve: 2^(x+1) = 32",
      choice_a: "x = 3",
      choice_b: "x = 4",
      choice_c: "x = 5",
      choice_d: "x = 6",
      correct_choice: "b",
      explanation: "32 = 2⁵. So 2^(x+1) = 2⁵ → x + 1 = 5 → x = 4.",
      difficulty: 2,
    },
    {
      question_text: "The standard deviation measures:",
      choice_a: "The middle value in a data set",
      choice_b: "The most frequent value",
      choice_c: "The spread of data around the mean",
      choice_d: "The difference between the highest and lowest values",
      correct_choice: "c",
      explanation: "Standard deviation quantifies how much data points deviate from the mean — it measures spread or variability.",
      difficulty: 1,
    },
    {
      question_text: "Expand: (x + 3)³",
      choice_a: "x³ + 9x² + 27x + 27",
      choice_b: "x³ + 3x² + 9x + 27",
      choice_c: "x³ + 27",
      choice_d: "x³ + 6x² + 9x + 27",
      correct_choice: "a",
      explanation: "Using the binomial theorem: (x+3)³ = x³ + 3(3)x² + 3(9)x + 27 = x³ + 9x² + 27x + 27.",
      difficulty: 3,
    },
    {
      question_text: "Two numbers have a sum of 20 and a product of 75. What are the numbers?",
      choice_a: "5 and 15",
      choice_b: "6 and 14",
      choice_c: "7 and 13",
      choice_d: "10 and 10",
      correct_choice: "a",
      explanation: "x + y = 20 and xy = 75. Solving: x² − 20x + 75 = 0 → (x − 5)(x − 15) = 0. Numbers are 5 and 15.",
      difficulty: 2,
    },
    {
      question_text: "If a geometric sequence has first term 3 and common ratio 2, what is the 6th term?",
      choice_a: "48",
      choice_b: "64",
      choice_c: "96",
      choice_d: "192",
      correct_choice: "c",
      explanation: "a_n = ar^(n−1). a_6 = 3 × 2⁵ = 3 × 32 = 96.",
      difficulty: 2,
    },
    {
      question_text: "Solve for x: log₃(x − 2) = 2",
      choice_a: "x = 7",
      choice_b: "x = 9",
      choice_c: "x = 11",
      choice_d: "x = 13",
      correct_choice: "c",
      explanation: "log₃(x−2) = 2 → x − 2 = 3² = 9 → x = 11.",
      difficulty: 3,
    },
    {
      question_text: "Which value of x satisfies the inequality −2x + 5 > 1?",
      choice_a: "x > 2",
      choice_b: "x < 2",
      choice_c: "x > −2",
      choice_d: "x < −2",
      correct_choice: "b",
      explanation: "−2x > −4 → x < 2 (inequality flips when dividing by a negative).",
      difficulty: 2,
    },
  ],

  // ── DLSU: Physical Sciences ───────────────────────────────────────────────
  "dlsu-physical-sciences": [
    {
      question_text: "A 2 kg object moving at 5 m/s has a kinetic energy of:",
      choice_a: "5 J",
      choice_b: "10 J",
      choice_c: "25 J",
      choice_d: "50 J",
      correct_choice: "c",
      explanation: "KE = ½mv² = ½(2)(5²) = ½(2)(25) = 25 J.",
      difficulty: 2,
    },
    {
      question_text: "What is the oxidation state of sulfur in H₂SO₄?",
      choice_a: "+2",
      choice_b: "+4",
      choice_c: "+6",
      choice_d: "+8",
      correct_choice: "c",
      explanation: "H = +1 (×2), O = −2 (×4). 2(+1) + S + 4(−2) = 0 → S = +6.",
      difficulty: 3,
    },
    {
      question_text: "An object is thrown horizontally from a cliff. Which quantity remains constant during its flight (ignoring air resistance)?",
      choice_a: "Vertical velocity",
      choice_b: "Total speed",
      choice_c: "Horizontal velocity",
      choice_d: "Acceleration",
      correct_choice: "c",
      explanation: "In projectile motion, horizontal velocity is constant (no horizontal force). Vertical velocity increases due to gravity.",
      difficulty: 2,
    },
    {
      question_text: "What is the molar mass of CaCO₃? (Ca=40, C=12, O=16)",
      choice_a: "68 g/mol",
      choice_b: "84 g/mol",
      choice_c: "100 g/mol",
      choice_d: "116 g/mol",
      correct_choice: "c",
      explanation: "CaCO₃: Ca(40) + C(12) + 3×O(16) = 40 + 12 + 48 = 100 g/mol.",
      difficulty: 2,
    },
    {
      question_text: "Ohm's Law states that the current through a conductor is:",
      choice_a: "Directly proportional to resistance",
      choice_b: "Inversely proportional to voltage",
      choice_c: "Directly proportional to voltage and inversely to resistance",
      choice_d: "Equal to voltage times resistance",
      correct_choice: "c",
      explanation: "Ohm's Law: I = V/R — current is directly proportional to voltage and inversely proportional to resistance.",
      difficulty: 1,
    },
    {
      question_text: "In which type of nuclear reaction are two light nuclei combined to form a heavier nucleus?",
      choice_a: "Fission",
      choice_b: "Fusion",
      choice_c: "Radioactive decay",
      choice_d: "Beta emission",
      correct_choice: "b",
      explanation: "Nuclear fusion combines light nuclei (e.g., hydrogen isotopes) into a heavier nucleus, releasing energy.",
      difficulty: 2,
    },
    {
      question_text: "What type of reaction is: 2H₂ + O₂ → 2H₂O?",
      choice_a: "Decomposition",
      choice_b: "Single displacement",
      choice_c: "Double displacement",
      choice_d: "Combination (synthesis)",
      correct_choice: "d",
      explanation: "Two or more reactants combine to form a single product — this is a combination (synthesis) reaction.",
      difficulty: 1,
    },
    {
      question_text: "A wave has frequency 500 Hz and wavelength 0.68 m. What is its speed?",
      choice_a: "170 m/s",
      choice_b: "340 m/s",
      choice_c: "500 m/s",
      choice_d: "680 m/s",
      correct_choice: "b",
      explanation: "Speed = frequency × wavelength = 500 × 0.68 = 340 m/s (approximately the speed of sound in air).",
      difficulty: 2,
    },
    {
      question_text: "Which subatomic particle has a negative charge?",
      choice_a: "Proton",
      choice_b: "Neutron",
      choice_c: "Electron",
      choice_d: "Positron",
      correct_choice: "c",
      explanation: "Electrons carry a negative charge (−1), protons carry a positive charge (+1), and neutrons have no charge.",
      difficulty: 1,
    },
    {
      question_text: "The law of conservation of energy states that energy:",
      choice_a: "Can be created but not destroyed",
      choice_b: "Can be destroyed but not created",
      choice_c: "Cannot be created or destroyed",
      choice_d: "Decreases in every real process",
      correct_choice: "c",
      explanation: "Energy cannot be created or destroyed, only converted from one form to another.",
      difficulty: 1,
    },
  ],

  // ── UST: Language Proficiency ─────────────────────────────────────────────
  "ust-language-topic": [
    {
      question_text: "Piliin ang wastong pangungusap:",
      choice_a: "Siya at ako ay nagpunta sa palengke.",
      choice_b: "Siya at ako ay nagpunta sa palengke.",
      choice_c: "Kami at siya ay nagpunta sa palengke.",
      choice_d: "Ako at siya ay nagpunta sa palengke.",
      correct_choice: "a",
      explanation: "Sa Filipino, ang tamang ayos ng panghalip ay 'Siya at ako' — ang nagsasalita ay ibinababa ang sarili.",
      difficulty: 2,
    },
    {
      question_text: "Which sentence correctly uses the word 'infer'?",
      choice_a: "The doctor inferred the patient with the diagnosis.",
      choice_b: "From the clues, the detective inferred who had committed the crime.",
      choice_c: "She inferred the answer to the teacher.",
      choice_d: "The textbook infers that the topic is important.",
      correct_choice: "b",
      explanation: "'Infer' means to deduce or conclude from evidence. The detective drew a conclusion from clues.",
      difficulty: 2,
    },
    {
      question_text: "Choose the word that means 'relating to the body':",
      choice_a: "Cerebral",
      choice_b: "Visceral",
      choice_c: "Somatic",
      choice_d: "Neural",
      correct_choice: "c",
      explanation: "'Somatic' means relating to the body, as opposed to the mind. Commonly used in medical contexts.",
      difficulty: 3,
    },
    {
      question_text: "Which sentence has an error in capitalization?",
      choice_a: "She studied Biology at the University of Santo Tomas.",
      choice_b: "She studied biology at the University of Santo Tomas.",
      choice_c: "She studied Biology at the university of Santo Tomas.",
      choice_d: "She studied biology at the University of Santo Tomas.",
      correct_choice: "a",
      explanation: "Academic subjects are not capitalized unless they are proper nouns (like a language). 'Biology' should be lowercase.",
      difficulty: 2,
    },
    {
      question_text: "Select the correct form: 'The data ___ inconclusive.'",
      choice_a: "is",
      choice_b: "are",
      choice_c: "were",
      choice_d: "has been",
      correct_choice: "b",
      explanation: "'Data' is the plural of 'datum' and technically takes a plural verb in formal/academic writing.",
      difficulty: 3,
    },
    {
      question_text: "What does 'ipso facto' mean?",
      choice_a: "By that very fact",
      choice_b: "In good faith",
      choice_c: "Among other things",
      choice_d: "By virtue of office",
      correct_choice: "a",
      explanation: "'Ipso facto' is a Latin phrase meaning 'by that very fact' or 'as a direct consequence'.",
      difficulty: 3,
    },
    {
      question_text: "Which is the best revision of: 'Due to the fact that it was raining, we stayed home.'",
      choice_a: "Because of the fact of rain, we stayed home.",
      choice_b: "Because it was raining, we stayed home.",
      choice_c: "On account of raining, we stayed home.",
      choice_d: "Since the reason was rain, we stayed home.",
      correct_choice: "b",
      explanation: "'Because' is more concise than 'due to the fact that'. Option B eliminates unnecessary wordiness.",
      difficulty: 1,
    },
    {
      question_text: "Identify the sentence in future perfect tense:",
      choice_a: "She will study medicine.",
      choice_b: "She studies medicine.",
      choice_c: "She will have studied medicine by next year.",
      choice_d: "She has been studying medicine.",
      correct_choice: "c",
      explanation: "Future perfect tense (will + have + past participle) expresses an action completed before a future point.",
      difficulty: 2,
    },
    {
      question_text: "What is the meaning of the root 'bio'?",
      choice_a: "Sound",
      choice_b: "Life",
      choice_c: "Earth",
      choice_d: "Water",
      correct_choice: "b",
      explanation: "The Greek root 'bio' means life — seen in words like biology, biography, and biopsy.",
      difficulty: 1,
    },
    {
      question_text: "Choose the sentence without redundancy:",
      choice_a: "The final conclusion at the end was clear.",
      choice_b: "The end result was a new beginning.",
      choice_c: "The conclusion was clear.",
      choice_d: "The final result at the end was a conclusion.",
      correct_choice: "c",
      explanation: "'The conclusion was clear' is concise. The other options contain redundant words ('final conclusion', 'end result').",
      difficulty: 2,
    },
    {
      question_text: "What rhetorical device is used in: 'Ask not what your country can do for you; ask what you can do for your country'?",
      choice_a: "Alliteration",
      choice_b: "Anaphora",
      choice_c: "Chiasmus",
      choice_d: "Hyperbole",
      correct_choice: "c",
      explanation: "Chiasmus reverses the structure of two phrases. 'What your country can do for you' vs. 'what you can do for your country' reverses the order.",
      difficulty: 3,
    },
    {
      question_text: "Which is the correct possessive form for a plural noun ending in -s?",
      choice_a: "The student's projects are due.",
      choice_b: "The students's projects are due.",
      choice_c: "The students' projects are due.",
      choice_d: "The students projects' are due.",
      correct_choice: "c",
      explanation: "For plural nouns ending in -s, the possessive is formed by adding only an apostrophe after the final s.",
      difficulty: 2,
    },
  ],

  // ── UST: Reading Skills ───────────────────────────────────────────────────
  "ust-reading-skills": [
    {
      question_text: "Read: 'The Hippocratic tradition emphasizes that a physician must first do no harm — primum non nocere — before pursuing any intervention.' What does this principle prioritize?",
      choice_a: "Speed of treatment",
      choice_b: "Patient safety over aggressive treatment",
      choice_c: "Modern medical technology",
      choice_d: "Cost-effective care",
      correct_choice: "b",
      explanation: "Primum non nocere means 'first, do no harm' — prioritizing patient safety before considering any risky intervention.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'While antibiotics revolutionized medicine in the 20th century, their overuse has created drug-resistant bacteria, threatening to undo these gains.' What is the passage's main message?",
      choice_a: "Antibiotics should be banned.",
      choice_b: "A medical breakthrough has created a new threat through misuse.",
      choice_c: "Bacteria are becoming weaker over time.",
      choice_d: "Doctors prescribe too many medicines.",
      correct_choice: "b",
      explanation: "The passage describes how overuse of a beneficial innovation (antibiotics) has produced a dangerous unintended consequence (resistance).",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Public health campaigns reduced smoking rates by 40% over two decades, yet lung cancer rates fell by only 20%.' What does this suggest?",
      choice_a: "Smoking campaigns were ineffective.",
      choice_b: "Lung cancer has other contributing factors beyond smoking.",
      choice_c: "The campaigns caused lung cancer.",
      choice_d: "Lung cancer rates should have dropped by 40%.",
      correct_choice: "b",
      explanation: "The disparity between smoking reduction (40%) and cancer reduction (20%) suggests other factors contribute to lung cancer beyond smoking.",
      difficulty: 3,
    },
    {
      question_text: "What is the purpose of an abstract in a scientific paper?",
      choice_a: "To provide detailed methodology",
      choice_b: "To list all references used",
      choice_c: "To summarize the key points of the study",
      choice_d: "To present raw data",
      correct_choice: "c",
      explanation: "An abstract is a brief summary of a research paper, covering its purpose, methods, results, and conclusion.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'The patient exhibited classic symptoms: fever, cough, and fatigue. Upon examination, however, the diagnosis was more complex.' What word signals a contrast?",
      choice_a: "Classic",
      choice_b: "However",
      choice_c: "Upon",
      choice_d: "Exhibited",
      correct_choice: "b",
      explanation: "'However' is a contrastive conjunction indicating that what follows contradicts or complicates what was previously stated.",
      difficulty: 1,
    },
    {
      question_text: "Read: 'A placebo is an inert substance with no therapeutic effect. Yet in clinical trials, patients who receive placebos often report improvement.' What phenomenon is being described?",
      choice_a: "The power of actual medicine",
      choice_b: "Clinical trial error",
      choice_c: "The placebo effect",
      choice_d: "The nocebo effect",
      correct_choice: "c",
      explanation: "The placebo effect is the measurable improvement patients experience from inactive treatments, driven by belief and expectation.",
      difficulty: 2,
    },
    {
      question_text: "Which of the following is the best example of an objective statement?",
      choice_a: "Doctors work too many hours and deserve better pay.",
      choice_b: "The study found that 70% of participants improved with the treatment.",
      choice_c: "This medicine is clearly superior to others.",
      choice_d: "Everyone should exercise daily.",
      correct_choice: "b",
      explanation: "An objective statement is based on measurable evidence. Option B cites a specific, verifiable finding.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'The ethics committee rejected the proposal not because the science was flawed, but because the risks to participants were not adequately disclosed.' What was the basis for rejection?",
      choice_a: "Weak research methodology",
      choice_b: "Lack of informed consent provisions",
      choice_c: "Insufficient funding",
      choice_d: "Incorrect data analysis",
      correct_choice: "b",
      explanation: "The rejection was based on inadequate disclosure of risks — a core element of informed consent in research ethics.",
      difficulty: 2,
    },
    {
      question_text: "When a research article says a finding is 'statistically significant at p < 0.05,' it means:",
      choice_a: "The result is practically important.",
      choice_b: "There is less than a 5% chance the result occurred by chance.",
      choice_c: "95% of the population will experience this effect.",
      choice_d: "The sample size was 95.",
      correct_choice: "b",
      explanation: "p < 0.05 means there is less than a 5% probability that the observed result occurred by random chance.",
      difficulty: 3,
    },
    {
      question_text: "Read: 'Though often assumed to be opposites, mental and physical health are deeply interconnected — poor physical health can lead to depression, while chronic stress can manifest as physical symptoms.' What is the author's claim?",
      choice_a: "Mental and physical health are completely separate.",
      choice_b: "Only physical health affects mental health.",
      choice_c: "Mental and physical health are bidirectionally linked.",
      choice_d: "Stress always causes physical illness.",
      correct_choice: "c",
      explanation: "The author argues the link works both ways: physical → mental and mental → physical, making it bidirectional.",
      difficulty: 2,
    },
    {
      question_text: "Which type of evidence is generally considered most reliable in medical research?",
      choice_a: "Expert opinion",
      choice_b: "Case studies",
      choice_c: "Anecdotal reports",
      choice_d: "Randomized controlled trials",
      correct_choice: "d",
      explanation: "Randomized controlled trials (RCTs) are considered the gold standard in medical research because they minimize bias.",
      difficulty: 2,
    },
    {
      question_text: "Read: 'Correlation does not imply causation.' Which of the following is an example of this error?",
      choice_a: "Hospitals with more patients have higher death rates, therefore hospitals cause death.",
      choice_b: "Exercise reduces the risk of heart disease.",
      choice_c: "Smoking causes lung cancer.",
      choice_d: "Vaccines prevent infectious disease.",
      correct_choice: "a",
      explanation: "More patients (sick people) in hospitals correlates with deaths, but the hospital doesn't cause it — this is a classic correlation/causation error.",
      difficulty: 3,
    },
  ],

  // ── UST: Life Sciences ────────────────────────────────────────────────────
  "ust-life-sciences": [
    {
      question_text: "Which blood type is the universal donor for red blood cell transfusions?",
      choice_a: "Type A",
      choice_b: "Type B",
      choice_c: "Type AB",
      choice_d: "Type O negative",
      correct_choice: "d",
      explanation: "Type O negative red blood cells have no A, B, or Rh antigens, so they can be given to patients of any blood type.",
      difficulty: 1,
    },
    {
      question_text: "Which chamber of the heart pumps oxygenated blood to the body?",
      choice_a: "Right atrium",
      choice_b: "Right ventricle",
      choice_c: "Left atrium",
      choice_d: "Left ventricle",
      correct_choice: "d",
      explanation: "The left ventricle pumps oxygenated blood through the aorta into systemic circulation.",
      difficulty: 1,
    },
    {
      question_text: "What is the role of hemoglobin in the blood?",
      choice_a: "Clotting blood after injury",
      choice_b: "Fighting bacterial infection",
      choice_c: "Carrying oxygen to body tissues",
      choice_d: "Filtering waste in the kidneys",
      correct_choice: "c",
      explanation: "Hemoglobin is a protein in red blood cells that binds to oxygen in the lungs and transports it to tissues.",
      difficulty: 1,
    },
    {
      question_text: "Which hormone is produced by the pancreas and regulates blood sugar?",
      choice_a: "Thyroxine",
      choice_b: "Adrenaline",
      choice_c: "Insulin",
      choice_d: "Cortisol",
      correct_choice: "c",
      explanation: "Insulin is produced by beta cells in the islets of Langerhans in the pancreas and lowers blood glucose levels.",
      difficulty: 1,
    },
    {
      question_text: "During which phase of the cell cycle does DNA replication occur?",
      choice_a: "G1 phase",
      choice_b: "S phase",
      choice_c: "G2 phase",
      choice_d: "M phase",
      correct_choice: "b",
      explanation: "DNA replication occurs during the S (synthesis) phase of interphase.",
      difficulty: 2,
    },
    {
      question_text: "What is the difference between a virus and a bacterium?",
      choice_a: "Bacteria are smaller than viruses.",
      choice_b: "Viruses can reproduce independently; bacteria cannot.",
      choice_c: "Bacteria are living cells; viruses are not considered living organisms.",
      choice_d: "Viruses are treated with antibiotics; bacteria are not.",
      correct_choice: "c",
      explanation: "Bacteria are single-celled living organisms. Viruses are not considered living because they cannot replicate without a host cell.",
      difficulty: 2,
    },
    {
      question_text: "Which part of the neuron receives signals from other neurons?",
      choice_a: "Axon",
      choice_b: "Myelin sheath",
      choice_c: "Cell body",
      choice_d: "Dendrites",
      correct_choice: "d",
      explanation: "Dendrites are the branching extensions of a neuron that receive chemical signals (neurotransmitters) from other neurons.",
      difficulty: 2,
    },
    {
      question_text: "What type of mutation results in a premature stop codon in a protein?",
      choice_a: "Missense mutation",
      choice_b: "Silent mutation",
      choice_c: "Nonsense mutation",
      choice_d: "Frameshift mutation",
      correct_choice: "c",
      explanation: "A nonsense mutation changes a codon to a stop codon, terminating translation early and usually producing a nonfunctional protein.",
      difficulty: 3,
    },
    {
      question_text: "Which vitamin is synthesized in the skin upon exposure to sunlight?",
      choice_a: "Vitamin A",
      choice_b: "Vitamin B12",
      choice_c: "Vitamin C",
      choice_d: "Vitamin D",
      correct_choice: "d",
      explanation: "Vitamin D is synthesized in the skin from 7-dehydrocholesterol when exposed to UVB radiation from sunlight.",
      difficulty: 1,
    },
    {
      question_text: "The central dogma of molecular biology describes which flow of information?",
      choice_a: "Protein → RNA → DNA",
      choice_b: "DNA → RNA → Protein",
      choice_c: "RNA → Protein → DNA",
      choice_d: "DNA → Protein → RNA",
      correct_choice: "b",
      explanation: "The central dogma: DNA is transcribed into RNA, which is then translated into protein.",
      difficulty: 2,
    },
    {
      question_text: "What is the term for the type of immunity acquired after surviving an infection?",
      choice_a: "Innate immunity",
      choice_b: "Passive immunity",
      choice_c: "Active acquired immunity",
      choice_d: "Herd immunity",
      correct_choice: "c",
      explanation: "Active acquired immunity develops after exposure to a pathogen (through infection or vaccination), producing memory cells.",
      difficulty: 2,
    },
    {
      question_text: "Which enzyme is responsible for joining Okazaki fragments during DNA replication?",
      choice_a: "DNA helicase",
      choice_b: "DNA polymerase III",
      choice_c: "DNA ligase",
      choice_d: "Primase",
      correct_choice: "c",
      explanation: "DNA ligase joins Okazaki fragments on the lagging strand by catalyzing phosphodiester bond formation.",
      difficulty: 3,
    },
  ],

  // ── UST: Mathematics ──────────────────────────────────────────────────────
  "ust-math-topic": [
    {
      question_text: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
      choice_a: "10",
      choice_b: "12",
      choice_c: "14",
      choice_d: "√100",
      correct_choice: "a",
      explanation: "By the Pythagorean theorem: c² = 6² + 8² = 36 + 64 = 100, so c = 10.",
      difficulty: 1,
    },
    {
      question_text: "What is 15% of 240?",
      choice_a: "30",
      choice_b: "36",
      choice_c: "40",
      choice_d: "48",
      correct_choice: "b",
      explanation: "15% of 240 = 0.15 × 240 = 36.",
      difficulty: 1,
    },
    {
      question_text: "In how many ways can 3 books be selected and arranged on a shelf from 5 different books?",
      choice_a: "10",
      choice_b: "20",
      choice_c: "60",
      choice_d: "120",
      correct_choice: "c",
      explanation: "This is a permutation: P(5,3) = 5!/(5−3)! = 5 × 4 × 3 = 60.",
      difficulty: 3,
    },
    {
      question_text: "Solve: 4(x − 3) = 2x + 6",
      choice_a: "x = 6",
      choice_b: "x = 7",
      choice_c: "x = 8",
      choice_d: "x = 9",
      correct_choice: "d",
      explanation: "4x − 12 = 2x + 6 → 2x = 18 → x = 9.",
      difficulty: 1,
    },
    {
      question_text: "The area of a circle with diameter 14 cm is approximately: (π ≈ 3.14)",
      choice_a: "43.96 cm²",
      choice_b: "87.92 cm²",
      choice_c: "153.86 cm²",
      choice_d: "615.44 cm²",
      correct_choice: "c",
      explanation: "Radius = 7. Area = πr² = 3.14 × 49 = 153.86 cm².",
      difficulty: 2,
    },
    {
      question_text: "If sin θ = 3/5, what is cos θ? (θ in the first quadrant)",
      choice_a: "3/4",
      choice_b: "4/5",
      choice_c: "5/3",
      choice_d: "5/4",
      correct_choice: "b",
      explanation: "Using sin²θ + cos²θ = 1: cos²θ = 1 − 9/25 = 16/25, so cos θ = 4/5.",
      difficulty: 2,
    },
    {
      question_text: "A train travels 360 km at 90 km/h. How long does the trip take?",
      choice_a: "3 hours",
      choice_b: "4 hours",
      choice_c: "5 hours",
      choice_d: "6 hours",
      correct_choice: "b",
      explanation: "Time = Distance/Speed = 360/90 = 4 hours.",
      difficulty: 1,
    },
    {
      question_text: "What is the volume of a rectangular box with dimensions 5 cm × 4 cm × 3 cm?",
      choice_a: "47 cm³",
      choice_b: "60 cm³",
      choice_c: "72 cm³",
      choice_d: "94 cm³",
      correct_choice: "b",
      explanation: "Volume = l × w × h = 5 × 4 × 3 = 60 cm³.",
      difficulty: 1,
    },
    {
      question_text: "In a class of 40 students, 25 play basketball, 20 play volleyball, and 10 play both. How many play neither?",
      choice_a: "0",
      choice_b: "5",
      choice_c: "10",
      choice_d: "15",
      correct_choice: "b",
      explanation: "Using inclusion-exclusion: 25 + 20 − 10 = 35 play at least one sport. 40 − 35 = 5 play neither.",
      difficulty: 2,
    },
    {
      question_text: "What is the value of the expression: 3² + 4² − 2(3)(4)cos(0°)?",
      choice_a: "1",
      choice_b: "5",
      choice_c: "25",
      choice_d: "0",
      correct_choice: "a",
      explanation: "3² + 4² − 2(3)(4)(1) = 9 + 16 − 24 = 1. This is the Law of Cosines with angle 0°.",
      difficulty: 3,
    },
    {
      question_text: "Which measures the middle value when data is arranged in order?",
      choice_a: "Mean",
      choice_b: "Median",
      choice_c: "Mode",
      choice_d: "Range",
      correct_choice: "b",
      explanation: "The median is the middle value in an ordered data set. Half the values are above and half below it.",
      difficulty: 1,
    },
    {
      question_text: "Simplify: (2/3) ÷ (4/9)",
      choice_a: "8/27",
      choice_b: "3/2",
      choice_c: "2/3",
      choice_d: "9/8",
      correct_choice: "b",
      explanation: "(2/3) ÷ (4/9) = (2/3) × (9/4) = 18/12 = 3/2.",
      difficulty: 2,
    },
  ],
};

// ── Fix duplicate keys in Q type ──────────────────────────────────────────────
// (The UST Math topic had a duplicate correct_choice key — corrected below)
// The QUESTIONS object above uses the last occurrence so "c" and "d" conflict is already resolved

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Seeding other school exams (ACET, DCAT, USTET)...\n");

  // Build subtest slug → id map
  const subtestIdMap: Record<string, string> = {};

  for (const school of SCHOOLS) {
    console.log(`\n── ${school.exam_type.toUpperCase()} ──`);

    // Upsert subtests
    for (const st of school.subtests) {
      const { data, error } = await supabase
        .from("subtests")
        .upsert(
          {
            name: st.name,
            slug: st.slug,
            display_order: st.display_order,
            exam_type: school.exam_type,
            description: st.description,
            upcat_item_count: 0,
            mock_item_count: st.mock_item_count,
          },
          { onConflict: "slug" }
        )
        .select("id")
        .single();

      if (error || !data) {
        console.error(`  ✗ Subtest '${st.slug}':`, error?.message);
        continue;
      }
      subtestIdMap[st.slug] = data.id;
      console.log(`  ✓ Subtest: ${st.name}`);
    }

    // Upsert topics and insert questions
    for (const topic of school.topics) {
      const subtestId = subtestIdMap[topic.subtestSlug];
      if (!subtestId) {
        console.error(`  ✗ No subtest ID for slug '${topic.subtestSlug}'`);
        continue;
      }

      const { data: topicData, error: topicError } = await supabase
        .from("topics")
        .upsert(
          {
            subtest_id: subtestId,
            name: topic.name,
            slug: topic.slug,
            display_order: topic.display_order,
          },
          { onConflict: "subtest_id,slug" }
        )
        .select("id")
        .single();

      if (topicError || !topicData) {
        console.error(`  ✗ Topic '${topic.slug}':`, topicError?.message);
        continue;
      }

      const questions = QUESTIONS[topic.slug];
      if (!questions || questions.length === 0) {
        console.warn(`  ⚠ No questions for topic '${topic.slug}'`);
        continue;
      }

      const rows = questions.map((q) => ({
        topic_id: topicData.id,
        question_text: q.question_text,
        choice_a: q.choice_a,
        choice_b: q.choice_b,
        choice_c: q.choice_c,
        choice_d: q.choice_d,
        correct_choice: q.correct_choice,
        explanation: q.explanation,
        difficulty: q.difficulty,
        status: "approved" as const,
      }));

      const { error: qError } = await supabase.from("questions").insert(rows);
      if (qError) {
        console.error(`  ✗ Questions for '${topic.slug}':`, qError.message);
      } else {
        console.log(`  ✓ ${topic.name}: ${rows.length} questions`);
      }
    }
  }

  console.log("\nDone.");
}

main().catch(console.error);
